Repository endless-sky/endless-sky, pull requests merged in 2020-03, with the labels that each got.

#4817 Add script that checks if the Xcode project is complete (and that suggests a fix)
  .github/workflows/xcode_check.yml
  tests/check_xcode.sh
Labels: enhancement

#4868 Buff Ion Rain Gun
  data/coalition weapons.txt
Labels: balance

#4823 Hai Security: varying planet security and Hai surveillance fleets
  data/hai ships.txt
  data/hai.txt
  data/map.txt
Labels: content

#4873 Updates to Kahet Mission.txt
  data/ka'het missions.txt
Labels: content

#4837 Remnant: Changes to Return the Sample Timer & Hint
  data/remnant missions.txt
Labels: content

#4876 Gave the Fire-lance projectiles a blue glow at the base
  images/projectile/fire-lance+0.png
  images/projectile/fire-lance+1.png
  images/projectile/fire-lance+2.png
  images/projectile/fire-lance+3.png
Labels: content

#4854 A couple more Bulk Passenger jobs for balance and diversity
  data/jobs.txt
  data/paradise world jobs.txt
Labels: content

#4898 Added a necessary requirement to a Ka'het mission
  data/ka'het/ka'het missions.txt
Labels: content

#4906 Reduce kestrel's gun ports from 18 to 12
  data/human/kestrel.txt
Labels: balance

#4894 feat: Solar heat mechanic for increased heat generation the closer you are to the system center
  data/tooltips.txt
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/ShipInfoDisplay.cpp
Labels: enhancement

#4914 fix: Account for the depreciation grace period in the max age of an outfit or ship
  source/Depreciation.cpp
Labels: bug

#4916 Phrasing fix
  data/wanderer/wanderers start.txt
Labels: bug

#4904 Updated the Primary Cooling's description
  data/ka'het/ka'het outfits.txt
Labels: content

#4936 Fix: Removed "Navy" license from Carrier and Cruiser
  data/deprecated outfits.txt
  data/human/outfits.txt
  data/human/ships.txt
  images/outfit/navy carrier license.png
  images/outfit/navy cruiser license.png
Labels: content

#4932 Allow negative repair costs
  source/Ship.cpp
Labels: mechanics

#4940 Tweak: Remnant-Ka'het, Taely's dialogue
  data/ka'het/ka'het missions.txt
Labels: content

#4652 Remnant: Bellows-Class Afterburner
  copyright
  data/remnant/remnant outfits.txt
  images/effect/remnant afterburner/remnant afterburner-00.png
  images/effect/remnant afterburner/remnant afterburner-01.png
  images/effect/remnant afterburner/remnant afterburner-02.png
  images/outfit/remnant afterburner.png
Labels: content

#4946 Bug fix: ships at Waypoint to refuel you
  data/map.txt
Labels: content

#4920 Remnant: Adding the Inhibitor Turret
  copyright
  data/remnant/remnant outfits.txt
  images/hardpoint/inhibitor turret.png
  images/outfit/inhibitor turret.png
Labels: content

#4948 Ion Hail Turret
  copyright
  data/coalition/coalition ships.txt
  data/coalition/coalition weapons.txt
  data/coalition/coalition.txt
  images/hardpoint/ion hail turret.png
  images/outfit/ion hail turret.png
Labels: content
