Repository endless-sky/endless-sky, pull requests merged in 2020-06, with the labels that each got.

#5104 Fix - Hyperspace capabilities of the Subsidurial
  data/drak/indigenous.txt
Labels: bug

#5049 Hope Recon 1C changes
  data/human/free worlds start.txt
Labels: content

#5036 Adding Flares to the Penguin
  data/remnant/remnant ships.txt
Labels: content

#5056 Polished "Wanderers: Defend Vara Ke'sok Hint"
  data/wanderer/wanderers start.txt
Labels: content

#5010 Finisher Torpedo storage outfit
  copyright
  data/coalition/coalition ships.txt
  data/coalition/coalition weapons.txt
  data/coalition/coalition.txt
  images/outfit/finisher storage.png
Labels: content

#5025 Reduce Heat of Coalition Engine Modules
  data/coalition/coalition outfits.txt
Labels: balance

#5032 Increase Reactor Modules Energy Generation
  data/coalition/coalition outfits.txt
Labels: balance

#5001 Renaming the Gascraft to the Puffin
  data/remnant/remnant missions.txt
  data/remnant/remnant ships.txt
  data/remnant/remnant.txt
  images/ship/puffin.png
  images/thumbnail/puffin.png
Labels: content

#4977 Fix: Reduce "take-off and reload" instances in the gascraft mission while making the Archon Deadlier
  data/drak/drak.txt
Labels: balance

#4981 Kestrel bays
  data/human/kestrel.txt
  data/persons.txt
Labels: balance

#4961 More Shields Kestrel +10% heat dissipation
  data/human/kestrel.txt
Labels: balance

#4391 refactor(mechanics): Change bay type identification to categories
  source/AI.cpp
  source/Engine.cpp
  source/PlayerInfo.cpp
  source/Ship.cpp
  source/Ship.h
  source/ShipInfoDisplay.cpp
Labels: mechanics

#5125 Remnant: Dialog explaining "buy to cargo" in Remnant: Key Stones
  data/remnant/remnant missions.txt
Labels: content

#5067 Builders power storage
  copyright
  data/ka'het/ka'het outfits.txt
  data/ka'het/ka'het ships.txt
  images/outfit/ka'het mhd generator.png
  images/outfit/ka'het reserve accumulator.png
Labels: content

#5012 New hails in humans space
  data/human/hails.txt
Labels: content

#5009 A couple Quarg missions
  data/quarg/quarg missions.txt
Labels: content

#4921 Remove Queri Ringworld
  data/ka'het/ka'het missions.txt
  data/map.txt
Labels: content

#5108 New Navy Ships
  copyright
  data/human/events.txt
  data/human/fleets.txt
  data/human/free worlds side plots.txt
  data/human/outfits.txt
  data/human/ships.txt
  data/map.txt
  images/outfit/auxiliary license.png
  images/ship/auxiliaryc.png
  images/ship/auxiliaryh.png
  images/ship/auxiliaryt.png
  images/ship/dropship.png
  images/thumbnail/auxiliaryc.png
  images/thumbnail/auxiliaryh.png
  images/thumbnail/auxiliaryt.png
  images/thumbnail/dropship.png
Labels: content

#5132 Updated log entries for various factions
  data/human/free worlds checkmate.txt
  data/human/free worlds reconciliation.txt
  data/wanderer/wanderers middle.txt
  data/wanderer/wanderers start.txt
Labels: content

#5006 Add "Antibiotics to South"
  data/human/transport missions.txt
Labels: content
