Repository endless-sky/endless-sky, pull requests merged in 2020-10, with the labels that each got.

#5352 AI improvements for afterburners and reverse thrusters.
  source/AI.cpp
Labels: mechanics

#5390 Fix: Conversation branch condition in "Remnant: Face to Maw 2"
  data/remnant/remnant missions.txt
Labels: bug

#5368 New Tarazed ship sprites
  copyright
  data/human/marauders.txt
  data/human/ships.txt
  data/persons.txt
  images/ship/blackbird.png
  images/ship/falcon.png
  images/ship/finch.png
  images/ship/hawk.png
  images/ship/mfalcone.png
  images/ship/mfalcons.png
  images/ship/mfalconw.png
  images/ship/mosprey.png
  images/ship/osprey.png
  images/ship/sparrow.png
  images/thumbnail/blackbird.png
  images/thumbnail/falcon.png
  images/thumbnail/finch.png
  images/thumbnail/hawk.png
  images/thumbnail/mfalcone.png
  images/thumbnail/mfalcons.png
  images/thumbnail/mfalconw.png
  images/thumbnail/osprey.png
  images/thumbnail/sparrow.png
Labels: content

#5422 Fix: Remnant Cognizance 12 Puffin-Penguin bug
  data/remnant/remnant missions.txt
Labels: bug

#5416 Make LG's gridfire friendly-safe
  data/persons.txt
Labels: balance

#5410 Add Fuel Pods and Bunks to Coalition outfitters
  data/coalition/coalition.txt
Labels: content

#5406 Content: Creating the Person Zitchas
  copyright
  data/persons.txt
  data/remnant/remnant ships.txt
  images/ship/heron.png
Labels: content

#5418 Fix: Remnant Cognizance 1
  data/remnant/remnant missions.txt
Labels: bug

#5436 Fix: Heron Description "Existance"
  data/remnant/remnant ships.txt
Labels: bug

#5432 Added fine 0 and bribe 0 for Governments where those don't make sense
  data/governments.txt
Labels: content

#5438 Ka'het graphical upgrade
  data/ka'het/ka'het ships.txt
  images/ship/maeri'het-00.png
  images/ship/maeri'het-01.png
  images/ship/maeri'het-02.png
  images/ship/maeri'het-03.png
  images/ship/maeri'het.png
  images/ship/telis'het.png
  images/thumbnail/maeri'het.png
  images/thumbnail/telis'het.png
Labels: content

#5426 Differentiate aborting from failing
  source/Mission.cpp
  source/Mission.h
  source/MissionPanel.cpp
Labels: enhancement

#5430 Add empty "on abort" sections to Syndicate target practice.
  data/human/free worlds intro.txt
  data/human/pirate jobs.txt
  data/human/syndicate jobs.txt
  data/remnant/remnant missions.txt
Labels: content

#5431 Make the language check a part of CanSendHail
  source/Engine.cpp
Labels: bug

#5402 "You have visited" map key highlights uninhabited systems with landable planets
  source/MapPanel.cpp
Labels: mechanics

#5413 On waypoint mission action
  source/Mission.cpp
  source/Mission.h
Labels: enhancement

#5403 Save variant names for gifted ships
  source/MissionAction.cpp
  source/Ship.cpp
  source/Ship.h
Labels: bug

#5449 Allow carried ships to be the player's flagship
  source/PlayerInfo.cpp
  source/Ship.cpp
  source/Ship.h
Labels: mechanics

#5460 2 new types of Bounty Missions
  data/governments.txt
  data/human/jobs.txt
Labels: content

#5433 Graveyard insights: Fixing the issues related to the planet descriptions and mission structuring
  data/ka'het/ka'het missions.txt
  data/map.txt
Labels: content

#5374 Add regional/noteworthy features attributes to systems
  data/map.txt
Labels: content

#5464 Stop blurshader thinking there is centervelocity movement after player death
  source/Ship.cpp
Labels: bug

#5468 Disallow selecting already destroyed ships by clicking/dragging
  source/PlayerInfo.cpp
Labels: bug

#5380 fix(doc) Update copyright file.
  copyright
Labels: documentation

#5444 Sheragi fighters and minor rebalancing
  copyright
  data/sheragi/archaeology missions.txt
  data/sheragi/sheragi outfits.txt
  data/sheragi/sheragi ships.txt
  images/effect/fissionflare+0.png
  images/effect/fissionflare+1.png
  images/effect/fissionflare+2.png
  images/effect/fissionflare+3.png
  images/effect/fusionflare+0.png
  images/effect/fusionflare+1.png
  images/effect/fusionflare+2.png
  images/effect/fusionflare+3.png
  images/icon/shard.png
  images/outfit/embattery.png
  images/outfit/fissiondrive.png
  images/outfit/hion.png
  images/outfit/shard.png
  images/outfit/sheragi ews.png
  images/outfit/small embattery.png
  images/outfit/small sheragi cooling.png
  images/projectile/hion+.png
  images/projectile/hionfrag+0.png
  images/projectile/hionfrag+1.png
  images/projectile/hionfrag+2.png
  images/projectile/shardactive-0.png
  images/projectile/shardactive-1.png
  images/projectile/shardactive-2.png
  images/projectile/shardactive-3.png
  images/projectile/shardinactive.png
  images/ship/blackdiamond.png
  images/thumbnail/blackdiamond.png
  sounds/hion~.wav
Labels: content
