Repository endless-sky/endless-sky, pull requests merged in 2020-01, with the labels that each got.

#4731 Bugfix: Add additional status parameter to scan rings emplace_back.
  source/Engine.cpp
Labels: bug

#4734 Removed the leaks from the Ibis
  data/remnant ships.txt
Labels: content

#4706 Fix remnant tech available log entry
  data/remnant missions.txt
Labels: bug

#4622 New Hai Reactor Images
  copyright
  data/hai outfits.txt
  images/outfit/hai boulder.png
  images/outfit/hai geode.png
  images/outfit/hai pebble core.png
Labels: content

#4737 Updating Ember Waste Wormholes so they will be used by fleets
  data/map.txt
Labels: content

#4739 Change Relic's description
  data/map.txt
Labels: content

#4716 New alien factions: the Builders and the Ka'het
  copyright
  data/governments.txt
  data/ka'het missions.txt
  data/ka'het outfits.txt
  data/ka'het ships.txt
  data/ka'het.txt
  data/landing messages.txt
  data/map.txt
  data/remnant outfits.txt
  images/effect/ravager impact+0.png
  images/effect/ravager impact+1.png
  images/effect/ravager impact+2.png
  images/hardpoint/annihilator turret.png
  images/hardpoint/ravager turret.png
  images/label/graveyard+.png
  images/outfit/ka'het annihilator turret.png
  images/outfit/ka'het annihilator.png
  images/outfit/ka'het emp deployer.png
  images/outfit/ka'het primary cooling.png
  images/outfit/ka'het ravager beam.png
  images/outfit/ka'het ravager turret.png
  images/outfit/ka'het shield restorer.png
  images/outfit/ka'het support cooling.png
  images/planet/dyson1.png
  images/planet/dyson2.png
  images/planet/dyson3.png
  images/planet/station1b.png
  images/planet/station2b.png
  images/planet/station3b.png
  images/planet/station3bd.png
  images/projectile/annihilator+0.png
  images/projectile/annihilator+1.png
  images/projectile/annihilator+2.png
  images/projectile/ravager beam+0.png
  images/projectile/ravager beam+1.png
  images/ship/faes'mar.png
  images/ship/maeri'het-00.png
  images/ship/maeri'het-01.png
  images/ship/maeri'het-02.png
  images/ship/maeri'het-03.png
  images/ship/selii'mar.png
  images/ship/telis'het.png
  images/thumbnail/faes'mar.png
  images/thumbnail/maeri'het.png
  images/thumbnail/selii'mar.png
  images/thumbnail/telis'het.png
Labels: content

#4741 Make fast-forward key configurable
  keys.txt
  source/Command.cpp
  source/Command.h
  source/PreferencesPanel.cpp
  source/main.cpp
Labels: enhancement

#4294 Add flagship crew info to conditions. Partially implements #4286
  source/PlayerInfo.cpp
Labels: enhancement

#4592 Combine multiple on visit dialogs into a single dialog to avoid being spammed
  source/Mission.cpp
  source/Mission.h
  source/MissionAction.cpp
  source/MissionAction.h
  source/PlayerInfo.cpp
Labels: mechanics

#4738 Adding a spaceport to Wormhole Alpha and reworking containing systems
  data/governments.txt
  data/hai missions.txt
  data/map.txt
Labels: content

#4446 Add mission about Southbound ship designer.
  data/transport missions.txt
Labels: content

#4531 Added a mission that helps the player if they become stuck in the Ember Waste
  data/remnant missions.txt
  data/remnant outfits.txt
Labels: content

#4493 Added additional Remnant: Key Stones missions
  data/remnant missions.txt
Labels: content

#4584 Providing more variety with hails related to media from friendly civilians
  data/hails.txt
Labels: content

#4657 More pirate names
  data/names.txt
Labels: content

#4724 Nitpicks
  data/free worlds checkmate.txt
  data/free worlds reconciliation.txt
  data/news.txt
  data/remnant missions.txt
  data/tooltips.txt
Labels: content

#4473 Adds new friendly civilian hail
  data/hails.txt
Labels: content

#4748 New Williwaw sprite
  copyright
  data/hai outfits.txt
  images/outfit/hai williwaw.png
Labels: content

#4310 Give FW Pug 2C: Jump Drive priority so that you aren't given an extra JD
  data/free worlds reconciliation.txt
Labels: content

#4747 Changes to Calda's description
  data/map.txt
Labels: content

#4735 New boarding mission
  data/boarding missions.txt
Labels: content

#4756 resume jump/board/land autopilot when movement keys are released
  source/Engine.cpp
Labels: mechanics

#4769 refactor: Require a new press to exit a conversation or select a choice
  source/ConversationPanel.cpp
Labels: mechanics

#4388 feat: If not carried, fighters and drones are launched instead of sold
  data/tooltips.txt
  source/AI.cpp
  source/Fleet.h
  source/PlanetPanel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/ShopPanel.cpp
Labels: mechanics
