Repository endless-sky/endless-sky, pull requests merged in 2020-02, with the labels that each got.

#4781 Swap RoP and RoW
  data/map.txt
Labels: content

#4787 More human stations
  copyright
  data/map.txt
  images/planet/station10.png
  images/planet/station11.png
  images/planet/station12.png
  images/planet/station13.png
  images/planet/station14.png
  images/planet/station15.png
  images/planet/station16.png
  images/planet/station17.png
  images/planet/station8.png
  images/planet/station9.png
Labels: content

#4782 New station0 (Lagrange) sprite
  copyright
  images/planet/station0.png
Labels: content

#4777 Hint missions for stealing an Electron Beam
  data/free worlds middle.txt
Labels: content

#4761 First Contact Ka'het: Quarg: allow landing on any Quarg planet, and don't tell the user where they are.
  data/ka'het missions.txt
Labels: content

#4762 Added Wanderer Mission that leads to Wanderers: Defend Vara Ke'sok
  data/wanderers start.txt
Labels: content

#4417 Ship::JumpsRemaining() calculates the jump counts a bit more optimistically.
  source/AI.cpp
  source/Ship.cpp
  source/Ship.h
Labels: mechanics

#3369 Injured, player-owned escorts regroup with the player's flagship
  source/AI.cpp
Labels: mechanics

#4538 Add phrase expansion and replacement functions to the phrase node.
  source/Format.cpp
  source/Format.h
  source/Phrase.cpp
  source/Phrase.h
Labels: enhancement

#4806 Don't auto-launch after accepting Project Hawking mission
  data/deep missions.txt
Labels: content

#4805 FW license
  data/free worlds intro.txt
  data/outfits.txt
  data/ships.txt
Labels: content

#4816 Fixed unnecessary tab
  data/free worlds intro.txt
Labels: bug

#4745 Stop command to have flagship perform a full stop
  source/AI.cpp
  source/AI.h
  source/Command.cpp
  source/Command.h
  source/Engine.cpp
Labels: enhancement

#4815 v0.9.11 Changelog Update
  changelog
Labels: documentation

#4832 Remnant: License Aquisition Options (and rejection tolerance)
  changelog
  data/remnant missions.txt
Labels: content

#4838 Remnant: Allow gain of reputation
  data/governments.txt
Labels: content

#4827 Mystery cube jobs for stations
  data/deep jobs.txt
Labels: content

#4792 Remnant leaks
  copyright
  data/effects.txt
  data/remnant ships.txt
  images/effect/remnant leak sparkle-0.png
  images/effect/remnant leak sparkle-1.png
  images/effect/remnant leak sparkle-2.png
  images/effect/remnant leak sparkle-3.png
  images/effect/remnant leak-0.png
  images/effect/remnant leak-1.png
  images/effect/remnant leak-2.png
  images/effect/remnant leak-3.png
Labels: content

#4685 Nanachi missions and variants
  data/hai missions.txt
  data/variants.txt
Labels: content

#4785 Adding the Subsidurial
  copyright
  data/indigenous.txt
  data/persons.txt
  images/effect/subsidurial death/subsidurial death~0.png
  images/effect/subsidurial death/subsidurial death~1.png
  images/effect/subsidurial death/subsidurial death~2.png
  images/effect/subsidurial death/subsidurial death~3.png
  images/effect/subsidurial death/subsidurial death~4.png
  images/effect/subsidurial death/subsidurial death~5.png
  images/ship/subsidurial.png
  images/thumbnail/subsidurial.png
Labels: content
