Repository endless-sky/endless-sky, pull requests merged in 2020-12, with the labels that each got.

#5537 Fix: An unparked, unarmed ship with <=20 cargo space reduces the fleet's piracy threat
  source/PlayerInfo.cpp
Labels: mechanics

#5535 New Syndicate redesigns
  copyright
  data/human/marauders.txt
  data/human/ships.txt
  data/persons.txt
  images/ship/arrow.png
  images/ship/barb.png
  images/ship/barbp.png
  images/ship/bulk freighter.png
  images/ship/freighter.png
  images/ship/marrowe.png
  images/ship/marrows.png
  images/ship/marroww.png
  images/ship/pointedstick vanguard.png
  images/ship/pointedstick_vanguard.png
  images/ship/protector.png
  images/ship/star barge.png
  images/ship/vanguard.png
  images/ship/wasp.png
  images/thumbnail/arrow.png
  images/thumbnail/barb.png
  images/thumbnail/barbp.png
  images/thumbnail/bulk freighter.png
  images/thumbnail/freighter.png
  images/thumbnail/marrowe.png
  images/thumbnail/marrows.png
  images/thumbnail/marroww.png
  images/thumbnail/protector.png
  images/thumbnail/star barge.png
  images/thumbnail/vanguard.png
  images/thumbnail/wasp.png
Labels: content

#4523 Added attributes for custom disabled thresholds
  data/tooltips.txt
  source/Outfit.cpp
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
Labels: enhancement

#4703 Added a mechanic for projectiles to lose damage over range
  source/Projectile.cpp
  source/Projectile.h
  source/Ship.cpp
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#5193 Added a "jump range" attribute for changing how far a jump drive can travel
  data/tooltips.txt
  source/AI.cpp
  source/DistanceMap.cpp
  source/DistanceMap.h
  source/Engine.cpp
  source/Fleet.cpp
  source/GameData.cpp
  source/GameData.h
  source/MapDetailPanel.cpp
  source/MapPanel.cpp
  source/MapPanel.h
  source/Outfit.cpp
  source/PlayerInfo.cpp
  source/Ship.cpp
  source/Ship.h
  source/System.cpp
  source/System.h
Labels: enhancement

#5553 Allow ionization to affect disabled ships
  source/Ship.cpp
Labels: bug

#4520 Added energy, fuel, and heat attributes for resistances
  data/tooltips.txt
  source/Outfit.cpp
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
Labels: enhancement

#5526 Fix: Remnant: Astral Job - Cognizance compatabiliy
  data/map.txt
  data/remnant/remnant missions.txt
Labels: bug

#4524 Added attributes that delay shield generation and hull repair
  data/tooltips.txt
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/Ship.h
Labels: enhancement

#5514 Re-detailed the Korath Raider
  copyright
  data/korath/korath ships.txt
  images/ship/raider.png
  images/thumbnail/raider.png
Labels: content

#5467 Add checks for AI so it does not try and land on Spriteless planets
  source/AI.cpp
  source/Engine.cpp
Labels: bug, waiting on OP

#4931 System hazards
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  source/CollisionSet.cpp
  source/CollisionSet.h
  source/Engine.cpp
  source/Engine.h
  source/GameData.cpp
  source/GameData.h
  source/Hazard.cpp
  source/Hazard.h
  source/Mask.cpp
  source/Mask.h
  source/Ship.cpp
  source/Ship.h
  source/System.cpp
  source/System.h
  source/Weapon.h
  source/Weather.cpp
  source/Weather.h
Labels: enhancement

#5567 Create a gravitational weapon tag that causes hit force to ignore mass
  source/Ship.cpp
  source/Ship.h
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#5557 Tweak Thermoelectric Cooler (TEC)
  data/remnant/remnant outfits.txt
Labels: balance

#5555 Allow min and max zoom levels to be defined in interfaces.txt
  credits.txt
  data/interfaces.txt
  source/MapPanel.cpp
Labels: enhancement

#4494 Update Pond Strider, Flea, associated outfits
  copyright
  data/hai/hai missions.txt
  data/hai/hai outfits.txt
  data/hai/hai ships.txt
  data/hai/hai.txt
  data/wanderer/wanderers start.txt
  images/outfit/railslug rack.png
Labels: content

#4432 feat: Hyperjump arrival distance variable
  source/Ship.cpp
  source/System.cpp
  source/System.h
Labels: enhancement

#5478 content: Create FW Epilogue mission for Barmy Edwards
  copyright
  data/human/free worlds epilogue.txt
  data/human/variants.txt
  data/human/weapons.txt
  images/outfit/plasma repeater.png
  images/scene/plasma scene.png
Labels: content

#5569 Create "relative" damage types that deal damage as a percentage of a target's stats
  data/tooltips.txt
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#5560 Content: Implementing System Hazards in the Ember Waste & Sagittarius A* systems
  data/hazards.txt
  data/map.txt
  images/effect/ew heat/ew heat~0.png
  images/effect/ew heat/ew heat~1.png
  images/effect/ew heat/ew heat~2.png
  images/effect/ew heat/ew heat~3.png
  images/effect/ew heat/ew heat~4.png
  images/effect/ew heat/ew heat~5.png
  images/effect/ew heat/ew heat~6.png
  images/effect/ew heat/ew heat~7.png
Labels: content

#5572 Check if a ship is overheated during Ship::TakeDamage
  source/Ship.cpp
Labels: bug

#4710 fix: Make gather command work for out-of-system fleet
  source/AI.cpp
Labels: bug

#4443 feat: Planetary outfits storage
  data/help.txt
  source/MapPanel.cpp
  source/MapPanel.h
  source/OutfitterPanel.cpp
  source/OutfitterPanel.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/ShipyardPanel.cpp
  source/ShipyardPanel.h
  source/ShopPanel.cpp
  source/ShopPanel.h
Labels: enhancement

#5576 Add consistent frequency formatting for person ships
  data/persons.txt
Labels: content

#5499 Added scrolling in the logbook category list
  source/LogbookPanel.cpp
  source/LogbookPanel.h
Labels: mechanics

#5000 feat(graphics): Add user preference for VSync setting
  source/GameWindow.cpp
  source/GameWindow.h
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
  source/main.cpp
Labels: enhancement

#2678 feat(mechanics): Issue out-of-system travel orders to escorts via the galaxy map
  data/interfaces.txt
  source/AI.cpp
  source/Engine.cpp
  source/MapDetailPanel.cpp
  source/MapDetailPanel.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/PreferencesPanel.cpp
Labels: enhancement

#4370 feat: Add initial framework for game-logic auto-testing
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  data/tests/tests_framework.txt
  endless-sky.6
  source/Files.cpp
  source/Files.h
  source/GameData.cpp
  source/GameData.h
  source/GameWindow.cpp
  source/GameWindow.h
  source/Test.cpp
  source/Test.h
  source/TestData.cpp
  source/TestData.h
  source/main.cpp
  tests/config/preferences.txt
  tests/run_tests.sh
  tests/run_tests_headless.sh
Labels: enhancement

#5577 Add new firing damages weapon attributes
  data/tooltips.txt
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#5558 High Heat Tweaks - Adjusting Remnant and Korath ships for the Ember Waste Environment
  data/drak/drak.txt
  data/drak/indigenous.txt
  data/hazards.txt
  data/korath/korath ships.txt
  data/remnant/remnant missions.txt
  data/remnant/remnant outfits.txt
  data/remnant/remnant ships.txt
  images/effect/ew heat/ew heat~0.png
  images/effect/ew heat/ew heat~1.png
  images/effect/ew heat/ew heat~2.png
  images/effect/ew heat/ew heat~3.png
  images/effect/ew heat/ew heat~4.png
  images/effect/ew heat/ew heat~5.png
  images/effect/ew heat/ew heat~6.png
  images/effect/ew heat/ew heat~7.png
Labels: balance

#5152 feat: Move swizzling into shader
  source/GameData.cpp
  source/GameData.h
  source/SpriteShader.cpp
  source/SpriteShader.h
  source/main.cpp
Labels: waiting on OP
