Repository endless-sky/endless-sky, pull requests merged in 2020-11, with the labels that each got.

#5509 feat(testing): add a unit testing framework
  .appveyor.yml
  .editorconfig
  .github/workflows/cd.yaml
  .github/workflows/ci.yml
  .gitignore
  .travis.yml
  .winmake
  EndlessSky.cbp
  EndlessSky.workspace
  EndlessSkyLib.cbp
  EndlessSkyTests.cbp
  SConstruct
  source/BatchShader.cpp
  source/Font.cpp
  source/Font.h
  source/ImageBuffer.cpp
  source/Music.cpp
  source/OutlineShader.cpp
  source/Shader.cpp
  source/StarField.cpp
  tests/include/catch.hpp
  tests/include/es-test.hpp
  tests/run_tests_headless.sh
  tests/src/README.md
  tests/src/test_conditionSet.cpp
  tests/src/test_datanode.cpp
  tests/src/test_main.cpp
  tests/src/test_point.cpp
  tests/src/test_random.cpp
  tests/src/test_set.cpp
  tests/src/test_template.txt
  tests/test_parse.sh
Labels: enhancement

#5493 Clean up borders of haze sprites
  images/_menu/haze+.jpg
  images/_menu/haze-133+.jpg
  images/_menu/haze-33+.jpg
  images/_menu/haze-67+.jpg
Labels: content

#5488 More variety to Heliarch ship names
  data/coalition/coalition.txt
Labels: content

#5487 Adding Scouts
  data/human/fleets.txt
Labels: content

#5490 Remove "minor" from the FW Epilogue missions
  data/human/free worlds epilogue.txt
Labels: bug

#5491 Typo fix and adjustments
  data/sheragi/archaeology missions.txt
  data/sheragi/sheragi outfits.txt
Labels: bug

#5482 Add copyright for clouds
  copyright
  images/land/clouds_00.jpg
  images/land/clouds_07.jpg
  images/land/clouds_08.jpg
Labels: content

#5451 Feat: Add 'D' keybind to finish conversation
  source/ConversationPanel.cpp
Labels: mechanics

#5477 content: Add some new hails (civilian and Syndicate dummy target).
  data/human/hails.txt
Labels: content

#5485 Add Finisher Storage Tube to stock Interdictor
  data/coalition/coalition ships.txt
Labels: content

#5367 Content: Remnant Expanded Horizons Astral
  copyright
  data/map.txt
  data/remnant/remnant missions.txt
  data/remnant/remnant outfits.txt
  images/outfit/research laboratory.png
  images/scene/sagittarius a.png
Labels: content

#5501 Ka'het Engines
  copyright
  data/ka'het/ka'het outfits.txt
  data/ka'het/ka'het ships.txt
  images/effect/ka'het flare/large+0.png
  images/effect/ka'het flare/large+1.png
  images/effect/ka'het flare/large+2.png
  images/effect/ka'het flare/large+3.png
  images/effect/ka'het flare/large+4.png
  images/effect/ka'het flare/large+5.png
  images/effect/ka'het flare/medium+0.png
  images/effect/ka'het flare/medium+1.png
  images/effect/ka'het flare/medium+2.png
  images/effect/ka'het flare/medium+3.png
  images/effect/ka'het flare/medium+4.png
  images/effect/ka'het flare/medium+5.png
  images/effect/ka'het flare/small+0.png
  images/effect/ka'het flare/small+1.png
  images/effect/ka'het flare/small+2.png
  images/effect/ka'het flare/small+3.png
  images/effect/ka'het flare/small+4.png
  images/effect/ka'het flare/small+5.png
  images/outfit/ka'het compact engine.png
  images/outfit/ka'het maeri engine.png
  images/outfit/ka'het sustainer engine.png
  images/outfit/ka'het telis engine.png
Labels: content

#5484 Six new Heliarch ships
  copyright
  data/coalition/coalition ships.txt
  data/coalition/coalition.txt
  images/ship/heliarch breacher.png
  images/ship/heliarch hunter.png
  images/ship/heliarch judicator.png
  images/ship/heliarch pursuer.png
  images/ship/heliarch rover.png
  images/ship/heliarch stalker.png
  images/thumbnail/heliarch breacher.png
  images/thumbnail/heliarch hunter.png
  images/thumbnail/heliarch judicator.png
  images/thumbnail/heliarch pursuer.png
  images/thumbnail/heliarch rover.png
  images/thumbnail/heliarch stalker.png
Labels: content
