Repository endless-sky/endless-sky, pull requests merged in 2020-09, with the labels that each got.

#5279 Content: Spaceport Graffiti poetry
  data/human/news.txt
Labels: content

#5274 Fix: Adds a description for Archons
  data/drak/drak.txt
Labels: content

#4801 feat: Add gun-port angles and gun convergence setting
  source/Armament.cpp
  source/Armament.h
  source/Hardpoint.cpp
  source/Hardpoint.h
  source/Ship.cpp
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#5319 Save ship outfits in alphabetic order to savegame.
  source/Ship.cpp
Labels: mechanics

#5328 Fixed instances of 'Membulem'
  data/map.txt
Labels: content

#5326 Arkhne's Unfettered First Contact Update
  data/hai/hai missions.txt
Labels: content

#5334 Conditional spaceport news
  source/GameData.cpp
  source/GameData.h
  source/News.cpp
  source/News.h
  source/SpaceportPanel.cpp
  source/SpaceportPanel.h
Labels: enhancement

#5333 feat(mechanics): Save collections in order by element name
  source/AI.cpp
  source/CargoHold.cpp
  source/DataWriter.h
  source/Depreciation.cpp
  source/Fleet.cpp
  source/GameData.cpp
  source/MapOutfitterPanel.cpp
  source/MapShipyardPanel.cpp
  source/MissionPanel.cpp
  source/Outfit.cpp
  source/PlayerInfo.cpp
  source/Ship.cpp
Labels: enhancement

#5233 feat(layout): Moved the outfitter and shipyard "detail information" into a sidebar
  data/interfaces.txt
  images/ui/outfitter selected+.png
  images/ui/shipyard selected+.png
  source/ItemInfoDisplay.cpp
  source/OutfitterPanel.cpp
  source/ShipyardPanel.cpp
  source/ShopPanel.cpp
  source/ShopPanel.h
Labels: mechanics

#5351 Some new civilian hails and some new news items.
  data/human/hails.txt
  data/human/news.txt
Labels: content

#5295 Content: Creating Person for MCOfficer
  copyright
  credits.txt
  data/persons.txt
  images/ship/mbactriane.png
Labels: content

#5219 Kor Efret jobs and missions
  data/korath/korath jobs.txt
  data/korath/korath missions.txt
  data/korath/korath news.txt
  data/wanderer/wanderer jobs.txt
  data/wanderer/wanderers middle.txt
  data/wanderer/wanderers.txt
Labels: content

#5302 Feat: Give ship
  source/MissionAction.cpp
  source/MissionAction.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: enhancement

#5389 typo: FWC Pug 4 missing period
  data/human/free worlds checkmate.txt
Labels: bug

#5388 Content: Remnant - Penguin Give
  data/remnant/remnant missions.txt
  data/remnant/remnant ships.txt
Labels: content

#5383 Bugfix: Remnant Thumbnails post processing change
  images/thumbnail/albatross.png
  images/thumbnail/ibis.png
  images/thumbnail/starling.png
Labels: content
