Repository endless-sky/endless-sky, pull requests merged in 2020-07, with the labels that each got.

#5074 warn if conversation text has multiple tokens (e.g. incorrectly-indented goto)
  source/Conversation.cpp
Labels: mechanics

#4749 feat: Allow more bay orientations / facing-angles
  source/Ship.cpp
  source/Ship.h
Labels: enhancement

#5142 Fixed pathing through undefined systems.
  source/GameData.cpp
  source/System.cpp
Labels: bug

#5079 Stop crashing when using weapons with infinite submunition
  source/Weapon.cpp
Labels: bug

#4719 feat: Deploy and recall only selected fighters instead of all.
  source/AI.cpp
  source/AI.h
  source/Ship.cpp
  source/Ship.h
Labels: mechanics

#4382 Add # of guns/turrets to --ships flag
  source/GameData.cpp
Labels: waiting on OP

#5122 Collected Minor Changes - Logs and Descriptions June 2020
  data/hai/hai missions.txt
  data/human/deep missions.txt
  data/human/free worlds middle.txt
  data/human/names.txt
  data/human/ships.txt
  data/human/transport missions.txt
  data/map.txt
Labels: content

#5126 Updates Help with outfitter/cargo
  data/help.txt
  source/OutfitterPanel.cpp
  source/OutfitterPanel.h
Labels: enhancement

#5158 Add plural gender-neutral titles to human names
  data/human/names.txt
Labels: content

#5164 System attributes for the Ember Waste and select systems
  data/map.txt
Labels: content

#5163 Fix: Map Editor Compatability
  data/map.txt
  data/pug map.txt
Labels: content

#4786 The Emerald Sword, an unique and ancient Sheragi warship.
  copyright
  data/human/outfits.txt
  data/sheragi/sheragi outfits.txt
  data/sheragi/sheragi ships.txt
  data/sheragi/the emerald sword.txt
  images/effect/dragonflame+0.png
  images/effect/dragonflame+1.png
  images/effect/dragonflame+2.png
  images/effect/dragonflame+3.png
  images/effect/dragonflame+4.png
  images/effect/fdrive+0.png
  images/effect/fdrive+1.png
  images/effect/fdrive+2.png
  images/effect/fdrive+3.png
  images/effect/pwave impact+0.png
  images/effect/pwave impact+1.png
  images/effect/pwave impact+2.png
  images/effect/pwave impact+3.png
  images/effect/sheragiam+0.png
  images/effect/sheragiam+1.png
  images/effect/sheragiam+2.png
  images/hardpoint/pwavehp.png
  images/hardpoint/sheragiam.png
  images/icon/dragonflame.png
  images/outfit/dragonflame.png
  images/outfit/embattery.png
  images/outfit/fusiondrive.png
  images/outfit/pwave turret.png
  images/outfit/sheragiam.png
  images/outfit/sheragicooling.png
  images/projectile/pwavecannon+.png
  images/scene/emeraldswordderelict.png
  images/ship/emeraldsword.png
  images/thumbnail/emeraldsword.png
  sounds/dragonflame.wav
  sounds/pwave.wav
Labels: content

#5156 Privateer Short Mission Line
  data/human/transport missions.txt
Labels: content

#4662 Remnant Peregrine
  copyright
  data/remnant/remnant ships.txt
  images/ship/peregrine/peregrine-00.png
  images/ship/peregrine/peregrine-01.png
  images/ship/peregrine/peregrine-02.png
  images/ship/peregrine/peregrine-03.png
  images/ship/peregrine/peregrine-04.png
  images/ship/peregrine/peregrine-05.png
  images/ship/peregrine/peregrine-06.png
  images/ship/peregrine/peregrine-07.png
  images/ship/peregrine/peregrine-08.png
  images/ship/peregrine/peregrine-09.png
  images/ship/peregrine/peregrine-10.png
  images/thumbnail/peregrine.png
Labels: content

#4896 Coalition Yottrite
  data/coalition/coalition missions.txt
Labels: content

#5170 Mouthparts sprite
  copyright
  data/drak/indigenous.txt
  images/outfit/mouthparts.png
Labels: content

#5173 Ringworld debris
  copyright
  data/ka'het/ka'het missions.txt
  images/scene/ringworld debris.jpg
Labels: content

#5148 feat: Switch off fast-forward if the player is not in flight
  source/MainPanel.cpp
  source/MainPanel.h
  source/MapPanel.cpp
  source/MapPanel.h
  source/Panel.cpp
  source/Panel.h
  source/PlayerInfoPanel.cpp
  source/PlayerInfoPanel.h
  source/main.cpp
Labels: mechanics

#5168 Fix: A spelling mistake and contractions outside of conversations
  data/sheragi/the emerald sword.txt
Labels: bug

#5178 Add missions to prevent the player from becoming stranded in Coalition space
  data/coalition/coalition missions.txt
Labels: content

#5161 Allow mission NPCs to spawn or despawn based off of ConditionSets
  source/Engine.cpp
  source/Mission.cpp
  source/Mission.h
  source/NPC.cpp
  source/NPC.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: enhancement

#5179 Allow the "fancy" sobel filters in ShopPanels to be replaced with "fast" sprite images
  source/Preferences.cpp
  source/PreferencesPanel.cpp
  source/ShopPanel.cpp
Labels: enhancement

#4934 Miscellaneous Coalition Missions
  data/coalition/coalition missions.txt
Labels: content

#5040 fix: Also consider "moving to position held" as HOLD position.
  source/AI.cpp
  source/AI.h
Labels: bug

#5044 Customizable jump drive and hyperdrive sounds and effects
  source/Engine.cpp
  source/Outfit.cpp
  source/Outfit.h
  source/Ship.cpp
  source/Ship.h
Labels: enhancement

#5042 New jump drive effect and sound
  copyright
  data/effects.txt
  images/effect/jump drive red~0.png
  images/effect/jump drive red~1.png
  images/effect/jump drive red~2.png
  images/effect/jump drive red~3.png
  images/effect/jump drive red~4.png
  images/effect/jump drive red~5.png
  images/effect/jump drive red~6.png
  images/effect/jump drive red~7.png
  sounds/jump drive red.wav
  sounds/jump in red.wav
  sounds/jump out red.wav
Labels: content

#5184 Change the Militia license to be more in line with the other Human licenses
  data/human/free worlds intro.txt
  data/human/outfits.txt
Labels: content
