Repository endless-sky/endless-sky, pull requests merged in 2020-08, with the labels that each got.

#5185 Move the Archaeology missions into the emerald sword.txt, rename emerald sword.txt to archaeology missions
  data/human/transport missions.txt
  data/sheragi/archaeology missions.txt
Labels: content

#5187 Remove portrait images from spaceport news
  data/hai/hai news.txt
  data/human/news.txt
  data/interfaces.txt
  source/SpaceportPanel.cpp
  source/SpaceportPanel.h
Labels: content

#5197 Typo fix
  data/map.txt
Labels: bug

#5202 Fix: Adding missing Key Stones to Remnant Ships
  data/remnant/remnant ships.txt
Labels: content

#5198 New builder weapon-station
  copyright
  data/map.txt
  images/land/loc3.jpg
  images/planet/station4b.png
  images/planet/station4bd.png
  images/scene/station4b firing.jpg
Labels: content

#5199 Add dialogue phrases for missing waypoints
  data/dialog phrases.txt
  data/human/transport missions.txt
Labels: content

#5007 Add "Earth Retirement"
  data/human/transport missions.txt
Labels: content

#4986 Haze for sparse and dense areas of the galaxy
  copyright
  data/map.txt
  images/_menu/haze-133+.jpg
  images/_menu/haze-33+.jpg
  images/_menu/haze-67+.jpg
  images/_menu/haze-blackbody+.jpg
  images/_menu/haze-full+.jpg
  images/_menu/haze-none+.png
  images/_menu/haze-yellow+.jpg
Labels: content

#5196 New news
  data/human/news.txt
Labels: content

#5206 Content: Breaking out Chilia logs (adjustment, not new content)
  data/remnant/remnant missions.txt
Labels: content

#5207 Kor Efreti spaceport news
  data/korath/korath news.txt
Labels: content

#5209 (Content) Remnant News 1 - Generic & Incomprehensible
  data/remnant/remnant news.txt
Labels: content

#5241 EMP Torpedo Storage Bays
  copyright
  data/remnant/remnant outfits.txt
  data/remnant/remnant ships.txt
  data/remnant/remnant.txt
  images/outfit/emp rack.png
Labels: content

#5238 Fix: Removed duplicate 'is' in Pincian's description
  data/map.txt
  data/remnant/remnant outfits.txt
Labels: bug

#5223 Support selecting systems without planning route
  source/MapPanel.cpp
Labels: enhancement

#4867 feat(mechanics): Update random planet selection criteria
  data/hai/hai jobs.txt
  data/human/deep jobs.txt
  data/human/frontier jobs.txt
  data/human/paradise world jobs.txt
  data/human/rim jobs.txt
  data/human/syndicate jobs.txt
  source/LocationFilter.cpp
  source/LocationFilter.h
  source/Mission.cpp
Labels: enhancement

#5228 Add "ion protection" to Heliarch ships
  data/coalition/coalition ships.txt
Labels: balance, waiting on OP

#5256 Update the Pilot's License description
  data/human/outfits.txt
Labels: content

#4822 Fill the default value in the save and ship rename dialogs
  source/Dialog.h
  source/LoadPanel.cpp
  source/ShipInfoPanel.cpp
Labels: mechanics

#5265 New ramscoop sprite
  copyright
  images/outfit/ramscoop.png
Labels: content

#5260 Update the Pilot's Licence's Argosy
  images/outfit/license.png
Labels: content

#5234 Content: Remnant license granting mission tweak
  data/remnant/remnant missions.txt
Labels: content

#4997 feat: Add Command loading and sending it to the Engine
  source/Command.cpp
  source/Command.h
  source/Engine.cpp
  source/Engine.h
  source/MainPanel.cpp
  source/MainPanel.h
Labels: enhancement

#4728 Remnant hails
  data/governments.txt
  data/remnant/remnant missions.txt
  data/remnant/remnant.txt
Labels: content
