Repository endless-sky/endless-sky, pull requests merged in 2020-04, with the labels that each got.

#4968 Referenced the Hauler IV in the "Hauler VI cargo prototype" missions
  data/human/transport missions.txt
Labels: content

#4911 Added some Ka'het hails
  data/governments.txt
  data/ka'het/ka'het.txt
Labels: content

#4960 Brown dwarves
  data/landing messages.txt
  data/map.txt
  data/stars.txt
  images/planet/browndwarf-l-rouge.png
  images/planet/browndwarf-l.png
  images/planet/browndwarf-t-rouge.png
  images/planet/browndwarf-t.png
  images/planet/browndwarf-y-rouge.png
  images/planet/browndwarf-y.png
Labels: content

#4947 Spaceport news stories for Hai
  data/hai/hai news.txt
  data/human/news.txt
Labels: content

#4950 v0.9.12 changelog update
  changelog
Labels: documentation

#4942 Attribute whitelist that allows negative attributes
  source/Outfit.cpp
Labels: enhancement

#4526 Fixes and changes to fines for illegal jobs
  source/CargoHold.cpp
  source/CargoHold.h
  source/Mission.cpp
  source/Mission.h
  source/Politics.cpp
Labels: bug, mechanics

#4522 Added velocity and range overrides
  source/AI.cpp
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#4525 Multipliers for shield generation and hull repair related stats
  data/tooltips.txt
  source/Outfit.cpp
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/ShipInfoDisplay.cpp
Labels: enhancement

#4519 Protection attributes
  data/tooltips.txt
  source/Outfit.cpp
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
Labels: enhancement

#4521 Added piercing resistance
  data/tooltips.txt
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/Weapon.cpp
Labels: enhancement
