Repository endless-sky/endless-sky, pull requests merged in 2021-08, with the labels that each got.

#5588 OpenGL ES support
  .github/workflows/ci.yml
  SConstruct
  source/BatchShader.cpp
  source/FillShader.cpp
  source/FogShader.cpp
  source/GameWindow.cpp
  source/LineShader.cpp
  source/OutlineShader.cpp
  source/PointerShader.cpp
  source/RingShader.cpp
  source/Shader.cpp
  source/SpriteShader.cpp
  source/StarField.cpp
  source/gl_header.h
  source/text/Font.cpp
Labels: enhancement

#5736 feat: Integration Test Framework: Add input loading for key, pointer(mouse) and command.
  data/tests/tests_common.txt
  data/tests/tests_framework.txt
  data/tests/tests_wormhole_navigation.txt
  source/Test.cpp
  source/Test.h
  source/main.cpp
Labels: cd/ci/testing

#5776 Fix dragAcceleration formula
  source/Ship.cpp
Labels: bug

#5763 Fix: Dealing with the Puffin availability and problems with the Lost in the EW mission
  data/remnant/remnant missions.txt
  data/remnant/remnant ships.txt
Labels: content

#5722 Tweak: Adding Reverse Thrusters to the stock Star Queen
  data/human/ships.txt
Labels: content

#5700 Tweak: Buffing the Heavy Shuttle
  data/human/ships.txt
Labels: balance

#5695 Content: Creating a Person ship for Brick
  copyright
  data/persons.txt
  images/ship/modified boxwing.png
  images/thumbnail/modified boxwing.png
Labels: content

#5792 Content: Adding the Capybara & X1100 Reverse Thrusters
  copyright
  data/human/engines.txt
  data/human/sales.txt
  images/outfit/reverse thruster ion.png
  images/outfit/reverse thruster plasma.png
Labels: content

#6175 fix(ui): Capitalize words after whitespace in cargo strings
  source/text/Format.cpp
  tests/src/text/test_format.cpp
Labels: bug

#5180 Replace modulo reduction with faster, better integer multiplication
  source/Random.cpp
Labels: mechanics

#6080 Ember Waste Raiding Economy Adjustments (aka changes to the cargo for Remnant and Korath Raiders, and adding missing ships to fleets)
  data/ka'het/ka'het.txt
  data/korath/korath.txt
  data/remnant/remnant.txt
Labels: content

#5793 Content: Creating light secondary weapon pods.
  copyright
  data/human/events.txt
  data/human/sales.txt
  data/human/weapons.txt
  images/outfit/javelin mini pod.png
  images/outfit/meteor pod.png
  images/outfit/rocket launcher.png
  images/outfit/rocket pod.png
  images/outfit/sidewinder pod.png
  images/outfit/torpedopod.png
  images/outfit/typhoonpod.png
Labels: content

#3621 Multiple outlines in mask.
  source/Mask.cpp
  source/Mask.h
  source/Ship.cpp
Labels: enhancement, mechanics

#5786 More news lines
  data/human/news.txt
Labels: content

#6161 feat(content): Add a Pirate-world mission about extortion
  data/human/transport missions.txt
Labels: content

#5837 refactor(content): Buff civilian Coalition ships
  data/coalition/coalition ships.txt
Labels: balance

#6169 Adds a mission where the player is invited to a Coalition university seminar
  data/coalition/coalition missions.txt
Labels: content

#5927 feat(content): Add a mission transporting a human to Hai space
  data/human/transport missions.txt
Labels: content

#5983 Boarding: Give <count> x <mass> even if <mass> is 1
  source/BoardingPanel.cpp
Labels: mechanics

#5975 Created four new damage types that deal DoT to shields, hull, fuel, and heat
  data/effects.txt
  data/tooltips.txt
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/Ship.h
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#5941 MapOutfitterPanel: show contents of planetary storage
  source/Color.cpp
  source/Color.h
  source/MapOutfitterPanel.cpp
  source/MapOutfitterPanel.h
  source/MapSalesPanel.cpp
  source/MapSalesPanel.h
Labels: mechanics

#4304 Better formatting for decimal numbers.
  source/text/Format.cpp
  tests/src/text/test_format.cpp
Labels: mechanics

#6174 Add crossfade effect when haze is changing
  source/DrawList.cpp
  source/DrawList.h
  source/Engine.cpp
  source/GameData.cpp
  source/GameData.h
  source/StarField.cpp
  source/StarField.h
Labels: enhancement
