Repository endless-sky/endless-sky, pull requests merged in 2021-07, with the labels that each got.

#5898 Coalition Folklore: Arachi
  data/coalition/coalition missions.txt
Labels: content

#5753 Rename "hit effect" for hazards to "target effect".
  data/hazards.txt
  source/Engine.cpp
  source/Ship.cpp
  source/Ship.h
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#5974 Expand the number of normal swizzles from 7 to all possible 27
  source/Engine.cpp
  source/ShipInfoPanel.cpp
  source/SpriteShader.cpp
Labels: mechanics

#5988 Only lower reputation due to atrocities if governments are friendly
  source/Planet.cpp
  source/Politics.cpp
Labels: mechanics

#6093 feat: Fines in mission actions
  source/MissionAction.cpp
  source/MissionAction.h
Labels: enhancement

#6095 feat: Ignore flotsam that was explicitly dumped by same government
  source/AI.cpp
  source/Engine.cpp
  source/Flotsam.cpp
  source/Flotsam.h
  source/Ship.cpp
  source/Ship.h
Labels: mechanics

#5870 Coalition Folklore: Kimek
  data/coalition/coalition missions.txt
Labels: content

#5809 Make some Remnant news comprehensible after completing sign studies
  data/remnant/remnant news.txt
Labels: content

#6101 Don't spam "does not have enough crew" message until it clears the queue.
  changelog
  source/Ship.cpp
Labels: mechanics

#6100 Swizzle the Emerald Sword (And Black Diamond)
  credits.txt
  data/sheragi/sheragi ships.txt
Labels: content

#6098 feat: Unify weapons and hazards Ship::TakeDamage() function
  source/Engine.cpp
  source/Ship.cpp
  source/Ship.h
Labels: mechanics

#6109 feat(UI): Add playtime tracker to Player Info Panel
  source/PlayerInfoPanel.cpp
Labels: enhancement

#6091 Fix captured fighters don't dock in free escort bays #6074
  source/Ship.cpp
Labels: bug

#6106 Allow the map to be opened when at the end of a conversation
  source/ConversationPanel.cpp
Labels: bug

#6113 Draw any gun hardpoints under the ship (by default)
  data/persons.txt
  source/Armament.cpp
  source/Armament.h
  source/Engine.cpp
  source/Hardpoint.cpp
  source/Hardpoint.h
  source/Ship.cpp
Labels: mechanics

#6085 feat: Add ability to fire all secondary weapons
  source/AI.cpp
  source/Engine.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: mechanics

#6110 feat(UI): Provide more detail/terminology for combat rating
  source/PlayerInfoPanel.cpp
Labels: enhancement

#6114 Create a hardpoint sprite for nuclear missiles
  data/human/weapons.txt
  images/hardpoint/nuke.png
Labels: content

#5971 Allow outfit and ship categories to be customized in the data files
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  data/categories.txt
  source/CategoryTypes.h
  source/Engine.cpp
  source/GameData.cpp
  source/GameData.h
  source/LocationFilter.cpp
  source/MapSalesPanel.cpp
  source/Outfit.cpp
  source/Ship.cpp
  source/Ship.h
  source/ShipInfoDisplay.cpp
  source/ShipInfoPanel.cpp
  source/ShopPanel.cpp
Labels: enhancement

#5904 Coalition: Alpha encounter
  data/coalition/coalition missions.txt
Labels: content

#5940 Dialogue changes about Deep Archaeology due to player's knowledge
  data/hai/hai missions.txt
  data/sheragi/archaeology missions.txt
Labels: content

#5972 Allow choices of phrases to have weights
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  source/Phrase.cpp
  source/Phrase.h
  source/WeightedList.h
  tests/src/test_weightedList.cpp
Labels: enhancement

#5973 Update human names to make use of phrase expansions, text replacements, and choice weights
  data/human/hails.txt
  data/human/names.txt
Labels: content

#6107 Don't leak the destination of invisible missions from the special marker
  source/Mission.cpp
Labels: bug

#6092 Change Default MinimumHull Formula
  data/tooltips.txt
  source/Ship.cpp
Labels: mechanics

#5730 Only display empty planet error message if moving slowly
  source/AI.cpp
  source/AI.h
Labels: mechanics

#6121 Mac: Embed external libraries in bundle before compilation
  .github/workflows/cd.yaml
  .github/workflows/ci.yml
  EndlessSky.xcodeproj/project.pbxproj
  readme-developer.txt
  source/ConditionSet.h
  utils/fetch_sdl2_framework.sh
  utils/set_dylibs_rpath.sh
Labels: cd/ci/testing

#6139 Test: Add minimal unit-test for account.cpp
  tests/src/test_account.cpp
Labels: cd/ci/testing
