Repository endless-sky/endless-sky, pull requests merged in 2021-05, with the labels that each got.

#5853 Set 'Interrupt fast-forward' to off by default
  source/Preferences.cpp
Labels: mechanics

#5916 fix(content): Fix Remnant: Keystone Research missions
  data/remnant/remnant missions.txt
Labels: bug, content

#5956 Update a log entry for the optional FW Quarg mission
  data/human/free worlds checkmate.txt
  data/human/free worlds reconciliation.txt
Labels: content

#5949 Bulk Freighter Sprite for Class C Freighter & old saves (abridged)
  copyright
  data/human/deep missions.txt
  data/human/fleets.txt
  data/human/free worlds checkmate.txt
  data/human/hails.txt
  data/human/jobs.txt
  data/human/sales.txt
  data/human/ships.txt
  data/human/variants.txt
  data/wanderer/wanderer ships.txt
  images/ship/bulk freighter.png
  images/ship/container transport.png
  images/thumbnail/bulk freighter.png
  images/thumbnail/container transport.png
Labels: content

#5945 Update the changelog and credits for v0.9.14
  changelog
  credits.txt
  endless-sky.appdata.xml
Labels: documentation

#5774 Vareti & Telis Engines: Minor Buff
  changelog
  credits.txt
  data/ka'het/ka'het outfits.txt
Labels: balance
