Repository endless-sky/endless-sky, pull requests merged in 2021-11, with the labels that each got.

#5715 Feature: Parallax stars/haze while flying
  source/Preferences.cpp
  source/PreferencesPanel.cpp
  source/StarField.cpp
Labels: enhancement

#5704 Update readme-developer to Markdown, centralizing build instructions
  README.md
  readme-developer.md
  readme-developer.txt
Labels: documentation

#6216 Fix hardpoints not being cleared when overwriting a ship's outfits.
  source/Armament.cpp
  source/Armament.h
  source/Ship.cpp
Labels: bug

#5437 Spaceport Culture
  data/hai/hai culture conversations.txt
  data/human/culture conversations.txt
Labels: content

#6343 feat(content): Additonal Disabled Hails
  data/human/hails.txt
Labels: content

#6356 feat(mechanics): Customizable text substitutions
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  source/GameData.cpp
  source/GameData.h
  source/GameEvent.cpp
  source/Mission.cpp
  source/Mission.h
  source/MissionAction.cpp
  source/Ship.cpp
  source/TextReplacements.cpp
  source/TextReplacements.h
Labels: enhancement

#6351 feat(mechanics): reputation changes for scanning and interaction with drones
  source/AI.cpp
  source/BoardingPanel.cpp
  source/Government.cpp
  source/Outfit.cpp
  source/Ship.cpp
  source/Ship.h
Labels: enhancement

#6360 Add the ability for governments to be provoked when starting a scan.
  source/Government.cpp
  source/Government.h
  source/Ship.cpp
  source/ShipEvent.h
Labels: enhancement

#6362 Content: Making the Remnant Secretive (aka scan-hostile)
  data/governments.txt
  data/remnant/remnant missions.txt
  data/remnant/remnant ships.txt
Labels: content

#6366 refactor(content): Standardize map data
  data/map.txt
Labels: content
