Repository endless-sky/endless-sky, pull requests merged in 2021-03, with the labels that each got.

#4204 feat: Overhaul jamming and tracking to make them more fun and realistic
  data/tooltips.txt
  source/Projectile.cpp
Labels: balance, mechanics

#4212 Adjust human guided missiles to adjust to jamming and tracking changes
  data/human/weapons.txt
Labels: balance

#5791 Fix: Remnant: Keystone Deliveries and Research sequencing.
  data/remnant/remnant missions.txt
Labels: bug
