Repository endless-sky/endless-sky, pull requests merged in 2021-01, with the labels that each got.

#5564 Fix: Improved reverse thruster behavior for landing
  source/AI.cpp
Labels: bug

#5581 Adding to the Inhibitor's description
  data/remnant/remnant outfits.txt
Labels: content

#5575 feat: Split arrival distance into hyperdrive and jump-drive version.
  data/map.txt
  source/Ship.cpp
  source/System.cpp
  source/System.h
Labels: enhancement

#5622 Feature: Additional Tutorials
  data/help.txt
  source/BankPanel.cpp
  source/Hazard.cpp
  source/MainPanel.cpp
  source/MapDetailPanel.cpp
  source/MapOutfitterPanel.cpp
  source/MapShipyardPanel.cpp
  source/MissionPanel.cpp
Labels: enhancement

#5613 Ka'het Expansion
  copyright
  data/hai/hai outfits.txt
  data/human/engines.txt
  data/ka'het/ka'het outfits.txt
  data/ka'het/ka'het ships.txt
  data/ka'het/ka'het.txt
  images/effect/ion explosion~0.png
  images/effect/ion explosion~1.png
  images/effect/ion explosion~2.png
  images/effect/ion explosion~3.png
  images/effect/ion explosion~4.png
  images/effect/ionball ring+00.png
  images/effect/ionball ring+01.png
  images/effect/ionball ring+02.png
  images/effect/ionball ring+03.png
  images/effect/ionball ring+04.png
  images/effect/ionball ring+05.png
  images/effect/ionball ring+06.png
  images/effect/ionball ring+07.png
  images/effect/ionball ring+08.png
  images/effect/ionball ring+09.png
  images/effect/ionball ring+10.png
  images/effect/ionball ring+11.png
  images/outfit/ka'het grand restorer.png
  images/outfit/ka'het nullifier.png
  images/outfit/ka'het vareti engine.png
  images/projectile/ionball+0.png
  images/projectile/ionball+1.png
  images/projectile/ionball+2.png
  images/ship/vareti'het.png
  images/thumbnail/vareti'het.png
  sounds/ionball.wav
Labels: content

#5624 make zoom work with numpad keys
  source/MainPanel.cpp
  source/MapPanel.cpp
Labels: mechanics

#5619 Shooting Star Expansion
  copyright
  data/persons.txt
  images/outfit/rock 0.png
  images/outfit/rock 1.png
  images/outfit/rock 2.png
  images/outfit/rock 3.png
  images/outfit/rock 4.png
Labels: content

#5634 Add Ship Info tutorial
  data/help.txt
  source/ShipInfoPanel.cpp
  source/ShipInfoPanel.h
Labels: enhancement

#5111 Remant/Deep - Conversation Option and Remnant Awareness
  data/human/deep missions.txt
  data/human/transport missions.txt
  data/remnant/remnant missions.txt
Labels: content

#5580 Tweak: Giving the Remnant Engines a Niche
  data/remnant/remnant outfits.txt
Labels: balance

#5651 Save human cultural data for later
  data/remnant/remnant missions.txt
  data/wanderer/wanderers start.txt
Labels: content

#5652 Standardize capitalization of Quantum Key Stone/quantum keystone
  data/human/deep missions.txt
  data/map.txt
  data/remnant/remnant missions.txt
Labels: content

#5640 Pwt flares
  copyright
  data/sheragi/sheragi outfits.txt
  images/effect/pwaveflare+0.png
  images/effect/pwaveflare+1.png
  images/effect/pwaveflare+2.png
  images/effect/pwaveflare+3.png
Labels: content

#5639 Fix: Culling 11 visitable objects from Remnant space
  data/map.txt
Labels: bug

#3462 Preserve undefined reference names when saving
  source/AI.cpp
  source/CargoHold.cpp
  source/DistanceMap.cpp
  source/DistanceMap.h
  source/Effect.cpp
  source/Effect.h
  source/Engine.cpp
  source/Fleet.cpp
  source/Fleet.h
  source/FogShader.cpp
  source/GameData.cpp
  source/GameEvent.cpp
  source/GameEvent.h
  source/Government.cpp
  source/Government.h
  source/LocationFilter.cpp
  source/LocationFilter.h
  source/MapDetailPanel.cpp
  source/MapOutfitterPanel.cpp
  source/MapPanel.cpp
  source/MapPanel.h
  source/MapSalesPanel.cpp
  source/MapShipyardPanel.cpp
  source/Mission.cpp
  source/Mission.h
  source/MissionAction.cpp
  source/MissionAction.h
  source/MissionPanel.cpp
  source/NPC.cpp
  source/NPC.h
  source/Outfit.cpp
  source/Outfit.h
  source/OutfitterPanel.cpp
  source/Planet.cpp
  source/Planet.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/Ship.cpp
  source/Ship.h
  source/StartConditions.cpp
  source/StartConditions.h
  source/System.cpp
  source/System.h
Labels: bug, mechanics

#5642 Change a few imperial units to SI
  data/human/free worlds middle.txt
  data/human/transport missions.txt
  data/map.txt
  data/wanderer/wanderers start.txt
Labels: content

#5648 Update Sheragi Archaeology missions
  data/governments.txt
  data/hai/hai missions.txt
  data/map.txt
  data/sheragi/archaeology missions.txt
  data/sheragi/sheragi outfits.txt
  data/sheragi/sheragi ships.txt
  data/wanderer/wanderers start.txt
Labels: content

#5643 Tweak: Looking at the Penguin's mobility in light of the Remnant Engines tweak
  data/remnant/remnant ships.txt
Labels: balance

#5661 Asteroid and ship selection enhancements
  source/Engine.cpp
  source/Ship.cpp
Labels: enhancement

#5665 Update references to population sizes of human worlds
  data/intro missions.txt
  data/map.txt
Labels: content

#5668 Fix Typo in "Raid Warning"
  data/human/jobs.txt
Labels: bug

#5669 Change Kestrels to use new bay syntax
  data/human/kestrel.txt
  data/persons.txt
Labels: content

#5674 Add some new spaceport messages.
  data/human/news.txt
Labels: content
