Repository endless-sky/endless-sky, pull requests merged in 2021-12, with the labels that each got.

#6277 Add updated Republic Navy ships by Gefüllte Taubenbrust
  copyright
  credits.txt
  data/human/ships.txt
  images/ship/auxiliaryc.png
  images/ship/auxiliaryh.png
  images/ship/auxiliaryt.png
  images/ship/carrier.png
  images/ship/combat drone.png
  images/ship/cruiser.png
  images/ship/frigate.png
  images/ship/gunboat.png
  images/ship/lance.png
  images/ship/rainmaker.png
  images/thumbnail/auxiliaryc.png
  images/thumbnail/auxiliaryh.png
  images/thumbnail/auxiliaryt.png
  images/thumbnail/carrier.png
  images/thumbnail/combat drone.png
  images/thumbnail/cruiser.png
  images/thumbnail/frigate.png
  images/thumbnail/gunboat.png
  images/thumbnail/lance.png
  images/thumbnail/rainmaker.png
Labels: content

#6347 Highlight conversation choice when hovering with the mouse.
  source/ConversationPanel.cpp
  source/ConversationPanel.h
Labels: enhancement

#6378 Standardize habitable ranges
  copyright
  data/map.txt
  data/stars.txt
  images/star/wr0.png
  images/star/wr1+.jpg
Labels: content

#6414 Fix Adaptive VSync detection.
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  source/FogShader.cpp
  source/GameWindow.cpp
  source/LoadPanel.cpp
  source/MainPanel.cpp
  source/MapPanel.cpp
  source/MenuPanel.cpp
  source/PreferencesPanel.cpp
  source/Shader.h
  source/ShopPanel.cpp
  source/Sprite.cpp
  source/StarField.h
  source/opengl.cpp
  source/opengl.h
  source/text/Font.h
Labels: bug

#6279 Async loading of data files.
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  data/interfaces.txt
  data/tests/tests_save_load.txt
  source/Engine.cpp
  source/Files.h
  source/GameData.cpp
  source/GameData.h
  source/GameLoadingPanel.cpp
  source/GameLoadingPanel.h
  source/MenuPanel.cpp
  source/MenuPanel.h
  source/PlanetPanel.cpp
  source/SpriteQueue.cpp
  source/SpriteQueue.h
  source/Test.cpp
  source/UI.cpp
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  source/main.cpp
Labels: mechanics

#6372 Add spellchecking CI with codespell.
  .codespell.exclude
  .github/path-filters.yml
  .github/workflows/ci.yml
Labels: cd/ci/testing

#6168 Don't update carry swizzle when undocking/launching.
  source/Ship.cpp
  source/Ship.h
Labels: mechanics

#6325 fix(integration-test): Adjust EW Navigation test dates to avoid tutorial prompt
  data/tests/tests_wormhole_navigation.txt
Labels: cd/ci/testing

#6361 Defined minable separately from uninstallable
  data/harvesting.txt
  source/Engine.cpp
  source/MapOutfitterPanel.cpp
  source/OutfitInfoDisplay.cpp
  source/TradingPanel.cpp
Labels: mechanics
