Repository endless-sky/endless-sky, pull requests merged in 2021-02, with the labels that each got.

#5667 Ships with "disables" personality no longer kill plundered ships
  data/human/fleets.txt
  data/remnant/remnant.txt
  source/AI.cpp
  source/Ship.cpp
Labels: mechanics

#5681 Player cannot attempt to hail / land / jump / board / whatever while landing / departing
  source/AI.cpp
  source/MainPanel.cpp
Labels: bug

#5683 Conflicting keybindings are saved
  data/interfaces.txt
  source/Command.cpp
  source/PreferencesPanel.cpp
Labels: mechanics

#5682 Fix: Missing link in Remnant: Postverta Reveal event
  data/map.txt
  data/remnant/remnant missions.txt
Labels: bug

#5689 Greatly increase flotsam lifetimes and add drag
  source/Flotsam.cpp
  source/Flotsam.h
Labels: mechanics

#5633 Fix: Remnant area issues: Replacing the World Ship with the Dredger
  copyright
  data/korath/korath ships.txt
  data/korath/korath.txt
  data/remnant/remnant missions.txt
  images/ship/dredger.png
  images/thumbnail/dredger.png
Labels: content

#5705 Add .gitmodules to ignored files
  .gitignore
Labels: documentation

#5703 Dredger visual update
  data/korath/korath ships.txt
  images/ship/dredger.png
  images/thumbnail/dredger.png
Labels: content

#5707 feat: Print firing and hit forces in weapons table overview
  source/GameData.cpp
Labels: documentation

#5626 Content: "Remnant: Expanded Horizons Storms 1"
  data/hazards.txt
  data/remnant/remnant missions.txt
Labels: content

#5721 On accepting mystery cube missions, sometimes give the player a more …
  data/human/deep jobs.txt
Labels: content

#5735 Fix: Making Postverta Properly Hidden
  data/map.txt
  data/remnant/remnant missions.txt
Labels: content

#5728 Don't mention insurance report in Sparrow description
  data/human/ships.txt
Labels: bug, content

#5733 Ignore some of player's input while landing
  source/AI.cpp
Labels: bug

#5512 Added ability for plugin creators to define multiple starts, and for players to choose between them.
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  data/interfaces.txt
  data/start.txt
  images/_menu/buttonless side panel.png
  images/_menu/scenario panel.png
  source/CoreStartData.cpp
  source/CoreStartData.h
  source/Engine.cpp
  source/GameData.cpp
  source/GameData.h
  source/GameWindow.h
  source/LoadPanel.cpp
  source/LoadPanel.h
  source/MainPanel.cpp
  source/MapDetailPanel.cpp
  source/MapOutfitterPanel.cpp
  source/MapShipyardPanel.cpp
  source/MenuPanel.cpp
  source/MenuPanel.h
  source/MissionPanel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/StartConditions.cpp
  source/StartConditions.h
  source/StartConditionsPanel.cpp
  source/StartConditionsPanel.h
Labels: enhancement

#5702 Void sprite corrections
  copyright
  images/land/nasa9.jpg
  images/scene/penguinscene.jpg
Labels: content

#5653 Changelog for v0.9.13
  changelog
  credits.txt
  endless-sky.appdata.xml
Labels: documentation
