Repository endless-sky/endless-sky, pull requests merged in 2021-09, with the labels that each got.

#6245 fix(content) Overhaul illegal good, drug, and slave missions
  data/dialog phrases.txt
  data/human/pirate jobs.txt
Labels: content

#6243 fix(content): Define and sort illegal cargoes better
  data/commodities.txt
Labels: content

#4588 Add a new "scale" attribute to sprites
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  source/Body.cpp
  source/Body.h
  source/GameData.cpp
  source/GameData.h
  source/ImageSet.cpp
  source/Mask.cpp
  source/Mask.h
  source/MaskManager.cpp
  source/MaskManager.h
  source/Sprite.cpp
  source/Sprite.h
Labels: enhancement

#6253 Don't reparent mission NPCs to NPC ships that haven't been spawned
  source/AI.cpp
Labels: bug

#5157 Allow conversations to grant payments, trigger events, create log entries, and more
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  source/Conversation.cpp
  source/Conversation.h
  source/ConversationPanel.cpp
  source/GameAction.cpp
  source/GameAction.h
  source/MissionAction.cpp
  source/MissionAction.h
  source/NPC.cpp
  source/StartConditions.cpp
  source/main.cpp
Labels: enhancement

#6265 Implement conversation payments into some missions
  data/human/transport missions.txt
Labels: content
