Repository endless-sky/endless-sky, pull requests merged in 2022-11, with the labels that each got.

#7467 Two small improvements to the PR template
  .github/pull_request_template.md
Labels: documentation

#7425 feat(dpi-support): Use SDL for Windows high dpi support
  endless-sky.exe.manifest
  source/GameWindow.cpp
  source/WinApp.rc
  utils/set_version.sh
Labels: refactor

#7509 doc(requirements): Update the system requirements
  README.md
Labels: documentation

#7508 feat(docs): Adding Lia Gerty and MasterOfGrey as Faction Authors for Korath and Hai respectively
  credits.txt
Labels: documentation

#7510 Typo fixes
  data/coalition/coalition missions.txt
  data/human/deep missions.txt
  data/human/free worlds 0 prologue.txt
  data/human/free worlds 1 start.txt
  data/human/pirate jobs.txt
  data/korath/korath missions.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant commodities.txt
  data/remnant/remnant events.txt
Labels: content, text - short

#7484 doc(PR template): Make automated tests an explicit item in the PR template.
  .github/pull_request_template.md
Labels: documentation

#7534 feat(new test): Test for flying with only an aterburner as regular engine
  tests/integration/config/plugins/integration-tests/data/tests/tests_afterburn_flight.txt
Labels: cd/ci/testing

#7499 fix(mechanics): Surveillance personality no longer overrides staying
  source/AI.cpp
Labels: bug

#7520 feat(testing): Better handling of known failing tests
  source/Test.cpp
  source/Test.h
  source/main.cpp
Labels: cd/ci/testing

#7485 [Mechanics] Drag Reduction Attribute
  data/tooltips.txt
  source/AI.cpp
  source/Outfit.cpp
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/Ship.h
  source/ShipInfoDisplay.cpp
Labels: enhancement

#7537 feat(test): Include known failures and missing features in integration tests to run
  endless-sky.6
  source/Test.cpp
  source/Test.h
  source/main.cpp
  tests/integration/config/plugins/integration-tests/data/tests/tests_ship_sale.txt
  tests/integration/run_tests.sh
Labels: cd/ci/testing

#7436 feat(content): Hai Transports: Scarab & Cicada
  copyright
  data/hai/hai ships.txt
  images/ship/hai cicada.png
  images/ship/hai scarab.png
  images/thumbnail/hai cicada.png
  images/thumbnail/hai scarab.png
Labels: content, art

#7526 fix(UI): Don't duplicate government entries in the map key
  source/Color.cpp
  source/Color.h
  source/MapDetailPanel.cpp
Labels: bug

#7492 fix?(content): HR Streamline events that change systems
  data/hai/hai reveal 3 early.txt
  data/hai/hai reveal 6 end.txt
  data/hai/hai reveal 7 epilogue.txt
Labels: content

#7517 fix(content): HR Cumulative Playthrough Edits
  data/hai/hai missions.txt
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 2 start.txt
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal 6 end.txt
  data/hai/hai.txt
Labels: content

#7518 Move the "Deep Space" systems from Hai Reveal away from the Coalition
  data/map.txt
Labels: content

#7512 Changing wording and syntax in Hai Revealed 1 - 4
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 2 start.txt
  data/hai/hai reveal 3 early.txt
  data/hai/hai reveal 4 middle.txt
Labels: content, text - long

#6193 Scanner Changes
  data/tooltips.txt
  source/Ship.cpp
Labels: mechanics

#7019 New ships & outfits for the Unfettered
  copyright
  data/hai/hai fleets.txt
  data/hai/hai outfits.txt
  data/hai/hai ships.txt
  data/hai/hai.txt
  images/hardpoint/hai ionic turret.png
  images/outfit/hai ionic blaster.png
  images/outfit/hai ionic turret.png
  images/outfit/tripulse shredder.png
  images/outfit/value detector.png
  images/projectile/ionic blast~0.png
  images/projectile/ionic blast~1.png
  images/projectile/ionic blast~2.png
  images/ship/hai sea scorpion.png
  images/thumbnail/hai sea scorpion.png
  sounds/ion blast.wav
Labels: content, art, text - short

#7553 removed unnecessary text in deep missions_Stone of Our Fathers 6
  data/human/deep missions.txt
Labels: content, text - short

#7250 Resized Hai stations
  data/map.txt
Labels: art

#7466 balance: Put some grab-strikes on the mining Rano'erek so it can defend itself
  data/korath/korath.txt
Labels: balance

#7264 feat(content): Korath Emergency Ships (Rai'alorej & Ikatila'ej)
  copyright
  data/korath/korath ships.txt
  data/korath/korath weapons.txt
  data/korath/korath.txt
  data/map.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant events.txt
  images/hardpoint/factory/microbot factory-00.png
  images/hardpoint/factory/microbot factory-01.png
  images/hardpoint/factory/microbot factory-02.png
  images/hardpoint/factory/microbot factory-03.png
  images/hardpoint/factory/microbot factory-04.png
  images/hardpoint/factory/microbot factory-05.png
  images/hardpoint/factory/microbot factory-06.png
  images/hardpoint/factory/microbot factory-07.png
  images/hardpoint/factory/microbot factory-08.png
  images/hardpoint/factory/microbot factory-09.png
  images/hardpoint/factory/microbot factory-10.png
  images/hardpoint/factory/microbot factory-11.png
  images/hardpoint/factory/microbot factory-12.png
  images/hardpoint/factory/microbot factory-13.png
  images/hardpoint/factory/microbot factory-14.png
  images/ship/ikatila-ej.png
  images/ship/rai-alorej.png
  images/thumbnail/ikatila-ej.png
  images/thumbnail/rai-alorej.png
Labels: content, art

#7561 [Fix] Coalition Asteroid Energy Reduction
  data/map.txt
Labels: content

#7556 Content(artwork): new ionic turret image and ionic blaster projectile image quickfix
  copyright
  data/hai/hai outfits.txt
  images/hardpoint/hai ionic turret.png
  images/outfit/hai ionic turret.png
  sounds/ionic blast.wav
Labels: bug, art

#7562 feat(content): Korath Probes, Ra'at Adjustment
  copyright
  data/korath/korath ships.txt
  data/korath/korath variants.txt
  data/korath/korath.txt
  data/map.txt
  images/ship/kas-ik tek 7.png
  images/thumbnail/kas-ik tek 7.png
Labels: balance, content, art, text - short

#7565 fix(map): Prevent dereferencing nullpointer
  source/MapPanel.cpp
Labels: bug

#7573 Fix Typo in "Remnant: Cognizance 9"
  data/remnant/remnant 2 cognizance.txt
Labels: text - short

#7563 Make Terraforming Tundra's fight less brutal
  data/human/human missions.txt
Labels: balance, text - short

#7551 Small Hai Reveal 1 changes
  data/hai/hai reveal 1 intro.txt
Labels: content, text - short

#7545 Bugfix(AI): account for special damages for forbearing
  source/Ship.cpp
Labels: mechanics

#7462 Make campaign missions offer more consistently
  data/human/deep jobs.txt
  data/human/deep missions.txt
  data/human/free worlds 0 prologue.txt
Labels: balance, content

#7494 Clean up the end of Skadenga Saga
  data/human/deep missions.txt
Labels: content, text - short

#7473 Inform the player if they lose their jump drive during FW
  data/human/free worlds 3 reconciliation.txt
Labels: content, text - short

#7548 [Mechanic] Inertia Reduction
  data/tooltips.txt
  source/AI.cpp
  source/Outfit.cpp
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/Ship.h
  source/ShipInfoDisplay.cpp
Labels: enhancement

#7505 Record distribution of off world mission cargo and passengers
  source/PlayerInfo.cpp
Labels: bug

#7589 Fixed Typo in "Remnant: Cognizance 25"
  data/remnant/remnant 2 cognizance.txt
Labels: typo

#7549 feat(ui): Park/Unpark Escorts in System
  data/interfaces.txt
  source/PlayerInfoPanel.cpp
Labels: mechanics

#7524 Feature: Departure distance
  source/AI.cpp
  source/Ship.cpp
  source/System.cpp
  source/System.h
Labels: enhancement

#7452 feat(UI): Support spreading settings across multiple pages
  data/interfaces.txt
  source/PreferencesPanel.cpp
  source/PreferencesPanel.h
Labels: enhancement

#7602 Fix race condition inside the MaskManager
  source/MaskManager.cpp
  source/MaskManager.h
Labels: bug

#7596 [mission tweak] Adjust on visits for a couple Coalition missions
  data/coalition/coalition missions.txt
Labels: bug, text - short

#7147 test(coding-style): Expanded CI code style test
  .github/workflows/ci.yml
  source/AI.cpp
  source/MissionPanel.cpp
  source/MissionPanel.h
  source/PlanetLabel.cpp
  source/PrintData.cpp
  source/Ship.cpp
  source/SpriteShader.cpp
  source/Test.cpp
  tests/unit/src/test_conditionsStore.cpp
  utils/check_code_style.py
Labels: cd/ci/testing, waiting on reviewer

#6132 feat(wormholes): Make wormholes first class citizens
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  data/map.txt
  data/wanderer/wanderers.txt
  source/AI.cpp
  source/DistanceMap.cpp
  source/Engine.cpp
  source/GameData.cpp
  source/GameData.h
  source/GameEvent.cpp
  source/MapPanel.cpp
  source/Planet.cpp
  source/Planet.h
  source/Ship.cpp
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  source/Wormhole.cpp
  source/Wormhole.h
Labels: enhancement, waiting on reviewer

#6768 feat(plugins): Add "Open Plugins" button to the plugins panel.
  data/interfaces.txt
  images/ui/plugins panel.png
  source/Files.cpp
  source/Files.h
  source/PreferencesPanel.cpp
Labels: enhancement

#7062 feat(Outfit Names): Differentiate between true outfit name and outfit display name
  source/Armament.cpp
  source/BoardingPanel.cpp
  source/CargoHold.cpp
  source/Depreciation.cpp
  source/Engine.cpp
  source/GameAction.cpp
  source/LocationFilter.cpp
  source/MainPanel.cpp
  source/MapOutfitterPanel.cpp
  source/MissionAction.cpp
  source/Outfit.cpp
  source/Outfit.h
  source/OutfitInfoDisplay.cpp
  source/OutfitterPanel.cpp
  source/PlayerInfo.cpp
  source/PrintData.cpp
  source/Ship.cpp
  source/ShipInfoDisplay.cpp
  source/ShipInfoPanel.cpp
  source/UniverseObjects.cpp
  source/comparators/ByName.h
Labels: enhancement

#6407 feat(fining, attrocity): allow government to define illegal goods and atrocities
  source/CargoHold.cpp
  source/CargoHold.h
  source/Government.cpp
  source/Government.h
  source/Politics.cpp
Labels: enhancement, waiting on reviewer

#7624 chore(code style): Fix code style issues in master
  source/Ship.cpp
Labels: bug, cd/ci/testing

#7626 Fix path filter for the integration tests
  .github/path-filters.yml
Labels: bug, cd/ci/testing

#7634 feat(capture): Indicate crew transfer on ship capture
  source/BoardingPanel.cpp
  source/Ship.cpp
  source/Ship.h
Labels: enhancement

#7630 Tests: false positive fix: increase capacities of test ships
  tests/integration/config/plugins/integration-tests/data/tests/tests_afterburn_flight.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_disown.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_wormhole_navigation.txt
Labels: bug, cd/ci/testing

#7623 Testing: new integration test for changing of illegal outfits per government
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
Labels: cd/ci/testing

#7635 Hai Reveal: Fix Agent Kopkow log
  data/hai/hai reveal 5 philosophers.txt
Labels: bug

#7633 Ensure Remnant Gascraft event compatibility
  data/remnant/remnant events.txt
Labels: bug

#7614 feat(content): MasterOfGrey Person Ship
  copyright
  data/persons.txt
  images/ship/modified ladybug.png
Labels: content, art

#7603 feat(content): Sound Adjustments
  copyright
  sounds/ion huge~.wav
  sounds/ion rain.wav
  sounds/particle.wav
  sounds/proton.wav
Labels: sound

#7566 Hai Reveal conversations: reduce text walls in hai reveal 1 intro
  data/hai/hai reveal 1 intro.txt
Labels: content

#7567 Hai Reveal conversations: reduce text walls in hai reveal 3 early
  data/hai/hai reveal 3 early.txt
Labels: content, text - short

#7604 Hai reveal tweaks
  data/governments.txt
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 4 middle.txt
  data/whispering void/critters.txt
Labels: content, text - short

#5440 Feature: Add support for conditional hiding of text or choices in conversations
  source/Conversation.cpp
  source/Conversation.h
  source/ConversationPanel.cpp
  source/ConversationPanel.h
  tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
Labels: enhancement, waiting on reviewer

#7643 Fix bug with outfit display names
  source/Outfit.cpp
Labels: bug

#7649 Fix scanning
  data/coalition/coalition outfits.txt
  data/hai/hai outfits.txt
  data/human/outfits.txt
  data/remnant/remnant outfits.txt
  data/remnant/remnant ships.txt
Labels: bug, balance

#7652 Test fix(integration): check for name working in conversation and initialize variables to 0
  source/ConversationPanel.h
  source/Test.h
  tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
Labels: bug, cd/ci/testing

#7647 Free Worlds typos
  data/human/free worlds 1 start.txt
Labels: typo

#7378 refactor: Move some potentially-expensive jump calculations from Ship to a new JumpNavigation class
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  source/AI.cpp
  source/DistanceMap.cpp
  source/Engine.cpp
  source/Fleet.cpp
  source/JumpTypes.h
  source/MapDetailPanel.cpp
  source/MapPanel.cpp
  source/PlayerInfo.cpp
  source/Ship.cpp
  source/Ship.h
  source/ShipJumpNavigation.cpp
  source/ShipJumpNavigation.h
Labels: refactor

#7665 Fix and clean up closestDeparturePoint calculation
  source/AI.cpp
Labels: bug

#7666 Print an error when a `key` string parses to SDLK_UNKNOWN for integration tests
  source/Test.cpp
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
Labels: cd/ci/testing

#7669 Always calculate attraction/deterrence
  source/Ship.cpp
Labels: bug

#7668 Filter warning messages from integration tests
  tests/integration/run_tests.sh
Labels: cd/ci/testing

#7511 feat(enhancement): Missile Indicator Overlays
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  data/interfaces.txt
  source/AlertLabel.cpp
  source/AlertLabel.h
  source/Engine.cpp
  source/Engine.h
  source/PreferencesPanel.cpp
Labels: enhancement, art

#7672 Fix Remnant Paradise visit branch
  data/remnant/remnant 2 side missions.txt
Labels: bug

#7676 ConversationPanel enter&down keys go past end of choice list when "to display" is used
  source/ConversationPanel.cpp
Labels: bug

#7671 A way to get every planet and system matching a provided LocationFilter
  endless-sky.6
  source/PrintData.cpp
  source/PrintData.h
Labels: enhancement

#7680 Test(integration): ensure that choices cannot go out of bound when to display is used
  tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
Labels: cd/ci/testing

#7659 fix(integration tests): Fix slow GLES integration test
  .github/workflows/ci.yml
  tests/integration/run_tests_headless.sh
Labels: cd/ci/testing

#7651 hai reveal grammar change
  data/hai/hai reveal 4 middle.txt
Labels: content, text - short

#7621 Minor human planet/spaceport descriptions update
  data/human/events.txt
  data/map.txt
Labels: content, text - short

#7500 refactor(content): Human "Slave Crew Rescue" mission
  data/human/boarding missions.txt
Labels: content

#7330 add support for ship bays removal
  source/Ship.cpp
  source/Ship.h
Labels: enhancement

#7109 Make moonbeams available
  copyright
  data/wanderer/wanderer outfits.txt
  data/wanderer/wanderer ships.txt
  data/wanderer/wanderers middle.txt
  data/wanderer/wanderers.txt
  sounds/moonbeam~.wav
Labels: content, text - short, sound

#7691 Fix Echo-Galleon Description
  data/korath/korath ships.txt
Labels: typo

#7571 Hai Reveal conversations: simplify dialog in hai reveal 4 missions A03-A07 and correct a dialog bug
  data/hai/hai reveal 4 middle.txt
Labels: content, text - short

#7570 Hai Reveal conversations: make the Teeneep intro conversation (A02) more concise
  data/hai/hai reveal 4 middle.txt
Labels: content, text - short

#7477 HR: balance devil-hide battle
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 5 philosophers.txt
  data/human/variants.txt
  data/map.txt
  data/whispering void/elenchus.txt
Labels: balance

#7639 fix(content): Address duplicate wormhole issue in 7605
  data/hai/hai reveal 1 intro.txt
Labels: bug

#7694 Fix deprecated `go get` usage in CD release upload
  .github/workflows/cd.yaml
Labels: cd/ci/testing

#7681 Cancel running workflows when starting new ones
  .github/workflows/cd.yaml
  .github/workflows/ci.yml
  .github/workflows/projects_check.yml
  .github/workflows/steam.yml
Labels: cd/ci/testing

#7700 Fix condition for copyright CI
  .github/workflows/projects_check.yml
Labels: cd/ci/testing

#7503 feat(content): Archon Energy buff
  data/drak/drak outfits.txt
  data/drak/drak ships.txt
Labels: bug, balance, content

#7695 feat(content): Superheavy category
  data/categories.txt
  data/korath/korath ships.txt
  data/remnant/remnant ships.txt
  data/sheragi/sheragi ships.txt
Labels: content

#7692 Let out-of-system escorts without fuel plan their next move
  source/AI.cpp
Labels: bug

#7718 Very minor wording change
  data/human/free worlds 1 start.txt
Labels: typo

#7720 CI only: Support file args for check_code_style.py
  utils/check_code_style.py
Labels: cd/ci/testing

#7716 fix typos in copyright file patterns
  copyright
Labels: typo

#7387 Add support for static and dynamic analysis tools
  .gitignore
  SConstruct
Labels: enhancement

#7581 Hai Reveal conversations: dialog improvements to A08 Symbol Identification
  data/hai/hai reveal 4 middle.txt
Labels: content, text - long

#6346 feat(mechanics): added boarding priorities in preference + cycle boarding targets
  source/AI.cpp
  source/Engine.cpp
  source/Engine.h
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
Labels: enhancement

#5997 Link on Linux to new OpenGL ABI
  SConstruct
Labels: enhancement

#7686 Add unit tests and benchmarks for Dictionary
  tests/unit/src/test_dictionary.cpp
Labels: cd/ci/testing

#7726 Fix the project check CI when adding a new test file.
  .github/workflows/projects_check.yml
  EndlessSkyTests.cbp
Labels: cd/ci/testing

#7727 Add missing runtime dependency to the integration tests
  .github/workflows/ci.yml
Labels: cd/ci/testing

#7733 Feat: add a save for the last spaceport
  source/PlayerInfo.cpp
Labels: enhancement

#7730 refactor(code): Remove universal ramscoop
  data/human/outfits.txt
  source/Ship.cpp
Labels: mechanics

#7725 Danforth is now timid when facing Sestor ships in Wanderers: Alpha Surveillance G
  data/wanderer/wanderers start.txt
Labels: content

#7737 Quarg Consider their Outfits and Ships Atrocities
  data/governments.txt
  data/quarg/quarg missions.txt
  data/quarg/quarg.txt
Labels: content, text - short
