Repository endless-sky/endless-sky, pull requests merged in 2022-12, with the labels that each got.

#7690 (Content): Tarazed ships are sold on FW shipyards after Tarazed Diplomacy
  data/human/events.txt
  data/human/free worlds 1 start.txt
  data/map.txt
Labels: content

#7749 Content: address wrong usage of Unfettered fleet (HR)
  data/hai/hai fleets.txt
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 5 philosophers.txt
Labels: bug, content

#7658 Hai Reveal: pirate weapon plot holes, A09 text walls, Teeneep continuity, and more player engagement
  data/hai/hai reveal 3 early.txt
  data/hai/hai reveal 4 middle.txt
Labels: content, text - short

#7689 [Content] Replace 577 Ember Raider With A Korath 582
  data/korath/korath variants.txt
  data/korath/korath.txt
Labels: balance

#7593 Hai Reveal conversations: reduce text walls in missions A12 & A13
  data/hai/hai reveal 4 middle.txt
Labels: content, text - short

#7677 Hai Reveal: Jump Drive plot hole & text walls in B09-B12 & continuity problems & B08 log glitch
  data/hai/hai reveal 5 philosophers.txt
Labels: content, text - short

#7732 Artwork: New Hai Railgun, Railslug, and Railslug Rack sprite
  copyright
  images/outfit/railgun.png
  images/outfit/railslug rack.png
  images/outfit/railslug.png
Labels: art

#7719 Content(mission): Free Worlds side mission to complete Zug's New Port expansion
  data/human/events.txt
  data/human/free worlds side plots.txt
Labels: content, text - short

#7715 Fix(content): Nanachi Pendant description & Remnant: Key Stones (various) checks
  data/hai/hai outfits.txt
  data/remnant/remnant 1 introduction.txt
Labels: bug, content, text - short

#7724 fix(content): Remnant: Tech Retrieval - Expanding the mission description slightly
  data/remnant/remnant 1 introduction.txt
Labels: bug, text - short

#7628 Make it more clear you need to kill chasers
  data/remnant/remnant 2 cognizance.txt
Labels: content, text - short

#7775 Internal: Two helper functions
  source/Engine.cpp
  source/Personality.cpp
  source/Personality.h
  source/Ship.cpp
  source/Ship.h
Labels: mechanics

#7753 rename the last spaceport save to previous spaceport
  source/PlayerInfo.cpp
Labels: mechanics

#7606 Nerf the flamethrower
  data/human/free worlds side plots.txt
  data/human/weapons.txt
Labels: balance

#7664 Hai Reveal: huge continuity error, no text walls in B03-B07, fix other minor problems
  data/governments.txt
  data/hai/hai reveal 5 philosophers.txt
  data/human/variants.txt
Labels: content

#7594 Hai Reveal conversations: in A14 (treaty negotiations) more player engagement and no text walls
  data/hai/hai reveal 4 middle.txt
Labels: content, text - long

#7754 Fix: false positive in integration test
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
Labels: bug

#7705 Add a coarse check on `Mask::Collide`
  source/Mask.cpp
  source/Mask.h
Labels: refactor

#7707 Hai Reveal conversations: bug fix to log entries, remove looping dialog and action choices from part 6
  data/hai/hai reveal 6 end.txt
Labels: content, text - short

#7764 Replacing Solace's landing picture & another better one for Earth
  copyright
  data/map.txt
  images/land/city20.jpg
  images/land/city23.jpg
Labels: art

#7699 fix(tests-output): Don't show condition errors during unit testing
  source/ConditionsStore.cpp
  tests/unit/src/test_conditionsStore.cpp
Labels: cd/ci/testing

#7729 Some fixes to the unit tests
  tests/unit/src/test_esuuid.cpp
  tests/unit/src/text/test_displaytext.cpp
Labels: cd/ci/testing

#7801 Fix oversight in path filters for CI
  .github/path-filters.yml
  .github/workflows/compute-changes.yml
Labels: cd/ci/testing

#7807 Fix crash when opening player info panel with no flagship
  source/PlayerInfoPanel.cpp
Labels: bug

#7743 Improve `CollisionSet::Line`
  source/CollisionSet.cpp
  source/CollisionSet.h
Labels: refactor

#7771 feat(content): Hai Reveal: Add new mission A11-C to provide optional updates on the election.
  data/hai/hai reveal 4 middle.txt
Labels: content, text - short

#7829 Fix 'Fury' appearing too often as a pirate ship name
  data/human/names.txt
Labels: bug, content

#7822 test(test robustness): Add CI to verify the integration tests syntax
  .github/workflows/ci.yml
  source/Test.cpp
  utils/test_parse.sh
Labels: cd/ci/testing

#7820 test(unit-test-buids): Fix test presets not working
  CMakePresets.json
Labels: cd/ci/testing

#7802 test(ui debug delay): Reduce the input delay when debugging integration tests
  source/main.cpp
Labels: cd/ci/testing

#7818 build(portability): Compile in strict C++ mode (without any compiler extensions)
  EndlessSkyLib.cbp
  EndlessSkyTests.cbp
  SConstruct
  source/CMakeLists.txt
  source/ConditionsStore.cpp
  source/OutfitterPanel.cpp
  source/Point.cpp
  source/Point.h
Labels: cd/ci/testing

#7841 Hai: Set Nanachi job to offer at Giverstone
  data/hai/hai missions.txt
Labels: content

#7831 feat(content): Adding an "on waypoint" to the Star Research mission
  data/human/human missions.txt
Labels: content, text - short

#7828 feat(conditions): Add "flagship planet attribute" general condition
  source/PlayerInfo.cpp
  tests/CMakeLists.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_planet_attribute.txt
Labels: enhancement

#7819 Do not offer landing missions in the shipyard or outfitter
  source/ShopPanel.cpp
Labels: mechanics

#7816 Reword Carla Von Hausen description
  data/human/deep missions.txt
Labels: typo

#7796 Feat(content) short range jobs
  data/human/jobs.txt
Labels: content

#7794 feat(content): Six new sets of pirate hails
  data/human/hails.txt
Labels: content

#7792 More date autoconditions
  source/Date.cpp
  source/Date.h
  source/PlayerInfo.cpp
Labels: enhancement

#7791 New autoconditions: `"hyperjumps to (planet|system): <planet|system>"`
  source/PlayerInfo.cpp
  tests/CMakeLists.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_hyperjumps_to_autocondition.txt
Labels: enhancement

#7784 chore(style fix): Content style fixes
  README.md
  data/hai/hai missions.txt
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 2 start.txt
  data/hai/hai reveal 3 early.txt
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal 6 end.txt
  data/hai/hai reveal 7 epilogue.txt
  data/hai/hai reveal news.txt
  data/hai/hai ships.txt
  data/human/boarding missions.txt
  data/human/free worlds side plots.txt
  data/human/variants.txt
  data/korath/korath ships.txt
  data/korath/korath weapons.txt
  data/korath/korath.txt
  data/map.txt
  data/persons.txt
  data/wanderer/wanderers start.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_framework.txt
  tests/unit/README.md
Labels: typo

#7782 fix(content):Fixing Erroneous Scan Speeds
  data/drak/indigenous.txt
  data/hai/hai ships.txt
  data/persons.txt
Labels: bug, content

#7757 Enlarge large syndicate fleet
  data/human/fleets.txt
Labels: balance

#7728 Pug ship descriptions
  data/pug/pug.txt
Labels: content, text - short

#7846 Don't let Laborer have the same destination and source
  data/human/human missions.txt
Labels: bug, content

#7843 fix(minor): HR: "Hai Leaks Response 2B" do not offer on Watcher
  data/hai/hai reveal 1 intro.txt
Labels: bug

#7842 feat(content) Quarg: Giving their engines unique flavor & capabilities
  data/quarg/quarg outfits.txt
Labels: balance, content, text - short

#7855 Update all our versions of Actions we use
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
  .github/workflows/steam.yml
Labels: cd/ci/testing

#7857 Add names to every job
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  .github/workflows/projects_check.yml
  .github/workflows/steam.yml
Labels: cd/ci/testing

#7856 Removes the Ubuntu CD run
  .github/workflows/cd.yaml
Labels: cd/ci/testing

#7858 Don't depend on non-existent job
  .github/workflows/cd.yaml
Labels: cd/ci/testing

#7830 Fix(code): Prevent manual hyperjumping from locking in a planned route, which enables the player to manually change destinations.
  source/AI.cpp
  source/Engine.cpp
Labels: bug, mechanics

#7866 Fix from @vitalchip: Ship::Carry() refuses to carry a disabled ship
  source/Ship.cpp
Labels: bug, mechanics

#7886 Import DefaultEnvironment from Scons
  SConstruct
Labels: cd/ci/testing

#7873 Test parse script improvements
  utils/test_parse.ps1
  utils/test_parse.sh
Labels: cd/ci/testing

#7870 Skadenga: Correct typo
  data/human/deep missions.txt
Labels: typo

#7797 Autoconditions for flagship (base) attributes
  source/PlayerInfo.cpp
  tests/CMakeLists.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
Labels: enhancement

#7704 System invisible fence radius
  source/AI.cpp
  source/System.cpp
  source/System.h
Labels: enhancement

#7872 Simplify data parsing CI jobs
  .github/workflows/ci.yml
Labels: cd/ci/testing

#7698 [Content] Remnant Job To Disable Worldship
  data/korath/korath variants.txt
  data/remnant/remnant 2 side missions.txt
  data/remnant/remnant jobs.txt
Labels: content, text - short

#7622 Enhancement: governments can use foreign penalties instead of their own
  data/governments.txt
  source/Government.cpp
  source/Government.h
  source/Politics.cpp
Labels: bug, enhancement

#7471 Hai Unfettered ballet at Wah Ki
  data/hai/hai fleets.txt
  data/map.txt
Labels: balance, content

#7885 Coalition: Sedlitaris Grammar Change
  data/coalition/coalition missions.txt
Labels: typo

#7887 fix(content): Make Nanachi pre-HR requirements not encourage mega fleets
  data/hai/hai missions.txt
Labels: balance, content

#7884 fix(content): Tweak remnant ground assualt bounty job
  data/remnant/remnant jobs.txt
Labels: bug, content

#7874 FW: Add advice on purchasing multiple outfit scanners
  data/human/free worlds 0 prologue.txt
Labels: content, text - short

#7860 Use dedicated sccache GHA support + Linux support
  .github/sccache/action.yml
  .github/workflows/cd.yaml
  .github/workflows/ci.yml
Labels: cd/ci/testing

#7813 Prevent Remnant Celebration 1 occurring in non-sensical places
  data/map.txt
  data/remnant/remnant 2 side missions.txt
Labels: bug, content

#7835 Add "to accept" ConditionSet
  source/Mission.cpp
  source/Mission.h
  source/PlayerInfo.cpp
  tests/CMakeLists.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_to_accept.txt
Labels: enhancement

#7903 fix(content): Make the Cognizance 32 blocked message work as intended
  data/remnant/remnant 2 cognizance.txt
Labels: bug

#7889 fix(content): HR bugfixes reported in
  data/hai/hai jobs.txt
  data/hai/hai missions.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal 6 end.txt
  data/map.txt
  data/wanderer/wanderers start.txt
Labels: bug, content

#7778 Balance: devil hide fleet tweaking
  data/human/variants.txt
  data/map.txt
  data/whispering void/elenchus.txt
Labels: balance, content

#7907 feat(sounds): Ember Tear Unique SFX
  copyright
  data/remnant/remnant outfits.txt
  sounds/ember tear hit0~.wav
  sounds/ember tear hit~.wav
  sounds/ember tear~.wav
Labels: sound

#7921 change line to Center() as expected by shader
  data/interfaces.txt
  source/Interface.cpp
Labels: bug

#7919 New "flagship landed" autocondition
  source/PlayerInfo.cpp
  tests/integration/config/plugins/integration-tests/data/tests/tests_afterburn_flight.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_model_condition.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_framework.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_shipyard_outfitter_missions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_store_outfits_on_take_off.txt
Labels: enhancement, cd/ci/testing

#7917 Closing some Cppchecks issues
  source/ClickZone.h
  source/CollisionSet.h
  source/DataFile.cpp
  source/Engine.cpp
  source/MapPlanetCard.h
  source/Minable.cpp
  source/Minable.h
  source/Ship.h
  source/ShipInfoPanel.cpp
Labels: refactor

#7799 Add support for debugging integration tests
  CMakePresets.json
  readme-cmake.md
  tests/CMakeLists.txt
  tests/integration/IntegrationTests.cmake
Labels: cd/ci/testing

#7935 fix(content): Gegno Yli Planet Fix
  data/map.txt
Labels: content

#7937 fix(artwork): Tweak Vesvi in Gegno space
  images/planet/vesvi.png
Labels: artwork

#7910 HR Yeertle mission: Change Syndicate refererence to a neutral term
  data/hai/hai reveal 2 start.txt
Labels: typo

#7940 fix missing quote mark in mission dialogue
  data/human/human missions.txt
Labels: typo

#7927 Update post-Sestor Wanderer and Korath jobs, news, etc
  data/korath/korath jobs.txt
  data/korath/korath missions.txt
  data/korath/korath news.txt
  data/wanderer/wanderer jobs.txt
  data/wanderer/wanderer news.txt
  data/wanderer/wanderers middle.txt
Labels: bug

#7925 fix(content): Add clearance to all FW Pug 2C variants
  data/human/free worlds 3 reconciliation.txt
Labels: bug

#7697 Hai Reveal conversations: split up text walls, simplify dialog, and fill minor plot holes in mission [B13] Freedom
  data/hai/hai reveal 5 philosophers.txt
Labels: content, text - short

#7901 Remnant shattered light tweaks
  data/remnant/remnant 2 side missions.txt
Labels: content, text - short

#7869 feat(code): Red Alert visual warning
  copyright
  data/interfaces.txt
  images/ui/red alert.png
  source/Engine.cpp
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
Labels: enhancement, artwork

#7922 Change Cloaking Device's Category to "Unique"
  data/human/outfits.txt
Labels: content

#7844 Sign over copyright of Hai Reveal to MasterOfGrey and Michael Zahniser
  copyright
  data/hai/hai news.txt
  data/hai/hai reveal 2 start.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal news.txt
  data/whispering void/critters.txt
  data/whispering void/elenchus.txt
Labels: documentation

#7875 Content: add tribute fleets for the unfettered
  data/map.txt
Labels: content

#7498 fix?(content): HR Geocoris sequence rework
  data/hai/hai outfits.txt
  data/hai/hai reveal 1 intro.txt
Labels: content

#7945 Fix typos in mission dialogue
  .codespell.exclude
  data/coalition/coalition missions.txt
  data/gegno/gegno intro missions.txt
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 2 start.txt
  data/hai/hai reveal 3 early.txt
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal 7 epilogue.txt
  data/human/deep jobs.txt
  data/human/deep missions.txt
  data/human/free worlds 4 epilogue.txt
  data/human/human missions.txt
  data/kahet/kahet missions.txt
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant 2 side missions.txt
  data/sheragi/archaeology missions.txt
  data/wanderer/wanderers middle.txt
Labels: typo

#7941 [Coalition] Heliarch Reactors Use Antimatter Catalyzed Fusion
  data/coalition/coalition outfits.txt
Labels: content, text - short

#6766 "Hound Racing" spaceport mission
  data/human/human missions.txt
  data/human/outfits.txt
Labels: content, text - short

#7329 Wool smuggling missions
  data/human/human missions.txt
Labels: content, text - long

#7949 Governments can refer to named colours
  source/Color.cpp
  source/Color.h
  source/Government.cpp
  source/Government.h
  source/UniverseObjects.cpp
Labels: enhancement

#7956 Disable various missions for integration tests
  tests/integration/config/plugins/integration-tests/data/disabling troublesome missions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_save_load.txt
Labels: cd/ci/testing

#7965 fix(content)-Gegno-First Contact Gegno Vi slight wording tweak
  data/gegno/gegno intro missions.txt
Labels: typo

#7929 Improvements and fixes to the MacOS CMake build
  CMakeLists.txt
  CMakePresets.json
  readme-cmake.md
  source/Files.cpp
Labels: cd/ci/testing

#7772 Artwork: Update Enforcer Riot Staff and Enforcer Confrontation Gear
  copyright
  images/outfit/enforcer confrontation gear.png
  images/outfit/enforcer riot staff.png
Labels: artwork

#7765 [Enhancement] Starfield Parallax Layers
  source/Engine.cpp
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
  source/StarField.cpp
  source/StarField.h
  source/System.cpp
  source/System.h
Labels: enhancement

#7971 FW: Make Oathkeeper singular to match regiment.
  data/human/free worlds 2 middle.txt
Labels: typo

#7967 Use named colours for governments
  data/governments.txt
Labels: refactor

#7980 Named colours default alpha to 1
  data/governments.txt
  source/UniverseObjects.cpp
Labels: enhancement

#7952 Higher precision CargoHold Free() and Used() reporting
  source/CargoHold.cpp
  source/CargoHold.h
  source/OutfitterPanel.cpp
Labels: bug

#7942 [Mechanic] Flotsam Drop Rate Attribute
  source/Outfit.cpp
  source/Ship.cpp
Labels: enhancement

#7939 Replace 'on offer' with 'to accept' in jobs requiring outfits, and update those jobs
  data/coalition/coalition jobs.txt
  data/hai/hai jobs.txt
  data/human/jobs.txt
  data/human/paradise world jobs.txt
  data/human/pirate jobs.txt
  data/human/syndicate jobs.txt
  data/wanderer/wanderer jobs.txt
Labels: content, text - short

#7968 feat(content): Gegno Intro Adjustments
  data/gegno/gegno intro missions.txt
  data/governments.txt
Labels: content, text - short

#7985 Feat(enhancement): Accept float quality precision for envoiremental effect amount
  source/Hazard.cpp
  source/Hazard.h
  source/Weather.cpp
Labels: enhancement

#7993 Assign `wormhole "Pug Wormhole"` to `planet "Pug Wormhole"`
  data/map.txt
Labels: bug

#7960 feat(graphics): Add a brown haze to systems that are in the center of the dust nebula
  copyright
  data/hai/hai reveal 6 end.txt
  data/map.txt
  images/_menu/haze-brown+0.jpg
  images/_menu/haze-brown+1.jpg
Labels: artwork

#7982 feat(UI) Giving the Star a unique color on the Radar
  data/interfaces.txt
  source/Radar.cpp
  source/Radar.h
  source/StellarObject.cpp
Labels: enhancement

#7976 Update Remnant mission description, GitHub #7975
  data/remnant/remnant 1 introduction.txt
Labels: content, text - short

#7963 feat(content): Adding some hails and news entries that provide hints about TMBR's mission requirements
  data/human/hails.txt
  data/human/news.txt
Labels: content, text - short

#7897 feat(content): New hails for the Free Worlds and the Republic & updates to some existing hails
  data/human/hails.txt
Labels: content, text - short

#7991 Print shipyard or outfitter list with items available in each
  source/PrintData.cpp
  source/PrintData.h
Labels: enhancement

#7992 fix(content): Prevent Earth Day jobs offering with deadlines after Earth Day
  data/human/near earth jobs.txt
Labels: bug

#7994 fixed typo in data/hai outfits
  data/hai/hai outfits.txt
Labels: typo

#7327 Inheritance deliverance mission(s)
  data/human/human missions.txt
Labels: content, text - short

#7996 feat(balance): Hawk and Berserker tweaks
  data/human/ships.txt
Labels: balance

#7998 HR-Mismatched tense in conversation.
  data/hai/hai reveal 4 middle.txt
Labels: typo

#7970 Custom penalties for actions against foreign governments!
  data/governments.txt
  source/Government.cpp
  source/Government.h
  source/Politics.cpp
Labels: enhancement

#7261 fix(content): Various issues in Cognizance
  .codespell.exclude
  data/remnant/remnant 2 cognizance.txt
Labels: content

#7924 Enhancement: do not show the bribe directly when hailing a hostile ship
  data/interfaces.txt
  source/HailPanel.cpp
  source/HailPanel.h
Labels: enhancement

#7916 fix(content): HR Fix government responses to traffickers
  data/governments.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal 6 end.txt
Labels: bug, content

#7990 Hai optical jammers
  copyright
  images/outfit/hai jammer overclocked.png
  images/outfit/hai jammer.png
Labels: artwork

#7989 Enhancement: optical jamming
  data/tooltips.txt
  source/Engine.cpp
  source/Projectile.cpp
Labels: enhancement

#7962 Tutorial: don't show more than one tutorial prompt at a time in the outfitter + show title
  data/help.txt
  source/OutfitterPanel.cpp
  source/Panel.cpp
Labels: mechanics

#7974 Feature: conditions for how the system was entered and last entered system
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  source/CMakeLists.txt
  source/Engine.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/SystemEntry.h
Labels: enhancement

#8005 Kahet: correct typo
  data/kahet/kahet missions.txt
Labels: typo

#7747 Planet Descriptions updates by Improvise
  data/kahet/kahet missions.txt
  data/map.txt
Labels: text - short, typo

#7972 Feat(art): Add a new sprite for a proto planetary disk
  copyright
  images/star/proto-planetary-disk+.jpg
Labels: artwork

#8009 Fix another crash
  source/Government.cpp
  source/Government.h
Labels: bug

#8006 Add help for `--sales` command and refactor PrintData
  endless-sky.6
  source/PrintData.cpp
  source/PrintData.h
Labels: refactor
