Repository endless-sky/endless-sky, pull requests merged in 2022-01, with the labels that each got.

#5727 Fix mission map gift
  source/GameAction.cpp
  source/MissionAction.cpp
  source/OutfitterPanel.cpp
  source/OutfitterPanel.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: mechanics

#6460 (Credit update) Add MCO & W1zrad to Developer section
  credits.txt
Labels: documentation

#6290 test: Test-Framework: Print the tests call-stack on failing tests.
  source/Test.cpp
Labels: cd/ci/testing

#6288 test: Test-framework: Compensate for zoom at depart so that landing also works.
  data/tests/tests_common.txt
  data/tests/tests_framework.txt
Labels: cd/ci/testing

#6431 feat(mechanics): Allow outfits to generate income
  data/tooltips.txt
  source/BankPanel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: enhancement

#6449 content: Add new mission about a repulsor failure.
  data/human/human missions.txt
Labels: content

#6445 refactor(content,grammar): Rephrase statement in FW Reconciliation
  data/human/free worlds reconciliation.txt
Labels: content

#6076 Coalition: Pilgrimage
  data/coalition/coalition missions.txt
Labels: content

#6374 feat(content) Robotic Musical - New Culture Conversation
  data/hai/hai culture conversations.txt
Labels: content

#6441 Thrall mission
  data/human/human missions.txt
Labels: content

#6375 feat(content) Academy Motto - New Culture Conversation
  data/hai/hai culture conversations.txt
  data/map.txt
Labels: content

#6432 Fix Coalition Interview Mission
  data/coalition/coalition missions.txt
Labels: content

#6409 Street Swindle Mission
  data/human/human missions.txt
Labels: content

#6465 Group outfit scan results by category
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  source/MainPanel.cpp
  source/MapOutfitterPanel.cpp
  source/comparators/ByGivenOrder.h
  source/comparators/ByName.h
Labels: enhancement

#5847 feat(content): Add Remnant "Search and Rescue" jobs
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant jobs.txt
Labels: content

#6492 New Nuke effects
  copyright
  images/effect/explosion/nuke+0.png
  images/effect/explosion/nuke+1.png
  images/effect/explosion/nuke+2.png
  images/effect/explosion/nuke+3.png
  images/effect/explosion/nuke+4.png
  images/effect/explosion/nuke+5.png
  images/effect/explosion/nuke+6.png
  images/effect/explosion/nuke+7.png
Labels: content

#6498 Add remodel of the Nuke
  copyright
  images/hardpoint/nuke.png
  images/outfit/nuke.png
  images/projectile/missile-0.png
  images/projectile/missile-1.png
Labels: content

#6458 Added more author hails.
  data/human/hails.txt
Labels: content

#6379 Feat(content) : rep changes with mereti and sestor
  data/governments.txt
  data/korath/korath ships.txt
Labels: content

#5747 Quotes for MCOfficer's person ship
  data/persons.txt
Labels: content

#6310 Remnant - Adding the Ember Tear
  copyright
  data/remnant/remnant outfits.txt
  data/remnant/remnant ships.txt
  images/effect/ember tear/ember tear fire.png
  images/effect/ember tear/ember tear impact.png
  images/effect/ember tear/ember tear spark~0.png
  images/effect/ember tear/ember tear spark~1.png
  images/effect/ember tear/ember tear spark~2.png
  images/effect/ember tear/ember tear spark~3.png
  images/effect/ember tear/ember tear spark~4.png
  images/effect/ember tear/ember tear spark~5.png
  images/effect/ember tear/ember tear vortex~00.png
  images/effect/ember tear/ember tear vortex~01.png
  images/effect/ember tear/ember tear vortex~02.png
  images/effect/ember tear/ember tear vortex~03.png
  images/effect/ember tear/ember tear vortex~04.png
  images/effect/ember tear/ember tear vortex~05.png
  images/effect/ember tear/ember tear vortex~06.png
  images/effect/ember tear/ember tear vortex~07.png
  images/effect/ember tear/ember tear vortex~08.png
  images/effect/ember tear/ember tear vortex~09.png
  images/effect/ember tear/ember tear vortex~10.png
  images/effect/ember tear/ember tear vortex~11.png
  images/effect/ember tear/ember tear vortex~12.png
  images/effect/ember tear/ember tear vortex~13.png
  images/outfit/ember tear.png
  images/projectile/ember tear/ember tear~0.png
  images/projectile/ember tear/ember tear~1.png
  images/projectile/ember tear/ember tear~2.png
  images/projectile/ember tear/ember tear~3.png
Labels: content

#6507 Add remodel of the Raven
  copyright
  data/human/marauders.txt
  data/human/ships.txt
  images/ship/mravene.png
  images/ship/mravens.png
  images/ship/mravenw.png
  images/ship/raven.png
  images/thumbnail/mravene.png
  images/thumbnail/mravens.png
  images/thumbnail/mravenw.png
  images/thumbnail/raven.png
Labels: content

#6486 feat(balance): Lower hard requirements for cargo/passenger job visibility
  data/hai/hai jobs.txt
  data/human/jobs.txt
  data/human/paradise world jobs.txt
Labels: balance

#6497 Add tests for comparators added in #6465
  EndlessSkyTests.cbp
  tests/src/comparators/test_byGivenOrder.cpp
  tests/src/comparators/test_byName.cpp
Labels: cd/ci/testing

#6485 Correctly draw ships with custom swizzles inside the map panel.
  source/MapOutfitterPanel.cpp
  source/MapSalesPanel.cpp
  source/MapSalesPanel.h
  source/MapShipyardPanel.cpp
  source/MapShipyardPanel.h
Labels: bug
