Repository endless-sky/endless-sky, pull requests merged in 2022-05, with the labels that each got.

#6775 [Content] Remnant: A breath of Calm
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant events.txt
Labels: content

#6777 Change the escort ships in FW Prisoner Parole, FW Prisoner Parole 2 and FW Southern Prisoners - Release so the escort ships are a new Prisoner Transport variant
  data/human/free worlds middle.txt
  data/human/free worlds start.txt
  data/human/variants.txt
Labels: content

#6758 Support the Home and End keys in the panels
  source/BoardingPanel.cpp
  source/BoardingPanel.h
  source/LogbookPanel.cpp
  source/MapSalesPanel.cpp
  source/PlayerInfoPanel.cpp
  source/ShopPanel.cpp
  source/ShopPanel.h
Labels: enhancement

#6791 Add outfitter to Spera Anatrusk
  data/wanderer/wanderers.txt
Labels: content

#6787 Add remodels of several Wanderer outfits
  copyright
  images/outfit/thunderhead launcher.png
  images/outfit/thunderhead storage.png
  images/outfit/wanderer anti-missile.png
  images/outfit/wanderer heat sink.png
Labels: content

#6751 Add "visualStart" to Fix Effect Placement Bug
  source/Hardpoint.cpp
Labels: bug

#6743 Submunition Velocity Fix
  source/Projectile.cpp
  source/Projectile.h
Labels: mechanics

#6810 Make the Coalition solars use Solar Heat
  data/coalition/coalition outfits.txt
Labels: content

#6812 Use "free" instead of "0" for outfits that are free.
  source/OutfitInfoDisplay.cpp
Labels: enhancement

#6592 Turn variant into its own class
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  source/Fleet.cpp
  source/Fleet.h
  source/Variant.cpp
  source/Variant.h
Labels: refactor

#6799 Ionization now causes weapons to jam in addition to draining energy
  data/hai/hai outfits.txt
  data/tooltips.txt
  source/Armament.cpp
  source/Armament.h
  source/Hardpoint.cpp
  source/Hardpoint.h
  source/Ship.cpp
Labels: balance, mechanics

#6783 [Content]Battery Buff
  data/coalition/coalition outfits.txt
  data/hai/hai outfits.txt
  data/human/power.txt
  data/kahet/kahet outfits.txt
  data/korath/korath outfits.txt
  data/quarg/quarg outfits.txt
  data/remnant/remnant outfits.txt
  data/sheragi/sheragi outfits.txt
  data/wanderer/wanderer outfits.txt
Labels: balance, content

#6244 [Combat/Fighters] Expanding System Arrival Distance
  data/map.txt
Labels: balance

#6819 Add missing hyperdrive to "Pure Finishers" Punisher variant.
  data/coalition/coalition ships.txt
Labels: bug

#6816 [Fix]Ka'het & Remnant: Dusk can be permanently locked as busy by failing Patir 5 (unintentional)
  data/kahet/kahet missions.txt
Labels: bug

#6820 Adding Nanachi's pendant
  data/hai/hai missions.txt
  data/hai/hai outfits.txt
  images/outfit/crystal pendant.png
Labels: content

#6679 docs: Updating Credits and standardize lines in Copyright
  copyright
  credits.txt
Labels: documentation

#6823 Coalition: Minmaxing Heliarch Variants
  data/coalition/coalition ships.txt
Labels: content

#6825 Fix Ions Punisher empty space
  data/coalition/coalition ships.txt
Labels: content

#6826 Skip ghost outfits when calculating the fine for outfits in a cargo hold.
  source/CargoHold.cpp
Labels: bug

#6500 feat(content): Hai Merchant Expansion
  data/governments.txt
  data/hai/hai fleets.txt
  data/hai/hai.txt
  data/map.txt
Labels: content

#6829 Improve the version identification for users.
  credits.txt
  utils/cd_update_versions.sh
  utils/set_version.sh
Labels: cd/ci/testing

#6831 Fix frames lagging one frame behind rendering.
  source/Engine.cpp
  source/Engine.h
Labels: bug

#6827 Make Automatic aiming option better
  source/AI.cpp
Labels: mechanics

#6655 Content: Remnant culture: Paradise 1 - Historic Spaceport
  copyright
  data/remnant/remnant 2 side missions.txt
  images/scene/remnant remote spaceport.png
Labels: content

#6754 Feature: Human culture - Post-conference at the pub
  data/human/culture conversations.txt
Labels: content

#6833 Fix crash when dying ships jettison their cargo.
  source/CargoHold.cpp
Labels: bug

#6813 Update Tear of Skade outfit sprite
  copyright
  images/outfit/skadetear.png
Labels: content

#6821 Add remodels of Wanderer Sunbeam weapons and Wanderer Anti-Missile hardpoint
  copyright
  data/wanderer/wanderer outfits.txt
  images/hardpoint/dual sunbeam turret.png
  images/hardpoint/sunbeam turret.png
  images/hardpoint/wanderer anti-missile.png
  images/outfit/dual sunbeam turret.png
  images/outfit/sunbeam turret.png
  images/outfit/sunbeam.png
Labels: content

#6815 Add editorconfig style checker CI.
  .ecrc
  .editorconfig
  .github/path-filters.yml
  .github/workflows/ci.yml
  data/remnant/remnant 1 introduction.txt
  source/AI.cpp
  source/Fleet.cpp
  source/GameEvent.cpp
  source/InfoPanelState.cpp
  source/InfoPanelState.h
  source/PlayerInfoPanel.cpp
  source/PlayerInfoPanel.h
  source/Ship.h
  source/ShipInfoPanel.cpp
  source/ShipInfoPanel.h
  source/ShopPanel.cpp
  source/System.cpp
  tests/unit/src/helpers/datanode-factory.cpp
  tests/unit/src/test_set.cpp
  utils/set_version.sh
  utils/test_parse.ps1
Labels: cd/ci/testing

#6841 Add sprites for the Caldera Afterburner
  copyright
  images/outfit/caldera afterburner.png
Labels: content

#6850 [Fix]Remnant: Reducing the search area for Remnant Rescue 5
  data/remnant/remnant jobs.txt
Labels: content

#6847 Added the Asteroid Damage attribute
  data/tooltips.txt
  source/Minable.cpp
  source/OutfitInfoDisplay.cpp
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#6857 fix(UI): Ensure planet label overlap check works correctly at all zoom levels
  source/PlanetLabel.cpp
Labels: bug

#6863 feat: Make minables have different hull values.
  data/harvesting.txt
  source/Minable.cpp
  source/Minable.h
Labels: enhancement

#6862 Add relative asteroid damage
  data/tooltips.txt
  source/Minable.cpp
  source/Minable.h
  source/OutfitInfoDisplay.cpp
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#6852 Add unique flare effect for the Wanderers' engines
  copyright
  data/wanderer/wanderer outfits.txt
  images/effect/wanderer flare/large+0.png
  images/effect/wanderer flare/large+1.png
  images/effect/wanderer flare/large+2.png
  images/effect/wanderer flare/large+3.png
  images/effect/wanderer flare/large+4.png
  images/effect/wanderer flare/medium+0.png
  images/effect/wanderer flare/medium+1.png
  images/effect/wanderer flare/medium+2.png
  images/effect/wanderer flare/medium+3.png
  images/effect/wanderer flare/medium+4.png
  images/effect/wanderer flare/small+0.png
  images/effect/wanderer flare/small+1.png
  images/effect/wanderer flare/small+2.png
  images/effect/wanderer flare/small+3.png
  images/effect/wanderer flare/small+4.png
  images/effect/wanderer flare/tiny+0.png
  images/effect/wanderer flare/tiny+1.png
  images/effect/wanderer flare/tiny+2.png
  images/effect/wanderer flare/tiny+3.png
  images/effect/wanderer flare/tiny+4.png
Labels: content

#6851 Add polished models for the Afterburner, Corvette and Dual Sunbeam
  images/hardpoint/dual sunbeam turret.png
  images/outfit/afterburner.png
  images/outfit/dual sunbeam turret.png
  images/ship/corvette.png
  images/thumbnail/corvette.png
Labels: content

#6854 Add reworked Plasma Flare effect
  copyright
  images/effect/plasma flare/huge+0.png
  images/effect/plasma flare/huge+1.png
  images/effect/plasma flare/huge+2.png
  images/effect/plasma flare/huge+3.png
  images/effect/plasma flare/huge+4.png
  images/effect/plasma flare/large+0.png
  images/effect/plasma flare/large+1.png
  images/effect/plasma flare/large+2.png
  images/effect/plasma flare/large+3.png
  images/effect/plasma flare/large+4.png
  images/effect/plasma flare/medium+0.png
  images/effect/plasma flare/medium+1.png
  images/effect/plasma flare/medium+2.png
  images/effect/plasma flare/medium+3.png
  images/effect/plasma flare/medium+4.png
  images/effect/plasma flare/small+0.png
  images/effect/plasma flare/small+1.png
  images/effect/plasma flare/small+2.png
  images/effect/plasma flare/small+3.png
  images/effect/plasma flare/small+4.png
  images/effect/plasma flare/tiny+0.png
  images/effect/plasma flare/tiny+1.png
  images/effect/plasma flare/tiny+2.png
  images/effect/plasma flare/tiny+3.png
  images/effect/plasma flare/tiny+4.png
Labels: content

#6867 Filipino volcano names
  data/human/names.txt
Labels: content

#6835 Refactor WeightedList so that Type doesn't need to know its weight
  source/AsteroidField.cpp
  source/AsteroidField.h
  source/Fleet.cpp
  source/Phrase.cpp
  source/Phrase.h
  source/System.cpp
  source/System.h
  source/WeightedList.h
  tests/unit/src/test_weightedList.cpp
Labels: refactor

#6616 Remnant Logistics Jobs
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant commodities.txt
  data/remnant/remnant jobs.txt
Labels: content

#6881 [Fix] Remnant: Give Cog 27 the landing attribute
  data/remnant/remnant 2 cognizance.txt
Labels: bug

#6880 [Fix]Remnant: Replacing reference to cloaking device
  data/remnant/remnant.txt
Labels: content

#6878 Add additional human ship names
  data/human/names.txt
Labels: content

#6876 Add reworked sprites for the Coalition flare effect
  copyright
  data/coalition/coalition outfits.txt
  images/effect/coalition flare/large+0.png
  images/effect/coalition flare/large+1.png
  images/effect/coalition flare/large+2.png
  images/effect/coalition flare/large+3.png
  images/effect/coalition flare/large+4.png
  images/effect/coalition flare/large~0.png
  images/effect/coalition flare/large~1.png
  images/effect/coalition flare/small+0.png
  images/effect/coalition flare/small+1.png
  images/effect/coalition flare/small+2.png
  images/effect/coalition flare/small+3.png
  images/effect/coalition flare/small+4.png
  images/effect/coalition flare/small~0.png
  images/effect/coalition flare/small~1.png
Labels: content

#6872 Expand the attribute whitelist
  source/Outfit.cpp
Labels: mechanics

#6869 Add unique flare effect for the Pug engines
  copyright
  data/pug/pug.txt
  images/effect/pug flare/huge+0.png
  images/effect/pug flare/huge+1.png
  images/effect/pug flare/huge+2.png
  images/effect/pug flare/huge+3.png
  images/effect/pug flare/huge+4.png
  images/effect/pug flare/large+0.png
  images/effect/pug flare/large+1.png
  images/effect/pug flare/large+2.png
  images/effect/pug flare/large+3.png
  images/effect/pug flare/large+4.png
  images/effect/pug flare/medium+0.png
  images/effect/pug flare/medium+1.png
  images/effect/pug flare/medium+2.png
  images/effect/pug flare/medium+3.png
  images/effect/pug flare/medium+4.png
  images/effect/pug flare/small+0.png
  images/effect/pug flare/small+1.png
  images/effect/pug flare/small+2.png
  images/effect/pug flare/small+3.png
  images/effect/pug flare/small+4.png
  images/effect/pug flare/tiny+0.png
  images/effect/pug flare/tiny+1.png
  images/effect/pug flare/tiny+2.png
  images/effect/pug flare/tiny+3.png
  images/effect/pug flare/tiny+4.png
Labels: content

#6868 Add new sprites for the Korath Flare effect
  copyright
  images/effect/korath flare/huge+0.png
  images/effect/korath flare/huge+1.png
  images/effect/korath flare/huge+2.png
  images/effect/korath flare/huge+3.png
  images/effect/korath flare/huge+4.png
  images/effect/korath flare/large+0.png
  images/effect/korath flare/large+1.png
  images/effect/korath flare/large+2.png
  images/effect/korath flare/large+3.png
  images/effect/korath flare/large+4.png
  images/effect/korath flare/medium+0.png
  images/effect/korath flare/medium+1.png
  images/effect/korath flare/medium+2.png
  images/effect/korath flare/medium+3.png
  images/effect/korath flare/medium+4.png
  images/effect/korath flare/small+0.png
  images/effect/korath flare/small+1.png
  images/effect/korath flare/small+2.png
  images/effect/korath flare/small+3.png
  images/effect/korath flare/small+4.png
  images/effect/korath flare/tiny+0.png
  images/effect/korath flare/tiny+1.png
  images/effect/korath flare/tiny+2.png
  images/effect/korath flare/tiny+3.png
  images/effect/korath flare/tiny+4.png
Labels: content

#6855 Remove reference to Republic system Porrima in Remnant event
  data/remnant/remnant events.txt
Labels: bug

#6883 Use pilot name to test deletion
  source/LoadPanel.cpp
Labels: bug

#6650 New "Mugger" Spaceport mission
  data/human/human missions.txt
Labels: content
