Repository endless-sky/endless-sky, pull requests merged in 2022-06, with the labels that each got.

#6886 Add slight tweaks to the Coalition and Pug engine flare effects
  images/effect/coalition flare/large+0.png
  images/effect/coalition flare/large+1.png
  images/effect/coalition flare/large+2.png
  images/effect/coalition flare/large+3.png
  images/effect/coalition flare/large+4.png
  images/effect/coalition flare/small+0.png
  images/effect/coalition flare/small+1.png
  images/effect/coalition flare/small+2.png
  images/effect/coalition flare/small+3.png
  images/effect/coalition flare/small+4.png
  images/effect/pug flare/huge+0.png
  images/effect/pug flare/huge+1.png
  images/effect/pug flare/huge+2.png
  images/effect/pug flare/huge+3.png
  images/effect/pug flare/huge+4.png
  images/effect/pug flare/large+0.png
  images/effect/pug flare/large+1.png
  images/effect/pug flare/large+2.png
  images/effect/pug flare/large+3.png
  images/effect/pug flare/large+4.png
  images/effect/pug flare/medium+0.png
  images/effect/pug flare/medium+1.png
  images/effect/pug flare/medium+2.png
  images/effect/pug flare/medium+3.png
  images/effect/pug flare/medium+4.png
  images/effect/pug flare/small+0.png
  images/effect/pug flare/small+1.png
  images/effect/pug flare/small+2.png
  images/effect/pug flare/small+3.png
  images/effect/pug flare/small+4.png
  images/effect/pug flare/tiny+0.png
  images/effect/pug flare/tiny+1.png
  images/effect/pug flare/tiny+2.png
  images/effect/pug flare/tiny+3.png
  images/effect/pug flare/tiny+4.png
Labels: content

#6908 Add 'staying' to the Korath fleet in Remnant Defense 1.
  data/remnant/remnant 1 introduction.txt
Labels: bug

#6895 [Artwork] Requested Additional Sprites
  copyright
  images/ship/hailstorm.png
  images/ship/heavy gust.png
  images/ship/mining drone.png
  images/ship/squall.png
  images/ship/sunder.png
  images/thumbnail/hailstorm.png
  images/thumbnail/heavy gust.png
  images/thumbnail/mining drone.png
  images/thumbnail/squall.png
  images/thumbnail/sunder.png
Labels: content

#6909 feat(content): Make unfriendly planet hails less friendly
  source/HailPanel.cpp
Labels: mechanics

#6887 [Fix]Remnant: Ssil Vida Activation & Deactivation event fixes
  data/map.txt
  data/remnant/remnant events.txt
Labels: bug

#6765 Remove mentions of Wanderers in news before you learn their language
  data/wanderer/wanderer news.txt
Labels: content

#6888 Add ExclusiveItem class
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  EndlessSkyTests.cbp
  source/Conversation.cpp
  source/Conversation.h
  source/ExclusiveItem.h
  source/MissionAction.cpp
  source/MissionAction.h
  source/NPC.cpp
  source/NPC.h
  source/Phrase.cpp
  source/Phrase.h
  source/StartConditions.cpp
  source/StartConditions.h
  tests/unit/src/test_exclusiveItem.cpp
Labels: refactor

#6918 Buying outfit to cargo when full displays reason
  source/OutfitterPanel.cpp
Labels: enhancement

#6832 fix(mechanics): Draw overlays with the correct zoom level
  source/Engine.cpp
  source/Engine.h
Labels: bug, mechanics

#6630 Changes to Stones of our Fathers/Skadenga
  .codespell.exclude
  data/human/deep missions.txt
Labels: content

#6939 Convert RGB pngs to RGBA before reading.
  source/ImageBuffer.cpp
Labels: bug

#6932 Add reworked Pug explosion effect
  copyright
  data/effects.txt
  images/effect/explosion/pug/huge~0.png
  images/effect/explosion/pug/huge~1.png
  images/effect/explosion/pug/huge~2.png
  images/effect/explosion/pug/huge~3.png
  images/effect/explosion/pug/huge~4.png
  images/effect/explosion/pug/huge~5.png
  images/effect/explosion/pug/huge~6.png
  images/effect/explosion/pug/huge~7.png
  images/effect/explosion/pug/huge~8.png
  images/effect/explosion/pug/huge~9.png
  images/effect/explosion/pug/large~0.png
  images/effect/explosion/pug/large~1.png
  images/effect/explosion/pug/large~2.png
  images/effect/explosion/pug/large~3.png
  images/effect/explosion/pug/large~4.png
  images/effect/explosion/pug/large~5.png
  images/effect/explosion/pug/large~6.png
  images/effect/explosion/pug/large~7.png
  images/effect/explosion/pug/large~8.png
  images/effect/explosion/pug/large~9.png
  images/effect/explosion/pug/medium~0.png
  images/effect/explosion/pug/medium~1.png
  images/effect/explosion/pug/medium~2.png
  images/effect/explosion/pug/medium~3.png
  images/effect/explosion/pug/medium~4.png
  images/effect/explosion/pug/medium~5.png
  images/effect/explosion/pug/medium~6.png
  images/effect/explosion/pug/medium~7.png
  images/effect/explosion/pug/medium~8.png
  images/effect/explosion/pug/medium~9.png
  images/effect/explosion/pug/small~0.png
  images/effect/explosion/pug/small~1.png
  images/effect/explosion/pug/small~2.png
  images/effect/explosion/pug/small~3.png
  images/effect/explosion/pug/small~4.png
  images/effect/explosion/pug/small~5.png
  images/effect/explosion/pug/small~6.png
  images/effect/explosion/pug/small~7.png
  images/effect/explosion/pug/small~8.png
  images/effect/explosion/pug/small~9.png
  images/effect/explosion/pug/tiny~0.png
  images/effect/explosion/pug/tiny~1.png
  images/effect/explosion/pug/tiny~2.png
  images/effect/explosion/pug/tiny~3.png
  images/effect/explosion/pug/tiny~4.png
  images/effect/explosion/pug/tiny~5.png
  images/effect/explosion/pug/tiny~6.png
  images/effect/explosion/pug/tiny~7.png
  images/effect/explosion/pug/tiny~8.png
  images/effect/explosion/pug/tiny~9.png
Labels: content

#6920 Reword the explanation of that train's speed of 11D.E8
  data/remnant/remnant 2 side missions.txt
Labels: content

#6935 [Fix]Remnant: Swapping to first person actions in choices
  data/kahet/kahet missions.txt
  data/remnant/remnant 2 cognizance.txt
Labels: bug

#6324 Coalition: Expeditions Past
  data/coalition/coalition missions.txt
  data/coalition/coalition news.txt
Labels: content

#6774 macOS: fix crash with background audio on older systems
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  EndlessSky.xcodeproj/project.pbxproj
  utils/build_custom_libmad.sh
  utils/fetch_sdl2_framework.sh
  utils/mad-compat.rb
Labels: bug

#6942 feat(graphics): Improved the Korath Chaser graphics
  copyright
  images/ship/chaser.png
  images/thumbnail/chaser.png
Labels: content

#6944 [Variants Tweak] Make Heliarch Hunter variants use Scram Drives
  data/coalition/coalition ships.txt
Labels: content

#6870 [Content] Korath Exiles Expansion Preparation: Raider Update
  copyright
  data/korath/korath ships.txt
  data/korath/korath weapons.txt
  images/effect/firestorm ring+00.png
  images/effect/firestorm ring+01.png
  images/effect/firestorm ring+02.png
  images/effect/firestorm ring+03.png
  images/effect/firestorm ring+04.png
  images/effect/firestorm ring+05.png
  images/effect/firestorm ring+06.png
  images/effect/firestorm ring+07.png
  images/effect/firestorm ring+08.png
  images/effect/firestorm ring+09.png
  images/effect/firestorm ring+10.png
  images/effect/firestorm ring+11.png
  images/effect/firestorm ring+12.png
  images/icon/firelight.png
  images/outfit/firelight bank.png
  images/outfit/firelight rack.png
  images/outfit/firelight.png
  images/projectile/firelight active~0.png
  images/projectile/firelight active~1.png
  images/projectile/firelight active~2.png
  images/projectile/firelight.png
  images/ship/raiderxlii.png
  images/thumbnail/raiderxlii.png
  sounds/firelight hit.wav
  sounds/firelight.wav
Labels: content

#6901 Action choices to First person
  data/human/human missions.txt
Labels: content

#6943 [Content] Coalition: Big Finisher Launcher
  copyright
  data/coalition/coalition ships.txt
  data/coalition/coalition weapons.txt
  data/coalition/coalition.txt
  images/outfit/finisher maegrolain.png
Labels: content

#6958 Add a validation CI for the copyright file
  .github/path-filters.yml
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
  copyright
  utils/check_copyright.py
Labels: cd/ci/testing

#6965 Bugfix: Smooth music playback
  source/Audio.cpp
  source/Music.cpp
  source/Music.h
Labels: bug

#6970 Fix Windows Actions caused by recent image update.
  .github/workflows/cd.yaml
  .github/workflows/ci.yml
Labels: cd/ci/testing

#6974 CI only: Bugfix windows build part 2
  .github/workflows/ci.yml
Labels: cd/ci/testing

#6971 fix(content): Remnant: Fixing a confusing block message in Cognizance 32
  data/remnant/remnant 2 cognizance.txt
Labels: bug

#6972 Add remodel of the Surveillance Drone
  copyright
  data/human/ships.txt
  images/ship/surveillance drone.png
  images/thumbnail/surveillance drone.png
Labels: content

#6955 [Content] Korath Raider Update Edits
  copyright
  data/korath/korath ships.txt
  data/korath/korath weapons.txt
  images/ship/raider xlii.png
  images/thumbnail/raider xlii.png
Labels: content

#6340 Coalition: Long Lost Property
  copyright
  data/coalition/coalition missions.txt
  data/coalition/coalition outfits.txt
  data/human/marauders.txt
  images/outfit/outskirts gauger.png
Labels: content

#6451 feat(content): In the FW Hope Recon 1C surrender case, make the Gunboat crew join the Oathkeepers
  data/human/free worlds start.txt
Labels: content

#6950 [Content] Worker transport mission
  data/human/human missions.txt
Labels: content
