Repository endless-sky/endless-sky, pull requests merged in 2022-10, with the labels that each got.

#7037 Pug ships redesign
  copyright
  data/pug/pug.txt
  images/ship/pug arfecta.png
  images/ship/pug enfolta.png
  images/ship/pug maboro.png
  images/ship/pug zibruka.png
  images/thumbnail/pug arfecta.png
  images/thumbnail/pug enfolta.png
  images/thumbnail/pug maboro.png
  images/thumbnail/pug zibruka.png
Labels: art

#7288 Fix Pug Maboro thumbnail dimensions
  images/thumbnail/pug maboro.png
Labels: bug, art

#7130 feat(graphics): Add screen mode preference in settings
  source/GameWindow.cpp
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
  source/main.cpp
Labels: enhancement

#7293 (Fix) Pug Flares
  data/pug/pug.txt
Labels: bug

#7295 Update contributor list
  credits.txt
Labels: documentation

#7281 fix(content): Remnant - Cognizance - Void Sprite Parts
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant outfits.txt
  data/remnant/remnant.txt
Labels: bug, content, text - short

#7239 fix(content) Remnant-Drak: Fixing the Archon and Dodging challenge
  copyright
  data/drak/drak outfits.txt
  data/map.txt
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant ships.txt
  images/land/nasa30.png
Labels: bug, balance, content, text - short

#7277 Add `remove` support for `object`s in `system`s
  source/System.cpp
  source/System.h
Labels: enhancement, mechanics

#7301 Fix possible bug in new `remove` feature
  source/System.cpp
Labels: bug

#7276 Coalition Miners
  copyright
  data/coalition/coalition ships.txt
  data/coalition/coalition weapons.txt
  data/coalition/coalition.txt
  data/map.txt
  images/outfit/mcs extractor.png
  sounds/drill~.wav
Labels: content

#7257 (Content) Coalition Games News
  data/coalition/coalition news.txt
Labels: content, text - short

#7258 Add reworked Quarg Ringworld sprites
  copyright
  data/map.txt
  images/planet/ringworld broken debris small.png
  images/planet/ringworld broken debris.png
  images/planet/ringworld broken left.png
  images/planet/ringworld broken right.png
  images/planet/ringworld left.png
  images/planet/ringworld right.png
  images/planet/ringworld.png
Labels: art

#7282 Buff the Scout
  data/human/marauders.txt
  data/human/ships.txt
Labels: balance

#7287 Add Hai Reverse Thrust Oufits
  data/hai/hai outfits.txt
  data/hai/hai ships.txt
  data/hai/hai.txt
  images/outfit/medium atomic reverse hai.png
  images/outfit/small atomic reverse hai.png
  images/outfit/tiny atomic reverse hai.png
Labels: content, art

#7272 Add remodel of the Dagger
  copyright
  data/human/ships.txt
  images/ship/dagger.png
  images/thumbnail/dagger.png
Labels: art

#7087 Update changelog for v0.9.15
  changelog
  credits.txt
Labels: documentation

#7303 Slight Changelog Typo Fix
  changelog
Labels: documentation

#7304 fix(content): Fix Wei battle events
  changelog
  data/human/free worlds 1 start.txt
Labels: bug, content

#7308 Variety of Grammar/Typo Fixes for the Changelog
  changelog
Labels: documentation

#7280 Add remodels of the Manta and its Marauder variants
  changelog
  copyright
  data/human/marauders.txt
  data/human/ships.txt
  images/ship/manta.png
  images/ship/mmantae.png
  images/ship/mmantas.png
  images/ship/mmantaw.png
  images/thumbnail/manta.png
  images/thumbnail/mmantae.png
  images/thumbnail/mmantas.png
  images/thumbnail/mmantaw.png
Labels: art

#7310 fix(content): Missing plural name for Firestorm Battery
  data/korath/korath weapons.txt
Labels: bug, text - short

#7312 Update versions to in-progress 0.9.16
  credits.txt
  endless-sky.6
  source/main.cpp
Labels: documentation

#7314 Mule is no longer a warship
  data/human/ships.txt
Labels: content, text - short

#7316 Enhancement(UI): select the destination planet from the new map UI
  source/MapDetailPanel.cpp
Labels: enhancement

#7319 Corrected passenger name for Pug 4 mission
  data/human/free worlds 3 reconciliation.txt
Labels: content, text - short

#7341 Some documentation fixes
  tests/README.md
  tests/integration/README.md
Labels: documentation

#7340 Skip the Steam auto cloud file when looking for save files
  source/LoadPanel.cpp
Labels: bug

#7339 Change Mainsail's and Inmost Blue's landscape image
  data/map.txt
Labels: art

#7334 Add Sound to Ka'het Annihilator Turret.
  data/kahet/kahet outfits.txt
Labels: bug

#7321 Change Saryd Traveler category to Utility
  data/coalition/coalition ships.txt
Labels: content

#7338 Make hai less defenceless in boarding
  data/governments.txt
  data/hai/hai ships.txt
Labels: balance

#7292 chore: Content typo fixes
  data/coalition/coalition missions.txt
  data/coalition/coalition ships.txt
  data/coalition/coalition.txt
  data/deprecated ships.txt
  data/hai/hai culture conversations.txt
  data/hai/hai missions.txt
  data/hai/hai outfits.txt
  data/human/culture conversations.txt
  data/human/deep missions.txt
  data/human/free worlds 1 start.txt
  data/human/human missions.txt
  data/kahet/kahet missions.txt
  data/korath/korath ships.txt
  data/korath/korath variants.txt
  data/korath/korath weapons.txt
  data/korath/korath.txt
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant 2 side missions.txt
  data/remnant/remnant events.txt
  data/remnant/remnant jobs.txt
  data/remnant/remnant ships.txt
  data/remnant/remnant.txt
  data/sheragi/archaeology missions.txt
  data/wanderer/wanderer news.txt
Labels: bug, text - short

#7344 [Content] Change <planet> to Bourne in FW Refinery 1
  data/human/free worlds 1 start.txt
Labels: bug

#7332 fix(chore): Some small code improvements
  source/EsUuid.cpp
  source/Files.cpp
  tests/unit/src/test_conditionsStore.cpp
  tests/unit/src/test_esuuid.cpp
  tests/unit/src/test_weightedList.cpp
Labels: enhancement

#7213 Fix: hyperdrive over jumpdrive
  source/AI.cpp
  source/Ship.cpp
  source/Ship.h
Labels: bug

#7360 Shorten Greenview's description
  data/map.txt
Labels: content, text - short

#7030 fix(flagship fighters): Proper carry and handling for ex-flagship fighters
  source/Engine.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/Ship.cpp
  source/Ship.h
Labels: bug

#7362 Bugfix: Add Checks to MoveShip()
  source/Engine.cpp
Labels: bug

#7364 Bugfix: retrigger archon missions for compatibility
  data/drak/drak missions.txt
Labels: bug, text - short

#7354 Add reworked sprites for the Atomic and Ion flare effects
  copyright
  images/effect/atomic flare/huge+0.png
  images/effect/atomic flare/huge+1.png
  images/effect/atomic flare/huge+2.png
  images/effect/atomic flare/huge+3.png
  images/effect/atomic flare/large+0.png
  images/effect/atomic flare/large+1.png
  images/effect/atomic flare/large+2.png
  images/effect/atomic flare/large+3.png
  images/effect/atomic flare/medium+0.png
  images/effect/atomic flare/medium+1.png
  images/effect/atomic flare/medium+2.png
  images/effect/atomic flare/medium+3.png
  images/effect/atomic flare/small+0.png
  images/effect/atomic flare/small+1.png
  images/effect/atomic flare/small+2.png
  images/effect/atomic flare/small+3.png
  images/effect/atomic flare/tiny+0.png
  images/effect/atomic flare/tiny+1.png
  images/effect/atomic flare/tiny+2.png
  images/effect/atomic flare/tiny+3.png
  images/effect/ion flare/huge+0.png
  images/effect/ion flare/huge+1.png
  images/effect/ion flare/huge+2.png
  images/effect/ion flare/huge+3.png
  images/effect/ion flare/large+0.png
  images/effect/ion flare/large+1.png
  images/effect/ion flare/large+2.png
  images/effect/ion flare/large+3.png
  images/effect/ion flare/medium+0.png
  images/effect/ion flare/medium+1.png
  images/effect/ion flare/medium+2.png
  images/effect/ion flare/medium+3.png
  images/effect/ion flare/small+0.png
  images/effect/ion flare/small+1.png
  images/effect/ion flare/small+2.png
  images/effect/ion flare/small+3.png
  images/effect/ion flare/tiny+0.png
  images/effect/ion flare/tiny+1.png
  images/effect/ion flare/tiny+2.png
  images/effect/ion flare/tiny+3.png
Labels: art

#7367 Fix Scar's Legion mission dialog
  data/hai/hai missions.txt
Labels: bug

#7350 chore: Fix punctuation
  data/human/human missions.txt
Labels: bug, content

#7372 fix: remove extra word "credits"
  data/human/deep missions.txt
Labels: bug

#7342 Disallow the planet label to jump around under different zooms
  source/PlanetLabel.cpp
  source/Preferences.cpp
  source/Preferences.h
Labels: bug

#7380 fix(content): fix Remnant rescue jobs
  data/remnant/remnant jobs.txt
Labels: bug, content

#7389 [sounds] A few tweaked sounds
  sounds/atomic huge~.wav
  sounds/electron beam~.wav
  sounds/skylance~.wav
  sounds/thrasher.wav
Labels: sound

#7381 Refactor: Improve game data printing
  source/PrintData.cpp
  source/PrintData.h
Labels: refactor

#7226 feat(robustness): Add checks and warnings for overlapping derived provider ranges.
  source/ConditionsStore.cpp
  source/ConditionsStore.h
  source/PlayerInfo.cpp
  tests/unit/src/test_conditionsStore.cpp
Labels: bug, enhancement

#7393 Make Korath and Remnant cargo more lore accurate
  data/korath/korath.txt
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant 2 side missions.txt
  data/remnant/remnant jobs.txt
  data/remnant/remnant.txt
Labels: content

#7377 fix(content): small changes to Ssil Vida events
  data/remnant/remnant events.txt
Labels: bug, content

#7394 BugFix: Switch Remnant: Bounty 4 to spawn a crippled ship
  data/remnant/remnant jobs.txt
Labels: bug

#7379 Re-PR: Fix stuck escorts after traveling through a wormhole
  source/AI.cpp
  source/Fleet.cpp
  source/HailPanel.cpp
  source/Ship.cpp
  source/Ship.h
Labels: bug

#7395 Correctly draw travel plans
  source/MapPanel.cpp
  source/Ship.cpp
  source/Ship.h
Labels: bug

#6866 Bugfix: Fighters should find new parents
  source/AI.cpp
  source/Ship.cpp
Labels: bug

#7351 QoL: the last Unfettered jump drive mission is made a job
  data/hai/hai jobs.txt
  data/hai/hai missions.txt
Labels: content, text - short

#7399 fix(content): Re-add events and missions to avoid breaking saves
  data/human/events.txt
  data/human/free worlds 1 start.txt
Labels: bug, content

#7397 Update the changelog for v0.9.16
  changelog
Labels: documentation

#7409 Update ubuntu runtime in CI
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  .github/workflows/steam.yml
Labels: cd/ci/testing

#7414 Mechanics: Frugal performance improvement and clarification
  source/AI.cpp
Labels: refactor

#7410 Bugfix: log at wrong location for unfettered jump drive source mission
  data/wanderer/wanderers start.txt
Labels: bug

#7382 Fix display for some compressed PNGs
  source/ImageBuffer.cpp
Labels: bug

#7247 feat(artwork): Remnant Swan
  copyright
  images/ship/swan/swan-00.png
  images/ship/swan/swan-01.png
  images/ship/swan/swan-02.png
  images/ship/swan/swan-03.png
  images/ship/swan/swan-04.png
  images/ship/swan/swan-05.png
  images/ship/swan/swan-06.png
  images/ship/swan/swan-07.png
  images/ship/swan/swan-08.png
  images/ship/swan/swan-09.png
  images/ship/swan/swan-10.png
  images/ship/swan/swan-11.png
  images/ship/swan/swan-12.png
  images/ship/swan/swan-13.png
  images/ship/swan/swan-14.png
  images/thumbnail/swan.png
Labels: art

#7307 A couple of improvements to the issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/wiki-issue.yml
Labels: documentation

#7402 feat(content): Twin Fixed Blasters (Regular and Modified)
  copyright
  data/human/sales.txt
  data/human/weapons.txt
  images/outfit/twin blaster.png
  images/outfit/twin mod blaster.png
Labels: balance, content, art

#7411 Feature: playername condition for easter eggs
  source/PlayerInfo.cpp
Labels: enhancement

#7403 Fix typo in ice crawler mission text
  data/human/deep missions.txt
Labels: bug

#7337 Sparrow/Flivver Stat Tweaks to Better Match their Roles
  data/human/ships.txt
Labels: balance

#7318 Make the Leviathan and Falcon more distinct
  data/human/marauders.txt
  data/human/ships.txt
Labels: balance

#7036 Refactor: use strength instead of cost directly and optimization of deterrence + cargo attraction
  source/AI.cpp
  source/Engine.cpp
  source/PlayerInfo.cpp
  source/Ship.cpp
  source/Ship.h
  source/Variant.cpp
Labels: mechanics, refactor

#6959 CI only: Better bash debug output for steam release build
  .github/workflows/steam.yml
Labels: cd/ci/testing

#7417 Add Range Override/Hit Effect to Newly Added Twin Blasters
  data/human/weapons.txt
Labels: bug

#7416 fix(content): Missing hidden attribute on Devil-Run
  data/hai/hai reveal 5 philosophers.txt
  data/map.txt
Labels: bug

#7421 Fix potential null dereference
  source/System.cpp
Labels: bug

#7422 fix(content): Account for saves that have already done Pirate Troubles
  data/hai/hai reveal 4 middle.txt
Labels: bug

#7419 Content: Palavret and Echo Descriptions
  data/korath/korath ships.txt
Labels: bug, content, text - short

#7317 Make bounty jobs more active
  data/human/free worlds 0 prologue.txt
  data/human/jobs.txt
  data/human/pirate jobs.txt
  data/human/syndicate jobs.txt
Labels: balance, content

#6364 New illegal cargo scan detection formula.
  data/human/outfits.txt
  data/tooltips.txt
  source/CargoHold.cpp
  source/CargoHold.h
  source/Politics.cpp
Labels: balance, mechanics

#6260 improvement(content): Increase weight of human launchers and rebalance missiles accordingly
  data/human/marauders.txt
  data/human/ships.txt
  data/human/variants.txt
  data/human/weapons.txt
  data/persons.txt
Labels: balance

#7415 Feature? Easter Egg!
  data/intro missions.txt
Labels: content, text - short

#7407 Split the implicit npc save objective from the accompany objective
  source/NPC.cpp
Labels: enhancement

#7430 feat(content): Hai language expansion/reconciliation
  data/hai/hai.txt
Labels: content, text - short

#7428 feat(artwork): Remodelled Korath Thermal Repeaters
  copyright
  images/outfit/repeater turret.png
  images/outfit/repeater.png
Labels: art

#7445 Make Unfettered JD jobs fail properly
  data/hai/unfettered jobs.txt
Labels: bug

#7443 Small fixes to the new scan evasion formula/logic
  source/Politics.cpp
Labels: bug

#7437 BugFix: Effect pincer beast shatter spelling mismatch
  images/effect/pincer beast shatter+00.png
  images/effect/pincer beast shatter+01.png
  images/effect/pincer beast shatter+02.png
  images/effect/pincer beast shatter+03.png
  images/effect/pincer beast shatter+04.png
  images/effect/pincer beast shatter+05.png
  images/effect/pincer beast shatter+06.png
  images/effect/pincer beast shatter+07.png
  images/effect/pincer beast shatter+08.png
  images/effect/pincer beast shatter+09.png
  images/effect/pincer beast shatter+10.png
  images/effect/pincer beast shatter+11.png
  images/effect/pincer beast shatter+12.png
  images/effect/pincer beast shatter+13.png
  images/effect/pincer beast shatter+14.png
  images/effect/pincer beast shatter+15.png
Labels: bug

#7413 Warn on undefined plural names when name ends in 's'
  data/hai/hai reveal 1 intro.txt
  source/Outfit.cpp
  source/Ship.cpp
Labels: mechanics

#7440 Update Android Sprite
  copyright
  images/outfit/android.png
Labels: art

#7450 Buff the Star Queen
  data/human/ships.txt
Labels: balance

#7446 Option to permanently underline shortcut keys on button labels
  source/PreferencesPanel.cpp
  source/text/Font.cpp
Labels: enhancement

#7368 Enhancement / View Fix: Display view range differently on the map from the jump range
  data/interfaces.txt
  source/MapPanel.cpp
Labels: mechanics, hacktoberfest

#5609 FTL Fuel Cost Attributes
  data/tooltips.txt
  source/Engine.cpp
  source/Ship.cpp
Labels: enhancement, waiting on reviewer

#7454 fix(content): Quick bugfix to the backup smuggler chain for HR
  data/hai/hai reveal 5 philosophers.txt
Labels: bug

#7456 fix(content): Added needed jump variants and put them in for HR
  data/hai/hai reveal 5 philosophers.txt
  data/human/variants.txt
Labels: bug

#7463 fix(internal): calling `back()` on an empty string
  source/Outfit.cpp
Labels: bug

#6915 Sort available jobs
  data/human/human missions.txt
  images/ui/sort abc.png
  images/ui/sort ascending.png
  images/ui/sort convenient.png
  images/ui/sort descending.png
  images/ui/sort pay.png
  images/ui/sort rush include.png
  images/ui/sort rush separate.png
  images/ui/sort speed.png
  images/ui/sort unacceptable include.png
  images/ui/sort unacceptable separate.png
  source/Mission.cpp
  source/Mission.h
  source/MissionAction.cpp
  source/MissionAction.h
  source/MissionPanel.cpp
  source/MissionPanel.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: enhancement

#7434 fix(copyrights): Fix misc errors/oversights in the copyright file
  copyright
  io.github.endless_sky.endless_sky.appdata.xml
Labels: documentation

#7122 Make fullscreen default preference on first launch
  source/Preferences.cpp
Labels: enhancement

#6906 Feat (mechanics): new merciful personality
  source/AI.cpp
  source/Personality.cpp
  source/Personality.h
  source/Ship.cpp
  source/Ship.h
Labels: enhancement

#7468 Bugfix(personality): mining personality no longer mines when it should flee
  source/AI.cpp
Labels: bug

#7478 Adjust stylistically awkward endings to old FW missions
  data/human/free worlds 1 start.txt
Labels: content, text - short

#7470 Make the log after taking drugs trigger properly
  data/human/human missions.txt
Labels: bug, content

#7472 Standardise formatting of old transport missions
  data/human/human missions.txt
Labels: content, text - short

#7457 Bug fixes to allow completion of Hai Reveal campaign
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 2 start.txt
  data/hai/hai reveal 3 early.txt
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal 6 end.txt
  data/human/variants.txt
Labels: bug

#7210 New auto-conditions: total ships, outfits, visited locations, and more
  source/PlayerInfo.cpp
  source/Ship.cpp
  source/Ship.h
Labels: enhancement

#7474 Tweak container transport description
  data/human/ships.txt
Labels: content, text - short

#6570 feat(engine): Add formation pattern code and unit-tests
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  EndlessSkyTests.cbp
  source/FormationPattern.cpp
  source/FormationPattern.h
  source/GameData.cpp
  source/GameData.h
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  tests/unit/src/test_formationPattern.cpp
Labels: enhancement, waiting on reviewer

#7490 feat(content): Gefüllte Taubenbrust Person Ship
  copyright
  data/persons.txt
  images/effect/plasma cloud+0.png
  images/effect/plasma cloud+1.png
  images/effect/plasma cloud+2.png
  images/effect/plasma cloud+3.png
  images/effect/plasma cloud+4.png
  images/effect/plasma fire+0.png
  images/effect/plasma fire+1.png
  images/effect/plasma fire+2.png
  images/effect/plasma fire+3.png
  images/effect/plasma impact+0.png
  images/effect/plasma impact+1.png
  images/effect/plasma impact+2.png
  images/effect/plasma impact+3.png
  images/effect/plasma impact+4.png
  images/effect/plasma impact+5.png
  images/effect/plasma impact+6.png
  images/effect/plasma impact+7.png
  images/effect/plasma impact+8.png
  images/effect/plasma impact+9.png
  images/outfit/fusion cannon.png
  images/projectile/fusion gun bolt.png
  images/ship/battleship.png
  images/thumbnail/battleship.png
Labels: content, art, text - short
