Repository endless-sky/endless-sky, pull requests merged in 2022-02, with the labels that each got.

#6402 Show additional dialogue between accepting mission and closing conversation (FW Katya)
  data/human/free worlds intro.txt
Labels: content

#6493 Culture Convos 1 & 2 from TheMarksman
  data/human/culture conversations.txt
Labels: content

#6509 Add remodel of the Bactrian & Mule
  copyright
  data/human/ships.txt
  images/ship/bactrian.png
  images/ship/mule.png
  images/thumbnail/bactrian.png
  images/thumbnail/mule.png
Labels: content

#6403 (codestyle) Alphabetize ship names
  data/human/names.txt
Labels: content

#6494 feat(content): Created two further one-liner spaceport missions
  data/human/culture conversations.txt
Labels: content

#6495 Culture Convos 5 & 6 from Marksman
  data/human/culture conversations.txt
Labels: content

#6433 Ask user to confirm the name of the pilot to delete.
  source/Dialog.cpp
  source/Dialog.h
  source/LoadPanel.cpp
  source/LoadPanel.h
Labels: enhancement

#6533 Various Typo Fixes
  data/human/boarding missions.txt
  data/human/culture conversations.txt
  data/human/deep missions.txt
  data/human/events.txt
  data/human/free worlds checkmate.txt
  data/human/free worlds epilogue.txt
  data/human/free worlds intro.txt
  data/human/free worlds middle.txt
  data/human/free worlds start.txt
  data/human/frontier jobs.txt
  data/human/hails.txt
  data/human/human missions.txt
  data/human/news.txt
  data/map.txt
Labels: bug

#6517 Drak: Making the Drak Ramp Up in response to threats
  data/drak/drak missions.txt
  data/drak/drak outfits.txt
  data/drak/drak ships.txt
  data/remnant/remnant 1 introduction.txt
Labels: balance

#6537 Jump drive remodel
  copyright
  images/outfit/jump drive (broken).png
  images/outfit/jump drive.png
Labels: content

#6514 fix(content): Add minor tag and extra formatting to Repulsor Failure
  data/human/human missions.txt
Labels: content

#6531 Add remodel of the Splinter
  copyright
  data/human/marauders.txt
  data/human/ships.txt
  images/ship/msplintere.png
  images/ship/msplinters.png
  images/ship/msplinterw.png
  images/ship/splinter.png
  images/thumbnail/msplintere.png
  images/thumbnail/msplinters.png
  images/thumbnail/msplinterw.png
  images/thumbnail/splinter.png
Labels: content

#6515 Add new mission where the player tries to get an Unfettered translator
  data/hai/hai missions.txt
  data/wanderer/wanderers start.txt
Labels: content

#6539 Introduce Mission::CanAccept to avoid accepting missions whose requirements aren't met anymore.
  source/MapPanel.cpp
  source/Mission.cpp
  source/Mission.h
  source/MissionPanel.cpp
Labels: mechanics

#6296 v0.9.15 changelog update
  changelog
Labels: documentation

#6545 fix(typo): Typos & Grammar in 0.9.15 changelog
  changelog
Labels: documentation

#6548 Polish the Raven marauders
  images/ship/mravene.png
  images/ship/mravens.png
  images/ship/mravenw.png
  images/thumbnail/mravene.png
  images/thumbnail/mravens.png
  images/thumbnail/mravenw.png
Labels: content

#6559 Add remodel of the Corvette
  copyright
  data/human/ships.txt
  images/ship/corvette.png
  images/thumbnail/corvette.png
Labels: content

#6556 Kestrel Update + Details
  copyright
  data/human/kestrel.txt
  data/persons.txt
  images/ship/kestrel.png
  images/ship/kestrele.png
  images/ship/kestreloriginal.png
  images/ship/kestrels.png
  images/ship/kestrelw.png
  images/thumbnail/kestrel.png
  images/thumbnail/kestrele.png
  images/thumbnail/kestreloriginal.png
  images/thumbnail/kestrels.png
  images/thumbnail/kestrelw.png
Labels: content

#6549 Osprey Remodel
  copyright
  data/human/ships.txt
  images/ship/osprey.png
  images/thumbnail/osprey.png
Labels: content

#6566 Add ramscoops to outfitters on Haven, Prime and Sunracer
  data/human/sales.txt
  data/map.txt
Labels: content

#6573 Quote strings that begin with a '#'.
  source/DataWriter.cpp
Labels: bug

#6427 Allow unlimited weapon hardpoints.
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  EndlessSkyTests.cbp
  source/AI.cpp
  source/AI.h
  source/Armament.cpp
  source/Armament.h
  source/Bitset.cpp
  source/Bitset.h
  source/Command.cpp
  source/Command.h
  source/FireCommand.cpp
  source/FireCommand.h
  source/Ship.cpp
  source/Ship.h
  tests/src/test_bitset.cpp
  tests/src/test_firecommand.cpp
Labels: enhancement
