Repository endless-sky/endless-sky, pull requests merged in 2022-03, with the labels that each got.

#6422 Identify the correct line where mixed whitespace is used in a file
  EndlessSkyTests.cbp
  source/DataFile.cpp
  source/DataNode.cpp
  tests/src/test_conditionSet.cpp
  tests/src/test_datafile.cpp
Labels: bug

#6511 Small refactor of GameData::GetProgress() to prevent a crash.
  source/GameData.cpp
  source/GameLoadingPanel.cpp
Labels: bug

#6572 Add a CI check to validate Code::Blocks project files.
  .github/path-filters.yml
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
  .github/workflows/xcode_check.yml
  EndlessSkyLib.cbp
  EndlessSkyTests.cbp
  tests/check_codeblocks.sh
  tests/check_xcode.sh
Labels: cd/ci/testing

#6581 Ships targeted by trigger radius weapons now become provoked
  source/DamageDealt.h
  source/DamageProfile.cpp
  source/Engine.cpp
  source/Ship.cpp
  source/Ship.h
Labels: mechanics

#6582 Fix segfault when closing the game before the data has finished loading.
  source/GameData.cpp
  source/GameData.h
  source/main.cpp
Labels: bug

#6584 Don't allow "required crew" to be less than 1.
  source/Outfit.cpp
Labels: mechanics

#6586 Properly configure headless run script.
  source/main.cpp
  tests/run_tests_headless.sh
Labels: cd/ci/testing

#6551 Culture Convos 10 through 12 from Marksman
  data/human/culture conversations.txt
Labels: content

#6263 Deep Missions: Skadenga Saga
  copyright
  data/human/deep missions.txt
  data/human/outfits.txt
  images/outfit/skadetear.png
  images/scene/Seasunset.jpg
  images/scene/buildings.jpg
  images/scene/busystreet.jpg
  images/scene/citydark.jpg
  images/scene/hroar.jpg
  images/scene/icepicture.jpg
  images/scene/iceplains.jpg
  images/scene/iceplains2.jpg
  images/scene/iceplains3.jpg
  images/scene/lonelyrock.jpg
  images/scene/redrocks.jpg
  images/scene/seascape.jpg
  images/scene/seasidecliffs.jpg
  images/scene/smeer.jpg
  images/scene/snowfield.jpg
  images/scene/snowplain.jpg
  images/scene/snowvillage.jpg
  images/scene/sunset.jpg
  images/scene/tower.jpg
Labels: content

#5807 Grabstrike sprite fix & hardpoint update
  copyright
  images/hardpoint/grab-strike.png
  images/outfit/grab-strike.png
Labels: content

#6547 Fix: Remnant: Lost in Space, Cog 24 Esquiline mention, and misc.
  data/kahet/kahet missions.txt
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant events.txt
Labels: bug

#5692 Fix: effects are no longer mirrored
  source/BatchDrawList.cpp
Labels: bug

#5714 Fix: Premature haze culling
  source/StarField.cpp
Labels: bug

#5638 Fix: Display only active flagship on load panel
  source/PlayerInfo.cpp
  source/SavedGame.cpp
Labels: bug

#6583 Update Quicksilver sprites
  copyright
  data/human/marauders.txt
  data/human/ships.txt
  images/ship/mquicksilvere.png
  images/ship/mquicksilvers.png
  images/ship/mquicksilverw.png
  images/ship/quicksilver.png
  images/thumbnail/mquicksilvere.png
  images/thumbnail/mquicksilvers.png
  images/thumbnail/mquicksilverw.png
  images/thumbnail/quicksilver.png
Labels: content

#5938 Coalition: Council of Ahr
  copyright
  data/coalition/coalition missions.txt
  images/scene/councilofahr1.png
  images/scene/councilofahr2.png
Labels: content

#6145 feat(content): Add additional jobs to the Deep to improve vibe, help find side quests
  data/human/deep jobs.txt
Labels: content

#6550 Culture Convos 7 through 9 from Marksman
  data/human/culture conversations.txt
Labels: content

#6552 Culture Convos 13 - 15 from Marksman
  data/human/culture conversations.txt
Labels: content

#6595 Add missions to remind the player to check spaceports
  data/human/human missions.txt
Labels: content

#6599 Fix: Culture: Syndicate Security Troops - Add a missing tab
  data/human/culture conversations.txt
Labels: bug

#5933 feat(content): Add another space creature to the Ember Wastes
  data/drak/indigenous.txt
  data/map.txt
  images/ship/embershade/embershade-0.png
  images/ship/embershade/embershade-1.png
  images/ship/embershade/embershade-2.png
  images/ship/embershade/embershade-3.png
  images/ship/embershade/embershade-4.png
Labels: content

#6543 Remove many instances where you are forced to fight friendly governments
  data/governments.txt
  data/human/deep missions.txt
  data/human/free worlds middle.txt
  data/human/pirate jobs.txt
Labels: content

#6421 Make coward and appeasing trigger earlier
  source/AI.cpp
Labels: mechanics

#6408 Thrusting attributes
  data/tooltips.txt
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
Labels: enhancement

#5629 Enough fuel renders as just one solid bar of fuel
  source/Engine.cpp
Labels: mechanics

#6326 Displayed ship info refinements from @stechio.
  data/tooltips.txt
  source/ShipInfoDisplay.cpp
  source/ShipInfoDisplay.h
  source/ShipInfoPanel.cpp
  source/ShipyardPanel.cpp
Labels: mechanics

#6609 feat(content): Add reputation gain to Hai jobs
  data/hai/hai jobs.txt
Labels: content

#6615 Modifications to New Deep jobs
  data/human/deep jobs.txt
Labels: bug

#6153 Patir Mystery I
  copyright
  data/governments.txt
  data/kahet/kahet missions.txt
  data/kahet/kahet ships.txt
  data/kahet/kahet.txt
  data/map.txt
  images/land/asteroid0.jpg
  images/scene/asteroid scene.jpg
  images/ship/fetri'sei.png
  images/thumbnail/fetri'sei.png
Labels: content

#4404 feat: Disabled damage type
  source/DamageProfile.cpp
  source/Ship.cpp
  source/Ship.h
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#6605 feat(content): Add Journalist flavour mission
  data/human/culture conversations.txt
Labels: content

#6601 Add reworked models of the Republic Navy ships
  data/human/ships.txt
  images/ship/auxiliaryc.png
  images/ship/auxiliaryh.png
  images/ship/auxiliaryt.png
  images/ship/carrier.png
  images/ship/combat drone.png
  images/ship/cruiser.png
  images/ship/frigate.png
  images/ship/gunboat.png
  images/ship/lance.png
  images/ship/rainmaker.png
  images/thumbnail/auxiliaryc.png
  images/thumbnail/auxiliaryh.png
  images/thumbnail/auxiliaryt.png
  images/thumbnail/carrier.png
  images/thumbnail/combat drone.png
  images/thumbnail/cruiser.png
  images/thumbnail/frigate.png
  images/thumbnail/gunboat.png
  images/thumbnail/lance.png
  images/thumbnail/rainmaker.png
Labels: content

#6291 test: Add tests for selling of ships.
  data/tests/tests_common.txt
  data/tests/tests_ship_sale.txt
Labels: cd/ci/testing

#6643 Let Unwanted Cargo trigger outside of human space
  data/hai/hai missions.txt
Labels: content

#6059 feat(UI): Toggle visibility of stored outfits in Outfitter
  data/help.txt
  images/ui/outfitter key.png
  source/OutfitterPanel.cpp
  source/OutfitterPanel.h
  source/ShopPanel.cpp
  source/ShopPanel.h
Labels: enhancement

#6649 Mention payments in the less-descriptive spaceport mission on offers
  data/human/human missions.txt
Labels: content

#6060 Coalition: Submarines
  data/coalition/coalition missions.txt
Labels: content

#6656 Play landing sound when starting the game with no recent pilot.
  source/GameLoadingPanel.cpp
Labels: bug

#6662 Remove PushOrPop after calling every Panel::Step.
  source/UI.cpp
Labels: refactor
