Repository endless-sky/endless-sky, pull requests merged in 2022-04, with the labels that each got.

#6664 Add MenuAnimationPanel that handles the starting animation and sfx.
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  source/GameLoadingPanel.cpp
  source/LoadPanel.cpp
  source/MenuAnimationPanel.cpp
  source/MenuAnimationPanel.h
  source/MenuPanel.cpp
  source/PlayerInfo.cpp
  source/UI.cpp
  source/UI.h
Labels: refactor

#6648 Make "Hauler VI cargo prototype 1" not offer if the player has no weapons
  data/human/human missions.txt
Labels: content

#5942 feat(mechanics): Show stored outfits count by planet
  source/MapPanel.cpp
  source/MapPanel.h
  source/Preferences.cpp
  source/PreferencesPanel.cpp
Labels: mechanics

#6663 Changed some pictures with NC licenses, updated copyright
  copyright
  images/land/station15.jpg
  images/land/station27.jpg
  images/land/station28.jpg
  images/land/station8.jpg
Labels: content

#6666 Add remodel of the Afterburner outfit
  copyright
  images/outfit/afterburner.png
Labels: content

#6654 Fix darkened edges around the Auxiliary and Combat Drone
  images/ship/auxiliaryc.png
  images/ship/auxiliaryh.png
  images/ship/auxiliaryt.png
  images/ship/combat drone.png
  images/thumbnail/auxiliaryc.png
  images/thumbnail/auxiliaryh.png
  images/thumbnail/auxiliaryt.png
  images/thumbnail/combat drone.png
Labels: content

#6680 Fix: Remnant: Cognizance 20: are to our
  data/remnant/remnant 2 cognizance.txt
Labels: bug

#6661 Fix a few typos in university lecture mission.
  data/coalition/coalition missions.txt
Labels: bug

#6671 Buff the Protector
  data/human/ships.txt
  data/human/variants.txt
  images/ship/protector.png
  images/thumbnail/protector.png
Labels: balance

#6373 feat: Minor code-improvements to prepare for auto-generated conditions
  source/ConditionSet.cpp
  source/Mission.cpp
  source/SpaceportPanel.cpp
Labels: refactor

#6674 Update Scout sprites
  copyright
  data/human/ships.txt
  images/ship/scout.png
  images/thumbnail/scout.png
Labels: content

#6682 Heatsink
  data/tooltips.txt
  source/Ship.cpp
Labels: mechanics

#6675 Rebalance human primary weapons: buff blasters and cannons, nerf lasers
  data/human/weapons.txt
Labels: balance

#6684 Moved the Strong Wind to the Wanderer licence
  data/wanderer/wanderer ships.txt
  data/wanderer/wanderers start.txt
Labels: content

#4482 Draw "available job" pointers before "active job" pointers
  source/MapPanel.cpp
  source/MapPanel.h
Labels: mechanics

#6691 Convert 16-bit linear sprites to 8-bit sRGB
  images/outfit/research laboratory.png
  images/thumbnail/merganser.png
Labels: bug

#6694 Add 1 more Small Heat Shunt to stock Raider
  data/korath/korath ships.txt
Labels: content

#6698 Set "Military Response Test" to offer on landing
  data/human/culture conversations.txt
Labels: content

#6715 Tweak: Adjust intro mission dialogue to encourage a map purchase
  data/intro missions.txt
Labels: content

#6703 Introduce new jobs to make smaller Marauders easier to obtain
  data/human/fleets.txt
  data/human/jobs.txt
  data/human/pirate jobs.txt
Labels: content

#6713 Greatly increase the amount of FW's salary + Make Recon's ending closer to Checkmate's
  data/human/free worlds checkmate.txt
  data/human/free worlds intro.txt
  data/human/free worlds middle.txt
  data/human/free worlds reconciliation.txt
  data/human/free worlds start.txt
Labels: content

#6709 Update enforcer confrontation gear.png
  copyright
  images/outfit/enforcer confrontation gear.png
Labels: content

#6696 Show different Kestrels on the "for sale" mission
  data/human/kestrel.txt
Labels: bug, content

#6710 Tweak: Add reverse thruster outfits to stock human ships where appropriate.
  data/human/ships.txt
Labels: content

#6725 Bugfix: Prevent some Hai missions on Darkwaste
  data/hai/hai missions.txt
  data/map.txt
Labels: bug

#6721 Typo fix in Cognizance 38
  data/remnant/remnant 2 cognizance.txt
Labels: bug

#6718 Bugfix: restore purchase into cargo
  source/OutfitterPanel.cpp
Labels: mechanics

#6686 Rebalance the engine sandbox
  data/coalition/coalition outfits.txt
  data/drak/drak ships.txt
  data/hai/hai outfits.txt
  data/human/engines.txt
  data/human/ships.txt
  data/pug/pug.txt
  data/remnant/remnant outfits.txt
  data/wanderer/wanderer outfits.txt
Labels: balance

#6731 Fix ammo capacity not matching installed ammo on several ships
  data/human/marauders.txt
  data/human/ships.txt
Labels: bug

#5894 Make Ka'Het ships take damage if overheated
  data/kahet/kahet ships.txt
  data/tooltips.txt
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
Labels: enhancement

#6732 Fix typo & add more checks to Hai missions for landing on Darkwaste
  data/hai/hai missions.txt
Labels: bug

#6642 Add Ambient Occlusion to several ship models
  images/ship/carrier.png
  images/ship/corvette.png
  images/ship/cruiser.png
  images/ship/frigate.png
  images/ship/gunboat.png
  images/ship/lance.png
  images/ship/mravene.png
  images/ship/mravens.png
  images/ship/mravenw.png
  images/ship/msplintere.png
  images/ship/msplinters.png
  images/ship/msplinterw.png
  images/ship/rainmaker.png
  images/ship/raven.png
  images/ship/splinter.png
  images/thumbnail/carrier.png
  images/thumbnail/corvette.png
  images/thumbnail/cruiser.png
  images/thumbnail/frigate.png
  images/thumbnail/gunboat.png
  images/thumbnail/lance.png
  images/thumbnail/mravene.png
  images/thumbnail/mravens.png
  images/thumbnail/mravenw.png
  images/thumbnail/msplintere.png
  images/thumbnail/msplinters.png
  images/thumbnail/msplinterw.png
  images/thumbnail/rainmaker.png
  images/thumbnail/raven.png
  images/thumbnail/splinter.png
Labels: content

#3996 Allow plugins to disable missions, events, and Person spawns
  source/GameData.cpp
  source/GameEvent.cpp
  source/GameEvent.h
  source/Mission.cpp
  source/Mission.h
  source/Person.cpp
  source/Person.h
  source/UniverseObjects.cpp
  source/UniverseObjects.h
Labels: enhancement, mechanics

#6737 Fix Remnant Afterburner flare graphics
  data/remnant/remnant outfits.txt
  images/effect/remnant afterburner/remnant afterburner~0.png
  images/effect/remnant afterburner/remnant afterburner~1.png
  images/effect/remnant afterburner/remnant afterburner~2.png
Labels: bug

#6735 Coalition: pay more for Yottrite samples
  data/coalition/coalition missions.txt
Labels: content

#6734 Content: add 'human mechanic' news
  data/human/news.txt
Labels: content

#6469 fix: wrong snapshot names
  source/Files.cpp
  source/LoadPanel.cpp
Labels: bug

#5574 Add ability to sort player fleet from info panel
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  data/help.txt
  data/interfaces.txt
  source/AI.cpp
  source/InfoPanelState.cpp
  source/InfoPanelState.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/PlayerInfoPanel.cpp
  source/PlayerInfoPanel.h
  source/ShipInfoPanel.cpp
  source/ShipInfoPanel.h
Labels: enhancement

#6723 Bugfix: endless-sky --talk shows conversation again
  source/ConversationPanel.cpp
  source/ConversationPanel.h
  source/GameLoadingPanel.cpp
  source/GameLoadingPanel.h
  source/main.cpp
Labels: bug

#6745 feat(content): Additional commodity subtypes
  data/commodities.txt
Labels: content

#5969 Bulk Freighter / Container Transport / Class C: Divergent stats & Variants
  data/human/fleets.txt
  data/human/sales.txt
  data/human/ships.txt
  data/human/variants.txt
Labels: balance

#6740 Add remodel of the Asteroid Scanner
  copyright
  images/outfit/asteroid scanner.png
Labels: content

#5686 Add fleet jump functionality
  source/AI.cpp
  source/Command.cpp
  source/Command.h
  source/Engine.cpp
Labels: enhancement

#6752 Smarter Appeasement
  source/AI.cpp
  source/AI.h
Labels: mechanics

#6657 Use space and double click to pause/unpause credits scroll.
  data/interfaces.txt
  source/MenuPanel.cpp
  source/MenuPanel.h
Labels: enhancement

#6767 Fix missing padding in the ship info panel.
  source/ShipInfoDisplay.cpp
Labels: bug

#6764 feat(content): Military commodities
  data/commodities.txt
Labels: content

#6759 Add remodels of the Wanderer Reactors
  copyright
  images/outfit/blue sun.png
  images/outfit/red sun.png
  images/outfit/white sun.png
  images/outfit/yellow sun.png
Labels: content

#6762 Add remodels of the Wanderer Shield Generators
  copyright
  images/outfit/bright cloud.png
  images/outfit/dark storm.png
Labels: content
