Repository endless-sky/endless-sky, pull requests merged in 2022-08, with the labels that each got.

#6923 docs: Add PrefersNonDefaultGPU and SingleMainWindow keys to desktop file
  endless-sky.desktop
Labels: documentation

#7080 Increase the outfit name limit by 3 units
  source/ShopPanel.h
Labels: bug

#7059 feat(content): Transport Category Rework
  data/categories.txt
  data/coalition/coalition ships.txt
  data/hai/hai ships.txt
  data/human/ships.txt
  data/korath/korath ships.txt
  data/remnant/remnant ships.txt
  data/wanderer/wanderer ships.txt
Labels: content

#7060 Add unique effects for the Burning und Corrosion status effects
  copyright
  data/effects.txt
  images/effect/burning spark-0.png
  images/effect/burning spark-1.png
  images/effect/burning spark-2.png
  images/effect/burning spark-3.png
  images/effect/burning spark-4.png
  images/effect/burning spark-5.png
  images/effect/burning spark-6.png
  images/effect/burning spark-7.png
  images/effect/burning spark-8.png
  images/effect/burning spark-9.png
  images/effect/corrosion spark-0.png
  images/effect/corrosion spark-1.png
  images/effect/corrosion spark-10.png
  images/effect/corrosion spark-11.png
  images/effect/corrosion spark-12.png
  images/effect/corrosion spark-13.png
  images/effect/corrosion spark-14.png
  images/effect/corrosion spark-2.png
  images/effect/corrosion spark-3.png
  images/effect/corrosion spark-4.png
  images/effect/corrosion spark-5.png
  images/effect/corrosion spark-6.png
  images/effect/corrosion spark-7.png
  images/effect/corrosion spark-8.png
  images/effect/corrosion spark-9.png
Labels: content

#7084 feat(saving): Write installed plugins to save file
  source/PlayerInfo.cpp
Labels: enhancement

#7053 feature(RFC-docs): Transfer RFCs from ES-community to ES main archive
  docs/rfcs/0000-template-rfc.md
  docs/rfcs/text/0001-plugin-index.md
Labels: documentation

#7092 fix(typo): Correct various typos
  data/human/deep missions.txt
  data/human/free worlds start.txt
Labels: bug

#7093 fix(mission): Clean up Saving Artifacts mission chain
  data/human/human missions.txt
Labels: bug

#7076 feat(events): Add event support for governments
  source/Government.cpp
Labels: bug, mechanics

#7099 fix(mission): replace <source> with <origin> in Saving Artifacts 2
  data/human/human missions.txt
Labels: bug

#7086 Restandardize habitable range of larger/brighter stars
  data/map.txt
Labels: content

#7042 Nerf overheat behavior
  data/coalition/coalition outfits.txt
  data/hai/hai outfits.txt
  data/human/free worlds side plots.txt
  data/human/outfits.txt
  data/human/power.txt
  data/human/weapons.txt
  data/tooltips.txt
  source/AI.cpp
  source/Ship.cpp
  source/Ship.h
Labels: balance, mechanics

#7102 Adjust display of bursty continuous weapons
  data/tooltips.txt
  source/OutfitInfoDisplay.cpp
Labels: enhancement

#6947 feat[content]: Remnant will now trust the player after a certain point (with mission explaining it and additional hails for clarity)
  .codespell.exclude
  data/map.txt
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant events.txt
  data/remnant/remnant.txt
Labels: content, text - short

#7117 Content(UI): Move the title on the main menu up
  data/interfaces.txt
Labels: content

#7125 feat(testing): Move logging facility out of Files-class to its own class
  .gitignore
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  source/Armament.cpp
  source/Audio.cpp
  source/CollisionSet.cpp
  source/ConditionSet.cpp
  source/DataNode.cpp
  source/Engine.cpp
  source/EsUuid.cpp
  source/Files.cpp
  source/Files.h
  source/Fleet.cpp
  source/GameWindow.cpp
  source/ImageBuffer.cpp
  source/ImageSet.cpp
  source/Logger.cpp
  source/Logger.h
  source/Mask.cpp
  source/MaskManager.cpp
  source/MenuPanel.cpp
  source/Mission.cpp
  source/PlayerInfo.cpp
  source/Preferences.cpp
  source/Shader.cpp
  source/Ship.cpp
  source/SpriteSet.cpp
  source/StartConditions.cpp
  source/Test.cpp
  source/UniverseObjects.cpp
  source/main.cpp
Labels: cd/ci/testing

#7119 fix(content): Remnant: Cognizance 34 "is" should be "are"
  data/remnant/remnant 2 cognizance.txt
Labels: bug, content, text - short

#7097 fix(content): Remnant Fixes: a couple spelling fixes and a variety of other fixes
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 cognizance.txt
Labels: bug, text - short

#7144 (bug) spellcheck quickfix
  .codespell.exclude
  data/human/human missions.txt
  data/wanderer/wanderer news.txt
Labels: bug, text - short

#6991 Add reworked sprites for the Finisher Impact effect
  copyright
  data/coalition/coalition weapons.txt
  images/effect/finisher impact~0.png
  images/effect/finisher impact~1.png
  images/effect/finisher impact~2.png
  images/effect/finisher impact~3.png
  images/effect/finisher impact~4.png
  images/effect/finisher impact~5.png
  images/effect/finisher impact~6.png
Labels: content, art

#7090 Add remodel of the Flivver
  copyright
  data/human/ships.txt
  images/ship/flivver.png
  images/thumbnail/flivver.png
Labels: content, art

#7082 Add reworked model of the Moonbeam and its turret
  copyright
  images/hardpoint/moonbeam turret.png
  images/outfit/moonbeam turret.png
  images/outfit/moonbeam.png
Labels: content, art

#7081 Add polished sprites for the Sunbeam outfits
  images/hardpoint/dual sunbeam turret.png
  images/hardpoint/sunbeam turret.png
  images/outfit/dual sunbeam turret.png
  images/outfit/sunbeam turret.png
  images/outfit/sunbeam.png
Labels: content, art

#7089 Coalition: Add sound to the Finisher's hit effect
  data/coalition/coalition weapons.txt
Labels: content, sound

#7148 fix: Missing copyright header in test_account.cpp
  tests/unit/src/test_account.cpp
Labels: bug

#7156 Miscellaneous grammar in data/human/
  data/human/boarding missions.txt
  data/human/deep missions.txt
Labels: bug, content, text - short

#7163 Fix from #7156
  data/human/deep missions.txt
Labels: bug

#6948 [Content] Dragonriders Mission (Dangerous Games Part 1)
  data/human/human missions.txt
Labels: content, waiting on reviewer, text - short

#7149 content: more commodities
  data/commodities.txt
Labels: content, text - short

#6989 Change blending for the Coalition Flare effects
  images/effect/coalition flare/large+0.png
  images/effect/coalition flare/large+1.png
  images/effect/coalition flare/large+2.png
  images/effect/coalition flare/large+3.png
  images/effect/coalition flare/large+4.png
  images/effect/coalition flare/large~0.png
  images/effect/coalition flare/large~1.png
  images/effect/coalition flare/large~2.png
  images/effect/coalition flare/large~3.png
  images/effect/coalition flare/large~4.png
  images/effect/coalition flare/small+0.png
  images/effect/coalition flare/small+1.png
  images/effect/coalition flare/small+2.png
  images/effect/coalition flare/small+3.png
  images/effect/coalition flare/small+4.png
  images/effect/coalition flare/small~0.png
  images/effect/coalition flare/small~1.png
  images/effect/coalition flare/small~2.png
  images/effect/coalition flare/small~3.png
  images/effect/coalition flare/small~4.png
Labels: content, art

#7159 fix(AI): Make owned ships ignore fence.
  source/AI.cpp
Labels: bug

#7162 fix(AI): Use unconstrained personality for defense fleet carried ships
  source/Personality.cpp
  source/Personality.h
  source/Planet.cpp
Labels: enhancement

#7164 modify names in data/human/news.txt
  data/human/news.txt
Labels: content, text - short

#7101 feat(content): remove Korath prefix from ship/outfit names, provide some native names
  copyright
  data/deprecated outfits.txt
  data/korath/korath outfits.txt
  data/korath/korath ships.txt
  data/korath/korath variants.txt
  data/korath/korath weapons.txt
  data/korath/korath.txt
  data/map.txt
  data/persons.txt
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant events.txt
  data/remnant/remnant jobs.txt
  data/remnant/remnant.txt
  data/wanderer/wanderers start.txt
  images/ship/tubfalet.png
  images/thumbnail/tubfalet.png
Labels: content, text - short

#7157 feat(content): Korath 'nra'ret (Ravager)
  copyright
  data/korath/korath ships.txt
  data/korath/korath variants.txt
  images/ship/-nra-ret.png
  images/thumbnail/-nra-ret.png
Labels: content, art

#6979 [Content] Dangerous Games part 2
  data/human/human missions.txt
Labels: content, text - short

#4128 feat(fighters): Restock fighter ammo from carrier's installed outfits
  source/AI.cpp
  source/Armament.cpp
  source/Armament.h
  source/GameWindow.cpp
  source/OutfitterPanel.cpp
  source/Ship.cpp
Labels: enhancement

#7178 Stop Wanderers: First Contact (Pre Hai) from triggering after visiting the Unfettered
  data/wanderer/wanderers start.txt
Labels: bug

#7180 fix(content): Remnant: spelling micheviously -> mischievously on L146
  data/remnant/remnant 2 side missions.txt
Labels: bug, text - short

#7027 fix: Unable to initialize GLEW on wayland
  source/GameWindow.cpp
Labels: bug
