Repository endless-sky/endless-sky, pull requests merged in 2022-09, with the labels that each got.

#6814 Improvements + refactoring + bug fix for #5574.
  source/InfoPanelState.cpp
  source/InfoPanelState.h
  source/PlayerInfoPanel.cpp
  source/PlayerInfoPanel.h
  source/ShipInfoPanel.cpp
Labels: bug, refactor

#7187 Add reworked Tracker Cloud effect
  copyright
  data/hai/hai outfits.txt
  images/effect/tracker cloud+0.png
  images/effect/tracker cloud+1.png
  images/effect/tracker cloud+2.png
  images/effect/tracker cloud+3.png
  images/effect/tracker cloud+4.png
  images/effect/tracker cloud+5.png
  images/effect/tracker fire+5.png
Labels: art

#7183 Add reworked sprites for the Quarg Ringworlds
  copyright
  images/planet/ringworld left.png
  images/planet/ringworld right.png
  images/planet/ringworld.png
Labels: art

#7179 Typo Fixes: Remastered
  source/AI.cpp
  source/BankPanel.cpp
  source/Engine.cpp
  source/GameWindow.cpp
  source/ImageBuffer.cpp
  source/MapPlanetCard.cpp
  source/Mask.cpp
  source/MaskManager.cpp
  source/OutfitterPanel.cpp
  source/PlayerInfo.cpp
  source/Shader.cpp
  source/Ship.cpp
  source/ShipyardPanel.cpp
  source/Test.cpp
  source/Weapon.cpp
  source/WeightedList.h
  source/main.cpp
  source/opengl.cpp
  tests/unit/src/comparators/test_byGivenOrder.cpp
  tests/unit/src/test_account.cpp
  tests/unit/src/test_conditionSet.cpp
  tests/unit/src/test_esuuid.cpp
  tests/unit/src/test_weightedList.cpp
Labels: refactor

#7070 feat(content) Remnant: Celebration of Remembrance with Taely
  data/remnant/remnant 2 side missions.txt
Labels: content, text - short

#6707 [Content] Remnant Teciimach Torpedo
  copyright
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 side missions.txt
  data/remnant/remnant events.txt
  data/remnant/remnant outfits.txt
  data/remnant/remnant ships.txt
  data/remnant/remnant.txt
  images/outfit/teciimach bay.png
  images/outfit/teciimach pod.png
Labels: content, art, text - short

#6913 feat(content): Added new Remnant ship, the "Smew"
  copyright
  data/remnant/remnant ships.txt
  images/ship/smew.png
  images/thumbnail/smew.png
Labels: content, waiting on OP, art, text - short

#7194 Fix physics.
  source/Ship.cpp
Labels: mechanics

#6910 More human news & human news changes
  .codespell.exclude
  data/human/names.txt
  data/human/news.txt
Labels: content, text - short

#7200 Add some missing words in a Coalition conversation
  data/coalition/coalition missions.txt
Labels: bug, text - short

#7196 Change Hai colours
  data/governments.txt
Labels: art

#7195 Feat(content): Remnant: Smew into the shipyard and fleets
  data/remnant/remnant events.txt
  data/remnant/remnant ships.txt
  data/remnant/remnant.txt
Labels: content

#6761 [Content] Remnant: Shattered Light missions
  .codespell.exclude
  copyright
  data/categories.txt
  data/deprecated outfits.txt
  data/remnant/remnant 2 side missions.txt
  data/remnant/remnant events.txt
  data/remnant/remnant outfits.txt
  data/remnant/remnant ships.txt
  images/ship/modified dromedary ghost.png
  images/ship/modified dromedary specter.png
  images/ship/modified dromedary wreck.png
  images/ship/modified dromedary.png
  images/thumbnail/modified dromedary wreck.png
  images/thumbnail/modified dromedary.png
Labels: content, art, text - short

#7206 fix(content): add missing "neither" in a Skadenga saga conversation
  data/human/deep missions.txt
Labels: text - short

#7208 Dromedary mask
  images/ship/modified dromedary ghost.png
Labels: bug, art

#7202 Replace non-free landscape images.
  copyright
  images/land/station15.jpg
  images/land/station28.jpg
Labels: art

#5244 feat(conditions): Implement on-demand auto-generated conditions.
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  EndlessSkyTests.cbp
  source/BankPanel.cpp
  source/ConditionSet.cpp
  source/ConditionSet.h
  source/ConditionsStore.cpp
  source/ConditionsStore.h
  source/Engine.cpp
  source/GameAction.cpp
  source/GameEvent.cpp
  source/HailPanel.cpp
  source/Mission.cpp
  source/News.cpp
  source/News.h
  source/OutfitterPanel.cpp
  source/Planet.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/PlayerInfoPanel.cpp
  source/ShipyardPanel.cpp
  source/ShopPanel.cpp
  source/Test.cpp
  source/TextReplacements.cpp
  source/TextReplacements.h
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_model_condition.txt
  tests/unit/src/test_conditionSet.cpp
  tests/unit/src/test_conditionsStore.cpp
Labels: enhancement

#7201 feat(content): Remnant: Adding a deadline and on fail to the Teciimach mission
  data/remnant/remnant 2 side missions.txt
Labels: bug, content, text - short

#7199 Fix libPNG warning on thumbnail/smew.png and ship/smew.png
  images/ship/smew.png
  images/thumbnail/smew.png
Labels: bug

#7205 Make Jakob slightly less cartoonishly sociopathic
  data/human/deep missions.txt
Labels: content, text - short

#7225 Fixing typos in Saving Artifacts
  data/human/human missions.txt
Labels: text - short

#7224 register derived conditions before reading the savefile; and set the …
  source/PlayerInfo.cpp
Labels: bug

#6946 Content: A number of new news messages, and a few new hails.
  data/human/hails.txt
  data/human/news.txt
Labels: content, text - short

#7232 fix(content): typos and grammar errors in some descriptions
  data/map.txt
Labels: text - short

#7233 fix(content): qualify Tomek's alleged tactical genius
  data/human/free worlds start.txt
Labels: content

#7235 fix(content) razer -> razor
  data/human/human missions.txt
Labels: bug, content, text - short

#7236 fix(content): fix inappropriate <source> tag
  data/human/human missions.txt
Labels: bug, content, text - short

#7222 fix(content): Remnant "Rano'erek (Ground Assault)" bounty and variant fix.
  data/korath/korath variants.txt
  data/remnant/remnant jobs.txt
Labels: bug, balance

#7223 Put more outfits in the "Unique" category
  data/categories.txt
  data/hai/hai outfits.txt
  data/human/outfits.txt
  data/remnant/remnant outfits.txt
Labels: content

#7244 minor(grammar) z plurals end in es
  data/korath/korath ships.txt
  data/remnant/remnant 2 cognizance.txt
Labels: bug

#7249 Pond Strider Alt Start origin -> planet
  data/wanderer/wanderers start.txt
Labels: bug

#7243 Fix Ringworld Desyncs
  data/map.txt
Labels: bug

#7241 Seperate licenses and minerals into their own categories
  data/categories.txt
  data/coalition/coalition outfits.txt
  data/harvesting.txt
  data/human/outfits.txt
  data/remnant/remnant outfits.txt
  data/wanderer/wanderer outfits.txt
Labels: content

#7218 Feat(content): Remnant: Scent of Rain 1 (Korath Tubfalet intro)
  data/korath/korath.txt
  data/remnant/remnant 2 side missions.txt
  data/remnant/remnant events.txt
Labels: content, text - short

#7252 fix(UI): Use Format::Credits for more things in the bank panel
  source/BankPanel.cpp
Labels: bug

#7072 feat(UI): Further improved the new planet display UI
  data/interfaces.txt
  source/DrawList.cpp
  source/DrawList.h
  source/MapDetailPanel.cpp
  source/MapDetailPanel.h
  source/MapPlanetCard.cpp
  source/MapPlanetCard.h
  source/MapSalesPanel.cpp
  source/SpriteShader.cpp
  source/SpriteShader.h
Labels: bug, mechanics

#7265 fix(variant): Add missing engines to "Korsmanath A'awoj (Special)"
  data/korath/korath variants.txt
Labels: bug, content

#7262 fix(graphics): Fix Firestorm Animation
  data/korath/korath weapons.txt
Labels: bug, art

#7268 Dragonriders/Karengo Mission: Correct planet references
  data/human/human missions.txt
Labels: bug, content, text - short

#7273 Fix bad apostrophes
  data/kahet/kahet missions.txt
  data/korath/korath outfits.txt
Labels: bug, content

#7083 feat(content): cleanup carbon systems & Ildaria, resolve/improve WR images
  copyright
  data/map.txt
  data/stars.txt
  images/star/nova-small.png
  images/star/wr+.jpg
  images/star/wr1+.jpg
Labels: content

#7134 feat(scaling): Tell Windows ES is high dpi aware using a manifest file
  endless-sky.exe.manifest
  source/WinApp.rc
  utils/set_version.sh
Labels: bug

#7275 Fix lighting on Worldship
  images/ship/world-ship d.png
Labels: art

#7270 Add remodels of the Photovoltaic outfits
  copyright
  images/outfit/small photovoltaic.png
  images/outfit/tiny photovoltaic.png
Labels: art

#7106 Improve Built In Game Data Printing
  EndlessSky.xcodeproj/project.pbxproj
  EndlessSkyLib.cbp
  endless-sky.6
  source/PrintData.cpp
  source/PrintData.h
  source/main.cpp
Labels: enhancement, refactor

#7285 fix(typo): Typos in my recent PR
  source/PrintData.cpp
Labels: bug
