Repository endless-sky/endless-sky, pull requests merged in 2023-07, with the labels that each got.

#8976 fix(typo): add in a missing space
  data/human/hails.txt
Labels: typo

#8961 Minor text corrections
  data/dialog phrases.txt
  data/human/human missions.txt
  data/human/pirate jobs.txt
Labels: typo

#8948 Re-add Eavine to the map
  data/map systems.txt
Labels: bug

#8954 Update TradingPanel.cpp (sell-all)
  source/TradingPanel.cpp
Labels: refactor

#8950 fix(content): Add `inscrutable` to Astral Cetaceans
  data/vyrmeid/vyrmeid.txt
Labels: content

#9005 Fix(content): Add unplunderable to the lasher pistol
  data/bunrodea/bunrodea outfits.txt
Labels: bug

#8999 Give the Frigate back its second torpedo launcher
  data/human/ships.txt
Labels: balance

#8992 Weapons Marauder Manta description tweak
  data/human/marauders.txt
Labels: bug

#9018 fix Shattered Light 4 conversation
  data/remnant/remnant 2 side missions.txt
Labels: content

#8991 fix(DataWriter): Properly save empty string tokens
  source/DataWriter.cpp
Labels: bug

#8984 Make "Expedition to Hope 2" provide clearance for the destination planet
  data/human/human missions.txt
Labels: bug

#8967 Wanderer outfits license patch
  data/wanderer/wanderers start.txt
Labels: bug

#8959 Bugfix: prevent negative value for bribes
  source/HailPanel.cpp
Labels: bug

#8951 fix(content): Prevent Remnant: Expanded Horizons Astral job from having the HR systems as waypoints
  data/hai/hai reveal 6 end.txt
  data/map systems.txt
Labels: content

#8905 Make defense missions have a deadline
  data/human/south jobs.txt
Labels: content

#8902 refactor(content): Separate pug.txt into different files
  data/pug/pug missions.txt
  data/pug/pug outfits.txt
  data/pug/pug ships.txt
  data/pug/pug.txt
Labels: refactor

#8880 Cold planets
  data/map planets.txt
Labels: content

#9000 Add some advice for participating in ffleet battles in Defend Sabik
  data/human/free worlds 0 prologue.txt
Labels: content, text - short

#8966 fix(content) Added missing quotes in various conversations
  data/hai/hai reveal 5 philosophers.txt
  data/human/deep missions.txt
  data/human/human missions.txt
  data/kahet/kahet missions.txt
  data/remnant/remnant 1 introduction.txt
Labels: text - short

#8845 Combine remnant keystone missions
  data/remnant/remnant 1 introduction.txt
Labels: content

#8994 feat(content): Add more human news
  data/human/news.txt
Labels: content, text - short

#8995 refactor(ui): Define Ship Info hardpoint colors as game data
  data/_ui/interfaces.txt
  source/ShipInfoPanel.cpp
Labels: refactor

#8777 feat(content): Add `provoke` to the Kor Efret
  data/governments.txt
Labels: content

#8764 feat(mechanics): Allow departing with less bunks than required crew
  data/_ui/flight checks.txt
  data/_ui/tooltips.txt
  source/Ship.cpp
Labels: enhancement

#8680 Add a Link to Endless Sky Mobile's Issue Page
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#8606 Add a mission trigger and a condition to check if the flagship is disabled
  source/Mission.cpp
  source/Mission.h
  source/PlayerInfo.cpp
Labels: enhancement

#8786 feat/refactor: Support for ship display names
  source/Depreciation.cpp
  source/Engine.cpp
  source/Fleet.cpp
  source/GameAction.cpp
  source/HailPanel.cpp
  source/MainPanel.cpp
  source/MapShipyardPanel.cpp
  source/NPC.cpp
  source/PlayerInfo.cpp
  source/PlayerInfoPanel.cpp
  source/PrintData.cpp
  source/Ship.cpp
  source/Ship.h
  source/ShipInfoDisplay.cpp
  source/ShipyardPanel.cpp
  source/ShopPanel.cpp
  source/StartConditions.cpp
  source/UniverseObjects.cpp
Labels: enhancement

#8706 Add support for drawing pointers in an interface
  source/Interface.cpp
  source/Interface.h
Labels: enhancement

#8643 Feat(enhancement): Scan opacity attributes
  data/_ui/tooltips.txt
  source/Ship.cpp
Labels: mechanics

#9020 fix(ui) : Shop detail panel click scrolling added
  source/ShopPanel.cpp
Labels: enhancement, UI

#9012 Use a more vibrant blue for shields
  data/_ui/interfaces.txt
Labels: UI

#9023 fix(typo): Mass production
  data/hai/hai missions.txt
  data/hai/hai outfits.txt
  data/hai/hai ships.txt
  data/human/free worlds 0 prologue.txt
  data/human/weapons.txt
  data/map planets.txt
Labels: typo

#6484 Feat(mechanics) : take ships with missions
  EndlessSkyLib.cbp
  source/CMakeLists.txt
  source/GameAction.cpp
  source/GameAction.h
  source/Mission.cpp
  source/Mission.h
  source/MissionAction.cpp
  source/MissionAction.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/ShipManager.cpp
  source/ShipManager.h
  tests/CMakeLists.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_take_ships.txt
  tests/unit/src/test_esuuid.cpp
Labels: enhancement, waiting on reviewer

#8871 feat(content): add Republic Navy Advisory System and add related humanitarian missions news
  data/commodities.txt
  data/human/human missions.txt
  data/human/jobs.txt
  data/human/news.txt
Labels: content, text - short

#8911 feat(content): Spaceport news for various pug planets
  data/pug/pug news.txt
Labels: content, text - short

#9007 feat(enhancement) Expand Flotsam Collection Setting
  source/Engine.cpp
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
Labels: enhancement

#8965 refactor(content): Relocate "famous warrior" warning to events.txt
  data/human/campaign events.txt
  data/human/human missions.txt
  data/human/jobs.txt
Labels: refactor

#8185 Hai Reveal: Revised smuggler story (option 2: simpler, no Pug)
  data/governments.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal 6 end.txt
  data/human/variants.txt
  data/map planets.txt
  data/map systems.txt
Labels: content, text - short

#9029 feat(enhancement): Fighter personalities
  data/bunrodea/bunrodea.txt
  data/coalition/coalition.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal 6 end.txt
  data/hai/hai reveal 7 epilogue.txt
  data/human/deep missions.txt
  data/human/fleets.txt
  data/human/free worlds 0 prologue.txt
  data/human/free worlds 1 start.txt
  data/human/free worlds 2 middle.txt
  data/human/free worlds 3 checkmate.txt
  data/human/free worlds 3 reconciliation.txt
  data/human/free worlds side plots.txt
  data/korath/korath.txt
  data/wanderer/wanderers middle.txt
  source/Fleet.cpp
  source/Fleet.h
Labels: mechanics

#9045 fix(content): Keep Ssil Vida's "remnant station" attribute
  data/remnant/remnant events.txt
Labels: bug

#9040 Feat(balance): Give the Dagger +5 engine space and an A120 atomic thruster, to give it a clearer niche and to better match its description
  data/human/ships.txt
Labels: balance, content

#9002 feat(ui): Outfits in drawshipssidebar
  source/OutfitterPanel.cpp
  source/ShipyardPanel.cpp
Labels: enhancement, UI

#9051 fix(typo): "you where"->"you were" in remnant.
  data/remnant/remnant 2 side missions.txt
  data/remnant/remnant jobs.txt
Labels: typo

#8974 Mortgage rounding fix
  source/Account.cpp
  source/Mortgage.cpp
  source/Mortgage.h
Labels: bug

#9010 feat(content): Bounty jobs pay out when killing the bounty
  data/dialog phrases.txt
  data/human/jobs.txt
Labels: balance, content

#8998 Reorder some hardpoints again
  data/bunrodea/bunrodea ships.txt
  data/drak/indigenous.txt
  data/hai/hai ships.txt
  data/human/free worlds 0 prologue.txt
  data/human/marauders.txt
  data/human/ships.txt
  data/human/variants.txt
  data/kahet/kahet ships.txt
  data/korath/korath ships.txt
  data/persons.txt
  data/pug/pug ships.txt
  data/quarg/quarg ships.txt
  data/remnant/remnant ships.txt
  data/sheragi/sheragi ships.txt
Labels: refactor

#9061 fix(saves): save all location tags for missions
  source/Mission.cpp
Labels: bug

#9063 Balance: violin spider weap cap 19 -> 23
  data/hai/hai ships.txt
Labels: balance

#8348 feat(enhancement): Make `surveillance` ships patrol the system
  source/AI.cpp
  source/AI.h
Labels: enhancement

#8903 fix(content): Fix pronouns in first contact missions
  data/bunrodea/bunrodea missions.txt
  data/coalition/coalition missions.txt
  data/wanderer/wanderers start.txt
Labels: content

#9086 Bugfix: `tribute: ` autocondition
  source/PlayerInfo.cpp
Labels: bug

#9090 fix(content): Stop Pug news from appearing on uninhabited planets
  data/pug/pug news.txt
Labels: bug

#9082 fix(content): Add `minor` to "FW Zug Expansion: Assisted"
  data/human/free worlds side plots.txt
Labels: bug

#9054 feat(ui): change map none color to darker blue (for shipyard/outfitter lists)
  source/MapOutfitterPanel.cpp
  source/MapSalesPanel.cpp
  source/MapShipyardPanel.cpp
Labels: UI

#8450 Feat(Enhancement): Landing Zoom
  source/Engine.cpp
  source/Engine.h
  source/Preferences.cpp
  source/PreferencesPanel.cpp
Labels: enhancement, UI

#9094 feat(fix): Adjust Face to Maw 1 to require the player to be flying a Puffin
  data/remnant/remnant 1 introduction.txt
Labels: bug

#8628 Improve shop ordering of human engines
  data/human/engines.txt
  data/series.txt
Labels: UI
