Repository endless-sky/endless-sky, pull requests merged in 2023-08, with the labels that each got.

#8919 feat: Tooltips for preferences
  data/_ui/tooltips.txt
  source/PreferencesPanel.cpp
  source/PreferencesPanel.h
Labels: UI

#9066 Fix a bug when displaying the amount of harvested materials a ship has in cargo
  source/MainPanel.cpp
Labels: bug

#9096 Update `fail` action with no mission name behavior
  source/Conversation.cpp
  source/Conversation.h
  source/ConversationPanel.cpp
  source/ConversationPanel.h
  source/GameAction.cpp
  source/GameAction.h
  source/Mission.cpp
  source/MissionAction.cpp
  source/MissionAction.h
  source/NPC.cpp
  source/NPC.h
  source/NPCAction.cpp
  source/NPCAction.h
  source/PlanetPanel.cpp
  source/ShipManager.h
Labels: bug

#9036 fix: style checker doesn't group similar quotes when checking for leading …
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 5 philosophers.txt
  data/human/culture conversations.txt
  data/human/deep missions.txt
  data/kahet/kahet missions.txt
  data/remnant/remnant 2 cognizance.txt
  utils/contentStyle.json
Labels: cd/ci/testing

#9008 feat(enhancment): More Motion Blur While Hyperspacing
  source/Engine.cpp
  source/Preferences.cpp
  source/PreferencesPanel.cpp
  source/Ship.cpp
  source/Ship.h
Labels: mechanics

#8944 feat(content): Add warning when you've upset Hai Sympathizers
  data/hai/hai missions.txt
Labels: content, text - short

#9107 Replace `shield resistance` on the Embersylph with `ion resistance`.
  data/drak/indigenous.txt
Labels: bug

#9116 feat(text): More pleasing grammar in FW Bounty 1
  data/human/free worlds 0 prologue.txt
Labels: content, text - short

#9119 fix(ui): Correctly check for double clicks on ship list of Player Info panel
  source/PlayerInfoPanel.cpp
Labels: bug

#9120 feat(ui): Allow opening the map in outfitter and shipyard
  source/ShopPanel.cpp
  source/ShopPanel.h
Labels: enhancement, UI

#9117 fix(bug): fix rare hail overwrite
  data/human/hails.txt
  source/text/WrappedText.cpp
Labels: bug

#9111 Use an unused government
  data/hai/hai fleets.txt
Labels: bug

#9115 Condition that allows rolling a random value in a specified range
  source/PlayerInfo.cpp
Labels: enhancement

#9125 Bugfix: exile rep being positive when deferring the diplomacy
  data/wanderer/wanderers middle.txt
Labels: bug

#9127 fix(ci): run apt update before apt install
  .github/workflows/steam.yml
Labels: cd/ci/testing

#9124 Feat(enhancement): destroyed persons autocondition
  source/PlayerInfo.cpp
Labels: enhancement

#9099 Update project license field in appdata
  io.github.endless_sky.endless_sky.appdata.xml
Labels: documentation

#9118 feat(ui): Display fighters of the hailed ship
  source/HailPanel.cpp
Labels: enhancement

#9101 feat(mechanic): handle fighter flagship for jump path planning
  source/MapPanel.cpp
Labels: bug

#9133 Update Robotic Musical to use Hai Tourism tag
  data/hai/hai culture conversations.txt
Labels: bug

#9129 Replace "scrambling protection/resistance" with "scramble protection/resistance" in various places
  data/remnant/remnant outfits.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_wormhole_navigation.txt
Labels: bug

#9143 fix troff errors in endless-sky.6
  endless-sky.6
Labels: typo

#9142 two small spelling mistakes
  source/Test.cpp
  source/main.cpp
Labels: typo

#9152 bugfix: fail missions not working properly
  source/Mission.cpp
  source/MissionAction.h
Labels: bug

#9150 feat(code): move angle unit cache creation to local storage
  source/Angle.cpp
  source/pi.h
Labels: refactor

#9147 fix(bug): check for exact turn prior to jumping
  source/Angle.cpp
  source/Angle.h
  source/Ship.cpp
Labels: bug

#8842 Feat(balance): Engine rebalance: flatter thruster scaling
  data/_deprecated/deprecated outfits.txt
  data/bunrodea/bunrodea outfits.txt
  data/coalition/coalition outfits.txt
  data/gegno/gegno outfits.txt
  data/hai/hai outfits.txt
  data/human/engines.txt
  data/kahet/kahet outfits.txt
  data/korath/korath outfits.txt
  data/pug/pug outfits.txt
  data/remnant/remnant outfits.txt
  data/sheragi/sheragi outfits.txt
  data/wanderer/wanderer outfits.txt
Labels: balance

#8923 feat(enhancement): Load plugin metadata (name, about) from plugin.txt.
  source/Plugins.cpp
Labels: enhancement

#9151 Content: add the solifuge to Unfettered shipyards when deployed during the wanderer campaign
  data/wanderer/wanderers start.txt
Labels: content

#9095 feat(content): Frozen climate news
  data/human/news.txt
Labels: content, text - short

#9148 feat(ui): change mission list accepting advance to be more intuitive
  source/MissionPanel.cpp
Labels: UI

#8512 feat(UI): Blinking deadline mission marker checks for distance
  data/_ui/tooltips.txt
  source/MapPanel.cpp
  source/PreferencesPanel.cpp
Labels: enhancement

#9154 fix(content): Separate Acheron Spacelife Government
  data/governments.txt
  data/iije/iije.txt
  data/vyrmeid/vyrmeid.txt
Labels: bug, content

#9165 feat(balance): Reduce Supercapacitor price from 12 per energy down to 2 per energy to be more inline with other batteries that are in the 1.7 to 1.5 per energy range.
  data/human/power.txt
Labels: balance

#9122 feat: new dialog type: always call callback with ok value
  source/Dialog.cpp
  source/Dialog.h
Labels: enhancement

#9138 Warn the player when taking off with outfits they can't carry
  source/PlanetPanel.cpp
  source/PlanetPanel.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_store_outfits_on_take_off.txt
Labels: enhancement

#9139 Fix a crash when spawning a defense fleet with no government
  source/Politics.cpp
Labels: bug

#9185 Move Ki Patek Ka inwards somewhat
  data/map systems.txt
Labels: bug

#9186 fix(content): Minor Free Worlds text changes
  data/human/free worlds 1 start.txt
  data/human/free worlds 2 middle.txt
  data/human/free worlds side plots.txt
Labels: content, text - short

#9184 refactor: moved DrawPlayerShipInfo into ShopPanel
  source/OutfitterPanel.cpp
  source/OutfitterPanel.h
  source/ShipyardPanel.cpp
  source/ShipyardPanel.h
  source/ShopPanel.cpp
  source/ShopPanel.h
Labels: refactor

#9140 fix(mechanics): Skip undefined fleets for tribute defense
  source/Planet.cpp
Labels: bug

#9190 feat(enhancement): Autocondition for counting flagship's bays
  source/PlayerInfo.cpp
Labels: enhancement

#9176 fix(content): Update the description of `Hai Reveal [B08] Syndicate Internal Affairs` and fix log's wording
  data/hai/hai reveal 5 philosophers.txt
Labels: content, text - short

#9194 fix(bug): move description zone in outfitters to match description
  source/OutfitterPanel.cpp
Labels: UI

#9032 feat(ui): always show subpanel buttons on Planet Panel
  data/_ui/interfaces.txt
  source/HiringPanel.cpp
  source/PlanetPanel.cpp
Labels: mechanics, UI

#8288 un-nerf scanners using a gaussian drop-off and adjusted size dependence
  source/Ship.cpp
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
Labels: mechanics

#9132 fix(balance): Unbuff fighter-carrier recharge
  source/Ship.cpp
Labels: balance

#9199 refactor: don't bother checking for existing description zone
  source/OutfitterPanel.cpp
  source/ShipyardPanel.cpp
Labels: refactor

#9145 fix(mechanics): Correctly pick flagship when landed on clearance planet
  source/PlayerInfo.cpp
Labels: bug

#9197 Handle empty descriptions in shops
  source/ItemInfoDisplay.cpp
  source/OutfitterPanel.cpp
  source/ShipyardPanel.cpp
Labels: bug, UI

#9192 Feat(ui): Make the message about missions require landing more notable
  data/_ui/interfaces.txt
  source/AI.cpp
  source/Engine.cpp
  source/Messages.h
Labels: UI

#9178 Fix Face to Maw 1 and 1B offering
  data/remnant/remnant 1 introduction.txt
Labels: bug

#9187 feat(content): Add cargo to ships in FW missions
  data/human/free worlds 0 prologue.txt
  data/human/free worlds side plots.txt
Labels: content

#9100 feat(balance): Adjusting pirate raid fleet to be more conducive to Piracy
  data/hai/hai reveal 5 philosophers.txt
  data/human/fleets.txt
Labels: balance

#9202 Fix duplicate scan dialog display
  source/Ship.cpp
Labels: bug

#9073 Balance: Nullifier rebalance
  data/kahet/kahet outfits.txt
Labels: balance

#8717 Allow interface bars to be drawn from the top left corner
  source/Interface.cpp
  source/Interface.h
Labels: enhancement

#9070 Balance: ion cannon 20% ions buff
  data/hai/hai outfits.txt
Labels: balance

#8747 Run content style checker on integration tests
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
  tests/integration/config/plugins/integration-tests/data/tests/tests_afterburn_flight.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_disown.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_model_condition.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_planet_attribute.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_framework.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_hyperjumps_to_autocondition.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_installed_plugin.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_save_load.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_ship_sale.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_shipyard_outfitter_missions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_store_outfits_on_take_off.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_take_ships.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_to_accept.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_wormhole_navigation.txt
  utils/contentStyle.json
Labels: cd/ci/testing

#8716 Make Hai space less profitable
  data/map systems.txt
Labels: balance

#9037 Combine the two Barbs into a single ship.
  data/human/campaign events.txt
  data/human/ships.txt
  data/human/variants.txt
Labels: balance, content

#8815 Include weapons the player doesn't have ammo for in deterrence calculation
  source/Ship.cpp
Labels: mechanics

#8875 Fix bug "pressing 't' twice on a planet kills you" with a tribute confirmation dialog.
  source/Dialog.cpp
  source/Dialog.h
  source/HailPanel.cpp
  source/Planet.cpp
  source/Planet.h
Labels: enhancement

#9026 content: adapt the Hai relations to better reflect the Hai-UHai situation
  data/governments.txt
Labels: content

#9217 fix(ci): Fix false positive in content style checker
  utils/contentStyle.json
Labels: bug, cd/ci/testing

#9214 fix(ui): Always clear orbits view storage
  source/MapDetailPanel.cpp
Labels: bug

#9208 feat(balance): Make the engine variants of the two marauder heavy warships less absurd
  data/human/marauders.txt
Labels: balance

#9225 fix(content): Make it clear where you are headed in Cognizance 7
  data/remnant/remnant 2 cognizance.txt
Labels: text - short

#9230 Undeprecated the simple "fighters <name>" syntax
  source/Fleet.cpp
Labels: refactor

#9228 Stop making fleets spawn from one single ringworld location
  source/Fleet.cpp
Labels: enhancement

#9102 feat(ui): when drawing travel plan on map&mission panels, jumps use dashed lines
  data/_ui/interfaces.txt
  source/LineShader.cpp
  source/LineShader.h
  source/MapPanel.cpp
  source/MapPanel.h
  source/MissionPanel.cpp
Labels: enhancement

#9206 Feat(enhancement): allow per system raid control
  EndlessSkyLib.cbp
  source/CMakeLists.txt
  source/Engine.cpp
  source/Government.cpp
  source/Government.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/RaidFleet.cpp
  source/RaidFleet.h
  source/System.cpp
  source/System.h
Labels: enhancement

#9033 Load panel scrolling with keyboard navigation
  source/LoadPanel.cpp
Labels: UI

#9013 feat(content): Standardize tooltips
  data/_ui/tooltips.txt
Labels: content, text - short

#8968 feat(mechanics): don't disable cooling and active cooling when overheated
  data/_ui/tooltips.txt
  data/coalition/coalition outfits.txt
  source/Ship.cpp
Labels: enhancement, balance

#7914 Feature(enhancement): Fadeout modifier for projectiles
  source/BatchDrawList.cpp
  source/BatchDrawList.h
  source/BatchShader.cpp
  source/Body.cpp
  source/Body.h
  source/Projectile.cpp
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement, artwork

#9227 Fix dependency update logic to fix future updates
  CMakeLists.txt
Labels: cd/ci/testing

#9243 Update all dependencies
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  vcpkg-configuration.json
  vcpkg.json
Labels: cd/ci/testing

#9244 Correctly update engine flares with the same sprite, but different scale
  source/Outfit.cpp
Labels: bug

#9247 Don't build unnecessary debug dependencies
  CMakePresets.json
Labels: cd/ci/testing

#9219 expanded planet label drawing
  source/Engine.cpp
  source/PlanetLabel.cpp
  source/PlanetLabel.h
  source/Preferences.cpp
  source/Preferences.h
  source/Rectangle.cpp
  source/Rectangle.h
Labels: UI

#8718 Define layout of escort display elements in an interface
  data/_ui/interfaces.txt
  source/EscortDisplay.cpp
  source/EscortDisplay.h
  source/Information.cpp
  source/Information.h
  source/Interface.cpp
  source/Interface.h
Labels: refactor, UI
