Repository endless-sky/endless-sky, pull requests merged in 2023-12, with the labels that each got.

#9583 fix(content): Update parts of Return to Paradise
  data/human/human missions.txt
Labels: text - short

#9578 fix(content): "Early south missions" adjustments
  data/human/human missions.txt
Labels: text - short, typo

#9588 feat(ui): Added button to open saves folder
  data/_ui/interfaces.txt
  source/Files.cpp
  source/Files.h
  source/LoadPanel.cpp
Labels: UI

#9438 feat(mechanics): Allow governments to define default attitudes toward other governments
  data/governments.txt
  source/Government.cpp
  source/Government.h
Labels: mechanics

#9423 Feat(ship): Allow ships to define their center of rotation (No.2)
  source/Body.cpp
  source/Body.h
  source/Engine.cpp
  source/Ship.cpp
Labels: enhancement

#9447 Nerf Shield Refactor Module again
  data/coalition/coalition outfits.txt
Labels: balance

#9466 Run integration tests without OpenGL
  source/GameData.cpp
  source/GameData.h
  source/GameWindow.cpp
  source/GameWindow.h
  source/ImageSet.cpp
  source/ImageSet.h
  source/Sprite.cpp
  source/Sprite.h
  source/SpriteQueue.cpp
  source/SpriteQueue.h
  source/main.cpp
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
Labels: cd/ci/testing

#8996 enhancement: Migrate to C++17
  CMakeLists.txt
  EndlessSky.cbp
  EndlessSkyLib.cbp
  EndlessSkyTests.cbp
  SConstruct
  source/DataWriter.h
  source/WeightedList.h
  tests/unit/include/es-test.hpp
  tests/unit/src/comparators/test_byGivenOrder.cpp
  tests/unit/src/test_datanode.cpp
  tests/unit/src/test_distance_calculation_settings.cpp
  tests/unit/src/test_esuuid.cpp
  tests/unit/src/test_point.cpp
  tests/unit/src/test_ship.cpp
  tests/unit/src/text/test_alignment.cpp
  tests/unit/src/text/test_displaytext.cpp
  tests/unit/src/text/test_layout.cpp
  tests/unit/src/text/test_truncate.cpp
Labels: enhancement

#9581 feat(ui): Keyboard Navigation for Preference & Plugin Panels
  source/PreferencesPanel.cpp
  source/PreferencesPanel.h
Labels: enhancement, UI

#9596 New Ionic turret prototype projectile
  copyright
  data/hai/hai outfits.txt
  images/effect/ionic impact~0.png
  images/effect/ionic impact~1.png
  images/effect/ionic impact~2.png
  images/effect/ionic impact~3.png
  images/effect/ionic impact~4.png
  images/projectile/ionic turret+0.png
  images/projectile/ionic turret+1.png
  images/projectile/ionic turret+2.png
  images/projectile/ionic turret+3.png
  images/projectile/ionic turret+4.png
  images/projectile/ionic turret+5.png
  images/projectile/ionic turret+6.png
Labels: artwork

#9412 Feat(npc): add a personality to make travel restrictions apply to mission npcs
  source/AI.cpp
  source/DistanceMap.cpp
  source/DistanceMap.h
  source/Fleet.cpp
  source/Personality.cpp
  source/Personality.h
  source/Politics.cpp
  source/Ship.cpp
  source/Ship.h
Labels: mechanics

#9613 enhancement: Resolve some C++17 todo items
  source/AI.cpp
  source/Engine.cpp
  source/UniverseObjects.cpp
Labels: enhancement, typo

#9546 Make the integration tests a bit more deterministic
  source/Engine.cpp
  source/Engine.h
  source/MainPanel.cpp
  source/MainPanel.h
  source/Panel.cpp
  source/Panel.h
  source/Test.cpp
  source/Test.h
  source/TestContext.h
  source/main.cpp
  tests/integration/config/plugins/integration-tests/data/tests/tests_afterburn_flight.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_framework.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_save_load.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_store_outfits_on_take_off.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_take_ships.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_wormhole_navigation.txt
Labels: cd/ci/testing

#9449 Use C++ instead of the test_parse scripts
  .github/workflows/ci.yml
  source/main.cpp
  utils/test_parse.ps1
  utils/test_parse.sh
Labels: cd/ci/testing

#9522 refactor: Rename & Newtype `calcTickTock`, `drawTickTock`
  source/Engine.cpp
  source/Engine.h
Labels: refactor

#6127 Make escorts only pathfind through systems that the player has visited.
  source/AI.cpp
  source/AI.h
  source/DistanceMap.cpp
  source/DistanceMap.h
  source/Engine.cpp
Labels: mechanics

#9617 fix(ui): Remember Selected Item in Shop Panel
  source/ShopPanel.cpp
  source/ShopPanel.h
Labels: UI

#9625 FIX: Typo in Puny mission
  data/human/human missions.txt
Labels: typo

#9618 Don't cancel commits to the main branch
  .github/workflows/cd.yaml
  .github/workflows/ci.yml
  .github/workflows/projects_check.yml
  .github/workflows/steam.yml
Labels: cd/ci/testing

#9607 Allow and run integration tests on every platform
  CMakeLists.txt
  CMakePresets.json
  source/GameWindow.cpp
  tests/integration/IntegrationTests.cmake
  tests/integration/RunIntegrationTest.cmake
Labels: cd/ci/testing

#9397 Minable payload drop rate manipulation
  source/Engine.cpp
  source/Minable.cpp
  source/Minable.h
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#9622 FIX: Hjlod use of 'w' in places, plus stopover name in mission
  .codespell.exclude
  data/human/deep missions.txt
Labels: bug, typo

#9589 feat(content): Insert joke about black box in Sheragi quest line
  data/sheragi/archaeology missions.txt
Labels: content, waiting on OP, text - short

#9623 feat(ui): Change Shortcut Key for Buy/Sell All
  data/_ui/interfaces.txt
  source/TradingPanel.cpp
Labels: UI

#9532 Feat(content): A new set of `entering` bounty jobs
  data/human/jobs.txt
Labels: content, text - short

#9629 Have Typhoons sold on planets with major Navy shipyards/outfitters, rather than only in the deep.
  data/human/campaign events.txt
Labels: balance

#9398 Create flotsam tractor beams
  data/_ui/tooltips.txt
  source/AI.cpp
  source/Armament.cpp
  source/Armament.h
  source/Engine.cpp
  source/Engine.h
  source/Flotsam.cpp
  source/Flotsam.h
  source/Hardpoint.cpp
  source/Hardpoint.h
  source/Outfit.cpp
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/Ship.h
  source/Weapon.cpp
  source/Weapon.h
  source/ship/ShipAICache.cpp
Labels: enhancement

#9446 feat(content): Diversify the Assisting Merchants missions
  data/hai/hai missions.txt
  data/human/boarding missions.txt
Labels: content, text - short

#9396 "Shrouded" systems that can't be seen unless in visible range
  source/AI.cpp
  source/DistanceMap.cpp
  source/Engine.cpp
  source/FogShader.cpp
  source/MapDetailPanel.cpp
  source/MapOutfitterPanel.cpp
  source/MapPanel.cpp
  source/MapShipyardPanel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/System.cpp
  source/System.h
Labels: enhancement

#9575 Add large Swiftsong transport jobs
  data/hai/hai jobs.txt
Labels: content, text - short

#9552 Fix algebra error in scan formula and replace 2s minimum scan time with exponential dropoff
  source/Ship.cpp
Labels: bug, mechanics
