Repository endless-sky/endless-sky, pull requests merged in 2023-06, with the labels that each got.

#8805 Remove Google Groups link
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: documentation

#8847 I missed a mention in the template
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: documentation

#8707 More interface ring options
  source/Interface.cpp
  source/Interface.h
Labels: enhancement

#8844 Add a PR template for balance changes.
  .github/pull_request_template.md
Labels: documentation

#8883 Correct text replacement in FW Pirates: Attack 2
  data/human/free worlds 1 start.txt
Labels: typo

#8836 Random text changes
  data/human/human missions.txt
Labels: typo

#8887 feat(content): Add Split-Quarg governments to Heliarch Relations
  data/governments.txt
Labels: content

#8697 Typo fix phenomenon/phenomena
  data/kahet/kahet missions.txt
Labels: typo

#8869 Increase the power of star/wr, to reflect its very large habitable distance
  data/stars.txt
Labels: content

#8868 feat(content): Gegno Intro Tweaks
  data/gegno/gegno intro missions.txt
Labels: content

#8867 Add FW war jobs that make use of Military cargo
  data/human/free worlds war jobs.txt
Labels: content

#8884 Properly account for suspension from the FW militia in FW Diplomacy 1
  data/human/free worlds 2 middle.txt
Labels: bug

#8849 Make the missions that trigger the Kestrel available events fail instead of persisting
  data/human/kestrel.txt
Labels: bug

#8873 Spaces on separate `words` in hails
  data/human/hails.txt
Labels: typo

#8866 Potential change for #7883
  data/human/free worlds 1 start.txt
Labels: content

#8882 Rename stopover jobs
  data/hai/hai jobs.txt
  data/hai/unfettered jobs.txt
  data/human/deep jobs.txt
  data/human/paradise world jobs.txt
  data/human/syndicate jobs.txt
Labels: content

#8901 feat(enhancement): Add proper pluralization to two messages
  source/PlayerInfo.cpp
Labels: enhancement

#8874 Fix remnant mission bug (scanning cloaked Starling) by adding a `decloaked` personality, plus some warp_core refactoring
  data/remnant/remnant 1 introduction.txt
  source/AI.cpp
  source/Personality.cpp
  source/Personality.h
Labels: enhancement

#8895 Fix plugin icon missing when no @2x is provided
  source/ImageSet.cpp
Labels: bug

#8892 Fix an issue with out of system escort refuelling
  source/AI.cpp
Labels: bug

#8897 Fix Remnant JD missions destination being Ssil Vida
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant jobs.txt
Labels: content

#8906 feat(ci): Fix some edge cases with the triggering of projects checks
  .github/path-filters.yml
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
Labels: cd/ci/testing

#8782 feat(content): Remove Gegno Quarg `custom penalties for`
  data/governments.txt
Labels: content

#8909 Upload all the Steam depots when creating a release
  .github/workflows/cd_release.yaml
Labels: cd/ci/testing

#8830 feat(UI): Truncate too long system names in the escort HUD
  source/EscortDisplay.cpp
Labels: waiting on OP, UI

#8879 fix(typo): Various Typos in 0.10.1
  data/bunrodea/bunrodea outfits.txt
  data/hai/hai reveal 0 prologue.txt
  data/hai/hai reveal 1 intro.txt
  data/human/deep missions.txt
  data/human/news.txt
  source/GameData.cpp
Labels: typo

#8912 bugfix(content): Prevent "financial analyst" news from showing up during the Pug occupation
  data/human/news.txt
Labels: bug

#8914 typo/feat: Enable codespell for changelog, fix typos.
  .github/path-filters.yml
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
  changelog
Labels: cd/ci/testing, typo

#8917 feat(content): Add missing condition to news entry (resolves TODO)
  data/human/news.txt
Labels: content

#8916 Fix/standardize capitalization of names in news entries
  data/human/news.txt
Labels: text - short

#8920 fix(typo): Don't capitalize "flotsam"
  data/_ui/help.txt
  keys.txt
  source/Command.cpp
Labels: typo

#8921 fix(typo): `ring world` -> `ringworld` in gegno intro missions
  data/gegno/gegno intro missions.txt
Labels: typo

#8855 Fix bug that keeps player's flagship from being destroyed after an "on enter" conversation `explode` (and split up Ship::Move)
  source/Ship.cpp
  source/Ship.h
Labels: bug, mechanics, refactor

#8881 Create NPCAction that wraps MissionAction for NPCs and records usage to prevent crash
  EndlessSkyLib.cbp
  source/CMakeLists.txt
  source/MissionAction.cpp
  source/MissionAction.h
  source/NPC.cpp
  source/NPC.h
  source/NPCAction.cpp
  source/NPCAction.h
Labels: bug

#8915 Do not prevent ships targeting an asteroid from looking for ships to target
  source/AI.cpp
Labels: bug

#8791 fix(bug): HR - fix rep with new (Friendly Unfettered) faction in plot
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 6 end.txt
Labels: bug, content

#8900 0.10.2 documentation update
  changelog
  credits.txt
  endless-sky.6
  io.github.endless_sky.endless_sky.appdata.xml
  source/main.cpp
Labels: documentation

#8925 Fix default status overlay preference
  changelog
  source/Preferences.cpp
Labels: bug

#8927 Update version numbers for 0.10.3-alpha
  CMakeLists.txt
  credits.txt
  endless-sky.6
  resources/EndlessSky-Info.plist
  source/main.cpp
Labels: documentation

#8763 Rescue downed Efreti crew and salvage ship (from @williaji)
  data/korath/korath missions.txt
Labels: content, text - short

#8521 feat(content): Vivid Aether wording tweak
  data/map planets.txt
Labels: content

#8473 feat(AI): Ships that run out of ammo will try to flee
  source/AI.cpp
  source/ship/ShipAICache.cpp
  source/ship/ShipAICache.h
Labels: mechanics, to be merged

#8666 feat(enhancement): Allow escorts to cloak when damaged
  source/AI.cpp
Labels: enhancement, to be merged

#8899 feat(testing): Add some rudamentary checks for indefinite articles to the content style checker
  utils/contentStyle.json
Labels: cd/ci/testing

#8256 Fix gas giant landing
  source/AI.cpp
  source/AI.h
  source/Engine.cpp
  source/PlayerInfo.cpp
  source/PlayerInfoPanel.cpp
  source/ShopPanel.cpp
Labels: bug, mechanics

#8736 refactor(code): Prevent checking for hyperspace capabilities while hyperspacing
  source/AI.cpp
Labels: refactor

#8935 Correct text replacement in "Remnant: Shattered Light 6"
  data/remnant/remnant 2 side missions.txt
Labels: typo

#8931 [Balance] Buff Stock Fighter Kits
  data/human/ships.txt
Labels: balance

#8939 Update human missions.txt
  data/human/human missions.txt
Labels: typo

#8933 Add text reminding player to hail Greenrock in the 'Deal Change' missions
  data/human/human missions.txt
Labels: content, text - short

#8385 feat(enhancement): Make motherships and carried ships recharge each other from battery power
  source/Ship.cpp
Labels: enhancement

#8918 feat(enhancement): Add support for displaying the fuel and regular ammo count properly
  source/AmmoDisplay.cpp
Labels: enhancement

#8946 fixed cargo capacity calculation when landing
  source/PlayerInfo.cpp
Labels: bug

#8958 A small refactor to planet selection for in-system escorts that can't land on the player's planet in PlayerInfo::Land
  source/PlayerInfo.cpp
Labels: refactor

#8956 Separate flagship overlay colours
  data/_ui/interfaces.txt
  source/Engine.cpp
Labels: UI

#8960 fix(ui): Fix map buttons overlapping on smaller screens
  data/_ui/interfaces.txt
  source/MapPanel.cpp
Labels: bug, UI
