Repository endless-sky/endless-sky, pull requests merged in 2023-09, with the labels that each got.

#9251 Allow toggling fullscreen in all panels
  source/main.cpp
Labels: enhancement, mechanics

#9248 fix(typo): Various typo fixes
  data/coalition/coalition jobs.txt
  data/gegno/gegno intro missions.txt
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 2 start.txt
  data/hai/hai reveal 7 epilogue.txt
  data/hai/unfettered jobs.txt
  data/human/culture conversations.txt
  data/human/deep jobs.txt
  data/korath/korath outfits.txt
  data/quarg/quarg missions.txt
  data/quarg/quarg.txt
Labels: typo

#9250 fix(content): Trim New Austria's post-bombing description to better fit text box
  data/human/campaign events.txt
Labels: content, typo

#7597 Add Total Energy/Heat Production to Ship Info Panel and Support for Advanced Shipyard Stats
  data/_ui/tooltips.txt
  source/ShipInfoDisplay.cpp
  source/ShipInfoDisplay.h
  source/ShipyardPanel.cpp
  source/ShopPanel.cpp
Labels: enhancement

#9159 Add mission to take refugees to Humanika
  data/human/human missions.txt
Labels: content, text - short

#9254 feat(ci): Exclude individual words from the spellcheck CI
  .codespell.words.exclude
  .github/path-filters.yml
  .github/workflows/projects_check.yml
Labels: cd/ci/testing

#9256 Typo fix
  data/map planets.txt
Labels: typo

#8556 [Mechanic] Shield/Hull Multipliers
  data/_ui/tooltips.txt
  source/AlertLabel.cpp
  source/DamageProfile.cpp
  source/MapShipyardPanel.cpp
  source/Outfit.cpp
  source/OutfitInfoDisplay.cpp
  source/PrintData.cpp
  source/Ship.cpp
  source/Ship.h
  source/ShipInfoDisplay.cpp
  source/ship/ShipAICache.cpp
Labels: mechanics

#9053 feat(ui): enhance maps with parked/stored item lists, system colors
  copyright
  images/ui/sales key.png
  source/MapOutfitterPanel.cpp
  source/MapSalesPanel.cpp
  source/MapSalesPanel.h
  source/MapShipyardPanel.cpp
  source/MapShipyardPanel.h
Labels: mechanics, UI

#9270 Fix NPC actiosn again
  source/NPC.cpp
Labels: bug

#9267 refactor: Remove now redundant conditions in deep archaeology
  data/sheragi/archaeology missions.txt
Labels: content, refactor

#8938 feat(ui): Display the government name on the planet card
  data/_ui/interfaces.txt
  source/MapDetailPanel.cpp
  source/MapPlanetCard.cpp
  source/MapPlanetCard.h
Labels: enhancement, UI

#9274 Update Heliarchs Buy JDs job
  data/coalition/coalition jobs.txt
Labels: content, text - short

#9277 chore(ci): Update actions/checkout
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
  .github/workflows/steam.yml
Labels: cd/ci/testing

#7324 Allow changing date format in GUI
  source/Date.cpp
  source/LoadPanel.cpp
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
Labels: enhancement, UI

#9280 Correct style in Date.cpp includes
  source/Date.cpp
Labels: bug

#9263 feat(content): Rename Hai "Railgun" to "Skipper Railgun" using `display name`
  data/hai/hai outfits.txt
  data/hai/hai ships.txt
Labels: content

#9281 fix(content): Fix Gegno reference in Gegno Intro Mission
  data/gegno/gegno intro missions.txt
Labels: content, typo

#9238 Fix plugins with a custom name
  source/GameData.cpp
  source/PlayerInfo.cpp
  source/Plugins.cpp
  source/Plugins.h
Labels: bug

#9282 Fix caching that's been broken for a while
  .github/sccache/action.yml
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  CMakePresets.json
Labels: cd/ci/testing

#8677 feat(mechanics): Governments can now fine the player for illegal ships
  source/Government.cpp
  source/Government.h
  source/Politics.cpp
Labels: mechanics

#9189 feat(mechanics): Show all applicable takeoff warnings
  source/PlanetPanel.cpp
Labels: enhancement, UI

#9283 fix(cd): Don't skip artifact uploads to continuous
  .github/workflows/cd.yaml
Labels: bug, cd/ci/testing

#6489 Feat(mechanics) : Government system restrictions
  data/governments.txt
  source/AI.cpp
  source/Fleet.cpp
  source/Government.cpp
  source/Government.h
  source/Personality.cpp
  source/Personality.h
  source/Politics.cpp
  tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt
Labels: enhancement, waiting on reviewer

#9297 Fix "Trash Fire Crops" source location filter
  data/human/culture conversations.txt
Labels: bug

#9266 Remove unused #includes
  source/BoardingPanel.cpp
  source/Body.cpp
  source/DrawList.cpp
  source/Engine.cpp
  source/EscortDisplay.cpp
  source/Fleet.cpp
  source/FormationPattern.cpp
  source/GameAction.cpp
  source/GameData.cpp
  source/GameEvent.cpp
  source/GameLoadingPanel.cpp
  source/HailPanel.cpp
  source/HiringPanel.cpp
  source/LoadPanel.cpp
  source/MainPanel.cpp
  source/MapPlanetCard.cpp
  source/MapSalesPanel.cpp
  source/Minable.cpp
  source/MissionAction.cpp
  source/MissionPanel.cpp
  source/NPC.cpp
  source/PlayerInfo.cpp
  source/Plugins.cpp
  source/Ship.cpp
  source/ShipJumpNavigation.cpp
  source/ShipyardPanel.cpp
  source/Sound.cpp
  source/SpriteQueue.cpp
  source/StarField.cpp
  source/StartConditions.cpp
  source/StartConditionsPanel.cpp
  source/TextReplacements.cpp
  source/UniverseObjects.cpp
  source/main.cpp
Labels: refactor

#9097 feat(content): Early south missions
  .codespell.exclude
  data/human/human missions.txt
Labels: content, text - long

#9303 rouge brown dwarves -> rogue brown dwarves
  copyright
  data/_ui/landing messages.txt
  data/map systems.txt
  data/stars.txt
  images/planet/browndwarf-l-rogue.png
  images/planet/browndwarf-t-rogue.png
  images/planet/browndwarf-y-rogue.png
Labels: typo

#9242 Update system requirements
  README.md
Labels: documentation

#9235 Tweaks to the build instructions
  docs/readme-cmake.md
Labels: documentation

#9091 feat(ui): shop item pane autoscrolling and handling vanished items
  source/OutfitterPanel.cpp
  source/OutfitterPanel.h
  source/ShipyardPanel.cpp
  source/ShipyardPanel.h
  source/ShopPanel.cpp
  source/ShopPanel.h
Labels: bug

#9326 Fix fewer crew than required
  source/PlanetPanel.cpp
Labels: bug

#9321 Some small build instruction tweaks
  docs/readme-cmake.md
Labels: documentation

#9323 Remove "and" from an on visit
  data/human/free worlds side plots.txt
Labels: typo

#9289 Fix jump navigation edge case
  source/Engine.cpp
  source/ShipJumpNavigation.cpp
  source/ShipJumpNavigation.h
Labels: bug

#6646 [Content] Coalition: Lunarium Intro
  copyright
  data/coalition/coalition jobs.txt
  data/coalition/coalition news.txt
  data/coalition/coalition outfits.txt
  data/coalition/coalition ships.txt
  data/coalition/coalition.txt
  data/coalition/lunarium intro.txt
  data/governments.txt
  data/map planets.txt
  data/quarg/quarg missions.txt
  images/outfit/anti-materiel gun.png
  images/outfit/decoy plating.png
  images/outfit/refuelling module.png
  images/outfit/shield refactor module.png
  images/outfit/small recovery module.png
Labels: content, waiting on reviewer, text - long

#6647 [Content] Coalition: Heliarch Intro
  copyright
  data/coalition/coalition jobs.txt
  data/coalition/coalition missions.txt
  data/coalition/coalition news.txt
  data/coalition/coalition outfits.txt
  data/coalition/coalition ships.txt
  data/coalition/coalition.txt
  data/coalition/heliarch intro.txt
  data/governments.txt
  images/outfit/heliarch license.png
Labels: content, waiting on reviewer, text - long

#9335 Fix crash when opening the outfitter
  source/OutfitterPanel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/ShopPanel.cpp
Labels: bug, refactor

#9319 Allow building for MinGW without having a VS toolchain installed
  CMakePresets.json
Labels: cd/ci/testing

#9332 Fix race condition when drawing the planet labels
  source/Engine.cpp
Labels: bug

#9252 feat(content): Add more high-end passenger transport missions
  data/human/deep jobs.txt
  data/human/dirt belt jobs.txt
  data/human/jobs.txt
  data/human/near earth jobs.txt
  data/human/paradise world jobs.txt
  data/human/rim jobs.txt
  data/human/syndicate jobs.txt
Labels: content

#9324 Make the player takeoff from the ringworld dock it landed on
  source/Engine.cpp
Labels: bug

#9339 Fix performance regression in Omnis system
  source/Engine.cpp
  source/Engine.h
Labels: refactor

#9337 Correctly add compiler flags for main.cpp
  CMakeLists.txt
Labels: cd/ci/testing

#9340 2 quick fixes to Coalition Intros
  data/coalition/heliarch intro.txt
  data/coalition/lunarium intro.txt
Labels: content

#9333 Optimize applying lots of events with map changes
  source/GameEvent.cpp
  source/GameEvent.h
  source/PlayerInfo.cpp
Labels: refactor

#9338 Feat(ui): Make the message about landing unavailable more visible
  source/AI.cpp
  source/Engine.cpp
Labels: UI

#9296 Fix usage of SDL_GetPrefPath
  source/Files.cpp
  source/Files.h
Labels: bug

#9343 Fix to 'Refugees to Humanika' mission
  data/human/human missions.txt
Labels: typo

#9347 Fix to intra-Sol transportation jobs
  data/human/near earth jobs.txt
Labels: typo

#9342 Heliarch Drills: Add Dialog in case you destroy the Punisher
  data/coalition/heliarch intro.txt
Labels: content, text - short

#9345 Give the Hallucination a noun
  data/human/human missions.txt
Labels: content

#9341 Nerf Refueling Module
  copyright
  data/coalition/coalition outfits.txt
  data/coalition/coalition.txt
  images/outfit/refueling module.png
Labels: balance

#9359 Fix use of "Heliarch License: (offered | done)" condition
  data/coalition/coalition jobs.txt
  data/coalition/coalition news.txt
  data/coalition/heliarch intro.txt
  data/coalition/lunarium intro.txt
Labels: bug

#9368 fix: Fix missing reference parameter
  source/AI.cpp
Labels: bug

#9364 Fix secure package delivery message
  data/human/deep jobs.txt
Labels: content

#9369 feat(content): Adjust how "Heliarch Drill 3" `fails`
  data/coalition/heliarch intro.txt
Labels: content, text - short

#9370 feat(content) Change `require` to `on offer` conditions in Lunarium Intro
  data/coalition/lunarium intro.txt
Labels: content

#9382 Fix some conditions in the Coalition intros
  data/coalition/heliarch intro.txt
  data/coalition/lunarium intro.txt
Labels: bug, content

#9376 Fix jump drive usage of hyperlinks from systems with limited jump range
  source/ShipJumpNavigation.cpp
Labels: bug

#9384 Typos: "on path to conflict" -> "on a path to conflict"
  data/coalition/heliarch intro.txt
  data/coalition/lunarium intro.txt
Labels: typo

#9374 fix(content): Adjust JD values of some Gegno & Rulei Systems
  data/map systems.txt
Labels: bug, content

#9385 Fix coalition campaign conditions
  data/coalition/coalition jobs.txt
  data/coalition/lunarium intro.txt
  data/quarg/quarg missions.txt
Labels: bug, content

#9344 v0.10.3 changelog
  changelog
Labels: documentation

#9386 Fix archaeology mission condition
  changelog
  data/sheragi/archaeology missions.txt
Labels: bug, content

#9329 0.10.3 docs update
  credits.txt
  endless-sky.6
  io.github.endless_sky.endless_sky.appdata.xml
  source/main.cpp
Labels: documentation
