Repository endless-sky/endless-sky, pull requests merged in 2023-05, with the labels that each got.

#8508 Autosteer key for pointing the ship at the selected ship, asteroid or planet (from @ChamEV)
  images/ui/keys panel.png
  keys.txt
  source/AI.cpp
  source/Command.cpp
  source/Command.h
  source/Engine.cpp
  source/PreferencesPanel.cpp
Labels: enhancement

#8366 feat(content): Continuation to Quicksilver package mixup
  data/human/human missions.txt
Labels: content, text - short

#8708 feat(content): Refactor Augen NPC Mission
  data/gegno/gegno intro missions.txt
  tests/integration/config/plugins/integration-tests/data/disabling troublesome missions.txt
Labels: content

#8719 feat(content): Adjust offer paramaeters for Gegno: Genocide Defense
  data/gegno/gegno intro missions.txt
Labels: content

#8715 fix(status-messages): Only report insufficient crew on player-owned ships
  source/Ship.cpp
Labels: bug

#8729 fix(bug): HR Bugfixes 5
  data/hai/hai reveal 6 end.txt
Labels: bug

#8601 feat(content): Remove Gegno Quarg Landables from Quarg Missions
  data/kahet/kahet missions.txt
  data/quarg/quarg missions.txt
Labels: content

#8731 (Bugfix)(Coalition) Add missing "blocked" field to mission Saryd Students 2
  data/coalition/coalition missions.txt
Labels: bug

#8733 (Style Fix) Remove extra whitespace from the Met Par Tek 53
  data/korath/korath ships.txt
  data/persons.txt
Labels: content

#8641 feat(content): Gegno Expansion ft. Mining!
  copyright
  data/gegno/gegno fleets.txt
  data/gegno/gegno outfits.txt
  data/gegno/gegno sales.txt
  data/gegno/gegno ships.txt
  data/map planets.txt
  data/map systems.txt
  images/hardpoint/burrower.png
  images/hardpoint/ion torch.png
  images/outfit/burrower.png
  images/outfit/ion torch.png
  images/projectile/torch+0.png
  images/projectile/torch+1.png
  images/projectile/torch+2.png
  images/projectile/torch+3.png
  images/projectile/torch+4.png
  images/projectile/torch+5.png
  images/projectile/torch+6.png
  images/ship/gegno conglomerate.png
  images/ship/gegno corundum.png
  images/ship/gegno granofel.png
  images/ship/gegno protolith.png
  images/thumbnail/gegno corundum.png
  images/thumbnail/gegno granofel.png
  images/thumbnail/gegno protolith.png
  sounds/drill~.wav
  sounds/excavator~.wav
  sounds/ion torch~.wav
Labels: balance, content, artwork

#8656 feat(content): Gegno Scin Additions
  copyright
  data/gegno/gegno fleets.txt
  data/gegno/gegno outfits.txt
  data/gegno/gegno ships.txt
  data/map planets.txt
  data/map systems.txt
  images/effect/explosion/neutron~0.png
  images/effect/explosion/neutron~1.png
  images/effect/explosion/neutron~2.png
  images/effect/explosion/neutron~3.png
  images/effect/explosion/neutron~4.png
  images/effect/explosion/neutron~5.png
  images/outfit/acumen.png
  images/planet/beryl/beryl-00.png
  images/planet/beryl/beryl-01.png
  images/planet/beryl/beryl-02.png
  images/planet/beryl/beryl-03.png
  images/planet/beryl/beryl-04.png
  images/planet/beryl/beryl-05.png
  images/planet/beryl/beryl-06.png
  images/planet/beryl/beryl-07.png
  images/planet/beryl/beryl-08.png
  images/planet/beryl/beryl-09.png
  images/planet/beryl/beryl-10.png
  images/planet/beryl/beryl-11.png
  images/planet/beryl/beryl-12.png
  images/projectile/neutron bolt.png
  images/ship/gegno kyanite.png
  images/thumbnail/gegno kyanite.png
  sounds/neutron bolt.wav
Labels: content, artwork

#8615 feat(enhancement): Hide less important scan messages
  source/Government.cpp
  source/Government.h
  source/Ship.cpp
Labels: enhancement, waiting on OP

#8334 feat(ui): Unbind Keybinds
  data/_ui/interfaces.txt
  source/Command.cpp
  source/Command.h
  source/PreferencesPanel.cpp
  source/PreferencesPanel.h
Labels: enhancement, UI

#8125 "lingering" personality tells ships to stay in a system for a while if they have nothing to do
  source/AI.cpp
  source/Personality.cpp
  source/Personality.h
  source/Ship.cpp
  source/Ship.h
  source/System.cpp
  source/System.h
Labels: enhancement

#8421 Conversation text can include formatted conditions.
  source/ConversationPanel.cpp
  source/text/Format.cpp
  source/text/Format.h
  tests/unit/src/text/test_format.cpp
Labels: enhancement

#8723 Chore(Update) planet attributes for tourism + humans
  data/map planets.txt
Labels: content

#8744 bugfix: Fix incorrect string delimiting in DataWriter
  source/DataWriter.cpp
Labels: bug

#8484 feat(content): add mission about transporting a blind man from Martini
  data/human/human missions.txt
Labels: content, text - short

#8748 Improve Remnant Rescue 4 location filter
  data/remnant/remnant jobs.txt
Labels: content

#8740 feat(content): Adjust Gegno Trade Prices
  data/map systems.txt
Labels: content

#8760 Add new ship category conditions to missions
  data/human/human missions.txt
  data/human/intro missions.txt
Labels: content

#8772 Bugfix(data): fix unlimited money/tripulses exploit
  data/hai/unfettered jobs.txt
Labels: bug

#8734 feat(content): HR player experience updates 5
  data/hai/hai reveal 5 philosophers.txt
Labels: content, text - short

#8766 Add additional human names
  data/human/names.txt
Labels: content

#8780 feat(content): Escort Betrayal mission
  data/governments.txt
  data/human/human missions.txt
Labels: content, text - short

#8776 Adjust M- and K- class supergiants' solar wind values to fit the trend in similar stars
  data/stars.txt
Labels: typo

#8800 Add a blocked message to Wanderers Invaded 3
  data/wanderer/wanderers start.txt
Labels: bug

#8789 Hai Reveal Reworked Introduction
  data/hai/hai missions.txt
  data/hai/hai reveal 0 prologue.txt
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 3 early.txt
  data/hai/hai reveal news.txt
  data/hai/unfettered 0 prologue.txt
  data/human/free worlds 4 epilogue.txt
  data/human/human missions.txt
  data/human/post-war reactions.txt
  data/wanderer/wanderers start.txt
Labels: content

#8696 Reorder settings
  source/PreferencesPanel.cpp
Labels: refactor, UI

#8793 v0.10.1 changelog update
  changelog
Labels: documentation

#8807 Update docs for 0.10.1
  changelog
  credits.txt
  endless-sky.6
  io.github.endless_sky.endless_sky.appdata.xml
  source/main.cpp
Labels: documentation

#8810 Update version numbers for 0.10.2 alpha
  CMakeLists.txt
  credits.txt
  endless-sky.6
  resources/EndlessSky-Info.plist
  source/main.cpp
Labels: documentation

#8812 Replace incorrect substitutions in new HR intro
  data/hai/hai reveal 0 prologue.txt
Labels: typo

#8739 A few new hails for friendly human merchants
  data/human/hails.txt
Labels: content, text - short
