Repository endless-sky/endless-sky, pull requests merged in 2023-04, with the labels that each got.

#8612 Update Actions and dependencies
  .github/sccache/action.yml
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  vcpkg-configuration.json
Labels: cd/ci/testing

#7054 Better shop ordering
  EndlessSkyLib.cbp
  EndlessSkyTests.cbp
  source/CMakeLists.txt
  source/CategoryList.cpp
  source/CategoryList.h
  source/CategoryTypes.h
  source/Engine.cpp
  source/GameData.cpp
  source/GameData.h
  source/LocationFilter.cpp
  source/MainPanel.cpp
  source/MapOutfitterPanel.cpp
  source/MapSalesPanel.cpp
  source/MapSalesPanel.h
  source/MapShipyardPanel.cpp
  source/Outfit.cpp
  source/Outfit.h
  source/OutfitterPanel.cpp
  source/Ship.cpp
  source/ShipInfoDisplay.cpp
  source/ShipInfoPanel.cpp
  source/ShipyardPanel.cpp
  source/ShopPanel.cpp
  source/ShopPanel.h
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  source/comparators/BySeriesAndIndex.h
  tests/CMakeLists.txt
  tests/unit/src/test_categoryList.cpp
Labels: enhancement, waiting on reviewer

#8517 Fix jobs requiring outfits being acceptable with the outfits in cargo, not installed
  data/coalition/coalition jobs.txt
  data/hai/hai jobs.txt
  data/human/jobs.txt
  data/human/paradise world jobs.txt
  data/human/pirate jobs.txt
  data/human/syndicate jobs.txt
  data/wanderer/wanderer jobs.txt
  source/PlayerInfo.cpp
Labels: bug

#8578 Reduce combat rating requirement for the Kestrel
  data/human/kestrel.txt
Labels: balance

#8558 Feature: Mining Asteroid Health Bar
  source/Engine.cpp
  source/Minable.cpp
  source/Minable.h
Labels: enhancement

#8594 feat(artwork): Vyu-Ir Update
  copyright
  data/rulei/rulei outfits.txt
  data/rulei/rulei ships.txt
  data/rulei/rulei.txt
  images/scene/rulei flash.png
  images/scene/rulei.png
  images/ship/vyuir/vyuir-0.png
  images/ship/vyuir/vyuir-1.png
  images/ship/vyuir/vyuir-2.png
  images/ship/vyuir/vyuir-3.png
  images/ship/vyuir/vyuir-4.png
  images/ship/vyuir/vyuir-5.png
  images/ship/vyuir/vyuir-6.png
  images/ship/vyuir/vyuir-7.png
  images/ship/vyuir/vyuir-8.png
  images/ship/vyuir/vyuir-9.png
  images/ship/vyuira/vyuira-0.png
  images/ship/vyuira/vyuira-1.png
  images/ship/vyuira/vyuira-2.png
  images/ship/vyuira/vyuira-3.png
  images/ship/vyuira/vyuira-4.png
  images/ship/vyuira/vyuira-5.png
  images/ship/vyuira/vyuira-6.png
  images/ship/vyuira/vyuira-7.png
  images/ship/vyuira/vyuira-8.png
  images/ship/vyuira/vyuira-9.png
  images/thumbnail/vyuir.png
  images/thumbnail/vyuira.png
  tests/integration/config/plugins/integration-tests/data/disabling troublesome missions.txt
Labels: balance, content, artwork

#8479 feat(content): Add a short mission about an Argosy hijacking in Syndicate space
  data/governments.txt
  data/human/human missions.txt
Labels: content, text - short

#8627 Fix license duplication in outfitter panel
  source/OutfitterPanel.cpp
Labels: bug

#7075 feat(derived conditions): Remove the primary condition iterators
  source/Account.cpp
  source/Account.h
  source/BankPanel.cpp
  source/ConditionsStore.cpp
  source/ConditionsStore.h
  source/HailPanel.cpp
  source/OutfitInfoDisplay.cpp
  source/OutfitterPanel.cpp
  source/OutfitterPanel.h
  source/Planet.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/PlayerInfoPanel.cpp
  source/ShipInfoDisplay.cpp
  source/ShipyardPanel.cpp
  source/ShopPanel.cpp
  source/Test.cpp
  tests/unit/src/test_conditionSet.cpp
  tests/unit/src/test_conditionsStore.cpp
Labels: enhancement

#8637 feat(outfitter UI): Point ships that have the selected item installed
  source/ShopPanel.cpp
Labels: UI

#8630 Give MZ credit for tooltips.txt
  data/tooltips.txt
  utils/contentStyle.json
Labels: documentation

#8599 Small docs improvements
  CONTRIBUTING.md
  docs/CONTRIBUTING.md
  docs/readme-cmake.md
  docs/readme-developer.md
Labels: documentation

#8604 Less repetition in Coalition university lecture
  data/coalition/coalition missions.txt
  data/hai/unfettered 0 prologue.txt
Labels: content

#8625 Fix some outfitter buttons bugs
  source/CargoHold.cpp
  source/OutfitterPanel.cpp
  source/ShopPanel.cpp
Labels: bug

#8464 [Balance] Unfettered Ion/Scrambling tweaks
  data/hai/hai outfits.txt
Labels: balance, content

#8619 Feat(content): New Civilian Hails
  data/human/hails.txt
Labels: content

#6669 Mining enhancement: fleet focus fire
  data/help.txt
  keys.txt
  source/AI.cpp
  source/AI.h
  source/Command.cpp
  source/Command.h
  source/Engine.cpp
  source/MainPanel.cpp
  source/Minable.cpp
  source/Minable.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/Preferences.cpp
  source/PreferencesPanel.cpp
  source/Ship.cpp
  source/UniverseObjects.cpp
  tests/integration/config/preferences.txt
Labels: enhancement

#8640 feat(artwork): New landing images for 13 planets
  copyright
  data/map planets.txt
  images/land/badlands13.jpg
  images/land/beach15.jpg
  images/land/city24.jpg
  images/land/city25.jpg
  images/land/desert14.jpg
  images/land/desert15.jpg
  images/land/forest10.jpg
  images/land/mountain27.jpg
  images/land/mountain28.jpg
  images/land/mountain29.jpg
  images/land/mountain30.jpg
  images/land/sea22.jpg
  images/land/snow22.jpg
Labels: artwork

#8610 Update Plasma Repeater Scene
  images/scene/plasma scene.png
Labels: artwork

#6846 Mission deadlines and payments with wormholes and jump drives
  EndlessSkyLib.cbp
  source/CMakeLists.txt
  source/DistanceMap.cpp
  source/DistanceMap.h
  source/Mission.cpp
  source/Mission.h
  source/WormholeStrategy.h
Labels: enhancement

#8633 Some improvements to the new status overlay settings
  source/Engine.cpp
  source/Engine.h
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
Labels: refactor

#8646 feat(ci): Enhance the detection capabilities of the content style checker
  data/gegno/gegno sales.txt
  utils/check_content_style.py
  utils/contentStyle.json
Labels: cd/ci/testing

#8624 fix(ui): Draw escort/storage map tooltips on top of other elements
  source/MapDetailPanel.cpp
  source/MapPanel.cpp
  source/MapPanel.h
  source/MapSalesPanel.cpp
  source/MissionPanel.cpp
Labels: UI

#8597 feat(content): Short Rulei Mission - Umbral Reach
  data/rulei/rulei.txt
Labels: content, text - short

#8648 Bugfix: Mining AI, melee, and other AI distance fix
  source/AI.cpp
  source/ship/ShipAICache.cpp
  source/ship/ShipAICache.h
Labels: mechanics

#8620 Feature: Remove r-alt and use mouse control preference
  data/help.txt
  keys.txt
  source/Command.cpp
  source/Command.h
  source/Engine.cpp
  source/Engine.h
  source/MainPanel.cpp
  source/Preferences.cpp
  source/PreferencesPanel.cpp
Labels: UI

#8661 fix(content): Stop "Immigrant Workers" from going to Pirate space
  data/human/human missions.txt
Labels: bug

#8652 NPC max mining time gamerule
  data/gamerules.txt
  source/AI.cpp
  source/Gamerules.cpp
  source/Gamerules.h
Labels: enhancement

#8649 Bugfix: Remove turning flares while stopping
  source/AI.cpp
  source/AI.h
Labels: bug

#7435 Content: Hai Reveal's warlord gets a unique ship
  copyright
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai ships.txt
  images/ship/hai emperor beetle.png
  images/thumbnail/hai emperor beetle.png
Labels: content, artwork, waiting on reviewer, text - short

#8498 feat(content): Navy Questioning / Human–Hai related missions adjusted
  data/human/free worlds 0 prologue.txt
  data/human/human missions.txt
Labels: content, text - short

#8664 feat(balance): Remove range overrides on missile pods
  data/human/weapons.txt
Labels: balance

#7760 Hai Reveal intro: rewrite pug media coverage with less narrator editorializing, as several missions in a new file
  data/hai/hai reveal 1 intro.txt
  data/human/post-war reactions.txt
Labels: content, text - short

#8036 Korath Exile and Kor Efret hails
  .codespell.exclude
  data/governments.txt
  data/korath/korath hails.txt
  utils/korath-cipher.py
Labels: enhancement, content, text - long

#8647 feat(content): Reduce payment of "Deal Change 2"
  data/categories.txt
  data/human/human missions.txt
Labels: balance

#8548 Have more missions use negative binomial cargo amounts
  data/hai/hai jobs.txt
  data/human/paradise world jobs.txt
  data/human/syndicate jobs.txt
  data/remnant/remnant jobs.txt
Labels: balance, content

#8667 fix(content): Remove temporary testing mission
  data/categories.txt
Labels: bug

#8672 HR: Fix a condition
  data/hai/hai reveal 1 intro.txt
Labels: bug

#8044 refactor(data): Organizing un-sorted files in the data folder
  data/_deprecated/deprecated outfits.txt
  data/_deprecated/deprecated ships.txt
  data/_ui/flight checks.txt
  data/_ui/help.txt
  data/_ui/interfaces.txt
  data/_ui/landing messages.txt
  data/_ui/ratings.txt
  data/_ui/tooltips.txt
  data/human/intro missions.txt
Labels: refactor

#8679 feat(UI): Escort HUD improvements
  data/_ui/interfaces.txt
  source/EscortDisplay.cpp
  source/EscortDisplay.h
Labels: UI

#8694 feat(enhancement): Guns-only and turrets-only autofire modes
  source/AI.cpp
  source/AI.h
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
Labels: enhancement

#8701 Fix some ships being unable to jump
  source/AI.cpp
Labels: bug

#8293 "ignore clearance" missions will offer even if player has no clearance
  source/Mission.cpp
  source/Mission.h
Labels: enhancement

#8711 Reduce Payment of "Wool Smuggling"
  data/human/human missions.txt
Labels: balance

#8684 feat(content): Alternate Gegno intro ending if hostile with Quarg
  data/gegno/gegno intro missions.txt
Labels: content

#8682 feat(artwork): New Bounder sprites
  copyright
  data/human/marauders.txt
  data/human/ships.txt
  images/ship/bounder.png
  images/ship/mboundere.png
  images/ship/mbounders.png
  images/ship/mbounderw.png
  images/thumbnail/bounder.png
  images/thumbnail/mboundere.png
  images/thumbnail/mbounders.png
  images/thumbnail/mbounderw.png
Labels: artwork
