Repository endless-sky/endless-sky, pull requests merged in 2023-11, with the labels that each got.

#9526 Lunarium: Smuggling: Charity 2 - correct offer condition
  data/coalition/lunarium intro.txt
Labels: bug, typo

#9533 fix(typo): Keep periods inside of parentheses in choices
  data/coalition/coalition missions.txt
  data/gegno/gegno intro missions.txt
  data/human/human missions.txt
Labels: typo

#9531 fix(typo): Hiding in Plain Sight missing period
  data/hai/hai missions.txt
Labels: typo

#9529 feat(content): Trim one of the Quarg News descriptions
  data/quarg/quarg news.txt
Labels: content

#9279 Define load panel list regions in interface
  data/_ui/interfaces.txt
  source/LoadPanel.cpp
  source/LoadPanel.h
Labels: UI

#9495 feat(balance): Reduce the turn rate and burn DPS of the Inferno and Blaze-pike
  data/korath/korath weapons.txt
Labels: balance

#9508 Feat(balance): nerf the Flamethrower again
  data/human/weapons.txt
Labels: balance

#9433 Double-width popup dialogs when needed
  images/ui/dialog bottom wide.png
  images/ui/dialog middle wide.png
  images/ui/dialog top wide.png
  source/Dialog.cpp
  source/Dialog.h
  source/text/WrappedText.cpp
  source/text/WrappedText.h
Labels: UI

#9523 Navy resupply 0 government filter update
  data/human/far north jobs.txt
Labels: bug

#9544 fix: Syndicate Security -> Syndicated Security
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal 7 epilogue.txt
  data/human/culture conversations.txt
  data/human/sales.txt
  data/human/variants.txt
Labels: typo

#9543 fix(content): Consistency fixes in text, adjust Deep's science ship names
  data/human/deep jobs.txt
  data/human/human missions.txt
  data/human/names.txt
  data/human/near earth jobs.txt
  data/human/paradise world jobs.txt
Labels: text - short

#9541 Fix heliarch intro
  data/coalition/heliarch intro.txt
Labels: bug

#9535 fix(typo): Add missing periods/full stops to choices
  data/human/culture conversations.txt
  data/human/deep missions.txt
  data/remnant/remnant 1 introduction.txt
Labels: typo

#9534 fix: some attributes in Coalition, Core missing
  data/map systems.txt
Labels: bug

#9456 fix(format): Add support for formatting non-finite values
  source/text/Format.cpp
  tests/unit/src/text/test_format.cpp
Labels: bug, enhancement

#9502 Increase the size of escort display click zones
  data/_ui/interfaces.txt
  source/EscortDisplay.cpp
  source/EscortDisplay.h
Labels: UI

#9485 Feat: add a new `"use crew equivalent as crew"` attribute
  source/Ship.cpp
Labels: enhancement

#9548 fix(typo): Fix hyphen usage
  data/human/culture conversations.txt
  data/human/human missions.txt
  data/map planets.txt
Labels: typo

#9550 Fix zoom mismatch with landing zoom and zooming in/out
  source/Engine.cpp
  source/Engine.h
Labels: bug

#9542 Add the "Selected system: X (Y jumps away)" element to all Map Panels
  source/MapDetailPanel.cpp
  source/MapPanel.cpp
  source/MapPanel.h
  source/MissionPanel.cpp
  source/MissionPanel.h
Labels: UI

#9417 Update outdated dialogue
  data/human/free worlds 4 epilogue.txt
Labels: text - short

#9557 (Bugfix)(Coalition) Added missing goto+label to the 'Saryd University Lecture' mission
  data/coalition/coalition missions.txt
Labels: typo

#9462 refactor(code): Minor tweaks, refactors and code style changes
  source/AI.cpp
  source/Account.cpp
  source/Account.h
  source/AmmoDisplay.h
  source/BoardingPanel.cpp
  source/CategoryList.h
  source/CollisionSet.cpp
  source/ConditionSet.h
  source/ConditionsStore.cpp
  source/ConditionsStore.h
  source/DamageProfile.h
  source/DataNode.cpp
  source/Depreciation.cpp
  source/Depreciation.h
  source/Dialog.cpp
  source/DistanceCalculationSettings.h
  source/DistanceMap.h
  source/Engine.cpp
  source/EsUuid.cpp
  source/File.h
  source/FormationPattern.h
  source/GameEvent.h
  source/HailPanel.cpp
  source/ImageSet.h
  source/InfoPanelState.h
  source/LocationFilter.h
  source/MapPanel.cpp
  source/MapPlanetCard.cpp
  source/MapSalesPanel.cpp
  source/MenuPanel.cpp
  source/Messages.h
  source/Mission.h
  source/MissionPanel.cpp
  source/NPC.cpp
  source/NPC.h
  source/NPCAction.h
  source/OutfitterPanel.cpp
  source/Phrase.h
  source/PlanetPanel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfoPanel.cpp
  source/ShipyardPanel.cpp
  source/ShopPanel.cpp
  source/Test.cpp
  source/Test.h
  source/TestContext.h
  source/UI.cpp
  source/Variant.h
  source/main.cpp
  source/text/Format.cpp
  source/text/Format.h
  tests/unit/include/datanode-factory.h
  tests/unit/include/output-capture.hpp
  tests/unit/src/helpers/datanode-factory.cpp
  tests/unit/src/test_weightedList.cpp
Labels: refactor

#9549 Make depth of spaceship in dangerous games 2 more reasonable
  data/human/human missions.txt
Labels: text - short

#9083 feat(ui): Provide in-game display of damage dropoff on weapons.
  data/_ui/tooltips.txt
  source/OutfitInfoDisplay.cpp
  source/Weapon.cpp
  source/Weapon.h
Labels: UI

#8741 Fix some issues with very high drag
  source/AI.cpp
  source/Ship.cpp
  source/Ship.h
Labels: bug

#9554 Add a landing destination to every integration test
  tests/integration/config/plugins/integration-tests/data/tests/tests_afterburn_flight.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_model_condition.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_framework.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_save_load.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_shipyard_outfitter_missions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_store_outfits_on_take_off.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_take_ships.txt
Labels: cd/ci/testing

#9553 Add an integration test for landing in systems with multiple planets
  tests/CMakeLists.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_landing.txt
Labels: cd/ci/testing

#9556 Run CMake check when only the integration tests were changed
  .github/workflows/projects_check.yml
Labels: cd/ci/testing

#9555 Remove saves folder workaround for integration tests
  tests/integration/config/saves/.gitkeep
Labels: cd/ci/testing

#9528 feat(content): Return to Paradise mission (adapted from #5112)
  data/human/human missions.txt
Labels: content, text - short

#7154 feat(UI): Use u/c unload/cargo action in ship panel to sell chassis only
  source/Depreciation.cpp
  source/Depreciation.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/ShipyardPanel.cpp
  source/ShipyardPanel.h
  source/ShopPanel.cpp
Labels: enhancement, mechanics

#9566 fix(ui): Limit heat meter length on escort HUD
  source/EscortDisplay.cpp
Labels: bug

#9561 fix(mechanics): Apply planetary security fines for illegal cargo
  source/PlayerInfo.cpp
  source/Politics.cpp
Labels: mechanics

#9527 feat/fix(content): Human hails trimmings and small additions
  data/human/hails.txt
Labels: content, text - short, typo

#9468 Improve the linux CMake instructions a bit
  docs/readme-cmake.md
Labels: documentation

#8217 feat(content): Conversation about Greenrock's reversion to piracy
  data/human/campaign events.txt
  data/human/free worlds side plots.txt
Labels: content, waiting on reviewer, text - short

#9570 Fix capture override integration test
  tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt
Labels: cd/ci/testing

#9569 Fix deadlock while loading the game
  source/SpriteQueue.cpp
Labels: bug

#9571 Allow ctest to repeatedly run integration tests
  .github/path-filters.yml
  tests/integration/IntegrationTests.cmake
  tests/integration/RunIntegrationTest.cmake
Labels: cd/ci/testing

#9515 Feature: Search functionality for Shipyard/Outfitter Panels
  copyright
  data/_ui/help.txt
  images/ui/find selected.png
  images/ui/find unselected.png
  source/MapOutfitterPanel.cpp
  source/MapPanel.cpp
  source/MapPanel.h
  source/MapShipyardPanel.cpp
  source/OutfitterPanel.cpp
  source/OutfitterPanel.h
  source/ShipyardPanel.cpp
  source/ShipyardPanel.h
  source/ShopPanel.cpp
  source/ShopPanel.h
  source/text/Format.cpp
  source/text/Format.h
Labels: enhancement, UI

#9574 Condense PR template
  .github/pull_request_template.md
Labels: documentation

#9579 Don't show 'shipyard' help message for integration tests
  tests/integration/config/preferences.txt
Labels: cd/ci/testing
