Repository endless-sky/endless-sky, pull requests merged in 2023-03, with the labels that each got.

#8480 feat(content): Adding solar to the Modified Dromedary
  data/remnant/remnant ships.txt
Labels: content

#8462 [Content]Hai wording tweak
  data/hai/hai reveal 4 middle.txt
Labels: content, text - short

#8469 Increase Gun Count on Small Combat Ships
  data/human/ships.txt
  data/human/variants.txt
  data/persons.txt
  images/ship/dagger.png
  images/ship/finch.png
  images/ship/fury.png
  images/ship/lance.png
  images/ship/mfury.png
  images/ship/sparrow.png
  images/ship/wasp.png
  images/thumbnail/dagger.png
  images/thumbnail/finch.png
  images/thumbnail/fury.png
  images/thumbnail/lance.png
  images/thumbnail/mfury.png
  images/thumbnail/sparrow.png
  images/thumbnail/wasp.png
Labels: balance, artwork

#8494 Make Nullifier a cluster firing weapon
  data/kahet/kahet outfits.txt
Labels: balance

#8500 Fix integration test warnings: `scan speed` => `scan efficiency`
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_wormhole_navigation.txt
Labels: cd/ci/testing

#8431 feat(content): Auxiliary Mark II
  data/human/events.txt
  data/human/fleets.txt
  data/human/free worlds side plots.txt
  data/human/variants.txt
Labels: content

#8466 Fix possible failed truncation
  source/text/Font.cpp
Labels: bug

#8467 feat(mechanics): Add 'planet stopovers' substitution for shorter list
  source/Mission.cpp
Labels: enhancement

#8481 Fix blurry thumbnail on outfitter selection panel
  source/OutfitterPanel.cpp
Labels: bug

#8501 feat(balance): Adding a fuel pod to afterburner Raven
  data/human/variants.txt
Labels: balance

#8514 Run CI workflow when CMake files have been edited
  .github/workflows/ci.yml
Labels: cd/ci/testing

#8274 [Content] More Landable Gas Giants
  data/map planets.txt
  data/map systems.txt
Labels: content

#8452 feat(content): More Gegno Landables
  copyright
  data/hazards.txt
  data/map planets.txt
  data/map systems.txt
  images/planet/asura.png
  images/planet/gas7-r.png
  images/planet/vajra/vajra-00.png
  images/planet/vajra/vajra-01.png
  images/planet/vajra/vajra-02.png
  images/planet/vajra/vajra-03.png
  images/planet/vajra/vajra-04.png
  images/planet/vajra/vajra-05.png
  images/planet/vajra/vajra-06.png
  images/planet/vajra/vajra-07.png
  images/planet/vajra/vajra-08.png
  images/planet/vajra/vajra-09.png
  images/planet/vajra/vajra-10.png
  images/planet/vajra/vajra-11.png
  images/planet/vajra/vajra-12.png
  images/planet/vajra/vajra-13.png
  images/planet/vajra/vajra-14.png
  images/planet/vajra/vajra-15.png
  images/planet/vajra/vajra-16.png
  images/planet/vajra/vajra-17.png
  images/planet/vajra/vajra-18.png
  images/planet/vajra/vajra-19.png
  images/planet/vajra/vajra-20.png
  images/planet/vajra/vajra-21.png
  images/planet/vajra/vajra-22.png
  images/planet/vajra/vajra-23.png
  images/planet/vajra/vajra-24.png
  images/planet/vajra/vajra-25.png
  images/planet/vajra/vajra-26.png
  images/planet/vajra/vajra-27.png
  images/planet/vajra/vajra-28.png
  images/planet/vajra/vajra-29.png
  images/planet/vajra/vajra-30.png
  images/planet/vajra/vajra-31.png
  images/planet/vajra/vajra-32.png
  images/planet/vajra/vajra-33.png
  images/planet/vajra/vajra-34.png
  images/planet/vajra/vajra-35.png
  images/planet/vajra/vajra-36.png
  images/planet/vajra/vajra-37.png
  images/planet/vajra/vajra-38.png
  images/planet/vajra/vajra-39.png
  images/planet/vajra/vajra-40.png
  images/planet/vajra/vajra-41.png
  images/planet/vajra/vajra-42.png
  images/planet/vajra/vajra-43.png
  images/planet/vajra/vajra-44.png
  images/planet/vajra/vajra-45.png
  images/planet/vajra/vajra-46.png
  images/planet/vajra/vajra-47.png
  images/planet/vajra/vajra-48.png
  images/planet/vajra/vajra-49.png
  images/planet/yniu eiu.png
  images/planet/yniu ena.png
Labels: content, artwork

#8511 Add a missing #include, caught by gcc 13
  source/Preferences.h
Labels: bug

#8513 Don't create the unnecessary static library for faster builds
  CMakeLists.txt
  source/CMakeLists.txt
  tests/CMakeLists.txt
Labels: cd/ci/testing

#8524 Fix spelling mistakes
  .codespell.exclude
  data/coalition/coalition missions.txt
  data/gegno/gegno intro missions.txt
  data/human/hails.txt
  data/human/news.txt
  data/iije/iije.txt
Labels: typo

#8486 feat(enhancement): Make inscrutable on player ships useful
  source/Politics.cpp
  source/Ship.cpp
Labels: mechanics

#8518 Adjust Active Cooling Mechanic
  source/Ship.cpp
Labels: mechanics

#8522 Improve shattered light 2 blocking
  data/remnant/remnant 2 side missions.txt
Labels: content

#8526 Fix MacOS compilation error in CI
  CMakeLists.txt
Labels: cd/ci/testing

#8510 Don't treat warnings as errors for release builds
  CMakePresets.json
  source/CMakeLists.txt
Labels: cd/ci/testing

#7805 feat(content): Expanding the description of Han Sizer jobs
  data/human/rim jobs.txt
Labels: content, waiting on reviewer, text - short

#7854 feat(content): add jobs relating to the atomic bombing of Martini
  data/human/events.txt
  data/human/paradise world jobs.txt
Labels: content, text - long

#8483 fix(typo): Skadenga Saga tweaks, Bulk Freighter capitalization, and various typos fixes
  data/human/deep missions.txt
  data/human/free worlds 1 start.txt
  data/human/free worlds side plots.txt
  data/human/human missions.txt
  data/human/news.txt
  data/human/ships.txt
  data/map planets.txt
  data/remnant/remnant 2 cognizance.txt
Labels: typo

#8503 bug fix: three dialogs had `accept` in their text
  data/remnant/remnant 2 cognizance.txt
Labels: bug

#8545 fix(typo): Remove duplicate backtick in a tooltip definition
  data/tooltips.txt
Labels: typo

#8359 phrases in mission description, display name, illegal, cargo, blocked, clearance, and dialog text
  source/Mission.cpp
  source/MissionAction.cpp
  source/NPC.cpp
Labels: enhancement

#8535 Add content box to bank/planet/spaceport/trading panels
  data/interfaces.txt
  source/BankPanel.cpp
  source/PlanetPanel.cpp
  source/SpaceportPanel.cpp
  source/SpaceportPanel.h
  source/TradingPanel.cpp
Labels: enhancement, UI

#7660 Use conditional conversation nodes to simplify some conversation
  data/human/deep missions.txt
  data/kahet/kahet missions.txt
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 side missions.txt
  data/sheragi/archaeology missions.txt
Labels: content

#8525 Give the wanderers non-default crew attack and defence stats
  data/governments.txt
Labels: balance

#8322 feat(enhancement): Shield permeability
  data/tooltips.txt
  source/DamageProfile.cpp
  source/OutfitInfoDisplay.cpp
Labels: enhancement

#6934 Click mission cycle waypoints
  source/MissionPanel.cpp
  source/MissionPanel.h
Labels: mechanics, waiting on reviewer

#6803 Optimize and provide more granularity to inaccuracy
  EndlessSkyLib.cbp
  source/CMakeLists.txt
  source/Distribution.cpp
  source/Distribution.h
  source/Hardpoint.cpp
  source/Projectile.cpp
  source/Projectile.h
  source/Random.cpp
  source/Random.h
  source/Weapon.cpp
  source/Weapon.h
Labels: mechanics

#7103 refactor(mechanics): Automatic minable mapping with asteroid scanners
  source/Engine.cpp
  source/Engine.h
Labels: mechanics, waiting on reviewer

#7688 [Content] Quarg Acknowledges Player Flying An Arfecta And Warns Them
  data/quarg/quarg missions.txt
Labels: content, text - short

#7137 feat(mechanics): Support for reputation limits on governments
  source/Government.cpp
  source/Government.h
  source/Politics.cpp
Labels: enhancement

#8550 New landscape photo by 1184
  copyright
  data/map planets.txt
  images/land/hills11.jpg
Labels: artwork

#7708 feat(ui): Capability for adding to credits in plugins
  source/MenuPanel.cpp
  source/MenuPanel.h
Labels: enhancement

#7913 Change disruption dynamic to not be stuuuuuupid
  data/tooltips.txt
  source/DamageProfile.cpp
Labels: balance, mechanics

#8471 Update jobs.txt at line 2304 to include "And Their Luggage"
  data/human/jobs.txt
Labels: content, text - short

#7326 feat(mechanics): NPCs can have actions for various ShipEvents
  source/Mission.cpp
  source/NPC.cpp
  source/NPC.h
Labels: enhancement

#8350 feat(content): Quicksilver package mixup
  data/human/human missions.txt
Labels: content, waiting on reviewer, text - short

#8563 Support removal of galaxy sprites
  source/Galaxy.cpp
Labels: enhancement

#8552 Some README improvements
  README.md
Labels: documentation

#8426 Fix one problem with scanning
  source/AI.cpp
  source/AI.h
  source/Ship.cpp
Labels: bug

#8566 Clean up Ringworld Debris Quarg
  data/kahet/kahet missions.txt
Labels: refactor

#8561 feat(content): Split the Quarg Government
  data/governments.txt
  data/map planets.txt
  data/map systems.txt
  data/quarg/quarg missions.txt
  data/quarg/quarg.txt
  data/wanderer/wanderers middle.txt
  data/wanderer/wanderers.txt
Labels: content

#8576 Fix total interest
  data/start.txt
Labels: content

#8568 Add a message when a ship is destroyed.
  source/Preferences.cpp
  source/PreferencesPanel.cpp
  source/Ship.cpp
Labels: enhancement

#6952 Refactor shop error code
  source/OutfitterPanel.cpp
  source/OutfitterPanel.h
  source/ShipyardPanel.cpp
  source/ShipyardPanel.h
  source/ShopPanel.cpp
  source/ShopPanel.h
Labels: refactor, waiting on reviewer

#8544 Tweaks to paradise jobs on pirate worlds
  data/human/paradise world jobs.txt
Labels: content

#8114 Fix(content): Restricting "Local Politics" mission from triggering on Albatross and Bloodsea after joining the FW.
  data/human/culture conversations.txt
  data/human/events.txt
Labels: bug, content

#8582 fix(content): Use new status change triggers in Deep Archaeology
  data/sheragi/archaeology missions.txt
Labels: content

#8444 Fix untranslated hails again
  data/governments.txt
  source/Government.cpp
  source/Government.h
  source/Ship.cpp
Labels: bug

#8405 Remove Zenith required reputation when not bombing
  data/wanderer/wanderers middle.txt
Labels: bug

#8536 fix(typo): Fix capitalization of jump drive
  data/coalition/coalition jobs.txt
  data/coalition/coalition missions.txt
Labels: text - short

#8225 Make farming jump water bugs have consequences
  data/governments.txt
  data/wanderer/wanderers start.txt
Labels: balance

#8474 Catalogue "Notable Stars"
  data/map systems.txt
Labels: content

#6953 List required license alongside the cost.
  source/MapShipyardPanel.cpp
  source/OutfitInfoDisplay.cpp
  source/OutfitInfoDisplay.h
  source/OutfitterPanel.cpp
  source/ShipInfoDisplay.cpp
  source/ShipInfoDisplay.h
  source/ShipInfoPanel.cpp
  source/ShipyardPanel.cpp
Labels: mechanics, waiting on reviewer

#8605 Fix LoadPanel double clicking
  source/LoadPanel.cpp
Labels: bug

#8583 use 64 bits instead of 32 to store commands (alternative to #8507)
  source/Command.cpp
  source/Command.h
Labels: refactor

#8519 Bugfix: Do not rely on preference for mouse hold
  source/AI.cpp
  source/Engine.cpp
Labels: bug

#8429 feat(UI): Add ship type-specific overlay settings + damaged-only overlay
  data/interfaces.txt
  source/Engine.cpp
  source/Engine.h
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
  source/Ship.cpp
  source/Ship.h
Labels: enhancement, UI

#7113 Allow NPCs to define cargo
  EndlessSkyLib.cbp
  source/CMakeLists.txt
  source/Fleet.cpp
  source/Fleet.h
  source/FleetCargo.cpp
  source/FleetCargo.h
  source/NPC.cpp
  source/NPC.h
Labels: enhancement, refactor

#8180 Switch the Steam Linux build to use the Sniper runtime
  .github/path-filters.yml
  .github/workflows/compute-changes.yml
  .github/workflows/steam.yml
  CMakeLists.txt
  overlays/linux-x64-release-static.cmake
  overlays/linux-x86-release-static.cmake
  steam/docker-compose.yml
  vcpkg.json
Labels: cd/ci/testing
