Repository endless-sky/endless-sky, pull requests merged in 2023-01, with the labels that each got.

#7930 content(balance): Changing the lifespan on Hai Trackers to 475 after confirming that they will still do a second pass at over 5.5k range.
  data/hai/hai outfits.txt
Labels: balance, content

#7838 feat(content): HR: make A11more engaging and align with noted narrative needs
  data/hai/hai reveal 4 middle.txt
  data/hai/hai.txt
Labels: content, text - short

#8004 feat(content): Gegno Intro Tweaks
  data/gegno/gegno intro missions.txt
Labels: content, typo

#8010 fix(content) [Coalition] Prevent Coalition Games jobs from offering with deadlines after July
  data/coalition/coalition jobs.txt
Labels: bug, content

#7812 Feature: Conditional starts
  data/interfaces.txt
  source/StartConditions.cpp
  source/StartConditions.h
  source/StartConditionsPanel.cpp
  source/StartConditionsPanel.h
Labels: enhancement

#6896 Selecting a new system selects the first mission
  source/MissionPanel.cpp
Labels: mechanics

#6933 Zoom to auto-selected mission when you change to mission panel
  source/MissionPanel.cpp
  source/MissionPanel.h
Labels: mechanics, waiting on OP

#8018 Coalition Pilgrimage dialogue: minor grammar fix
  data/coalition/coalition missions.txt
Labels: typo

#8019 Another grammar fix - Yottrite mission
  data/coalition/coalition missions.txt
Labels: typo

#8017 Fix custom penalties again
  source/Government.cpp
Labels: bug

#8034 Fix: Display Info of starts
  source/StartConditionsPanel.cpp
Labels: bug

#8047 fix(typo): Erba Yle plastic price
  data/map.txt
Labels: bug

#8043 Fix missing 'word' in 'friendly navy' phrase.
  data/human/hails.txt
Labels: bug

#8056 Content fix: add automaton and crew equivalent to the Korath Exile drone
  data/korath/korath ships.txt
Labels: bug

#8064 Add Reverse Modules to Kimek Briar
  data/coalition/coalition ships.txt
Labels: content

#7893 build(MacOS): Fully replace Xcode by CMake for MacOS build
  .github/path-filters.yml
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
  CMakeLists.txt
  CMakePresets.json
  EndlessSky.xcodeproj/project.pbxproj
  README.md
  XCode/Images.xcassets/AppIcon.appiconset/Contents.json
  readme-developer.md
  resources/EndlessSky-Info.plist
  source/Audio.cpp
  source/CMakeLists.txt
  source/Sound.cpp
  utils/build_custom_libmad.sh
  utils/cd_update_versions.sh
  utils/check_xcode.sh
  utils/fetch_sdl2_framework.sh
  utils/mad-compat.rb
  utils/set_dylibs_rpath.sh
  utils/set_plist_build.sh
  utils/set_version.sh
Labels: cd/ci/testing

#8040 Docs(manual): Add a reference to the player's manual in the credits.
  credits.txt
Labels: documentation

#7986 Split the map file into multiple files
  data/map planets.txt
  data/map systems.txt
Labels: refactor

#8069 fix(data): Fix stilted dialog/writing in mission "FW Southern Battle 1B"
  data/human/free worlds 2 middle.txt
Labels: content, text - short

#8020 Content(balance, Hai): buff grasshopper
  data/hai/hai fleets.txt
  data/hai/hai ships.txt
Labels: balance

#8032 Brighten some gov colors to improve map readabilty
  data/governments.txt
Labels: artwork

#8061 feat(content): Balance - Quicksilver price decrease & cargo buff
  data/human/ships.txt
Labels: balance

#8078 Specify a toolchain host architecture for the Windows Clang build
  CMakePresets.json
Labels: cd/ci/testing

#8072 feat(artwork): Material and Lighting edit for the Twin Blasters
  images/outfit/twin blaster.png
  images/outfit/twin mod blaster.png
Labels: artwork

#8052 HR: match tenses within sentence for clarity
  data/hai/hai reveal 5 philosophers.txt
Labels: text - short

#8086 Fix vector iterator incompatibility in ShipInfoDisplay
  source/ShipInfoPanel.cpp
Labels: bug

#8084 Test: cleanup: disable the renamed outfitter helps and the ruin landing mission
  tests/integration/config/plugins/integration-tests/data/disabling troublesome missions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_planet_attribute.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_shipyard_outfitter_missions.txt
  tests/integration/config/preferences.txt
Labels: cd/ci/testing

#8051 Feat(UI): show as much as possible of the planets
  data/interfaces.txt
  source/MapDetailPanel.cpp
Labels: enhancement

#7641 Test(integration): ensure proper execution of game start
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
Labels: cd/ci/testing

#6877 feat(UI): Clickable secondary weapon icons in the HUD
  EndlessSkyLib.cbp
  data/interfaces.txt
  source/AI.cpp
  source/AmmoDisplay.cpp
  source/AmmoDisplay.h
  source/CMakeLists.txt
  source/Engine.cpp
  source/Engine.h
  source/MainPanel.cpp
  source/MainPanel.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/Rectangle.cpp
  source/Rectangle.h
Labels: enhancement

#8080 feat(balance): Reduce v0.9.15 afterburner buff by about 50%
  data/human/engines.txt
  data/korath/korath outfits.txt
  data/remnant/remnant outfits.txt
Labels: balance

#8098 Grammar fix - Sheragi Archaeology: The Box 6a
  data/sheragi/archaeology missions.txt
Labels: typo

#8099 Several grammar fixes to Emerald Sword dialogues
  data/sheragi/archaeology missions.txt
Labels: content

#8016 Content: two use cases for custom penalties to fix unwanted behavior
  data/governments.txt
Labels: content

#8062 feat(content): Add the Mammoth (Pirate Behemoth)
  copyright
  data/human/free worlds 0 prologue.txt
  data/human/free worlds 2 middle.txt
  data/human/ships.txt
  images/ship/mammoth.png
  images/thumbnail/mammoth.png
Labels: content, artwork

#8050 Grammar fix - Remnant 1 intro
  data/remnant/remnant 1 introduction.txt
Labels: typo

#8026 Feat(content): Add departure distances to ringworlds
  data/map systems.txt
Labels: content

#7746 Make void sprites drop void sprite parts
  copyright
  data/drak/indigenous.txt
  data/remnant/remnant outfits.txt
  images/effect/void sprite parts/void sprite parts-00.png
  images/effect/void sprite parts/void sprite parts-01.png
  images/effect/void sprite parts/void sprite parts-02.png
  images/effect/void sprite parts/void sprite parts-03.png
  images/effect/void sprite parts/void sprite parts-04.png
  images/effect/void sprite parts/void sprite parts-05.png
  images/effect/void sprite parts/void sprite parts-06.png
  images/effect/void sprite parts/void sprite parts-07.png
  images/effect/void sprite parts/void sprite parts-08.png
  images/effect/void sprite parts/void sprite parts-09.png
  images/effect/void sprite parts/void sprite parts-10.png
  images/effect/void sprite parts/void sprite parts-11.png
  images/effect/void sprite parts/void sprite parts-12.png
  images/effect/void sprite parts/void sprite parts-13.png
  images/effect/void sprite parts/void sprite parts-14.png
  images/effect/void sprite parts/void sprite parts-15.png
  images/effect/void sprite parts/void sprite parts-16.png
  images/effect/void sprite parts/void sprite parts-17.png
  images/effect/void sprite parts/void sprite parts-18.png
  images/effect/void sprite parts/void sprite parts-19.png
  images/outfit/void sprite parts.png
Labels: content, artwork

#8015 Content: Add very weak pirate ship, Scrapper.
  copyright
  data/human/fleets.txt
  data/human/sales.txt
  data/human/ships.txt
  data/human/variants.txt
  images/ship/scrapper.png
  images/thumbnail/scrapper.png
Labels: content, artwork

#8106 content(typo): Change ascent to assent
  data/hai/hai reveal 4 middle.txt
Labels: typo

#8107 HR: Typo remove article with wrong tense
  data/hai/hai reveal 4 middle.txt
Labels: typo

#8109 feat(content) Add Pirate Blackbird (Nighthawk)
  copyright
  data/human/fleets.txt
  data/human/ships.txt
  data/human/variants.txt
  images/ship/pirate nighthawk.png
  images/thumbnail/pirate nighthawk.png
Labels: content, artwork

#8111 Fix spelling and grammar in mission dialogue
  data/hai/hai reveal 4 middle.txt
  data/kahet/kahet missions.txt
Labels: typo

#8110 feat(content): Further adjust Mammoth stats
  data/human/ships.txt
Labels: balance

#8112 Park off-system escorts that fail flight checks + insufficient bunks check
  data/conversations.txt
  data/tooltips.txt
  source/Dialog.h
  source/PlanetPanel.cpp
  source/PlanetPanel.h
  source/PlayerInfo.cpp
  source/Ship.cpp
Labels: bug

#8118 Allow systems to be made inaccessible, preventing them from being seen or traveled to
  source/LocationFilter.cpp
  source/MapDetailPanel.cpp
  source/MapPanel.cpp
  source/Planet.cpp
  source/System.cpp
  source/System.h
Labels: enhancement

#8132 fix(code): Adding the "install" folder to gitignore
  .gitignore
Labels: bug

#8121 Add Pirate Clipper, Cutthroat
  copyright
  data/human/fleets.txt
  data/human/free worlds 2 middle.txt
  data/human/ships.txt
  data/human/variants.txt
  images/ship/pirate cutthroat.png
  images/thumbnail/pirate cutthroat.png
Labels: content, artwork

#8091 Eat any parse errors when discovering integration tests
  tests/integration/IntegrationTests.cmake
Labels: cd/ci/testing

#8129 feat(content): Add the Valkyrie (Pirate Aerie)
  copyright
  data/human/fleets.txt
  data/human/free worlds 2 middle.txt
  data/human/ships.txt
  images/ship/pirate valkyrie.png
  images/thumbnail/pirate valkyrie.png
Labels: content, artwork

#8138 Fix two issues with #8112
  data/conversations.txt
  source/Ship.cpp
Labels: bug

#8135 Add Pirate Bastion, Bulwark
  copyright
  data/human/ships.txt
  data/human/variants.txt
  images/ship/pirate bulwark.png
  images/thumbnail/pirate bulwark.png
Labels: content, artwork

#8139 fix(content): Make Void Sprite Parts non-installable
  data/remnant/remnant outfits.txt
Labels: content

#8140 Valkyrie Description Change
  data/human/ships.txt
Labels: content

#8014 Content(Hai): add optical jammers and put them on recent/military ships
  data/hai/hai fleets.txt
  data/hai/hai outfits.txt
  data/hai/hai ships.txt
  data/hai/hai.txt
Labels: content, text - short

#8022 Improving the wording of human hails
  data/human/hails.txt
Labels: text - short

#8053 Feat: split ion and weapon jamming (scrambling)
  data/coalition/coalition ships.txt
  data/coalition/coalition weapons.txt
  data/drak/drak outfits.txt
  data/drak/drak ships.txt
  data/drak/indigenous.txt
  data/effects.txt
  data/hai/hai outfits.txt
  data/hazards.txt
  data/iije/iije.txt
  data/kahet/kahet outfits.txt
  data/persons.txt
  data/quarg/quarg outfits.txt
  data/remnant/remnant outfits.txt
  data/remnant/remnant ships.txt
  data/rulei/rulei ships.txt
  data/sheragi/sheragi outfits.txt
  data/tooltips.txt
  source/DamageDealt.h
  source/DamageProfile.cpp
  source/Outfit.cpp
  source/OutfitInfoDisplay.cpp
  source/PrintData.cpp
  source/Ship.cpp
  source/Ship.h
  source/Weapon.cpp
  source/Weapon.h
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_wormhole_navigation.txt
Labels: enhancement

#8141 Fix nullpointer dereference, you guessed it, with no flagship!
  source/Planet.cpp
Labels: bug

#8146 Fix typo in Deal Change 1
  data/human/human missions.txt
Labels: content, text - short

#8151 feat(content): Name Change Gegno "Protolith" to "Granulite"
  copyright
  data/gegno/gegno fleets.txt
  data/gegno/gegno sales.txt
  data/gegno/gegno ships.txt
  images/ship/gegno granulite.png
  images/thumbnail/gegno granulite.png
Labels: content

#8158 fix(content): Gegno Hunter Fleet Hotfix
  data/gegno/gegno intro missions.txt
Labels: bug, content

#8159 feat(content): Nerf rate of Gefu & Grey's person ships
  data/persons.txt
Labels: content

#8148 Update Quarg Atrocity Conversation to account for mid-flight scanning
  data/quarg/quarg.txt
Labels: content, text - short

#8120 Feat(content): Hai keystone differentiation
  data/hai/hai outfits.txt
Labels: bug, content

#8144 Update weapon table header with scrambling damage
  source/PrintData.cpp
Labels: enhancement

#8157 Significant Slash to New Tortuga's Tribute Amount
  data/map planets.txt
Labels: balance

#8154 Content(hazard): Add a weak hazard to neutron stars
  data/hazards.txt
  data/map systems.txt
Labels: content

#8160 Hai: Expanding Business 3: Grammar Edit
  data/hai/hai missions.txt
Labels: typo

#8152 build(cmake): Fix CMake build on path with whitespace
  tests/CMakeLists.txt
  tests/integration/IntegrationTests.cmake
Labels: cd/ci/testing

#7444 Content: 2 new jobs kinds for the Unfettered, mining and medical rush
  data/hai/unfettered jobs.txt
Labels: content, text - short

#8092 Feature: multiple raid fleets with more flexibility, and accounting for local attraction
  source/Engine.cpp
  source/Government.cpp
  source/Government.h
  source/Panel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: enhancement

#8170 fix(typo): Fix typos in data files
  data/gegno/gegno events.txt
  data/gegno/gegno fleets.txt
  data/gegno/gegno intro missions.txt
  data/gegno/gegno outfits.txt
  data/gegno/gegno sales.txt
  data/gegno/gegno ships.txt
  data/hai/hai reveal 4 middle.txt
  data/human/hails.txt
  data/human/human missions.txt
  data/human/variants.txt
  data/map planets.txt
  data/remnant/remnant jobs.txt
  data/rulei/rulei ships.txt
Labels: typo

#7580 Content(mission/job): Unfettered trade 1 Jump Drive for 2 Tripulse Shredders
  data/hai/unfettered 0 prologue.txt
  data/hai/unfettered jobs.txt
Labels: content, text - short

#8094 build(cmake/linux): Use CMake for building on Linux in CI
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  CMakePresets.json
  utils/build_appimage.sh
Labels: cd/ci/testing

#8136 test(integration): Support injection of missions in integration tests
  source/GameData.cpp
  source/GameData.h
  source/TestData.cpp
  source/TestData.h
  source/UniverseObjects.h
  tests/integration/config/plugins/integration-tests/data/tests/tests_framework.txt
Labels: cd/ci/testing

#8096 build(cmake/windows) Use CMake for building on Windows in CI
  .github/path-filters.yml
  .github/sccache/action.yml
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  .github/workflows/compute-changes.yml
  CMakePresets.json
Labels: cd/ci/testing

#7029 New personality, evading scan: secretive
  data/remnant/remnant.txt
  source/AI.cpp
  source/AI.h
  source/Government.cpp
  source/Government.h
  source/Personality.cpp
  source/Personality.h
  source/Ship.cpp
Labels: enhancement, waiting on reviewer

#8174 test(integration): Print relevant conditions on test failure instead of only test conditions
  source/ConditionSet.cpp
  source/ConditionSet.h
  source/Test.cpp
  source/Test.h
Labels: cd/ci/testing

#8153 feat(content): Adjust Firelight description
  data/korath/korath weapons.txt
Labels: content

#8182 Actually build an AppImage
  .github/workflows/cd.yaml
  utils/build_appimage.sh
Labels: cd/ci/testing

#8035 Feat(enhancement): Conditional Starts expansion
  source/CoreStartData.cpp
  source/CoreStartData.h
  source/StartConditions.cpp
  source/StartConditions.h
  source/StartConditionsPanel.cpp
Labels: enhancement

#8186 fix(content): Raven has too many torpedos
  data/human/ships.txt
Labels: bug

#8169 fix(content): Shorten descriptions for brig & luxury jobs
  data/human/jobs.txt
  data/human/syndicate jobs.txt
Labels: content

#8168 fix(typo): Fix hex-based scientific notation
  data/remnant/remnant 2 side missions.txt
Labels: typo

#8179 test(cleanup): Remove obsolete "test:" variables
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_hyperjumps_to_autocondition.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_save_load.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_ship_sale.txt
Labels: cd/ci/testing

#7145 feat: allow for varying ship landing speeds
  data/tooltips.txt
  source/Ship.cpp
Labels: enhancement

#8191 bugfix: secretive personality does not ignore fence and properly runs away
  source/AI.cpp
Labels: bug

#8046 Feat: allow customizing ramscoop per system and turn universal back on by default
  source/Ship.cpp
  source/System.cpp
  source/System.h
Labels: enhancement

#8195 fix(content & code): Bug in Gegno Genocide Defense & various code spelling mistakes.
  CMakeLists.txt
  data/gegno/gegno intro missions.txt
  source/PlayerInfo.cpp
  source/System.cpp
  source/System.h
Labels: bug, typo

#8176 Fix missing reputation changes in Wanderers: Hai Diplomat
  data/wanderer/wanderers start.txt
Labels: bug

#8183 Integration test adjustments
  tests/integration/config/plugins/integration-tests/data/tests/tests_afterburn_flight.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_disown.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_model_condition.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_planet_attribute.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_framework.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_hyperjumps_to_autocondition.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_save_load.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_ship_sale.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_shipyard_outfitter_missions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_store_outfits_on_take_off.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_to_accept.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_wormhole_navigation.txt
Labels: cd/ci/testing, refactor

#8193 (Content): Hai Sea Scorpion and Cicada Adjustments
  data/hai/hai fleets.txt
  data/hai/hai ships.txt
Labels: balance, content

#8167 Fix unparking
  source/PlayerInfoPanel.cpp
  source/ShipInfoPanel.cpp
Labels: bug

#8117 Split heroic personality into daring and hunting
  source/AI.cpp
  source/Engine.cpp
  source/Personality.cpp
  source/Personality.h
Labels: enhancement

#8038 bug fix to allow random interval untranslated hails
  source/Engine.cpp
Labels: mechanics

#8164 Minable display names and nouns
  source/Engine.cpp
  source/Minable.cpp
  source/Minable.h
  source/UniverseObjects.cpp
Labels: enhancement

#8204 Fix Government penalty loading
  source/Government.cpp
Labels: bug

#7934 [Enhancement] Custom Wormhole Link Colors
  data/interfaces.txt
  source/Color.cpp
  source/Color.h
  source/MapPanel.cpp
  source/PlanetLabel.cpp
  source/Wormhole.cpp
  source/Wormhole.h
Labels: enhancement

#8175 Suppress package usage information
  CMakeLists.txt
Labels: cd/ci/testing

#8166 phrases in conversations
  source/Conversation.cpp
  source/Phrase.cpp
  source/Phrase.h
Labels: enhancement

#8208 Fix wormhole link drawing for wormholes connecting more than two systems
  source/MapPanel.cpp
Labels: bug

#8198 refactor/bugfix: move CanSendHail to ship
  source/Engine.cpp
  source/Ship.cpp
  source/Ship.h
Labels: bug, refactor

#7552 Mechanics/Bugfix: better AI distancing when using artillery or explosives at short range
  EndlessSkyLib.cbp
  source/AI.cpp
  source/AI.h
  source/CMakeLists.txt
  source/Engine.cpp
  source/Personality.cpp
  source/Personality.h
  source/PlayerInfo.cpp
  source/Ship.cpp
  source/Ship.h
  source/ShipJumpNavigation.cpp
  source/ShipJumpNavigation.h
  source/Weapon.cpp
  source/Weapon.h
  source/ship/ShipAICache.cpp
  source/ship/ShipAICache.h
Labels: enhancement, mechanics

#7767 Enhancement: make boarding missions able to temporarily capture uncapturable
  source/BoardingPanel.cpp
  source/BoardingPanel.h
  source/ConversationPanel.cpp
  source/Mission.cpp
  source/Mission.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  tests/CMakeLists.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt
Labels: enhancement

#8224 Fix jump navigation and weapon data caching issues
  source/AI.cpp
  source/PlayerInfo.cpp
  source/Ship.cpp
  source/Ship.h
  source/ShipJumpNavigation.cpp
  source/ShipJumpNavigation.h
  source/ship/ShipAICache.cpp
  source/ship/ShipAICache.h
Labels: bug

#8229 Make `<payment>` work with `"apparent payment"`
  data/human/human missions.txt
  source/Mission.cpp
  source/MissionAction.cpp
Labels: enhancement

#8234 Mute audio for testing
  endless-sky.6
  source/main.cpp
Labels: cd/ci/testing

#8237 Integration test: cleanup capture-override
  tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt
Labels: cd/ci/testing

#8210 [Enhancement] Give Unstable Wormholes Red Links
  data/map planets.txt
Labels: artwork

#8233 Fix typo
  data/coalition/coalition missions.txt
  data/sheragi/archaeology missions.txt
Labels: typo

#8165 Fix Deep: TMBR 0 persisting after TMBR 1 is offered
  data/human/deep missions.txt
Labels: content

#7876 Properly Deal with Scan Speed
  data/coalition/coalition outfits.txt
  data/drak/indigenous.txt
  data/gegno/gegno ships.txt
  data/hai/hai outfits.txt
  data/hai/hai ships.txt
  data/human/outfits.txt
  data/korath/korath ships.txt
  data/persons.txt
  data/remnant/remnant outfits.txt
  data/remnant/remnant ships.txt
  data/tooltips.txt
  source/Outfit.cpp
  source/Ship.cpp
  tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
Labels: mechanics

#7176 Add <npcmodel> replacement variable for missions
  data/remnant/remnant jobs.txt
  data/wanderer/wanderers start.txt
  source/NPC.cpp
Labels: enhancement, waiting on reviewer

#8189 test(content-style): Expanded CI data file check
  .github/workflows/ci.yml
  utils/check_content_style.py
  utils/contentStyle.json
Labels: cd/ci/testing

#8028 Separate trade commodity profit and price level into two columns
  source/TradingPanel.cpp
Labels: enhancement

#6963 Outfit details handles negative values as "needed" better
  data/tooltips.txt
  source/OutfitInfoDisplay.cpp
  source/OutfitInfoDisplay.h
Labels: mechanics, waiting on reviewer

#7995 feat(content) Rulei Contact Conversation
  copyright
  data/governments.txt
  data/map planets.txt
  data/map systems.txt
  data/rulei/rulei missions.txt
  data/rulei/rulei ships.txt
  data/rulei/rulei.txt
  images/scene/rulei flash.png
Labels: content, artwork

#7560 feat(mechanics): Returns auto aim only when firing as an option
  source/AI.cpp
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
Labels: mechanics

#8253 fix(typo): Fix capitalization of Syndicate in HR
  data/hai/hai reveal 5 philosophers.txt
Labels: typo

#8081 Feat(code): Additional Zoom Levels & Zoom smoothing
  source/Engine.cpp
  source/Preferences.cpp
Labels: mechanics, waiting on reviewer
