Repository endless-sky/endless-sky, pull requests merged in 2023-02, with the labels that each got.

#7591 Update Remnant Cognizance 28
  data/remnant/remnant 2 cognizance.txt
Labels: bug, content, text - short

#8201 Feat(content): Ember Waste Ramscoop Changes
  data/map systems.txt
  data/remnant/remnant outfits.txt
  data/remnant/remnant ships.txt
Labels: content

#8251 content: Narriative change when first offered the Emerald Sword
  data/sheragi/archaeology missions.txt
Labels: content

#8263 List outfit cost and requirements above attributes and weapon data
  source/OutfitterPanel.cpp
Labels: enhancement

#8262 [Content] Unfettered Shipyard and Outfitter Updates
  data/hai/hai fleets.txt
  data/hai/hai ships.txt
  data/hai/hai.txt
Labels: balance, content

#8241 Miscellaneous CI cleanup and fixes.
  .github/path-filters.yml
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
  vcpkg-configuration.json
Labels: cd/ci/testing

#6936 Added option for firing and rotating the ship with mouse
  keys.txt
  source/AI.cpp
  source/AI.h
  source/Command.cpp
  source/Command.h
  source/Engine.cpp
  source/Engine.h
  source/PreferencesPanel.cpp
Labels: enhancement, waiting on reviewer

#8245 Allow user to increase previous save count from preferences file
  source/PlayerInfo.cpp
  source/Preferences.cpp
  source/Preferences.h
Labels: enhancement

#8270 Some PrintData refactoring
  source/PrintData.cpp
  source/main.cpp
Labels: refactor

#8215 feat(ui): Hide storage on planets without outfitters
  source/MapOutfitterPanel.cpp
  source/MapPanel.cpp
Labels: enhancement

#8238 feat(docs): Emphasising CMake in Readme
  README.md
Labels: documentation

#8097 Everyone gets their own colour! (All the targets, anyway.)
  data/interfaces.txt
  source/Engine.cpp
  source/Engine.h
  source/MapPlanetCard.cpp
  source/Planet.cpp
  source/Planet.h
Labels: mechanics

#7168 Skip using rendezvousTime with beam weapon turrets
  source/AI.cpp
Labels: mechanics, waiting on reviewer

#8143 Add ambient sounds to more stations
  data/map planets.txt
Labels: content, sound

#7933 feat(sounds): Bay Launch Sounds
  copyright
  data/coalition/coalition ships.txt
  data/effects.txt
  data/gegno/gegno ships.txt
  data/hai/hai ships.txt
  data/human/kestrel.txt
  data/human/ships.txt
  data/korath/korath ships.txt
  data/korath/korath variants.txt
  data/persons.txt
  data/remnant/remnant ships.txt
  data/sheragi/sheragi ships.txt
  sounds/coalition launch.wav
  sounds/ember tear hit0~.wav
  sounds/hai launch.wav
  sounds/human launch external.wav
  sounds/human launch.wav
  sounds/korath launch external.wav
  sounds/korath launch.wav
  sounds/remnant launch external.wav
  sounds/remnant launch.wav
  sounds/scin launch.wav
  sounds/sheragi launch.wav
Labels: sound

#8285 fix(typo): Correct auto-pilot to autopilot
  data/help.txt
  data/remnant/remnant 1 introduction.txt
  source/AI.cpp
Labels: typo

#8147 feat(content): Gegno Content Enhancements
  copyright
  data/gegno/gegno fleets.txt
  data/gegno/gegno intro missions.txt
  data/gegno/gegno outfits.txt
  data/gegno/gegno sales.txt
  data/gegno/gegno ships.txt
  data/map planets.txt
  data/map systems.txt
  images/outfit/irate carronade.png
  images/outfit/plasma grenades.png
  images/outfit/plasmasickle.png
  images/outfit/savagery pike.png
Labels: content, artwork, waiting on reviewer

#8209 Change landing messages for uninhabited worlds
  source/System.cpp
Labels: content

#8142 feat(content): Adds more attributes to human planets & new Forest attribute jobs
  data/human/jobs.txt
  data/map planets.txt
Labels: content

#8281 Revert "feat(UI): Additional zoom levels (#8081)"
  source/Engine.cpp
  source/Preferences.cpp
Labels: mechanics

#8289 Small CMake tweaks
  CMakeLists.txt
  readme-cmake.md
Labels: cd/ci/testing

#8302 Some small fixes to the CI
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
Labels: cd/ci/testing

#8301 New ES release process that simplifies the existing one
  .github/workflows/cd_release.yaml
Labels: cd/ci/testing

#8284 Catalytic ramscoop for jump Cruiser
  data/human/variants.txt
Labels: balance

#8291 Fix selected choice text added to conversation when some choice nodes are conditionally hidden
  source/ConversationPanel.cpp
Labels: bug

#8278 fix(typo): Fix capitalization of outfit names (stage 1)
  data/gegno/gegno ships.txt
  data/human/weapons.txt
  data/korath/korath ships.txt
  data/quarg/quarg outfits.txt
  data/remnant/remnant outfits.txt
Labels: typo

#8305 bugfix: Fix fighters choosing boarding targets
  source/AI.cpp
Labels: bug

#5717 Player name entry improvements
  data/interfaces.txt
  source/ConversationPanel.cpp
  source/ConversationPanel.h
Labels: enhancement

#8300 Hai Reveal: bug fix: remove unneeded clean-up mission and event
  data/hai/hai reveal 6 end.txt
Labels: refactor

#8280 Hai Reveal: bug fix: do not provide ongoing election updates after the election has ended
  data/hai/hai reveal 4 middle.txt
Labels: bug

#8306 Hai Reveal: bug fix: each HR5 path blocks the other from starting
  data/hai/hai reveal 5 philosophers.txt
Labels: bug

#8318 feat(balance): Nerf the value detector
  data/hai/hai outfits.txt
  data/hai/hai ships.txt
Labels: balance

#8269 fix(content): Purging two swears from Remnant related content
  data/remnant/remnant 1 introduction.txt
Labels: content, text - short

#8328 Fix typo in Quarg Satellites mission
  data/quarg/quarg missions.txt
Labels: content, text - short

#8310 feat(UI): Add support for hold to mouse turn
  keys.txt
  source/Command.cpp
  source/Command.h
  source/Engine.cpp
  source/Engine.h
  source/PreferencesPanel.cpp
Labels: enhancement

#8307 Feat(enhancement): Preference to hide asteroid target overlay with asteroid scanning
  source/Engine.cpp
  source/Preferences.cpp
  source/PreferencesPanel.cpp
Labels: enhancement

#8333 fix(content): Typo in data/gegno outfits
  data/gegno/gegno outfits.txt
Labels: typo

#8327 Modify wording in Hai Rescue: Gipeep
  data/hai/hai reveal 2 start.txt
Labels: content, text - short, typo

#7751 Use a PlayerInfo transaction to prevent saving state from mid-conversation
  source/ConversationPanel.cpp
  source/ConversationPanel.h
  source/DataWriter.cpp
  source/DataWriter.h
  source/MissionAction.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  tests/integration/config/plugins/integration-tests/data/disabling troublesome missions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_save_load.txt
Labels: bug

#8296 Feat(enhacement): Check if a ship has the means to run from its target.
  source/AI.cpp
Labels: enhancement

#8341 Default to "fast" parallax
  source/Preferences.cpp
Labels: enhancement

#8304 Bugfix: Do not overthrust when ship is pointing at mouse
  source/AI.cpp
  source/AI.h
Labels: bug

#8243 fix(content): Minor HR fixes and player experience edits
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 3 early.txt
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal 6 end.txt
  data/whispering void/elenchus.txt
Labels: content, text - short

#8346 bugfix: Fix ships attempting to re-board boarded targets (#8228)
  source/AI.cpp
Labels: bug

#8347 fix(content): Adjust Dangerous Games riddle display
  data/human/human missions.txt
Labels: bug, content, text - short

#8342 fix(content): Let "Hai Wormhole Warning" offer correctly
  data/human/human missions.txt
Labels: bug

#8323 bug fix: ships scanning will try to stay near their target instead of moving erratically
  source/AI.cpp
Labels: mechanics

#8335 Fix typos in Hai Rescue: Ooonem
  data/hai/hai reveal 2 start.txt
Labels: content, text - short, typo

#8343 Bugfix: Reduce overthrusting when landing or boarding
  source/AI.cpp
Labels: bug

#8329 feat(content): HR player experience updates 3
  data/hai/hai reveal 3 early.txt
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 6 end.txt
Labels: content, text - short

#8345 Fix(content): Sort out the lead from Alondo sequence (address 8259)
  data/hai/hai reveal 4 middle.txt
Labels: bug, content, text - short

#8369 fix(content): Shorten Paradise Job: Debtors description to fit
  data/human/paradise world jobs.txt
Labels: bug

#8367 Change the stock Manta's weapons so that they're symmetrical
  data/human/ships.txt
Labels: balance

#8352 fix(typo): Fix the usage of `off-world`.
  data/human/free worlds 1 start.txt
  data/map planets.txt
Labels: typo

#8320 Fix uninstalling a Command Center
  source/Outfit.cpp
Labels: bug

#8373 feat(enhancement): Proper formatting for mass
  source/Engine.cpp
  source/MainPanel.cpp
  source/MapOutfitterPanel.cpp
  source/Mission.cpp
  source/MissionPanel.cpp
  source/OutfitterPanel.cpp
  source/PlanetPanel.cpp
  source/PlayerInfo.cpp
  source/TradingPanel.cpp
  source/text/Format.cpp
  source/text/Format.h
  tests/unit/src/text/test_format.cpp
Labels: mechanics

#8368 Fix thrust becoming unbounded
  source/Ship.cpp
Labels: bug

#8330 fix(bug): HR Bugfixes 3
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 5 philosophers.txt
Labels: bug

#8377 Allow mission clearance to bypass language barriers
  source/HailPanel.cpp
Labels: bug

#8378 fix(typo): Correct automatic aiming preference typo
  source/PreferencesPanel.cpp
Labels: typo

#8381 fix(typo): Fix typo in quarg news
  data/quarg/quarg news.txt
Labels: typo

#8380 Don't display "Plant2" and "Large Plant2" when targeting those minables
  data/harvesting.txt
Labels: content

#8356 fix(typo): Fix capitalization of outfit names (stage 3) - Engines
  data/coalition/coalition outfits.txt
  data/gegno/gegno outfits.txt
  data/hai/hai outfits.txt
  data/human/engines.txt
  data/human/hails.txt
  data/remnant/remnant outfits.txt
Labels: typo

#8355 fix(typo): Fix capitalization of outfit names (stage 2)
  data/coalition/coalition missions.txt
  data/coalition/coalition outfits.txt
  data/hai/hai outfits.txt
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal news.txt
  data/hai/hai ships.txt
  data/harvesting.txt
  data/human/deep missions.txt
  data/human/free worlds 0 prologue.txt
  data/human/free worlds 1 start.txt
  data/human/free worlds 2 middle.txt
  data/human/free worlds 4 epilogue.txt
  data/human/free worlds side plots.txt
  data/human/hails.txt
  data/human/news.txt
  data/human/power.txt
  data/human/ships.txt
  data/human/weapons.txt
  data/korath/korath outfits.txt
  data/persons.txt
  data/remnant/remnant 1 introduction.txt
  data/sheragi/sheragi outfits.txt
  data/wanderer/wanderers middle.txt
Labels: typo

#8357 fix(typo): Fix capitalization of outfit names (stage 4) - Missiles
  data/coalition/coalition weapons.txt
  data/deprecated outfits.txt
  data/hai/hai outfits.txt
  data/human/hails.txt
  data/human/weapons.txt
  data/intro missions.txt
  data/kahet/kahet missions.txt
  data/korath/korath weapons.txt
  data/remnant/remnant 2 side missions.txt
  data/remnant/remnant outfits.txt
  data/sheragi/sheragi outfits.txt
  data/wanderer/wanderer outfits.txt
Labels: typo

#8358 fix(typo): Fix capitalization of outfit names (stage 7) - H2H and the most controversial outfits
  data/hai/hai reveal 4 middle.txt
  data/hai/hai ships.txt
  data/human/free worlds 1 start.txt
  data/human/free worlds side plots.txt
  data/human/hails.txt
  data/human/human missions.txt
  data/human/outfits.txt
  data/human/ships.txt
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant 2 side missions.txt
  data/remnant/remnant events.txt
  data/remnant/remnant jobs.txt
  data/remnant/remnant outfits.txt
  data/wanderer/wanderers start.txt
Labels: typo

#8384 feat(content): Changing Ibis license requirement Capital to Remnant
  data/remnant/remnant ships.txt
Labels: balance, content

#8386 Fix missing 'gegno quarg' attribute for 'Giaru Gegno'
  data/map planets.txt
Labels: content

#8389 fix(content): Replace Deprecated Stars
  data/map systems.txt
Labels: content

#8382 bugfix: Fix hails for disabled hostile ships when the player requires assitance
  source/HailPanel.cpp
Labels: bug

#8181 Content: Allow Jump Drives to be sold to the Heliarchs
  data/coalition/coalition jobs.txt
  data/coalition/coalition missions.txt
Labels: content, text - short

#8394 [CI] Fix MacOS pkg-config error
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
Labels: cd/ci/testing

#7740 Gamerules minimum viable product
  EndlessSkyLib.cbp
  data/gamerules.txt
  data/human/outfits.txt
  source/CMakeLists.txt
  source/DataNode.cpp
  source/DataNode.h
  source/Engine.cpp
  source/GameData.cpp
  source/GameData.h
  source/Gamerules.cpp
  source/Gamerules.h
  source/Ship.cpp
  source/System.cpp
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  tests/unit/src/test_datanode.cpp
Labels: enhancement

#8383 Add new contributors to the credits
  credits.txt
Labels: documentation

#8393 Adjust "artillery" AI threshold
  source/ship/ShipAICache.cpp
Labels: mechanics

#8402 fix(content): Remove floating pixel for Astral Cetacean
  images/ship/astral cetacean/astral-26.png
Labels: bug, artwork

#8399 feat(content): Acheron Touch-Up
  data/gegno/gegno outfits.txt
  data/map systems.txt
Labels: content

#8396 Lock Hai Reveal from offering for v0.10.0
  data/hai/hai reveal 1 intro.txt
  data/wanderer/wanderers start.txt
Labels: content

#8407 feat(content): Adjust Tanto Engine Hardpoints
  data/bunrodea/bunrodea ships.txt
Labels: content

#8401 Feat(content?): Add brown haze to acheron
  data/map systems.txt
Labels: content

#8408 feat(content): Add Rulei Megastructure
  copyright
  data/hazards.txt
  data/map systems.txt
  images/planet/vajra/vajra-00.png
  images/planet/vajra/vajra-01.png
  images/planet/vajra/vajra-02.png
  images/planet/vajra/vajra-03.png
  images/planet/vajra/vajra-04.png
  images/planet/vajra/vajra-05.png
  images/planet/vajra/vajra-06.png
  images/planet/vajra/vajra-07.png
  images/planet/vajra/vajra-08.png
  images/planet/vajra/vajra-09.png
  images/planet/vajra/vajra-10.png
  images/planet/vajra/vajra-11.png
  images/planet/vajra/vajra-12.png
  images/planet/vajra/vajra-13.png
  images/planet/vajra/vajra-14.png
  images/planet/vajra/vajra-15.png
  images/planet/vajra/vajra-16.png
  images/planet/vajra/vajra-17.png
  images/planet/vajra/vajra-18.png
  images/planet/vajra/vajra-19.png
  images/planet/vajra/vajra-20.png
  images/planet/vajra/vajra-21.png
  images/planet/vajra/vajra-22.png
  images/planet/vajra/vajra-23.png
  images/planet/vajra/vajra-24.png
  images/planet/vajra/vajra-25.png
  images/planet/vajra/vajra-26.png
  images/planet/vajra/vajra-27.png
  images/planet/vajra/vajra-28.png
  images/planet/vajra/vajra-29.png
  images/planet/vajra/vajra-30.png
  images/planet/vajra/vajra-31.png
  images/planet/vajra/vajra-32.png
  images/planet/vajra/vajra-33.png
  images/planet/vajra/vajra-34.png
  images/planet/vajra/vajra-35.png
  images/planet/vajra/vajra-36.png
  images/planet/vajra/vajra-37.png
  images/planet/vajra/vajra-38.png
  images/planet/vajra/vajra-39.png
  images/planet/vajra/vajra-40.png
  images/planet/vajra/vajra-41.png
  images/planet/vajra/vajra-42.png
  images/planet/vajra/vajra-43.png
  images/planet/vajra/vajra-44.png
  images/planet/vajra/vajra-45.png
  images/planet/vajra/vajra-46.png
  images/planet/vajra/vajra-47.png
  images/planet/vajra/vajra-48.png
  images/planet/vajra/vajra-49.png
  sounds/gravity well~.wav
Labels: content, artwork

#8410 feat(content): A Few Edits
  data/gegno/gegno intro missions.txt
  data/map systems.txt
Labels: content

#8134 Update changelog for 0.10.0 (from 0.9.16.1)
  changelog
Labels: documentation

#8406 Make 3 the minimum number of previous saves
  source/Preferences.cpp
Labels: bug, mechanics

#8413 Update man page and appdata.xml file to 0.10.0
  credits.txt
  endless-sky.6
  io.github.endless_sky.endless_sky.appdata.xml
  source/main.cpp
Labels: documentation

#8414 Fix a mistake in the changelog
  changelog
Labels: documentation

#8416 Update version numbers to 0.10.1(-alpha)
  CMakeLists.txt
  credits.txt
  endless-sky.6
  resources/EndlessSky-Info.plist
  source/main.cpp
Labels: documentation

#8387 feat(enhancement): Support for unlimited personalities
  source/Personality.cpp
  source/Personality.h
Labels: enhancement

#7881 fix(documenation): Remove duplicate copyright entries
  copyright
Labels: documentation

#8398 Make Hai Leaks Response 4B invisible and a couple of other things
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 4 middle.txt
Labels: bug

#8337 [Content/Bugfix] "Hai (Unfettered Civilians)" and "Hai (Friendly Unfettered)" Attitudes Fix
  data/governments.txt
  data/hai/hai fleets.txt
Labels: bug, content

#8418 Change Coalition requirement for some missions to License instead of Contributor Mission
  data/coalition/coalition missions.txt
Labels: content

#7192 Feature: Enable and Disable plugins from in-game
  EndlessSkyLib.cbp
  data/interfaces.txt
  source/CMakeLists.txt
  source/GameData.cpp
  source/GameData.h
  source/PlayerInfo.cpp
  source/Plugins.cpp
  source/Plugins.h
  source/PreferencesPanel.cpp
  source/main.cpp
Labels: enhancement, waiting on reviewer

#8433 Remove TODO comments from changelog
  changelog
Labels: documentation

#8432 Fix plural for Solar Batteries
  data/bunrodea/bunrodea outfits.txt
Labels: typo

#8430 fix: use backticks in Basrem Reverse Thrusters description to allow use of quotes
  data/hai/hai outfits.txt
Labels: typo

#8428 feat(balance): Adding a reverse thruster to the Mule's standard loadout
  data/human/ships.txt
Labels: balance

#8435 `language: Hai`: Split Wanderer and Hai languages in game data files
  data/hai/hai culture conversations.txt
  data/hai/hai missions.txt
  data/wanderer/wanderers start.txt
Labels: content

#8442 fix(bug): HR Bugfixes 4
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 6 end.txt
Labels: bug

#8441 feat(content): HR player experience updates 4
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 4 middle.txt
Labels: balance, content, text - short

#8411 Fix uninstallable outfits being sold with minables
  source/TradingPanel.cpp
Labels: mechanics

#8324 bug fix: ships you don't own will sometimes follow cloaked player flagship
  source/AI.cpp
Labels: bug

#8454 Fix(art): Dust haze brightness
  images/_menu/haze-brown+0.jpg
Labels: artwork

#8420 Change Heliarch swizzle to Gold
  data/governments.txt
Labels: artwork

#8455 feat(UI): Implement settings pagination
  source/PreferencesPanel.cpp
Labels: enhancement, UI

#8425 static_assert to ensure PERSONALITY_COUNT matches PersonalityTraits
  source/Personality.cpp
  source/Personality.h
Labels: refactor

#8434 Add the Scrapper to Bounty/Escort Jobs
  data/human/jobs.txt
Labels: content

#8445 Fix weird size for Sheragi Archaeology: The Box 2
  data/sheragi/archaeology missions.txt
Labels: content

#8463 [Content]Repeatable Unfettered Jobs Grant Clearance
  data/hai/unfettered jobs.txt
Labels: content, text - short
