Repository endless-sky/endless-sky, pull requests merged in 2024-10, with the labels that each got.

#10528 fix(typo): Cassandra wording fix
  data/map planets.txt
Labels: typo

#10534 fix(balance): Add required crew to Successor turrets
  data/successors/successor weapons.txt
Labels: balance

#10543 fix(ui): Fix compilation error & visuals for LineShader in GLES
  source/LineShader.cpp
Labels: bug, UI

#10535 fix(content): Successors FC2 Prompt does not offer after FC2
  data/successors/successor 1 prologue.txt
Labels: bug, content

#10537 fix(content): allow players to land to complete Successors: Predecessor Research 1
  data/successors/successor side missions.txt
Labels: bug, content

#10536 fix(typo): Tubfalet description fix
  data/korath/korath ships.txt
Labels: typo

#10533 fix(content): Make `Ringworld Debris: Quarg` not offer on Incipias Quarg planets
  data/kahet/kahet missions.txt
Labels: bug, content

#10532 fix(typo): `descendants` -> `antecedents` in Stone of our Fathers
  data/human/deep missions.txt
Labels: typo

#10530 Fix(content): Add missing government definitions to Incipias systems
  data/map systems.txt
Labels: bug, content

#10527 Correct the error message for incorrect syntax in the children of a text node within a conversation
  source/Conversation.cpp
Labels: bug, waiting on dev

#10549 [Bugfix] Minimum Distance for Successor Rush Delivery Jobs
  data/successors/successor jobs.txt
Labels: bug, content

#10541 fix(content): add `weapon` to Incipias ships
  data/incipias/incipias ships.txt
Labels: bug, content

#10498 feat(artwork): Swarm Missile icon
  copyright
  data/bunrodea/bunrodea weapons.txt
  images/icon/swarm.png
Labels: artwork

#10559 feat(balance): Rebalance certain defense-heavy outfits to account for defense being used more often.
  data/korath/korath outfits.txt
  data/pug/pug outfits.txt
  data/quarg/quarg outfits.txt
Labels: balance

#10551 [Bugfix] Make Successors: Researchers Out 1 and Large Researchers Out 1 Account for Distance
  data/successors/successor jobs.txt
Labels: bug, content

#10485 Add names for Wanderer missions
  data/wanderer/wanderers start.txt
Labels: content, text - short

#10470 Remnant cognizance 1 description and on visit
  data/remnant/remnant 2 cognizance.txt
Labels: bug, content

#10545 fix(ci): Remove unneeded Steam configurations from CI and enable testing for Steam
  .github/path-filters.yml
  .github/workflows/ci.yml
  .github/workflows/compute-changes.yml
  steam/docker-compose.yml
Labels: cd/ci/testing

#10484 "Incipias: Help the Stranded" description
  data/incipias/incipias first contact.txt
Labels: bug, content

#10560 fix(balance): rebalance `Wanderers: Sestor Attack`
  data/wanderer/wanderers middle.txt
Labels: balance

#10247 Fix(content): only give a hyperdrive if there is an installed Jump Drive
  data/hai/unfettered 0 prologue.txt
  data/hai/unfettered jobs.txt
Labels: bug

#10568 fix(content): make Earth Blackout offer on the right day
  data/human/culture conversations.txt
Labels: bug, content

#10569 fix(style): Use camelCase for variables
  source/Date.cpp
Labels: typo

#10472 Don't delete cargo dumped from a carried ship
  source/Flotsam.cpp
  source/Flotsam.h
  source/Ship.cpp
  source/Ship.h
Labels: bug, mechanics

#10572 Two new pull request template categories
  .github/pull_request_template.md
Labels: documentation

#10574 feat(content): Reduce offer rate of Strike Breaker jobs
  data/human/jobs.txt
Labels: content

#10571 fix(typo): surroundings -> surrounding in a Korath mission
  data/korath/korath missions.txt
Labels: typo

#10554 fix(content): "Gegno Intervention" no longer offers if you have done "Gegno Anticipation"
  data/gegno/gegno I corroboration.txt
Labels: bug, content

#10466 Don't send the appeasement message from "mute" ships or when the player doesn't know the language
  source/AI.cpp
Labels: bug, mechanics, waiting on dev

#10606 Prevent Plume from turning into a ghost in Remnant: Cognizance 7
  data/remnant/remnant 2 cognizance.txt
Labels: bug

#10584 feat(content): New Coalition License description
  data/coalition/coalition outfits.txt
Labels: content, text - short

#10590 Typo fixes
  data/coalition/coalition jobs.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai reveal 6 end.txt
  data/human/human missions.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant.txt
  data/sheragi/archaeology missions.txt
Labels: bug

#10602 docs: Add instructions for building without tests
  docs/readme-cmake.md
  docs/readme-developer.md
Labels: documentation

#10621 fix(ci): Add missing setup-python step to the old copyright check
  .github/workflows/projects_check.yml
Labels: cd/ci/testing

#10642 Correct Fertriery spelling
  data/remnant/remnant events.txt
Labels: typo

#10613 fix(ui): Show sold non-installable outfits as "in stock"
  source/OutfitterPanel.cpp
Labels: bug, UI

#10653 Fix Shattered Light duplication
  data/remnant/remnant 2 side missions.txt
Labels: bug, content

#10628 More typo fixes
  changelog
  data/bunrodea/bunrodea missions.txt
  data/hai/hai missions.txt
  data/hai/unfettered 0 prologue.txt
  data/human/free worlds 2 middle.txt
  data/human/human missions.txt
  data/incipias/incipias ships.txt
  data/remnant/remnant jobs.txt
  data/vyrmeid/vyrmeid.txt
Labels: typo

#10652 Remove hold fire and unrefactor orders
  data/_ui/tooltips.txt
  keys.txt
  source/AI.cpp
  source/AI.h
  source/CMakeLists.txt
  source/Command.cpp
  source/Command.h
  source/Orders.cpp
  source/Orders.h
  source/PreferencesPanel.cpp
Labels: bug, mechanics

#10663 (Content Tweak) Increase Frequency of Single Planet Culture Conversations
  data/human/culture conversations.txt
Labels: content

#10542 fix(ui): Make system stored outfit indicator closer to previous visuals
  source/MapPanel.cpp
Labels: bug, UI

#10667 fix(content): restrict Quarg First Contact from offering on non-human/Hai worlds
  data/quarg/quarg missions.txt
Labels: bug

#10630 Khosa-Kella-Oa is at the southern not eastern end
  data/map planets.txt
Labels: typo

#10679 Fix png iccp srgb profiles
  images/land/igna.png
  images/land/methuselah.png
  images/land/treser.png
  images/land/vulpa.png
Labels: bug, artwork

#10624 fix(content): Add landing message to novas
  data/_ui/landing messages.txt
Labels: bug, content

#10689 Replace deprecated "Korath Piercers" with "Piercer Missiles" in some variants
  data/korath/korath variants.txt
Labels: content

#10648 Silent scans and jumps
  data/_ui/tooltips.txt
  source/Engine.cpp
  source/Ship.cpp
Labels: enhancement, sound

#10691 fix(content): Use the new silent jumps attribute
  data/drak/drak ships.txt
Labels: bug, content, sound

#10651 Update changelog
  changelog
  credits.txt
  endless-sky.6
  io.github.endless_sky.endless_sky.appdata.xml
  source/main.cpp
Labels: documentation

#10695 0.10.11 alpha version numbers
  CMakeLists.txt
  credits.txt
  endless-sky.6
  resources/EndlessSky-Info.plist
  source/main.cpp
Labels: documentation

#7721 Content: New Hai advanced start
  copyright
  data/globals.txt
  data/hai/hai missions.txt
  data/human/deep missions.txt
  data/human/free worlds 0 prologue.txt
  data/human/free worlds 4 epilogue.txt
  data/human/human missions.txt
  data/human/intro missions.txt
  data/map planets.txt
  data/quarg/quarg missions.txt
  data/remnant/remnant 1 introduction.txt
  data/start.txt
  data/starts.txt
  images/scene/hai bank.jpg
  images/scene/hai shipyard.jpg
  images/scene/hai start.jpg
Labels: content, text - short, to be merged

#9562 Hai scan opacity and holographic amenity outfits
  copyright
  data/hai/hai fleets.txt
  data/hai/hai outfits.txt
  data/hai/hai ships.txt
  data/hai/hai.txt
  data/map planets.txt
  images/outfit/holovid zone.png
  images/outfit/phantom pallet.png
Labels: content, artwork, text - short, to be merged

#10501 feat(content): New culture conversation for Solace
  data/human/culture conversations.txt
Labels: content, text - short, to be merged

#10670 feat(content): New Finisher Torpedo description
  data/coalition/coalition weapons.txt
Labels: content, text - short, to be merged

#10374 feat(content): Petervdmeer Person Ship
  copyright
  data/persons.txt
  images/ship/hauler vi.png
  images/thumbnail/hauler vi.png
Labels: content, to be merged

#10579 feat(content): Additional spaceport descriptions during Remembrance Day
  data/human/human missions.txt
  data/map planets.txt
Labels: content, text - short, to be merged

#9177 Some changes to how Dusk being busy is handled
  data/remnant/remnant 2 cognizance.txt
Labels: content, to be merged

#8853 A few more things in Cognizance
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 cognizance.txt
Labels: bug, content, text - short, to be merged

#10686 fix(content): Add missing passengers to the Hai Roleplay mission
  data/hai/hai jobs.txt
Labels: content

#10674 fix(mechanics): Outfits stored on take-off no longer count towards excess cargo sold
  source/PlayerInfo.cpp
Labels: bug

#10619 feat(content): mark systems in the Electron Beam mission
  data/human/free worlds 2 middle.txt
Labels: content, to be merged

#9893 Feature: Remove parentheses in price difference column.
  data/_ui/tooltips.txt
  source/MapDetailPanel.cpp
  source/PreferencesPanel.cpp
Labels: UI, to be merged

#10043 feat(balance): Rebalance turret turn rates for consistency, and apply a global nerf
  data/bunrodea/bunrodea weapons.txt
  data/coalition/coalition weapons.txt
  data/gegno/gegno outfits.txt
  data/hai/hai outfits.txt
  data/human/weapons.txt
  data/incipias/incipias outfits.txt
  data/kahet/kahet outfits.txt
  data/korath/korath weapons.txt
  data/pug/pug outfits.txt
  data/quarg/quarg outfits.txt
  data/remnant/remnant outfits.txt
  data/sheragi/sheragi outfits.txt
  data/successors/successor weapons.txt
  data/wanderer/wanderer outfits.txt
Labels: balance, to be merged

#10690 feat(mechanics): Fall back to the vanilla starting location when a custom one is invalid
  source/CoreStartData.cpp
Labels: mechanics

#6940 Re-work DistanceMap to be consistent
  source/AI.cpp
  source/CMakeLists.txt
  source/DistanceMap.cpp
  source/DistanceMap.h
  source/LocationFilter.cpp
  source/MapPanel.cpp
  source/Mission.cpp
  source/MissionPanel.cpp
  source/PlayerInfo.cpp
  source/RouteEdge.cpp
  source/RouteEdge.h
  source/RoutePlan.cpp
  source/RoutePlan.h
Labels: bug, refactor, waiting on reviewer

#10692 Correct a comment
  source/Armament.cpp
  source/Armament.h
Labels: documentation

#10623 fix(mechanics): Stop ships when their velocity is exceedingly low
  source/AI.cpp
Labels: bug, mechanics

#10586 refactor: use constexpr array for formatting credits
  source/text/Format.cpp
Labels: refactor, waiting on dev

#10490 feat(testvars): Remove %-characters in test variable names
  tests/integration/config/plugins/integration-tests/data/tests/tests_capture_override.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_illegal_atrocity.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_shipyard_outfitter_missions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_take_ships.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_to_accept.txt
Labels: cd/ci/testing, waiting on dev

#10610 feat(mechanics): Cloaked shield permeability
  data/_ui/tooltips.txt
  source/DamageProfile.cpp
  source/OutfitInfoDisplay.cpp
Labels: enhancement, mechanics

#10473 Fix large ammo counts overflowing secondary weapon icon
  source/AmmoDisplay.cpp
  source/text/Format.cpp
  source/text/Format.h
  tests/unit/src/text/test_format.cpp
Labels: bug, UI

#10702 fix(bug): Un-halve the number of hostile disabled hails
  data/human/hails.txt
Labels: content

#10650 Refactor status overlay types
  source/Engine.cpp
  source/Engine.h
Labels: refactor

#10704 Fix #10462: Systems with increased "jump range" work
  source/ShipJumpNavigation.cpp
Labels: bug, mechanics

#10710 feat(mechanics): Add a new personality to make ships with full cargo flee
  data/human/fleets.txt
  source/AI.cpp
  source/Personality.cpp
  source/Personality.h
Labels: enhancement, balance, mechanics, waiting on dev

#10718 Update gegno intro missions.txt - minor grammar
  data/gegno/gegno intro missions.txt
Labels: typo

#10715 Fix flagship highlight with scaled ship sprites
  source/Engine.cpp
Labels: bug, waiting on dev

#10581 Minor UI bug fix / improvement to display all reasons preventing Outfitter purchase, not just first one
  source/OutfitterPanel.cpp
Labels: enhancement, UI
