Repository endless-sky/endless-sky, pull requests merged in 2024-08, with the labels that each got.

#10347 feat(content): Gegno: Zydee event, Jyelio planet, and various tweaks
  data/gegno/gegno I corroboration.txt
  data/gegno/gegno events.txt
  data/map planets.txt
  data/map systems.txt
Labels: content, text - short

#10373 code(style): Alphabetize forward class declarations
  source/FillShader.h
  source/Government.h
  source/OutfitInfoDisplay.h
  source/RaidFleet.h
  source/SpaceportPanel.h
  source/test/Test.h
Labels: waiting on dev

#10362 refactor: Use various C++20 features
  source/AI.cpp
  source/ConditionSet.cpp
  source/Conversation.cpp
  source/DistanceMap.cpp
  source/Engine.cpp
  source/EscortDisplay.cpp
  source/Fleet.cpp
  source/GameAction.cpp
  source/GameData.cpp
  source/GameEvent.cpp
  source/Government.cpp
  source/Information.cpp
  source/Interface.cpp
  source/LoadPanel.cpp
  source/LocationFilter.cpp
  source/MapDetailPanel.cpp
  source/MapOutfitterPanel.cpp
  source/MapPanel.cpp
  source/MapSalesPanel.cpp
  source/MapShipyardPanel.cpp
  source/Mission.cpp
  source/OutfitterPanel.cpp
  source/Planet.cpp
  source/PlanetPanel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfoPanel.cpp
  source/Plugins.cpp
  source/Politics.cpp
  source/PrintData.cpp
  source/Set.h
  source/Ship.cpp
  source/ShipJumpNavigation.cpp
  source/ShipyardPanel.cpp
  source/ShopPanel.cpp
  source/System.cpp
  source/TextReplacements.cpp
  source/UniverseObjects.cpp
  source/pi.h
  source/test/Test.cpp
  source/text/FontSet.cpp
  tests/unit/include/es-test.hpp
  tests/unit/src/test_datafile.cpp
Labels: refactor, waiting on dev

#10331 feat(ci): Enable sanitizers for debug builds
  CMakeLists.txt
  tests/CMakeLists.txt
Labels: cd/ci/testing

#10375 Feat(content): Incipias Tractor Beam
  copyright
  data/incipias/incipias outfits.txt
  data/incipias/incipias ships.txt
  data/incipias/incipias.txt
  images/effect/horizon grappler+0.png
  images/effect/horizon grappler+1.png
  images/hardpoint/horizon grappler.png
  images/outfit/horizon grappler.png
Labels: balance, content, artwork

#10377 feat(persons): Add formation patterns for Persons (Person ships)
  source/Person.cpp
  source/Person.h
Labels: enhancement, mechanics, waiting on dev

#10372 feat(mechanics): Submunition spawning attributes
  data/korath/korath weapons.txt
  source/Projectile.cpp
  source/Projectile.h
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement, mechanics, waiting on dev

#10394 Adding existing quality checklist & style goals documents to CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation

#10401 Added hostile disabled pirate hails
  data/human/hails.txt
Labels: content, text - short

#8854 expand `${phrases}` and `<substitutions>` in npc & gift ship names
  source/GameAction.cpp
  source/Mission.cpp
  source/NPC.cpp
  source/NPC.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/ShipManager.cpp
  source/ShipManager.h
Labels: enhancement, waiting on dev

#10414 fix(ci): Add missing exclude to codespell
  .codespell.exclude
Labels: bug, cd/ci/testing

#10389 fix(ui): Fix formatting of large numbers
  source/text/Format.cpp
  tests/unit/src/text/test_format.cpp
Labels: bug, UI, waiting on dev

#10386 fix(ci): Fix release CD
  .github/workflows/cd_release.yaml
  vcpkg.json
Labels: bug, cd/ci/testing, waiting on dev

#10230 UI: Harvesting message includes fleet remaining free space
  source/Engine.cpp
Labels: waiting on reviewer, UI

#10406 fix(data-files): Fix has, not and assign condition usage in datafiles
  data/hai/hai reveal 2 start.txt
  data/human/human missions.txt
Labels: bug

#10419 doc(building): Mention ccache to speed-up rebuilds
  docs/readme-cmake.md
Labels: documentation

#10418 fix(Engine): Check if system is not null before making it a reference
  source/Engine.cpp
Labels: bug, waiting on dev

#10415 refactor: Make ImageSet and ImageBuffer use std::filesystem for path handling
  source/image/ImageBuffer.cpp
  source/image/ImageBuffer.h
  source/image/ImageSet.cpp
  source/image/ImageSet.h
Labels: refactor

#10420 feat(ci): Use official sccache action
  .github/sccache/action.yml
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
Labels: cd/ci/testing

#10437 fix(documentation): Add GOG to the README
  README.md
Labels: documentation

#10432 feat(content): Adding friendly Hai hails
  data/hai/hai.txt
Labels: content, text - short

#10438 docs: Clarify required mingw version
  docs/readme-cmake.md
Labels: documentation

#10425 refactor(ui): Switch from PopThrough to Pop in Dialog
  source/Dialog.cpp
Labels: refactor, UI

#10424 fix(audio): Fix missing sound effect for `star tail hit`
  data/incipias/incipias outfits.txt
Labels: bug, sound, waiting on dev
