Repository endless-sky/endless-sky, pull requests merged in 2024-01, with the labels that each got.

#9603 Add scrolling and clipping to the plugin pref page
  EndlessSkyLib.cbp
  data/_ui/interfaces.txt
  source/Animate.h
  source/CMakeLists.txt
  source/GameData.cpp
  source/PreferencesPanel.cpp
  source/PreferencesPanel.h
  source/RenderBuffer.cpp
  source/RenderBuffer.h
  source/Screen.cpp
  source/Screen.h
  source/ScrollVar.h
Labels: UI

#9646 fix(typo): Add missing punctuation in FW
  data/human/free worlds 1 start.txt
Labels: typo

#9647 fix(content): Avoid mentioning that the player invaded Greenrock with Tomek when they did not invade Greenrock
  data/human/free worlds 2 middle.txt
Labels: bug

#9649 small tweaks to James' intro
  data/human/intro missions.txt
Labels: content

#9651 Single typo change, drive -> devices
  data/coalition/coalition missions.txt
Labels: typo

#9624 Ensure that all steps of the player's travel plan are visible
  source/Engine.cpp
Labels: bug, UI

#6276 Allow projectiles to penetrate through ships, dealing damage multiple times
  EndlessSkyLib.cbp
  source/AsteroidField.cpp
  source/AsteroidField.h
  source/CMakeLists.txt
  source/Collision.cpp
  source/Collision.h
  source/CollisionSet.cpp
  source/CollisionSet.h
  source/CollisionType.h
  source/Engine.cpp
  source/Projectile.cpp
  source/Projectile.h
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#9653 feat(content): Add a carrier variant option for the Kestrel
  copyright
  data/human/kestrel.txt
  images/ship/kestrelc.png
  images/thumbnail/kestrelc.png
Labels: balance, content, artwork

#9652 feat(content): Gegno Intro Content Adjustments (separated from #8750)
  data/gegno/gegno intro missions.txt
  data/governments.txt
  data/map planets.txt
  data/map systems.txt
Labels: content

#9633 More grammar fixes - Heliarch and Lunarium intros
  data/coalition/heliarch intro.txt
  data/coalition/lunarium intro.txt
Labels: text - short

#9621 feat(content): Mining Update - Assets + Balance
  copyright
  data/coalition/coalition weapons.txt
  data/gegno/gegno outfits.txt
  data/harvesting.txt
  data/human/campaign events.txt
  data/human/fleets.txt
  data/human/sales.txt
  data/human/ships.txt
  data/human/variants.txt
  data/human/weapons.txt
  data/korath/korath weapons.txt
  images/effect/tractor beam+0.png
  images/effect/tractor beam+1.png
  images/hardpoint/mining laser turret.png
  images/hardpoint/tractor beam.png
  images/outfit/mining laser turret.png
  images/outfit/mining laser.png
  images/outfit/tractor beam.png
  images/projectile/mining laser+0.png
  images/projectile/mining laser+1.png
  images/ship/sunder.png
  images/thumbnail/sunder.png
  sounds/mining laser~.wav
  sounds/tractor beam~.wav
Labels: balance, content, artwork, text - short, sound

#9597 feat(content): Pirate Expansion - Remains of the CCOR
  copyright
  data/human/fleets.txt
  data/human/free worlds 0 prologue.txt
  data/human/free worlds 1 start.txt
  data/human/hails.txt
  data/human/sales.txt
  data/human/ships.txt
  data/human/variants.txt
  data/human/weapons.txt
  data/map planets.txt
  data/map systems.txt
  images/hardpoint/gat turret hardpoint.png
  images/hardpoint/javelin turret.png
  images/icon/gat turret.png
  images/icon/javelin turret.png
  images/land/mercury1.jpg
  images/land/sea23.jpg
  images/land/station46.jpg
  images/land/station47.jpg
  images/land/station48.jpg
  images/outfit/gat turret.png
  images/outfit/javelin turret.png
  images/planet/alvorada.png
  images/planet/mendez.png
  images/planet/station18.png
  images/projectile/2x tinyflare+0.png
  images/projectile/2x tinyflare+1.png
  images/projectile/2x tinyflare+2.png
  images/ship/enforcer.png
  images/ship/hogshead.png
  images/ship/saber.png
  images/thumbnail/enforcer.png
  images/thumbnail/hogshead.png
  images/thumbnail/saber.png
Labels: balance, content, artwork, text - short

#9667 Fix(shader): Shader compilation error as in 9648
  source/RenderBuffer.cpp
Labels: bug

#9664 Minor word fix in human news
  data/human/news.txt
Labels: typo

#9660 (fix) Change Lunarium rescue jobs distances to prevent overlap
  data/coalition/coalition jobs.txt
Labels: bug

#9246 feat(enhancement): Message log UI
  EndlessSkyLib.cbp
  data/_ui/interfaces.txt
  keys.txt
  source/CMakeLists.txt
  source/Command.cpp
  source/Command.h
  source/ConversationPanel.cpp
  source/Engine.cpp
  source/LogbookPanel.cpp
  source/MainPanel.cpp
  source/MapSalesPanel.cpp
  source/MessageLogPanel.cpp
  source/MessageLogPanel.h
  source/Messages.cpp
  source/Messages.h
  source/Panel.cpp
  source/Panel.h
  source/PlanetPanel.cpp
  source/PreferencesPanel.cpp
Labels: enhancement, UI

#9538 Mission: Ask the Quarg about the Coalition after having joined Heliarchs or Lunarium
  data/quarg/quarg missions.txt
Labels: content, text - short

#9677 fix(typo): Fix various typos
  data/_ui/help.txt
  data/_ui/tooltips.txt
  data/coalition/lunarium intro.txt
  data/korath/korath missions.txt
  source/Animate.h
  source/Engine.cpp
  source/Government.cpp
  source/PreferencesPanel.cpp
  source/ScrollVar.h
  source/Ship.h
  source/ShipInfoPanel.cpp
  source/TestData.h
Labels: typo

#9678 Output the reason why an integration test failed if it failed because of a segfault
  tests/integration/RunIntegrationTest.cmake
Labels: cd/ci/testing

#9606 Add missions where you transport a Hai film crew to Darkrest
  data/hai/hai culture conversations.txt
  data/hai/hai missions.txt
Labels: content, text - short

#9601 Add a mission transporting a group of Hai college students to Darkrest
  data/hai/hai missions.txt
Labels: content, text - short

#9163 Mining tutorial
  data/human/intro missions.txt
Labels: content, text - short

#9680 fix(typos): Gegno planet description improvements
  .codespell.exclude
  data/map planets.txt
Labels: text - short, typo

#9049 feat(enhancement): Add "on encounter" trigger for NPCs
  source/Engine.cpp
  source/NPC.cpp
  source/NPC.h
  source/ShipEvent.h
Labels: enhancement

#9681 fix(mission): Fix location filters for Hai Film Crew missions
  data/hai/hai missions.txt
Labels: bug

#9683 Fix typos in mission text
  data/gegno/gegno intro missions.txt
  data/human/free worlds 0 prologue.txt
  data/map planets.txt
Labels: typo

#9684 fix(content): Disable Gegno Intro if player has not met the Quarg
  data/gegno/gegno intro missions.txt
Labels: bug

#9685 Add a tooltip for the message log
  data/_ui/tooltips.txt
Labels: text - short

#9688 fix(content): Fix hai reveal check in "hai wormhole warning"
  data/human/human missions.txt
Labels: bug, content

#9687 fix(mechanics): Always face the flight direction on takeoff
  source/Ship.cpp
Labels: bug, mechanics

#9686 fix(ui): Reset zoom modifier if "Landing zoom" is off
  source/Engine.cpp
Labels: bug, UI

#9682 Apply license definitions in variants
  source/Outfit.cpp
Labels: bug, mechanics

#9694 Fix "Visit void sprite planets" mission dialog
  data/remnant/remnant 1 introduction.txt
Labels: bug

#9695 Add proper location attributes to Clink and Mutiny
  data/map planets.txt
Labels: bug

#9702 feat(content): Add Missing Nest Mining Variant
  data/human/variants.txt
Labels: content

#9708 Fix(typo): Convert (some) quotes to proper American English.
  .codespell.exclude
  data/coalition/heliarch intro.txt
  data/coalition/lunarium intro.txt
  data/gegno/gegno intro missions.txt
  data/hai/hai missions.txt
  data/hai/hai reveal 1 intro.txt
  data/hai/hai reveal 2 start.txt
  data/hai/hai reveal 3 early.txt
  data/hai/hai reveal 4 middle.txt
  data/hai/hai reveal 5 philosophers.txt
  data/hai/hai ships.txt
  data/human/culture conversations.txt
  data/human/human missions.txt
  data/human/news.txt
  data/human/post-war reactions.txt
  data/kahet/kahet missions.txt
  data/korath/korath ships.txt
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant outfits.txt
Labels: typo

#9724 Fix outfit licenses propagating onto ships (option 2)
  source/Outfit.cpp
  source/Outfit.h
  source/Ship.cpp
Labels: bug

#9668 v0.10.5 changelog
  changelog
Labels: documentation

#9725 0.10.5 docs update
  credits.txt
  endless-sky.6
  io.github.endless_sky.endless_sky.appdata.xml
  source/main.cpp
Labels: documentation

#9730 Add "GoG" as an option for "Game source" in the bug report issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: documentation

#9712 feat(content): Reduce the spawn rate of Astral Cetaceans
  data/map systems.txt
Labels: content
