Repository endless-sky/endless-sky, pull requests merged in 2024-12, with the labels that each got.

#10738 fix(bug): clear tribute from Wanderer planets correctly
  data/wanderer/wanderers start.txt
  data/wanderer/wanderers.txt
Labels: bug, content

#10814 style(doxygen): Allow doxygen single line comments from style checker
  source/Preferences.h
  utils/check_code_style.py
Labels: cd/ci/testing, style

#10426 fix(ui): Don't display undefined outfits and categories
  source/MainPanel.cpp
  source/ShipInfoDisplay.cpp
  source/ShipInfoPanel.cpp
Labels: bug, UI, waiting on dev

#10830 feat(ci): More aggressive timeouts for integration tests
  tests/integration/IntegrationTests.cmake
Labels: cd/ci/testing

#10834 content(fix): Remove extra tabs from two human missions
  data/human/human missions.txt
Labels: content, typo

#10323 refactor(ui): Extract magic numbers from Dialog
  source/Dialog.cpp
  source/Dialog.h
  source/text/WrappedText.cpp
Labels: refactor, UI, waiting on dev

#8937 feat(enhancement): Add engine support for time travel
  source/Engine.cpp
  source/GameEvent.cpp
  source/GameEvent.h
  source/Messages.cpp
  source/Messages.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: enhancement, mechanics, waiting on dev

#10835 fix(ci): Disable mission with stowaway during CI tests
  tests/integration/config/plugins/integration-tests/data/disabling troublesome missions.txt
Labels: cd/ci/testing

#10836 refactor(random): Move random from ConditionSet to on-demand auto-conditions
  source/ConditionSet.cpp
  source/PlayerInfo.cpp
Labels: mechanics, refactor

#10727 Mission destination ding
  data/_ui/tooltips.txt
  source/AI.cpp
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
Labels: enhancement, sound

#10831 feat(artwork): Make the Systems Core (Tiny) fit in with the rest of the System Cores
  images/outfit/tiny systems core.png
Labels: artwork

#10842 Fix typo in Dangerou Games 2
  data/human/human missions.txt
Labels: typo

#10273 feat(balance): Human Carrier Rework - Navy Carrier + Aerie Changes
  copyright
  data/human/campaign events.txt
  data/human/deep missions.txt
  data/human/fleets.txt
  data/human/free worlds 0 prologue.txt
  data/human/free worlds 1 start.txt
  data/human/free worlds 2 middle.txt
  data/human/free worlds 3 checkmate.txt
  data/human/free worlds 3 reconciliation.txt
  data/human/free worlds side plots.txt
  data/human/pirate jobs.txt
  data/human/ships.txt
  data/human/variants.txt
  data/wanderer/wanderers middle.txt
  data/wanderer/wanderers start.txt
  images/ship/carrier.png
  images/ship/modified carrier.png
  images/thumbnail/carrier.png
  images/thumbnail/modified carrier.png
Labels: balance, content, artwork

#10846 fix(content): Update Aerie description
  data/human/ships.txt
Labels: content

#10839 Outfitter: highlight differences in a group of same-model ships
  data/_ui/interfaces.txt
  source/OutfitterPanel.cpp
Labels: enhancement, UI

#10850 fix(typo): fix a typo in Patir Mystery 5
  data/kahet/kahet missions.txt
Labels: typo

#10649 Dim scan overlay when out of range
  data/_ui/interfaces.txt
  source/Engine.cpp
  source/Engine.h
Labels: enhancement, UI

#10852 Missions that don't block minors
  source/Mission.cpp
  source/Mission.h
  source/PlayerInfo.cpp
Labels: enhancement

#10844 Improve GameData::GetProgress
  source/GameData.cpp
Labels: refactor

#9098 Refactor face to maw 1(b)
  data/remnant/remnant 1 introduction.txt
Labels: content, refactor, waiting on reviewer

#10474 fix(ui): Fix target display leaking out of system information
  source/Engine.cpp
  source/Engine.h
Labels: bug, mechanics, UI

#8852 Various changes to some Remnant missions
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant events.txt
Labels: content

#10841 fix(ui-bug): Fix mission waypoint/stopover/mark pointers disappearing
  source/MapPanel.cpp
  source/MapPanel.h
Labels: bug, UI

#10416 refactor: Make Files use std::filesystem
  source/Command.cpp
  source/Command.h
  source/ConversationPanel.cpp
  source/DataFile.cpp
  source/DataFile.h
  source/DataWriter.cpp
  source/DataWriter.h
  source/File.cpp
  source/File.h
  source/Files.cpp
  source/Files.h
  source/GameData.cpp
  source/GameData.h
  source/GameWindow.cpp
  source/LoadPanel.cpp
  source/LoadPanel.h
  source/MenuPanel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/Plugins.cpp
  source/Plugins.h
  source/Preferences.cpp
  source/PreferencesPanel.cpp
  source/SavedGame.cpp
  source/SavedGame.h
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  source/audio/Audio.cpp
  source/audio/Audio.h
  source/audio/Music.cpp
  source/audio/Music.h
  source/audio/Sound.cpp
  source/audio/Sound.h
  source/image/ImageSet.cpp
  source/main.cpp
  source/test/TestData.cpp
  source/test/TestData.h
  source/text/Font.cpp
  source/text/Font.h
  source/text/FontSet.cpp
  source/text/FontSet.h
Labels: refactor, waiting on dev

#10858 fix(typo): Efreti Distress Call: specify a noun in a blocked message
  data/korath/korath missions.txt
Labels: typo

#10861 fix(startup): Fix application directory query
  source/Files.cpp
Labels: bug

#10194 feat(ui) Add park key to shop (shipyard/outfitter) panels.
  source/ShopPanel.cpp
Labels: UI, waiting on dev

#8172 feat(scanning): extra and more finegrained tactical and strategic scanning options
  copyright
  data/_ui/interfaces.txt
  data/_ui/tooltips.txt
  images/ui/tactical/acceleration.png
  images/ui/tactical/crew.png
  images/ui/tactical/energy.png
  images/ui/tactical/fuel.png
  images/ui/tactical/gun range.png
  images/ui/tactical/range.png
  images/ui/tactical/tactical.png
  images/ui/tactical/thermal.png
  images/ui/tactical/turn.png
  images/ui/tactical/turret range.png
  images/ui/tactical/velocity.png
  source/AI.cpp
  source/Engine.cpp
  source/PlayerInfo.cpp
  source/Ship.cpp
  source/Ship.h
  source/ship/ShipAICache.cpp
  source/ship/ShipAICache.h
Labels: enhancement, UI, waiting on dev

#10864 fix(ui): Fix conversation height offset
  source/Dialog.cpp
  source/TextArea.cpp
  source/TextArea.h
  source/text/WrappedText.cpp
  source/text/WrappedText.h
Labels: bug, UI

#10833 test(integration/ci): Option to print debug messages from integration tests
  source/test/Test.cpp
  source/test/Test.h
  tests/integration/config/plugins/integration-tests/data/tests/tests_afterburn_flight.txt
Labels: cd/ci/testing

#10865 refactor(conditions): Remove unused condition erase functionality
  source/ConditionsStore.cpp
  source/ConditionsStore.h
  source/PlayerInfo.cpp
  tests/unit/src/test_conditionsStore.cpp
Labels: refactor

#10856 feat(content): Revert `shrouded` from most Umbral Reach systems
  data/map systems.txt
Labels: content

#10463 fix(mechanics): Fix weapon jamming accumulation
  source/Hardpoint.cpp
Labels: bug, mechanics

#8502 feat(fleets,hazards): `to spawn` condition in system fleets and hazards
  source/Engine.cpp
  source/RandomEvent.h
  source/System.cpp
Labels: enhancement, to be merged

#10885 feat(balance): Balance the Pug Seeker's `missile strength` against human AMs
  data/pug/pug outfits.txt
Labels: balance

#10731 Fix(content): Standardize Free Worlds plurality
  data/hai/hai reveal 4 middle.txt
  data/human/campaign events.txt
  data/human/free worlds 0 prologue.txt
  data/human/free worlds 1 start.txt
  data/human/free worlds 2 middle.txt
  data/human/free worlds 3 checkmate.txt
  data/human/free worlds 3 reconciliation.txt
  data/human/free worlds side plots.txt
  data/human/free worlds war jobs.txt
  data/human/hails.txt
  data/human/human missions.txt
  data/human/post-war reactions.txt
Labels: content, style

#10883 refactor(content): Give the Spaceport Resetter mission non-blocking
  data/human/human missions.txt
Labels: refactor
