Repository endless-sky/endless-sky, pull requests merged in 2024-04, with the labels that each got.

#9931 fix(content): Ensure player can't access planetary facilities while evacuating Vara Ke'stai and Varu Mer'ek
  data/wanderer/wanderers start.txt
Labels: content

#9741 feat(enhancement): Allow boarding ships with a fighter flagship
  source/Ship.cpp
Labels: enhancement

#9962 fix(content): Remove duplicate korath phrase
  data/korath/korath hails.txt
Labels: typo

#9976 fix(content): Clarify FS27 description
  data/korath/korath ships.txt
Labels: text - short

#9990 fix comm typo, add some hu locale strings
  io.github.endless_sky.endless_sky.appdata.xml
  io.github.endless_sky.endless_sky.desktop
Labels: typo

#9985 fix(content): Block Lunarium: Questions from finishing if you are assiting the heliarchs and explain why
  data/coalition/lunarium intro.txt
Labels: bug

#9865 feat(content): Add new civilian hails, revise others, and add some more disabled hails for pirates
  data/governments.txt
  data/human/hails.txt
Labels: content, text - short

#9982 Minor fix to Deep's description
  data/map planets.txt
Labels: typo

#9459 Fix copyright for unsplash images
  copyright
  images/land/water4.jpg
  images/scene/buildings.jpg
  images/scene/citydark.jpg
Labels: documentation

#10003 fix(map ui): Draw distance to the selected system after mission markers
  source/MapPanel.cpp
  source/MapPanel.h
Labels: bug, UI

#10011 fix: Ships with `disables` personality shouldn't ask for destroying their enemies
  source/Engine.cpp
Labels: bug

#10001 fix(typo): Fix various typos
  data/bunrodea/bunrodea missions.txt
  data/coalition/coalition missions.txt
  data/coalition/coalition.txt
  data/coalition/heliarch intro.txt
  data/hai/hai reveal 2 start.txt
  data/hai/hai reveal 3 early.txt
  data/hai/hai reveal news.txt
  data/human/culture conversations.txt
  data/human/deep missions.txt
  data/human/free worlds 3 checkmate.txt
  data/human/hails.txt
  data/human/human missions.txt
  data/kahet/kahet outfits.txt
  data/remnant/remnant 2 side missions.txt
Labels: typo, waiting on dev

#10012 (bugfix) Correct indentation in Gohl's mission choices
  data/quarg/quarg missions.txt
Labels: bug

#10014 (bugfix) Don't display the "you have missions that require landing on [planet]" notice for bounty hunter missions
  source/AI.cpp
Labels: bug, mechanics

#7987 Enhancement: conditional links
  source/Engine.cpp
  source/GameData.cpp
  source/GameData.h
  source/PlayerInfo.cpp
  source/System.cpp
  source/System.h
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  tests/CMakeLists.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_random_links.txt
Labels: enhancement, waiting on reviewer

#10023 fix: Remove outdated watchdog
  tests/integration/config/plugins/integration-tests/data/tests/tests_random_links.txt
Labels: cd/ci/testing

#9989 fix(content): Add back instances of "ser" and explain what it means in the Skadenga and Stones of Our Fathers missions
  .codespell.exclude
  .codespell.words.exclude
  data/human/deep missions.txt
Labels: content, text - short

#10016 Content: Update the descriptions of two Sestor worlds after the factories are shut down.
  data/wanderer/wanderers middle.txt
Labels: text - short

#10019 Fix two typos
  data/gegno/gegno intro missions.txt
  data/human/free worlds 0 prologue.txt
Labels: typo

#9978 Link GLEW::glew instead of GLEW::GLEW in CMakeLists.txt
  CMakeLists.txt
Labels: bug

#9950 Simplify CMake build on Linux and MacOS
  CMakeLists.txt
  CMakePresets.json
  docs/readme-cmake.md
  vcpkg.json
Labels: cd/ci/testing

#10029 fix(typo): Remove unnecessary speech mark
  .codespell.exclude
  data/human/deep missions.txt
Labels: typo

#10021 feat(content): Outfitters near Earth stock new outfits after the war begins
  data/human/campaign events.txt
  data/human/sales.txt
Labels: content, text - short, waiting on dev
