Repository endless-sky/endless-sky, pull requests merged in 2024-11, with the labels that each got.

#10725 Fix navigation while mid-jump
  source/MapPanel.cpp
Labels: bug

#10723 fix(bug): reference the Gneiss in its description correctly
  data/gegno/gegno ships.txt
Labels: typo

#10657 fix(mechanics): Fix bug where over-capacity fleets don't unload all their cargo
  source/PlanetPanel.cpp
  source/PlayerInfo.cpp
Labels: bug, mechanics

#10696 Update vcpkg packages
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  vcpkg-configuration.json
Labels: cd/ci/testing

#10709 fix(bug): Make the Hai Start actually show up
  data/starts.txt
Labels: bug, content

#10671 feat(artwork): Scale Lance engine plumes normally
  data/human/ships.txt
Labels: artwork

#10675 feat(content): Hai culture conversation for acorn bread
  .codespell.exclude
  data/hai/hai culture conversations.txt
Labels: content, text - short

#10730 fix(bug): display the fuel cost for the Fusion Drive correctly
  data/sheragi/sheragi outfits.txt
Labels: UI

#10739 Fix destroyed ship landing message
  source/Engine.cpp
Labels: UI, waiting on dev

#10750 feat(content): Adjust Gegno Vi Slate description
  data/gegno/gegno ships.txt
Labels: content, text - short

#10752 fix(content): Shorten Hai station Sandsnap's description
  data/map planets.txt
Labels: bug, content, text - short

#10751 fix(content): Shorten News entry about Betelgeuse ships
  data/human/news.txt
Labels: bug, content, text - short

#10580 feat(mechanics): Support for removing special log entries
  source/GameAction.cpp
  source/GameAction.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: enhancement, mechanics

#10754 feat(mechanics): Dates and credit values under `on (display || reveal)` can now be formatted
  data/starts.txt
  source/StartConditions.cpp
  source/StartConditions.h
Labels: bug, enhancement, mechanics

#10756 feat(content): Clarify unlock conditions for the Hai start
  data/globals.txt
  data/starts.txt
Labels: content, text - short

#10726 Some editor config updates that at least Visual Studio uses:
  .editorconfig
Labels: cd/ci/testing

#10732 Set the default jump fuel on the outfit, not just internally for navigation
  data/_ui/tooltips.txt
  source/Outfit.cpp
  source/ShipJumpNavigation.cpp
  source/ShipJumpNavigation.h
Labels: enhancement

#10762 fix(bug): remove duplicate outfits node in a Splinter variant
  data/human/variants.txt
Labels: typo

#10719 Grammar fix for the Quicksilver package mixup mission.
  data/human/human missions.txt
Labels: typo

#10767 Remove a duplicate Scin bay definition and fix a Remnant typo
  data/gegno/gegno ships.txt
  data/remnant/remnant 2 cognizance.txt
Labels: typo

#10712 fix(mechanics): Make haywire missiles go off target properly
  source/Projectile.cpp
  source/Projectile.h
Labels: bug, balance, mechanics

#10711 Minor wording edit to post-liberation Poisonwood's spaceport description
  data/human/campaign events.txt
  data/map planets.txt
Labels: content, text - short

#10758 fix(content): Make "Tarazed neutrality" apply immediately
  data/human/free worlds 1 start.txt
Labels: bug, content

#10749 fix(content): Fix overlapping planets in a few Gegno systems
  data/map systems.txt
Labels: bug, content

#10748 fix(content): Stop Hai tourism jobs from using Swiftsong as a destination
  data/hai/hai jobs.txt
Labels: bug, content

#10745 Bugfix: hai first contact conditions in hai start and other
  data/human/human missions.txt
  data/korath/korath missions.txt
  data/starts.txt
Labels: bug, content

#10728 tweak: update a Coalition culture conversation
  data/coalition/coalition culture conversations.txt
Labels: content

#10660 feat(content): update tooltip for `energy capacity`
  data/_ui/tooltips.txt
Labels: content, UI

#10669 feat(balance): Reduce spawn rate of Korsmanath A'awoj, so that fewer are in-system at any given time
  data/map systems.txt
Labels: balance

#10771 fix(ui): Fix duplicated display of the new fuel attributes
  data/_ui/tooltips.txt
  source/Outfit.cpp
Labels: bug, UI, waiting on dev

#10724 A few tweaks to #10581
  source/OutfitterPanel.cpp
Labels: bug, UI

#10777 fix(mechanics): Don't allow buying outfits with insufficient credits
  source/OutfitterPanel.cpp
Labels: bug

#10615 feat(content): More Successor hails and ship names
  .codespell.exclude
  data/successors/successor events.txt
  data/successors/successor hails.txt
  data/successors/successors.txt
Labels: content, text - short

#10774 feat(content): Successor Stargazing accounts for Hai start
  data/successors/successor side missions.txt
Labels: content

#10783 fix(ui): Apply proper swizzle to 'target sprite' and 'player sprite' in 'fast' 'outline' mode
  source/Engine.cpp
  source/Information.cpp
  source/Information.h
  source/Interface.cpp
Labels: bug, UI, waiting on dev

#10369 feat(input-validation): Add validation warnings for condition names and missions
  data/human/human missions.txt
  source/ConditionSet.cpp
  source/ConditionsStore.cpp
  source/DataNode.cpp
  source/DataNode.h
  source/GameEvent.cpp
  source/Mission.cpp
Labels: enhancement

#10706 Navigation supports multiple jump drives
  source/DistanceMap.cpp
  source/DistanceMap.h
  source/Outfit.cpp
  source/Outfit.h
Labels: enhancement

#10790 feat(ui): Allow steering while reversing
  source/AI.cpp
Labels: mechanics

#10773 fix(content): Old Houses required reputation, bribe-ability
  data/governments.txt
  data/map planets.txt
Labels: content

#10753 feat(balance): Tone down the excessively high drag of many human freighters.
  data/human/ships.txt
Labels: balance

#10798 fix(ghactions): remove aesthetic and variants from `.codespell.words.exclude`
  .codespell.exclude
  .codespell.words.exclude
Labels: cd/ci/testing

#10779 fix(typo): more typo fixes
  data/_ui/tooltips.txt
  data/bunrodea/bunrodea ships.txt
  data/gegno/gegno.txt
  data/hai/hai reveal 1 intro.txt
  data/hai/hai ships.txt
  data/human/human missions.txt
Labels: typo

#10799 fix: Increase Venta ammo count
  data/incipias/incipias ships.txt
Labels: content

#9977 feat(content): Tim the Stowaway - Human mission
  data/human/human missions.txt
Labels: content, text - long, waiting on dev

#10802 fix(text/dates): Date::LongString should output the DDth of Month
  source/Date.cpp
Labels: bug, mechanics, waiting on dev

#10353 feat(conditions): Move the condition assignments interface to its own class
  source/CMakeLists.txt
  source/ConditionAssignments.cpp
  source/ConditionAssignments.h
  source/ConditionSet.cpp
  source/ConditionSet.h
  source/Conversation.cpp
  source/GameAction.h
  source/GameEvent.cpp
  source/GameEvent.h
  source/Mission.cpp
  source/StartConditions.cpp
  source/StartConditions.h
  source/TextReplacements.cpp
  source/test/Test.cpp
  source/test/Test.h
  tests/CMakeLists.txt
  tests/unit/src/test_conditionAssignments.cpp
  tests/unit/src/test_conditionSet.cpp
Labels: mechanics, refactor, waiting on dev

#10806 fix(content): Remove reference to 'Embers' in an early Remnant mission
  data/remnant/remnant 1 introduction.txt
Labels: content, text - short

#10812 fix(typo): Fix tabulator character in condition name
  data/human/human missions.txt
Labels: typo

#10800 Deep mission typos and grammar fixes
  .codespell.exclude
  data/human/deep missions.txt
Labels: typo

#10736 feat(enhancement): Distance dependent hidden objects
  source/AI.cpp
  source/BatchDrawList.cpp
  source/Body.cpp
  source/Body.h
  source/DrawList.cpp
  source/PlanetLabel.cpp
  source/PlanetLabel.h
  source/System.cpp
Labels: enhancement

#10654 feat(audio): Pause sound effects in the menu
  source/MenuPanel.cpp
  source/MenuPanel.h
  source/audio/Audio.cpp
  source/audio/Audio.h
  source/main.cpp
Labels: enhancement, sound, to be merged

#10491 fix(ui): Don't generate key presses from inactive interfaces
  source/BankPanel.cpp
  source/BoardingPanel.cpp
  source/HailPanel.cpp
  source/HiringPanel.cpp
  source/Information.cpp
  source/Information.h
  source/Interface.cpp
  source/LoadPanel.cpp
  source/MapPanel.cpp
  source/MenuPanel.cpp
  source/MessageLogPanel.cpp
  source/MissionPanel.cpp
  source/Panel.cpp
  source/Panel.h
  source/PlanetPanel.cpp
  source/PlayerInfoPanel.cpp
  source/PreferencesPanel.cpp
  source/ShipInfoPanel.cpp
  source/ShipInfoPanel.h
  source/StartConditionsPanel.cpp
  source/StartConditionsPanel.h
  source/TradingPanel.cpp
Labels: bug, UI, waiting on dev

#10563 Add json and py to editorconfig
  .editorconfig
  CMakePresets.json
  utils/check_copyright.py
  utils/korath-cipher.py
  vcpkg-configuration.json
  vcpkg.json
Labels: cd/ci/testing, to be merged

#10411 fix(mechanics): Always allow `on fail` to trigger after failure
  source/MissionAction.cpp
Labels: bug, mechanics

#10561 ci(build): Add MacOS ARM CI job
  .github/workflows/ci.yml
  CMakePresets.json
  overlays/macos-arm64-ci.cmake
Labels: cd/ci/testing

#10817 fix(bug): Use "AA" instead of "aa" in the Spaceport Reminder Resetter
  data/human/human missions.txt
Labels: bug, content

#10821 Revert "fix(ui): Don't generate key presses from inactive interfaces …
  source/BankPanel.cpp
  source/BoardingPanel.cpp
  source/HailPanel.cpp
  source/HiringPanel.cpp
  source/Information.cpp
  source/Information.h
  source/Interface.cpp
  source/LoadPanel.cpp
  source/MapPanel.cpp
  source/MenuPanel.cpp
  source/MessageLogPanel.cpp
  source/MissionPanel.cpp
  source/Panel.cpp
  source/Panel.h
  source/PlanetPanel.cpp
  source/PlayerInfoPanel.cpp
  source/PreferencesPanel.cpp
  source/ShipInfoPanel.cpp
  source/ShipInfoPanel.h
  source/StartConditionsPanel.cpp
  source/StartConditionsPanel.h
  source/TradingPanel.cpp
Labels: UI

#10826 Warn users that SCons is deprecated and point them to the CMake instructions
  SConstruct
Labels: documentation

#10815 Update disabling troublesome missions.txt
  tests/integration/config/plugins/integration-tests/data/disabling troublesome missions.txt
Labels: cd/ci/testing

#10820 Fix boarding panel buttons
  data/_ui/interfaces.txt
  source/BoardingPanel.cpp
Labels: UI

#10786 feat(ui): Add a help message describing how to see help messages
  data/_ui/help.txt
  source/Engine.cpp
  tests/integration/config/preferences.txt
Labels: UI, waiting on dev

#10740 Typo (?) fix
  data/successors/successor side missions.txt
Labels: typo

#10825 Don't override ship cargo display with pooled cargo when not appropriate
  source/ShipInfoPanel.cpp
Labels: bug, UI
