Repository endless-sky/endless-sky, pull requests merged in 2024-02, with the labels that each got.

#9744 Fix reference in 'First Contact: Gegno Vi'
  data/gegno/gegno intro missions.txt
Labels: bug, text - short

#9736 Fix typos in boarding missions.txt
  data/human/boarding missions.txt
Labels: typo

#9698 feat(content): Add to placeholder descriptions for uninhabited Hai stations
  data/map planets.txt
Labels: content, text - short

#9778 Give required crew to the Javelin and Gatling Turrets
  data/human/weapons.txt
Labels: bug

#9798 fix(bug): Update conditions in Gemini Shipyards jobs
  data/human/paradise world jobs.txt
Labels: bug

#9795 Give Dreadnoughts back their fourth torpedo launcher
  data/human/ships.txt
Labels: balance

#9788 Ship info display fixes
  source/ShipInfoDisplay.cpp
Labels: bug, UI

#9782 feat(content): Mention the presence of abandoned Navy bases on planets during Checkmate
  data/human/campaign events.txt
Labels: content, text - short

#9779 Make Lasher Pistols more defensive than offensive
  data/bunrodea/bunrodea outfits.txt
Labels: balance

#9775 Rename feature request template
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: documentation

#9774 ui: Fix credits not showing if speed is set to 0
  source/MenuPanel.cpp
Labels: bug

#9758 feat(content): Some new human hails about dumping cargo for pirates
  data/human/hails.txt
Labels: content, text - short

#9752 fix(typo): Various typo fixes
  data/_ui/help.txt
  data/coalition/coalition missions.txt
  data/coalition/lunarium intro.txt
  data/hai/hai missions.txt
  data/hai/hai news.txt
  data/hai/hai reveal 0 prologue.txt
  data/harvesting.txt
  data/human/deep missions.txt
  data/human/human missions.txt
  data/human/news.txt
  data/human/paradise world jobs.txt
  data/map planets.txt
Labels: typo

#9748 fix(content): Uninhabited systems & Kaus Borealis switch sides throughout the FW campaign
  data/human/campaign events.txt
  data/human/free worlds 3 checkmate.txt
Labels: bug

#9767 Render animated sprites in the hail panel correctly
  source/HailPanel.cpp
  source/HailPanel.h
Labels: bug

#9751 fix(balance): Fix the timer ship AI
  data/sheragi/archaeology missions.txt
Labels: bug

#9807 fix(typo): Move apostrophe in Solifuge description
  data/hai/hai ships.txt
Labels: typo

#9808 fix(typo): Typos in Southern Fiance 2 and Gegno: First Contact
  data/gegno/gegno intro missions.txt
  data/human/human missions.txt
Labels: typo

#9816 Remove second "on complete" in a Lunarium mission
  data/coalition/lunarium intro.txt
Labels: bug

#9812 fix(bug): Various typos and wording style changes
  data/_ui/help.txt
  data/map planets.txt
  data/quarg/quarg.txt
Labels: typo

#9793 Lunarium missions - grammar fixes
  data/coalition/lunarium intro.txt
Labels: typo

#9804 feat(content): Add `lingering` to Gegno Protolith Fleet
  data/gegno/gegno fleets.txt
Labels: content

#9837 fix(typo): Fix typo in changelog
  changelog
Labels: typo

#9821 chore(CI): Update Github Actions
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
  .github/workflows/steam.yml
Labels: cd/ci/testing

#9750 Stricter copyright checking
  utils/check_copyright.py
Labels: cd/ci/testing

#9789 fix(CI): Fix edge case in code style checker
  utils/check_code_style.py
Labels: bug, cd/ci/testing

#9810 Content: give the harvest personality to unfettered, and add more cargo to the logistic fleets
  data/hai/hai fleets.txt
Labels: balance, content

#9699 Balance: Remove Bactrian from all non-mission Pirate fleets
  data/human/fleets.txt
  data/human/pirate jobs.txt
Labels: balance, content

#9716 Autocondition for testing if you can land on a given planet
  source/PlayerInfo.cpp
Labels: enhancement

#9715 fix(content): Earth day jobs no longer offer unless you can land on Earth
  data/human/near earth jobs.txt
Labels: bug

#9232 balance: nerf the express unfettered medical job
  data/hai/unfettered jobs.txt
Labels: balance

#9787 feat(enhancement): Log response messages from the hail panel
  source/HailPanel.cpp
  source/HailPanel.h
  source/Messages.cpp
  source/Messages.h
Labels: enhancement, UI

#9806 fix(content): Make TMBR 3a dialogue choices consistent
  data/human/human missions.txt
Labels: content

#9773 Feat/Style/Dunno(Code): Remove unnecessary memory managment from LoadPanel.cpp
  source/LoadPanel.cpp
Labels: mechanics, UI

#9845 fix(typo): Add a missing word in a bounty description
  data/human/jobs.txt
Labels: typo

#9822 Allow blast radius projectiles to explode when their lifetime runs out
  source/Engine.cpp
  source/Projectile.cpp
  source/Projectile.h
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#9823 Allow projectiles to not collide with ships or asteroids
  source/Engine.cpp
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement

#9825 Add shop tooltips for total credits and ship names
  source/ShopPanel.cpp
  source/ShopPanel.h
Labels: UI

#9855 Don't consider the "Parsing: <file>" output when in debug mode errors when test parsing
  source/main.cpp
Labels: bug

#9869 fix(crash): Fix game crash on short error messages
  source/main.cpp
Labels: bug

#9866 Remove the forced-default disabled hails from Government
  data/governments.txt
  source/Government.cpp
Labels: mechanics

#9857 feat(personality): `Quiet` personality
  source/Personality.cpp
  source/Personality.h
  source/Ship.cpp
Labels: mechanics

#9753 [Content] Add a mission transporting a Hai that requires a Quantum Keystone
  data/hai/hai missions.txt
Labels: content, text - short

#9756 Feat(content): add unfettered related hai news
  data/hai/hai news.txt
Labels: content, text - short
