Repository endless-sky/endless-sky, pull requests merged in 2024-05, with the labels that each got.

#9809 Content: remove pirates from Ildaria
  data/human/campaign events.txt
  data/map systems.txt
Labels: content, waiting on dev

#9979 feat(content): A short set of missions involving the Wanderers and Mereti
  data/wanderer/wanderer missions.txt
Labels: content, text - short, waiting on dev

#9879 feat(content): Add new uninhabited landable planets to existing systems in Human space
  copyright
  data/map planets.txt
  data/map systems.txt
  images/land/haze0.jpg
  images/land/haze1.jpg
  images/land/haze2.jpg
  images/land/snow23.jpg
Labels: content, text - short, waiting on dev

#9973 feat(content): Revert missile changes + miscellaneous balance tweaks
  data/human/ships.txt
  data/human/variants.txt
  data/human/weapons.txt
Labels: balance, text - short

#9912 Balance: reduce the damage and increase the blast radius of heavy rockets, making them less likely to one-shot small ships and giving them a clearer role as an anti-swarm weapon.
  data/human/intro missions.txt
  data/human/weapons.txt
Labels: balance

#10017 fix(content) make remnant cognizance 4 desc more helpful
  data/remnant/remnant 2 cognizance.txt
Labels: text - short

#9819 Balance: tweak marauder builds, and remove later game content from them
  data/human/marauders.txt
Labels: balance, waiting on dev

#10036 fix(content): make the <npc> substitution in Wanderers: Mereti: The Plant 5 point to the right npc
  data/wanderer/wanderer missions.txt
Labels: bug

#9924 feat(content): Changes to Pre-war Missions
  .codespell.exclude
  data/human/campaign events.txt
  data/human/free worlds 1 start.txt
  data/human/free worlds 2 middle.txt
  data/human/free worlds side plots.txt
  data/human/human missions.txt
Labels: content, text - short, waiting on dev

#9846 [Mechanic] Disabled Self-Repair
  data/_ui/tooltips.txt
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/Ship.h
Labels: mechanics

#10038 feat(balance): Tone down the missile strength and turn rate of the Firelight, so that it is less excessively difficult to evade and/or shoot down.
  data/korath/korath weapons.txt
Labels: balance

#10027 Fix terraform
  data/human/human missions.txt
Labels: bug, waiting on dev

#9850 Balance: Give the Quicksilver +20 weapon space and a reverse thruster, to make it perform better in its specific niche than the more versatile Clipper and Headhunter.
  data/human/marauders.txt
  data/human/ships.txt
Labels: balance

#10034 fix(content): Make certain blasters are sold on pirate planets, by adding them to pirate outfits sales
  data/human/sales.txt
Labels: content

#10008 Allow triggers to play a sound
  source/GameAction.cpp
  source/GameAction.h
Labels: enhancement, sound, waiting on dev

#10028 Variable inconsistency between Patir Mystery and Cognizance
  data/remnant/remnant 2 cognizance.txt
Labels: bug, waiting on dev

#7025 Feat(mechanics): Cloaking flexibility with additional attributes
  data/_ui/tooltips.txt
  source/AI.cpp
  source/DamageProfile.cpp
  source/Engine.cpp
  source/MainPanel.cpp
  source/Outfit.cpp
  source/OutfitInfoDisplay.cpp
  source/Projectile.cpp
  source/Projectile.h
  source/Ship.cpp
  source/Ship.h
Labels: mechanics, waiting on reviewer

#10047 fix(typo): "cloaking shield" -> "cloaking shields"
  data/_ui/tooltips.txt
  source/Outfit.cpp
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
Labels: typo

#9961 feat(content): Bringing a lost dog to its owner on Glory
  data/human/human missions.txt
Labels: content, text - short

#10050 fix(content): syntax in Lost Dog missions
  data/human/human missions.txt
Labels: bug

#10053 Don't select Graffias as a target for Free Worlds "Scouting Run" jobs
  data/human/free worlds war jobs.txt
Labels: bug

#7094 feat: Ability to limit turret firing arc
  data/_ui/tooltips.txt
  source/AI.cpp
  source/Angle.cpp
  source/Angle.h
  source/Armament.cpp
  source/Armament.h
  source/Hardpoint.cpp
  source/Hardpoint.h
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/Weapon.cpp
  source/Weapon.h
  tests/unit/src/test_angle.cpp
Labels: enhancement, waiting on dev

#10059 feat(code): Ensuring label and line positions adapt to Weapons box positioning
  source/ShipInfoPanel.cpp
Labels: bug, UI, waiting on dev

#9772 feat(content): Core Pirate Ship Variants with Tractor Beams
  data/human/fleets.txt
  data/human/variants.txt
Labels: content

#10015 fix(mechanics): Properly check if a mission is failed
  source/AI.cpp
  source/CargoHold.cpp
  source/CargoHold.h
  source/Government.cpp
  source/Government.h
  source/MapPanel.cpp
  source/Mission.cpp
  source/Mission.h
  source/PlayerInfo.cpp
  source/Politics.cpp
  source/Ship.cpp
Labels: bug, mechanics, waiting on dev

#10055 feat(content): Prevent "Deep: Interrogation" from offering during the Main Campaign
  data/human/deep missions.txt
Labels: content

#10056 fix(content): "Remnant: Continue Research" no longer offers if you've completed the missions after it
  data/human/deep missions.txt
Labels: bug, content

#9642 feat(enhancement): "Fancy" Cloaked Ship Outlines
  data/_ui/interfaces.txt
  data/_ui/tooltips.txt
  source/DrawList.cpp
  source/DrawList.h
  source/Engine.cpp
  source/Engine.h
  source/Preferences.cpp
  source/PreferencesPanel.cpp
Labels: enhancement

#9740 fix(content): Yet another pirate job bugfix
  data/dialog phrases.txt
  data/human/human missions.txt
  data/human/pirate jobs.txt
Labels: bug, waiting on dev

#10057 feat(content): Adjust Imo Dep Minables & Add Hai Mining fleets
  data/hai/hai fleets.txt
  data/map systems.txt
Labels: content

#9039 content: Derelict ship encounters
  data/governments.txt
  data/human/boarding missions.txt
  data/human/campaign events.txt
  data/human/derelicts.txt
  data/human/human missions.txt
  data/map systems.txt
Labels: content, text - long

#10063 feat(content): Separate the Kestrel from "Tarazed Advanced" shipyard
  data/human/kestrel.txt
Labels: content

#9496 feat(enhancement): Add plugin metadata to plugin.txt
  source/Plugins.cpp
  source/Plugins.h
  source/PreferencesPanel.cpp
Labels: enhancement

#10072 fix(balance): Adjust explosion stats for the Korsmanath A'awoj and Echo-galleon to follow the trend in explosions from other comparable Korath ships.
  data/korath/korath ships.txt
Labels: bug, balance

#9530 feat(content): Adelita Journalism missions 1 through 5 (adapted from #5112)
  data/human/human missions.txt
Labels: content, text - long, waiting on dev

#8489 Feature: Auto-Pilot stops thrusting at ship max speed
  source/AI.cpp
  source/Ship.cpp
  source/Ship.h
Labels: mechanics

#10054 Feat(events): Allow explicit 0 for events to apply directly
  source/GameAction.cpp
  source/PlanetPanel.cpp
  source/PlayerInfo.cpp
  source/SpaceportPanel.cpp
Labels: enhancement, mechanics, waiting on dev

#9826 Allow GameActions to give the player mortgages
  source/Account.cpp
  source/Account.h
  source/GameAction.cpp
  source/GameAction.h
  source/Mortgage.cpp
  source/Mortgage.h
  source/PlayerInfo.cpp
  source/Ship.cpp
Labels: enhancement

#9827 Allow missions to mark systems of importance
  source/GameAction.cpp
  source/GameAction.h
  source/MapPanel.cpp
  source/Mission.cpp
  source/Mission.h
  source/MissionPanel.cpp
  source/PlayerInfo.cpp
Labels: enhancement, UI

#10074 fix(bug): Indicate Betelgeuse as a system of importance in Deep Scientist Rescue 0
  data/human/deep missions.txt
Labels: bug

#10073 fix(content): You only have to visit the system with the pirate fleet in Pact Recon 3
  data/human/free worlds 0 prologue.txt
Labels: content

#10075 Don't recalculate escort's distance maps every step when jumping.
  source/AI.cpp
Labels: bug

#9638 feat(enhancement): Dynamic Camera Acceleration
  source/Engine.cpp
  source/Engine.h
  source/Point.cpp
  source/Point.h
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
Labels: UI

#10079 Couple of Fixes to the Lost Dog mission
  data/human/human missions.txt
Labels: bug, content

#10081 typo: Various typo fixes
  copyright
  data/wanderer/wanderer missions.txt
  docs/readme-cmake.md
  source/Ship.cpp
Labels: typo

#10077 fix(content): Fix outdated news entry about human drones
  data/human/news.txt
Labels: bug, text - short

#9616 Balance: Rebalance of ship mass and handling across the board again
  data/_deprecated/deprecated outfits.txt
  data/_deprecated/deprecated ships.txt
  data/bunrodea/bunrodea outfits.txt
  data/bunrodea/bunrodea ships.txt
  data/bunrodea/bunrodea weapons.txt
  data/coalition/coalition outfits.txt
  data/coalition/coalition ships.txt
  data/coalition/coalition weapons.txt
  data/drak/drak outfits.txt
  data/drak/drak ships.txt
  data/drak/indigenous.txt
  data/gegno/gegno outfits.txt
  data/gegno/gegno ships.txt
  data/hai/hai outfits.txt
  data/hai/hai ships.txt
  data/human/engines.txt
  data/human/kestrel.txt
  data/human/marauders.txt
  data/human/outfits.txt
  data/human/ships.txt
  data/human/weapons.txt
  data/iije/iije.txt
  data/kahet/kahet outfits.txt
  data/kahet/kahet ships.txt
  data/korath/korath outfits.txt
  data/korath/korath ships.txt
  data/korath/korath weapons.txt
  data/persons.txt
  data/pug/pug outfits.txt
  data/pug/pug ships.txt
  data/quarg/quarg outfits.txt
  data/quarg/quarg ships.txt
  data/remnant/remnant outfits.txt
  data/remnant/remnant ships.txt
  data/rulei/rulei outfits.txt
  data/rulei/rulei ships.txt
  data/sheragi/sheragi outfits.txt
  data/sheragi/sheragi ships.txt
  data/vyrmeid/vyrmeid.txt
  data/wanderer/wanderer outfits.txt
  data/wanderer/wanderer ships.txt
  data/whispering void/critters.txt
Labels: balance

#9696 feat(content): Give korath worldships names instead of serial numbers
  data/korath/korath ships.txt
Labels: content, waiting on reviewer, text - short

#10080 fix(style): Fix function spacing in the source files
  source/AI.cpp
  source/Color.cpp
  source/Dialog.cpp
  source/Files.cpp
  source/Hardpoint.cpp
  source/Hazard.cpp
  source/Interface.cpp
  source/Personality.cpp
  source/Preferences.cpp
  source/Ship.cpp
  source/ShipEvent.cpp
  source/System.cpp
  source/Wormhole.cpp
Labels: typo

#10076 fix(ui): Add missing tooltip for `Camera acceleration`
  data/_ui/tooltips.txt
Labels: text - short, UI

#10086 Properly set camera position when leaving planet
  source/Engine.cpp
Labels: bug, UI

#10095 fix(content): Remove an empty log from Adelita
  data/human/human missions.txt
Labels: bug

#10099 fix(ci): Add missing codespell excludes for the new version
  .codespell.exclude
Labels: cd/ci/testing

#10078 0.10.7 docs update
  .codespell.exclude
  changelog
  copyright
  credits.txt
  endless-sky.6
  io.github.endless_sky.endless_sky.appdata.xml
  source/main.cpp
Labels: documentation

#10102 fix: steam workflow is missing libmad0-dev library
  changelog
  io.github.endless_sky.endless_sky.appdata.xml
  steam/docker-compose.yml
Labels: bug, cd/ci/testing

#10098 (fix)content: Fix sentence fragment in Stormhold description
  data/map planets.txt
Labels: text - short, typo

#10097 fix(content): Shorten Darkrest's description to better fit description box
  data/map planets.txt
Labels: bug, text - short

#10107 fix(content): Typo in new mereti missions
  data/wanderer/wanderer missions.txt
Labels: typo

#10096 fix(style): Replace duplicated words with weights in phrases
  data/hai/hai reveal news.txt
  data/human/deep jobs.txt
  data/human/hails.txt
  data/kahet/kahet.txt
  data/persons.txt
  data/pug/pug.txt
  data/wanderer/wanderers.txt
Labels: typo

#10100 fix(content): Prevent the Pact Recon missions from offering right after each other
  data/human/free worlds 0 prologue.txt
Labels: bug

#10112 feat(balance): Divide `relative heat damage` by 1.5, for consistency with #9616
  data/hazards.txt
Labels: balance

#10119 Typo fix in "archaeology missions.txt"
  data/sheragi/archaeology missions.txt
Labels: typo
