Repository endless-sky/endless-sky, pull requests merged in 2024-03, with the labels that each got.

#9770 feat(content): Hogshead's Dilemma
  data/human/human missions.txt
Labels: content, text - short

#9875 Add missing indent to Mafia Extortion mission
  data/human/human missions.txt
Labels: typo

#9883 fix(ui): Don't draw name tooltips for ships hidden under the shop sidebar footer
  source/ShopPanel.cpp
Labels: bug

#9790 (content): Add darker mood Coalition culture conversations
  data/coalition/coalition culture conversations.txt
Labels: content, text - short

#9842 Style: Some minor changes in armament
  source/Armament.cpp
  source/Armament.h
Labels: refactor

#9769 feat(content): Add new human merchant hails about mining asteroids
  data/human/hails.txt
Labels: content, text - short

#9889 fix(content): Fix overlapping stars in Umbral system
  data/map systems.txt
Labels: bug, content

#9743 Revert the buff to `energy capacity` that the Wanderer Sun reactors recieved in #6783 and nerf the energy generation of Wanderer biochemical cells
  data/wanderer/wanderer outfits.txt
Labels: balance

#9714 NPC scan and surveillance personality behavior changes
  source/AI.cpp
  source/AI.h
Labels: balance, mechanics

#9897 fix(bug): Apply display name of base ship models to variants
  source/Ship.cpp
Labels: bug

#9908 fix: Fix plural `ships` in messages when recalling/deploying a single ship
  source/AI.cpp
Labels: bug

#9853 fix(copyright): Fix errors in the copyright file
  copyright
Labels: documentation

#9907 Fix 'ambiguous name' compilation error using clang
  source/Audio.cpp
Labels: cd/ci/testing

#8816 feat(enhancement): Hide unknown system names in the escort HUD
  source/Engine.cpp
  source/EscortDisplay.cpp
  source/EscortDisplay.h
  source/PlayerInfoPanel.cpp
Labels: enhancement

#9913 feat(ui): Allow multiple pages of controls
  data/_ui/interfaces.txt
  source/PreferencesPanel.cpp
  source/PreferencesPanel.h
Labels: UI

#9915 fix(CI): Don't check for leading/trailing spaces in substitutions defined in missions
  utils/contentStyle.json
Labels: bug, cd/ci/testing

#8095 build(IDE): Support CodeBlocks no longer stand-alone, but only through CMake
  .github/path-filters.yml
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
  EndlessSky.cbp
  EndlessSky.workspace
  EndlessSkyLib.cbp
  EndlessSkyTests.cbp
  README.md
  docs/readme-developer.md
  utils/check_codeblocks.sh
Labels: cd/ci/testing

#9919 Bugfix: give Cruiser in `FWC Cebalrai 1B` Combat Drones instead of Lances.
  data/human/free worlds 3 checkmate.txt
Labels: bug

#9905 fix(mechanics): Fix ship parenting on takeoff with fighter flagship
  source/PlayerInfo.cpp
Labels: bug

#9882 feat(CI): Expand copyright checks
  .github/workflows/projects_check.yml
Labels: cd/ci/testing

#6928 Refactor: General purpose TaskQueue instead of SpriteQueue.
  source/CMakeLists.txt
  source/CollisionSet.h
  source/Engine.cpp
  source/Engine.h
  source/GameData.cpp
  source/GameData.h
  source/GameLoadingPanel.cpp
  source/GameLoadingPanel.h
  source/PlanetPanel.cpp
  source/SpriteQueue.cpp
  source/SpriteQueue.h
  source/SpriteSet.h
  source/TaskQueue.cpp
  source/TaskQueue.h
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  source/main.cpp
Labels: refactor

#9901 refactor(content): Refactor the Argosy Hijacking mission
  data/governments.txt
  data/human/human missions.txt
Labels: content, refactor

#8798 feat(ui): Conditions to word-form numbers in conversations
  source/text/Format.cpp
  source/text/Format.h
  tests/unit/src/text/test_format.cpp
Labels: enhancement

#9760 feat(mechanics): Make stray projectiles not hit disabled fighters
  source/AI.cpp
  source/CollisionSet.cpp
  source/CollisionSet.h
  source/Engine.cpp
  source/Projectile.cpp
  source/Projectile.h
Labels: balance, mechanics

#9771 feat(mechanics): Separate delayed and non-delayed shield generation and hull repair attributes
  data/_ui/tooltips.txt
  data/kahet/kahet outfits.txt
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
  source/ShipInfoDisplay.cpp
Labels: mechanics

#9910 feat(ui): A help message for managing multiple ships in the outfitter
  data/_ui/help.txt
  source/OutfitterPanel.cpp
  source/OutfitterPanel.h
  source/ShopPanel.cpp
  tests/integration/config/preferences.txt
Labels: enhancement

#9872 [Content] Create more passenger jobs requiring keystones in Hai space
  data/hai/hai jobs.txt
Labels: content

#9929 fix(ui): Correctly handle arrow keys with no item selected in the shop
  source/ShopPanel.cpp
Labels: bug, UI

#9757 Small tweaks to the Unfettered Jump Drive Trading missions + move the transport hai child mission
  data/hai/unfettered 0 prologue.txt
  data/hai/unfettered side missions.txt
Labels: content, text - short

#9932 fix(content): split off "CCOR Logistics" fleet from Large CCOR fleet
  data/human/fleets.txt
  data/map systems.txt
Labels: bug, content

#9922 Fix plugin checkbox click zones
  source/PreferencesPanel.cpp
Labels: bug

#9921 Fix mission distance calculation with distance calculation settings
  source/Mission.cpp
Labels: bug

#9928 [Content] Add some more human news referring to Korath attacks in the core
  data/human/news.txt
Labels: content, text - short

#9941 Fix various crashes when loading/unloading images
  source/Engine.cpp
  source/GameData.cpp
  source/PlanetPanel.cpp
  source/TaskQueue.cpp
  source/TaskQueue.h
  source/main.cpp
Labels: bug

#9946 Fix custom port button name when using "add port"
  source/Port.cpp
Labels: bug

#9944 feat(content): Juggle around some South and Pirate outfitter sales
  data/human/free worlds 4 epilogue.txt
  data/human/sales.txt
  data/map planets.txt
Labels: content

#9936 fix(content): Allow quantum keystone jobs to offer properly
  data/hai/hai jobs.txt
Labels: bug

#9942 "fast" mode for flagship and target images in the HUD
  data/_ui/interfaces.txt
  data/_ui/tooltips.txt
  source/Engine.cpp
  source/Preferences.cpp
  source/PreferencesPanel.cpp
Labels: enhancement, UI

#9939 fix(content): Replace `Kraz Basics` and `Delta V Basics` with `Syndicate Basics` and `Lovelace Basics` on New China, and replace the Militia defense fleet with a Republic defense fleet on Geyser
  data/map planets.txt
Labels: bug

#9900 Yet Another Copyright Fix PR
  copyright
Labels: documentation

#9943 Rotate interface images
  source/Interface.cpp
  source/SpriteShader.cpp
  source/SpriteShader.h
Labels: enhancement, UI

#9947 feat(Balance): Cut the asteroid scanner's price in half
  data/human/outfits.txt
Labels: balance

#9937 feat(content): Conspiracy theorist spaceport news
  data/human/news.txt
Labels: content, text - short

#9945 ci: Run CI workflows when their configuration file is changed
  .github/path-filters.yml
  .github/workflows/ci.yml
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
Labels: cd/ci/testing

#9938 feat(content): Add logbook entries for Alastair Korban
  data/human/free worlds 3 reconciliation.txt
Labels: content, text - short

#9954 Fix government reputation error when loading data files
  source/Government.cpp
Labels: bug

#9916 feat(enhancement): Hotkey for toggling turret tracking mode
  data/_ui/tooltips.txt
  source/Command.cpp
  source/Command.h
  source/MainPanel.cpp
  source/PreferencesPanel.cpp
Labels: enhancement

#9955 fix(typo): Replace two mentions of "Burthensider" with "Burthenian"
  data/human/culture conversations.txt
Labels: typo
