Repository endless-sky/endless-sky, pull requests merged in 2025-09, with the labels that each got.

#11673 ui: Use dark theme on Windows
  source/GameWindow.cpp
Labels: UI

#11267 feat(content): Lost Racer mission chain
  copyright
  data/human/human missions.txt
  data/map planets.txt
  data/map systems.txt
  images/scene/flivver crash.png
  images/ship/racing flivver.png
  images/thumbnail/racing flivver.png
Labels: content, artwork, text - long

#11626 Remove unused icon setting code
  .github/workflows/cd_release.yaml
  icon.png
  source/GameWindow.cpp
  source/GameWindow.h
Labels: refactor

#10854 New implementation of the hold fire command
  data/_ui/tooltips.txt
  keys.txt
  source/AI.cpp
  source/Command.cpp
  source/Command.h
  source/PreferencesPanel.cpp
  source/orders/OrderSet.cpp
  source/orders/Orders.h
Labels: enhancement

#11664 feat(audio): Add FLAC support for music playback
  CMakeLists.txt
  docs/readme-developer.md
  source/CMakeLists.txt
  source/audio/Music.cpp
  source/audio/Music.h
  source/audio/supplier/AsyncAudioSupplier.cpp
  source/audio/supplier/AsyncAudioSupplier.h
  source/audio/supplier/FlacSupplier.cpp
  source/audio/supplier/FlacSupplier.h
  source/audio/supplier/Mp3Supplier.cpp
  source/audio/supplier/Mp3Supplier.h
  vcpkg.json
Labels: enhancement, sound

#10391 feat(enhancement): Add support for AVIF and image sequences
  CMakeLists.txt
  docs/readme-developer.md
  source/image/ImageBuffer.cpp
  source/image/ImageBuffer.h
  source/image/ImageSet.cpp
  vcpkg.json
Labels: enhancement, artwork

#11627 refactor(timers): Various fixes for timers on Windows
  CMakeLists.txt
  source/CMakeLists.txt
  source/FrameTimer.cpp
  source/main.cpp
  source/windows/TimerResolutionGuard.cpp
  source/windows/TimerResolutionGuard.h
  source/windows/WinApp.rc
Labels: bug, refactor

#11741 Only have one Quarg ship to scan in Remnant Expanded Horizons
  data/remnant/remnant 1 introduction.txt
Labels: bug

#11758 fix(bug): Lost Racer bug fix
  data/human/human missions.txt
Labels: bug

#11746 fix: Change openal-soft version to 1.23.1
  CMakePresets.json
  overlays/macos-arm64-ci.cmake
  overlays/macos-arm64-release.cmake
  overlays/macos64-ci.cmake
  overlays/macos64-release.cmake
  vcpkg.json
Labels: bug, cd/ci/testing

#11757 Fix Remnant Research Expedition jobs again
  data/map beyond patir.txt
  data/remnant/remnant jobs.txt
Labels: bug

#11264 feat(content): Ka'het: Voice From The Past
  copyright
  data/kahet/kahet missions.txt
  images/ship/builder satellite.png
Labels: content, artwork, text - long

#11743 fix(audio): Increase bit rate of `explosion huge.wav` to 705kbps
  sounds/explosion huge.wav
  sounds/explosion huge@3x.wav
Labels: bug, sound

#11770 fix(mechanics): Make it possible to clear "hold position" orders by pressing the key again
  source/orders/OrderSet.cpp
Labels: bug, mechanics

#11728 refactor: Make reverse thrust work properly
  source/AI.cpp
  source/Ship.cpp
  source/Ship.h
Labels: bug, mechanics, refactor

#11769 code checker catch bad structured bindings
  utils/check_code_style.py
Labels: cd/ci/testing, style

#11781 Fix the map not recentring about the mouse pointer when zooming by scrolling
  source/MapPanel.cpp
Labels: bug, UI
