Repository endless-sky/endless-sky, pull requests merged in 2025-05, with the labels that each got.

#11377 Fix improper click handling in the mission panel sometimes
  source/TextArea.cpp
Labels: bug, UI

#11383 fix(conditions): Replace manual memory management
  source/ConditionEntry.cpp
  source/ConditionEntry.h
  source/ConditionsStore.cpp
  source/ConditionsStore.h
  source/PlayerInfo.cpp
Labels: bug

#11379 fix(ui): Fix dialog flickering
  source/TextArea.cpp
Labels: bug, UI

#11380 fix(ui): Fully clear the jump fuel attribute
  source/Dictionary.cpp
  source/Dictionary.h
  source/Outfit.cpp
Labels: bug, UI

#11360 feat(news): Prevent add on News children that don't actually add
  source/News.cpp
Labels: enhancement

#11394 Symlink compilation database to build for LSP discoverability
  CMakeLists.txt
Labels: cd/ci/testing

#11396 Repricing Navy Combat Drone
  data/human/ships.txt
Labels: balance

#11392 refactor(strings): replace uses of std::string::compare with starts_with or ends_with
  source/ConditionsStore.cpp
  source/GameData.cpp
  source/OutfitterPanel.cpp
  source/System.cpp
  source/image/ImageSet.cpp
  source/image/SpriteSet.cpp
  tests/unit/src/test_conditionsStore.cpp
Labels: refactor, waiting on dev

#11405 fix(mechanics): Update fleet cargo cache on auto unpark
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: bug, mechanics

#11381 feat(build): Use external pkgconf only when needed
  CMakeLists.txt
  docs/readme-developer.md
Labels: enhancement, documentation

#11390 Don't constantly refresh engine sounds while paused
  source/Engine.cpp
Labels: bug, sound

#11391 Fix sounds resuming when switching map panel modes
  source/MapDetailPanel.cpp
  source/MapSalesPanel.cpp
  source/MissionPanel.cpp
Labels: bug, sound

#11365 feat(ci): Check OpenGL shader conformance
  .github/path-filters.yml
  .github/workflows/compute-changes.yml
  .github/workflows/projects_check.yml
  utils/check_shaders.sh
Labels: cd/ci/testing

#11291 fix(bug) Timothy Fix
  data/human/human missions.txt
Labels: bug, typo, waiting on dev

#11185 [Map] Adjust labels for the Ember Waste, Graveyard, and Tangled Shroud
  data/map systems.txt
  images/label/graveyard+.png
  images/label/tangled shroud+.png
  images/label/waste+.png
Labels: artwork

#11408 fix(typo) : Fixes several typos
  CMakeLists.txt
  source/DistanceMap.cpp
  source/GameAction.cpp
  source/MissionAction.cpp
  source/MissionAction.h
  source/PlayerInfo.cpp
  source/Projectile.cpp
  source/TaskQueue.h
  tests/integration/config/plugins/integration-tests/data/tests/tests_conditional_choice.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_hyperjumps_to_autocondition.txt
  tests/unit/src/test_categoryList.cpp
  tests/unit/src/test_conditionsStore.cpp
Labels: typo

#11409 Replace the "weekday" number condition with a "weekday: <day>" true/false condition
  source/Date.cpp
  source/Date.h
  source/PlayerInfo.cpp
Labels: refactor

#11410 fix(typo): Fix a couple more typos
  shaders/line.frag
  source/PlayerInfo.cpp
Labels: typo

#11404 Added test for account.AddMortgage
  tests/unit/src/test_account.cpp
Labels: cd/ci/testing

#11407 fix(ui): Update planet labels if the planet's data has changed
  source/Engine.cpp
  source/PlanetLabel.cpp
  source/PlanetLabel.h
Labels: bug, UI

#10508 feat(mechanics): Support for turret blindspots
  data/_ui/interfaces.txt
  data/_ui/tooltips.txt
  source/Engine.cpp
  source/Engine.h
  source/Hardpoint.cpp
  source/Hardpoint.h
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
  source/Ship.cpp
Labels: enhancement, mechanics

#11422 Specify Venta gun hardpoints to be symmetric
  data/incipias/incipias ships.txt
Labels: content

#11423 feat(content): Syndicate Business minor tweaks and bugfix
  data/human/human missions.txt
Labels: bug, content

#11427 fix(ui): More specific reasons for being unable to land
  data/_ui/landing messages.txt
  source/System.cpp
Labels: bug, UI

#11428 Refactor load functions to use `key` and `hasValue` variables
  source/Account.cpp
  source/Body.cpp
  source/CargoHold.cpp
  source/ConditionAssignments.cpp
  source/ConditionSet.cpp
  source/ConditionsStore.cpp
  source/Conversation.cpp
  source/Effect.cpp
  source/Fleet.cpp
  source/FleetCargo.cpp
  source/FormationPattern.cpp
  source/GameAction.cpp
  source/GameData.cpp
  source/GameEvent.cpp
  source/Government.cpp
  source/Interface.cpp
  source/LocationFilter.cpp
  source/Mission.cpp
  source/MissionAction.cpp
  source/Mortgage.cpp
  source/NPC.cpp
  source/Phrase.cpp
  source/Planet.cpp
  source/PlayerInfo.cpp
  source/Plugins.cpp
  source/Port.cpp
  source/Preferences.cpp
  source/PrintData.cpp
  source/Sale.h
  source/SavedGame.cpp
  source/Ship.cpp
  source/ShipManager.cpp
  source/System.cpp
  source/Trade.cpp
  source/UniverseObjects.cpp
  source/Weapon.cpp
  source/test/Test.cpp
  source/test/TestData.cpp
Labels: style

#8621 Feat(mechanics): Reviving NPC Travel Instructions (Part 1)
  source/AI.cpp
  source/AI.h
  source/Engine.cpp
  source/Mission.cpp
  source/NPC.cpp
  source/NPC.h
  source/PlayerInfo.cpp
  source/Ship.cpp
  source/Ship.h
  source/ShipEvent.h
  tests/CMakeLists.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_npc_destination.txt
Labels: enhancement, waiting on dev

#11345 feat(ui): Prevent absurd starfield zoom levels + add a preference for having a fixed starfield zoom
  data/_ui/interfaces.txt
  data/_ui/tooltips.txt
  source/ConditionsStore.cpp
  source/Engine.cpp
  source/GameData.cpp
  source/GameData.h
  source/GameLoadingPanel.cpp
  source/LoadPanel.cpp
  source/MenuPanel.cpp
  source/PreferencesPanel.cpp
  source/StartConditionsPanel.cpp
  source/shader/StarField.cpp
  source/shader/StarField.h
Labels: waiting on reviewer, UI

#11433 fix(ui): Stop starfield movement when the engine is inactive
  source/Engine.cpp
Labels: bug

#11437 fix(content): Add missing "distance 4 8" to Hai job
  data/hai/hai jobs.txt
Labels: bug, content

#11417 Remove Nerve Gas from Pirates' Basic Outfitter
  data/human/sales.txt
Labels: balance, content

#11425 feat(content): Red Colored Pirate Jobs & Pirate Job Counter
  data/human/pirate jobs.txt
Labels: content

#11373 feat(content): New descriptions for Remnant and Wanderer Licenses
  data/remnant/remnant outfits.txt
  data/wanderer/wanderer outfits.txt
Labels: content, text - short

#11371 feat(enhancement): Generalize font shader
  shaders/font.vert
  source/text/Font.cpp
  source/text/Font.h
Labels: bug, enhancement, UI

#11367 Allow LocationFilters to filter on whether a planet/system has been visited
  source/GameData.cpp
  source/GameData.h
  source/Government.cpp
  source/Government.h
  source/LocationFilter.cpp
  source/LocationFilter.h
  source/Mission.cpp
  source/Mission.h
  source/MissionAction.cpp
  source/MissionAction.h
  source/NPC.cpp
  source/NPC.h
  source/NPCAction.cpp
  source/NPCAction.h
  source/News.cpp
  source/News.h
  source/Person.cpp
  source/Person.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/PrintData.cpp
  source/PrintData.h
  source/Shop.h
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  source/main.cpp
  source/test/Test.cpp
  source/test/TestData.cpp
  source/test/TestData.h
Labels: enhancement

#11411 Create attributes for multiplying shield generation/hull repair while cloaked
  data/_ui/tooltips.txt
  source/Outfit.cpp
  source/OutfitInfoDisplay.cpp
  source/Ship.cpp
Labels: enhancement

#11416 Don't check the offer location when filtering non-priority missions
  data/human/campaign events.txt
  source/Mission.cpp
  source/Mission.h
  source/PlayerInfo.cpp
Labels: bug, mechanics, to be merged

#11435 feat(ui): Animate the main menu background stars and haze
  data/_ui/interfaces.txt
  data/_ui/tooltips.txt
  source/MenuPanel.cpp
  source/MenuPanel.h
  source/Preferences.cpp
  source/PreferencesPanel.cpp
Labels: UI

#11419 Create conditional outfitters for restocking most secondary weapons
  data/avgi/avgi weapons.txt
  data/bunrodea/bunrodea weapons.txt
  data/coalition/coalition weapons.txt
  data/hai/hai outfits.txt
  data/human/weapons.txt
  data/incipias/incipias outfits.txt
  data/kahet/kahet outfits.txt
  data/korath/korath weapons.txt
  data/remnant/remnant outfits.txt
  data/rulei/rulei outfits.txt
  data/successors/successor weapons.txt
  data/wanderer/wanderer outfits.txt
Labels: balance, content

#11343 Differentiate cloaking abilities from differing sources
  data/bunrodea/bunrodea ships.txt
  data/drak/drak ships.txt
  data/drak/indigenous.txt
  data/human/outfits.txt
  data/remnant/remnant ships.txt
Labels: balance

#11388 Add an "entering" mission location tag for offering missions after jumping or taking off
  source/Engine.cpp
  source/MainPanel.cpp
  source/Mission.cpp
  source/Mission.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: enhancement

#11130 feat(ui): Add sound effects to the UI
  sounds/ui/buzz soft.wav
  sounds/ui/click soft.wav
  sounds/ui/click.wav
  sounds/ui/fail.wav
  sounds/ui/target.wav
  source/AI.cpp
  source/ConversationPanel.cpp
  source/Engine.cpp
  source/HailPanel.cpp
  source/HiringPanel.cpp
  source/LoadPanel.cpp
  source/LogbookPanel.cpp
  source/MapPanel.cpp
  source/MapSalesPanel.cpp
  source/MenuPanel.cpp
  source/MissionPanel.cpp
  source/PlanetPanel.cpp
  source/PlayerInfo.cpp
  source/ShopPanel.cpp
  source/StartConditionsPanel.cpp
  source/UI.cpp
  source/UI.h
  source/main.cpp
Labels: sound, UI

#11451 fix(typo): Misspelling of "Berserker" in Jackal description
  data/human/ships.txt
Labels: typo

#11460 fix(mechanics): Correct field bounds calculation for fancy parallax
  source/shader/StarField.cpp
Labels: bug, waiting on dev

#11461 fix(typo): Abberant to Aberrant
  data/avgi/avgi 0 first contact.txt
Labels: typo

#11464 Patir 2 corrections
  data/kahet/kahet missions.txt
Labels: bug

#11463 Lower Patir 2 gravities across the board
  data/map beyond patir.txt
Labels: balance, content

#11467 feat(mechanics): Allow extended jump effects to function independent of motion blur
  source/Engine.cpp
Labels: UI

#11462 fix(ui): Fix camera acceleration/starfield movement/motion blur breaking under certain circumstances
  source/CMakeLists.txt
  source/Camera.cpp
  source/Camera.h
  source/Engine.cpp
  source/Engine.h
Labels: bug

#11348 fix(mechanics): Fix cases where the AI could try to cloak and recover in circumstances where that isn't possible
  source/AI.cpp
Labels: bug, mechanics

#11465 feat(ui): Adjust the starfield behavior and menu animation
  data/_ui/interfaces.txt
  source/Engine.cpp
  source/GameData.cpp
  source/GameData.h
  source/MenuPanel.cpp
  source/MenuPanel.h
  source/shader/StarField.cpp
  source/shader/StarField.h
Labels: UI

#11476 feat(ui): Warn the player if their ship is too cold to use their engines
  data/_ui/tooltips.txt
  source/Ship.cpp
Labels: UI, to be merged

#11474 0.10.13 docs update
  changelog
  credits.txt
  endless-sky.6
  io.github.endless_sky.endless_sky.appdata.xml
  source/main.cpp
Labels: documentation
