Repository endless-sky/endless-sky, pull requests merged in 2025-03, with the labels that each got.

#9986 feat(data): Creating Unclassified and Unclassified Minor Categories
  data/avgi/windjammers.txt
  data/categories.txt
  data/drak/drak ships.txt
  data/drak/indigenous.txt
  data/human/human missions.txt
  data/iije/iije.txt
  data/incipias/tace mesa.txt
  data/korath/nanobots.txt
  data/persons.txt
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant jobs.txt
  data/rulei/rulei ships.txt
  data/sheragi/archaeology missions.txt
  data/vyrmeid/vyrmeid.txt
  data/whispering void/critters.txt
Labels: content

#11086 Allow direct execution of utils/check_code_style.py
  utils/check_code_style.py
Labels: cd/ci/testing

#11038 feat(balance): Adjust fleet sizes and balance in various Free Worlds combat missions
  data/human/free worlds 0 prologue.txt
  data/human/free worlds 1 start.txt
  data/human/free worlds 2 middle.txt
  data/human/free worlds 3 checkmate.txt
Labels: balance

#11093 feat(balance): Remove Unnecessary Carrier Outfit Expansions post-rework
  data/human/variants.txt
Labels: balance

#11098 Remnant typo fixes
  data/remnant/remnant 2 cognizance.txt
Labels: typo

#11115 feat(fix): Revised wording in Remnant Cognizance 2 that were mis-interpreted.
  data/remnant/remnant 2 cognizance.txt
Labels: typo

#11090 fix(code): Fix a misplaced bracket in AI::MoveToAttack
  source/AI.cpp
Labels: bug

#11076 fix(style): Minor code style fixes and cleanup for conditions
  source/ConditionAssignments.cpp
  source/ConditionAssignments.h
  source/ConditionSet.cpp
  source/ConditionSet.h
Labels: style

#11079 feat(error-handling): Include image name and frame number in collision mask error message
  source/image/ImageSet.cpp
  source/image/Mask.cpp
  source/image/Mask.h
Labels: enhancement

#11106 Ildico Save Compatibility Patch
  data/human/deep missions.txt
  data/human/human missions.txt
Labels: bug

#11112 feat(artwork): Brighten Selected Outfit Background
  images/ui/outfitter selected+.png
Labels: artwork

#11103 Add "blocked" dialog to incipias first contact.txt
  data/incipias/incipias first contact.txt
Labels: bug

#11099 fix(bug): add missing passenger to Remnant: Cognizance 21
  data/remnant/remnant 2 cognizance.txt
Labels: bug

#11088 Update `Argosy Hijacking` `on offer` conditions
  data/human/human missions.txt
Labels: bug

#11083 fix(bug): remove duplicate log entry in mission `Boarding Ka'het`
  data/kahet/kahet missions.txt
Labels: bug

#11024 fix(content): Make the Coalition Intros easier to find
  data/coalition/heliarch intro.txt
  data/coalition/lunarium intro.txt
Labels: content

#11020 feat(balance): Make the first pug fight in checkmate less absurdly difficult
  data/human/free worlds 3 checkmate.txt
Labels: balance

#11094 Timothy Fix
  data/human/human missions.txt
Labels: bug, typo

#11118 feat(content): Show Arachi Cartoonist Your Leviathan
  data/coalition/coalition missions.txt
Labels: content, waiting on dev

#11123 fix(bug): fix Kasii-Tuur-Saqru overlapping its mother planet
  data/map systems.txt
Labels: bug

#11116 `Damselflyman Abilities` fixes
  data/avgi/avgi side missions.txt
Labels: bug

#11091 fix(jobs-code): Allow jobs to fail themselves on offer or accept
  source/PlayerInfo.cpp
Labels: enhancement

#11105 Successor, Avgi afterburners zoom with engine scale
  data/avgi/avgi outfits.txt
  data/successors/successor outfits.txt
Labels: artwork

#11117 `cloaked <attribute>` description updates
  source/OutfitInfoDisplay.cpp
Labels: typo

#11125 feat(content): Create and use `colour "governments: Quarg"`
  data/governments.txt
Labels: content, refactor

#11126 fix(ci): Rename editorconfig-checker's config file
  .ecrc
  .editorconfig-checker.json
Labels: cd/ci/testing

#11070 feat(build): CMake only, remove Scons completely
  README.md
  SConstruct
  docs/readme-cmake.md
  docs/readme-developer.md
Labels: enhancement, documentation

#10997 fix(mechanics): Fix blast damage not affecting minables
  source/AsteroidField.cpp
  source/AsteroidField.h
  source/CMakeLists.txt
  source/DamageProfile.cpp
  source/DamageProfile.h
  source/Engine.cpp
  source/Minable.cpp
  source/Minable.h
  source/MinableDamageDealt.h
Labels: bug, mechanics

#10993 feat(mechanics): Turret turn multipliers
  data/_ui/tooltips.txt
  source/AI.cpp
  source/Armament.cpp
  source/Armament.h
  source/Hardpoint.cpp
  source/Hardpoint.h
  source/Outfit.cpp
  source/Ship.cpp
Labels: enhancement

#11078 Fix adding minables and asteroids error detection and reporting
  source/System.cpp
Labels: bug

#10629 Organize all outfits using series
  data/avgi/avgi outfits.txt
  data/avgi/avgi weapons.txt
  data/avgi/windjammers.txt
  data/bunrodea/bunrodea outfits.txt
  data/bunrodea/bunrodea weapons.txt
  data/coalition/coalition outfits.txt
  data/coalition/coalition weapons.txt
  data/drak/drak outfits.txt
  data/drak/indigenous.txt
  data/gegno/gegno outfits.txt
  data/hai/hai outfits.txt
  data/human/engines.txt
  data/human/outfits.txt
  data/human/power.txt
  data/human/weapons.txt
  data/incipias/incipias outfits.txt
  data/kahet/aberrant outfits.txt
  data/kahet/kahet outfits.txt
  data/korath/korath outfits.txt
  data/korath/korath weapons.txt
  data/korath/nanobots.txt
  data/pug/pug outfits.txt
  data/quarg/quarg outfits.txt
  data/remnant/remnant outfits.txt
  data/rulei/rulei outfits.txt
  data/series.txt
  data/sheragi/sheragi outfits.txt
  data/successors/successor outfits.txt
  data/successors/successor weapons.txt
  data/vyrmeid/vyrmeid.txt
  data/wanderer/wanderer outfits.txt
  data/whispering void/critters.txt
Labels: content, UI

#10936 Print an error if a system attempts to link to itself
  source/System.cpp
Labels: cd/ci/testing, to be merged, waiting on dev

#10999 feat(content): Some Gegno content adjustments
  data/gegno/gegno I corroboration.txt
  data/gegno/gegno fleets.txt
  data/gegno/gegno intro missions.txt
  data/gegno/gegno ships.txt
Labels: content, waiting on dev

#11132 fix(load/ui): Use display names for systems and planets in the load panel
  source/SavedGame.cpp
Labels: bug, UI, waiting on dev

#11146 fix(bug): hardcode the planet name in `Stones of Skadenga 3`
  data/human/deep missions.txt
Labels: bug

#11148 fix(bug): standardize use of Radrickson
  data/human/human missions.txt
Labels: typo

#11096 content: FW Embassy 1B: better ambassadorial explanation
  data/human/free worlds 3 reconciliation.txt
Labels: content

#11082 Ice Queen 6: Use feminine spelling for Ildico's mother
  data/human/human missions.txt
Labels: typo

#11101 feat(content): Culture Conversation for native life on Glaze
  data/human/culture conversations.txt
Labels: content

#10996 feat(content): Adding unique Coalition commodities
  data/coalition/coalition jobs.txt
  data/coalition/coalition.txt
Labels: content

#11109 feat(content): Culture Conversations for the Delvan Shipworm
  data/human/culture conversations.txt
Labels: content

#11154 fix(style): fix overindentation in Cap'n Pester's definition
  data/persons.txt
Labels: style

#11153 feat(content): Avgi Culture: Fencing
  data/avgi/avgi culture conversations.txt
Labels: content, waiting on dev

#10368 feat(ui): New interface elements using WrappedText
  source/Interface.cpp
  source/Interface.h
Labels: enhancement, waiting on reviewer, UI

#11122 fix(content): Aberrant take overheat damage
  data/kahet/aberrant ships.txt
  data/kahet/kahet ships.txt
Labels: bug

#11137 docs: Add alternative linker instructions and remove old scons related file
  .winmake
  docs/readme-developer.md
Labels: documentation

#10962 Bring back the Windows x86 release CD job
  .github/workflows/cd_release.yaml
  CMakePresets.json
Labels: cd/ci/testing

#11168 fix(bug) Fix resource directory not being found on linux
  source/Files.cpp
Labels: bug, waiting on dev

#11087 feat(content): Adding a Multilingual Culture Conversation to New Austria
  .codespell.exclude
  data/human/culture conversations.txt
Labels: content, text - short

#11183 Refactor: Increase const correctness of reference parameters and member functions
  source/AI.cpp
  source/AI.h
  source/CategoryList.h
  source/ConditionSet.cpp
  source/ConditionsStore.cpp
  source/ConditionsStore.h
  source/DataWriter.cpp
  source/DataWriter.h
  source/Engine.cpp
  source/Engine.h
  source/Fleet.cpp
  source/Fleet.h
  source/FormationPattern.cpp
  source/FormationPattern.h
  source/MissionPanel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfoPanel.cpp
  source/Ship.cpp
  source/System.cpp
  source/System.h
  source/audio/Sound.cpp
  source/comparators/BySeriesAndIndex.h
  source/image/ImageSet.cpp
Labels: refactor, style

#11176 feat(style): Force tab-indents in CMakeLists
  .editorconfig
Labels: style

#11181 Aberrant first contact edits
  data/kahet/aberrant missions.txt
Labels: content

#11134 feat: Gradient in the LineShader
  source/Interface.cpp
  source/Interface.h
  source/shader/LineShader.cpp
  source/shader/LineShader.h
Labels: enhancement, UI, waiting on dev

#11180 fix(bug): add a description to `Timothy Radrickson 3c: Escort the Convoy`
  data/human/human missions.txt
Labels: bug

#11178 fix(content): Refer to `the <ship>` instead of just `<ship>` in `"Hai Wormhole Warning"`
  data/human/human missions.txt
Labels: content, waiting on dev, style

#11145 feat(content): Several Successor culture conversations
  data/successors/successor culture conversations.txt
Labels: content

#10393 Adding New Syndicate Business Missions
  copyright
  data/human/human missions.txt
  images/ship/escape shuttle.png
Labels: content, text - long

#10422 feat(content): Part 2 of Adding New Syndicate Business Missions
  data/human/human missions.txt
Labels: content, text - long

#11193 fix(content): Have `Timmy Radrickson 1` describe how you entered the system before detecting Timmy
  data/human/human missions.txt
Labels: bug, content

#11165 ui: Fix off-by-one index on boarding panel
  source/BoardingPanel.cpp
Labels: UI

#11133 [Bugfix] Fix `on enter` popup in Avgi First Contact 1
  data/avgi/avgi 0 first contact.txt
Labels: bug, waiting on dev

#11141 Use PlayerInfo::AddPlayerSubstitutions method more widely
  source/ConversationPanel.cpp
  source/Mission.cpp
  source/MissionAction.cpp
Labels: refactor, waiting on dev

#11081 Ka'het and Aberrant attitude updates
  data/governments.txt
Labels: bug, waiting on dev

#11140 feat(news): Use global and player substitutions in news messages
  source/SpaceportPanel.cpp
Labels: enhancement, waiting on dev

#11077 ui: Clipboard refactor and enhancements
  source/CMakeLists.txt
  source/ConversationPanel.cpp
  source/Dialog.cpp
  source/text/Clipboard.cpp
  source/text/Clipboard.h
Labels: enhancement, refactor, UI

#11164 feat(ui): Display the reason when you can't plunder
  source/BoardingPanel.cpp
  source/BoardingPanel.h
Labels: enhancement, UI, waiting on dev

#11198 Timothy Radrickson 5: Oblivion Meeting: simplify and fix
  data/human/human missions.txt
Labels: bug, typo

#11174 fix(content): Block more human space jobs from offering without landing access or in pirate space
  data/human/deep jobs.txt
  data/human/far north jobs.txt
  data/human/near earth jobs.txt
  data/human/paradise world jobs.txt
  data/human/rim jobs.txt
  data/human/south jobs.txt
  data/human/syndicate jobs.txt
Labels: bug, content

#11199 fix(sound): Read 32 and 16 bit sound fragments fully
  source/audio/Sound.cpp
Labels: bug, sound

#11210 feat(content): Adjust the contents of the `Large Core Pirates` fleet
  data/human/fleets.txt
Labels: content

#10557 fix afterburner combat usage
  source/AI.cpp
Labels: balance, mechanics

#11162 tweak(UI): Use the darker background sprite for outfitter display
  source/OutfitterPanel.cpp
Labels: UI

#11142 Allow "--matches" to handle wormholes
  source/PrintData.cpp
  source/StellarObject.cpp
  source/StellarObject.h
Labels: bug

#11143 Differentiate variants in map shipyard
  source/MapOutfitterPanel.cpp
  source/MapSalesPanel.cpp
  source/MapSalesPanel.h
  source/MapShipyardPanel.cpp
  source/Ship.cpp
  source/Ship.h
Labels: enhancement, waiting on OP

#10573 Add outfit attribute to maps to reveal minables
  source/GameAction.cpp
  source/MissionAction.cpp
  source/OutfitInfoDisplay.cpp
  source/OutfitterPanel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/System.cpp
  source/System.h
Labels: enhancement, mechanics

#11120 feat(sound): Unique Sjeja Lance sound effect
  copyright
  data/successors/successor weapons.txt
  sounds/sjeja lance.wav
Labels: sound

#10981 Map planets formatting
  data/map planets.txt
Labels: style

#11179 feat(mechanics): A command for pausing time in the game
  copyright
  data/_ui/tooltips.txt
  images/ui/paused.png
  keys.txt
  source/AI.h
  source/Command.cpp
  source/Command.h
  source/Engine.cpp
  source/Engine.h
  source/PreferencesPanel.cpp
  source/main.cpp
Labels: enhancement

#10693 feat(enhancement): Sounds for out-of-ammo weapons
  source/Engine.cpp
  source/Engine.h
  source/Ship.cpp
  source/Ship.h
  source/Weapon.cpp
  source/Weapon.h
Labels: enhancement, waiting on reviewer, sound

#10917 Use some better default preferences
  source/Preferences.cpp
Labels: UI

#11216 fix(bug): Camera disassociates while paused
  source/Engine.cpp
Labels: bug, mechanics

#11186 feat(content): Quarg Revamp Follow-up Adjustments
  data/quarg/quarg outfits.txt
  data/quarg/quarg.txt
Labels: balance, waiting on dev

#11213 fix(bug): Li-7 star changes
  data/map systems.txt
Labels: bug

#11211 (balance) Nerf Heliarch Ion Weapons
  data/coalition/coalition weapons.txt
Labels: balance

#10956 Content (improvement): check if you need that hyperdrive
  data/hai/unfettered 0 prologue.txt
  data/hai/unfettered jobs.txt
Labels: content

#8784 Feat(content): add Unfettered raids in Unfettered space, Wah Ki and bordering systems
  data/governments.txt
  data/hai/hai fleets.txt
  data/hai/hai ships.txt
  data/map systems.txt
  data/wanderer/wanderers start.txt
Labels: balance, content

#10953 feat(mechanics): Manually aim turret with your mouse
  data/_ui/tooltips.txt
  source/AI.cpp
  source/AI.h
  source/Command.cpp
  source/Command.h
  source/Engine.cpp
  source/PreferencesPanel.cpp
Labels: enhancement

#11215 feat(ci): Add a check for commonly doubled-up words
  data/gegno/gegno events.txt
  data/human/human missions.txt
  data/wanderer/wanderer missions.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_to_accept.txt
  utils/contentStyle.json
Labels: cd/ci/testing, typo

#11188 [Balance] Buff the Sheragi EM Batteries
  data/sheragi/sheragi outfits.txt
Labels: balance

#10276 Wanderers no longer offer amenities before translator
  data/map planets.txt
  data/wanderer/wanderers start.txt
Labels: bug

#11209 Timothy Radrickson wording changes
  data/human/human missions.txt
Labels: typo

#11222 fix(bug): Clear selected ships when landing
  source/Ship.cpp
Labels: bug, UI

#11239 fix(content): Fix remaining shipment jobs from offering on pirate planets
  data/human/paradise world jobs.txt
  data/human/south jobs.txt
Labels: bug

#11233 Fix to Baianus description
  data/map planets.txt
Labels: content, text - short

#10703 Revert the workaround for SSil Vida jump ranges
  data/remnant/remnant events.txt
Labels: content, refactor

#11235 Fix follow-up question display logic in Successors: First Contact 3
  data/successors/successor 1 prologue.txt
Labels: bug, content, waiting on dev

#9019 feat(enhancement): Smoother Thruster Visuals & Non-Uniform Sprite Scaling
  source/Body.cpp
  source/Body.h
  source/Engine.cpp
  source/MapPanel.cpp
  source/Point.cpp
  source/Point.h
  source/Ship.cpp
  source/Ship.h
  source/image/Mask.cpp
  source/image/Mask.h
  source/image/MaskManager.cpp
  source/image/MaskManager.h
  tests/unit/src/test_point.cpp
Labels: enhancement

#10957 Update Katar Fort description in map planets.txt
  data/map planets.txt
Labels: text - short

#11184 feat(artwork): Allow Quarg ships to swizzle and make them do so correctly
  data/governments.txt
  data/quarg/quarg ships.txt
  images/ship/quarg drake.png
  images/ship/quarg guivre.png
  images/ship/quarg hydra.png
  images/ship/quarg lindwyrm.png
  images/ship/quarg wardragon.png
  images/ship/quarg wyvern.png
  images/thumbnail/quarg drake.png
  images/thumbnail/quarg guivre.png
  images/thumbnail/quarg hydra.png
  images/thumbnail/quarg lindwyrm.png
  images/thumbnail/quarg wardragon.png
  images/thumbnail/quarg wyvern.png
Labels: artwork

#11241 Spelling/grammar fixes
  data/avgi/avgi 0 first contact.txt
  data/avgi/avgi side missions.txt
  data/human/post-war reactions.txt
  data/map planets.txt
  data/successors/successor 1 prologue.txt
Labels: typo

#10672 feat(content): Add stats for the Heavy Gust
  data/wanderer/wanderer ships.txt
Labels: balance, content

#10486 feat(mechanics, balance): Rescale optical and IR tracking
  source/Projectile.cpp
Labels: balance, mechanics

#10887 feat(missions): Add an "offer precedence" token to Missions for controlling offer order
  source/Mission.cpp
  source/Mission.h
  source/PlayerInfo.cpp
Labels: enhancement

#11250 fix(ci/cd): Fix libjpeg version on Mac
  .github/workflows/cd.yaml
  vcpkg.json
Labels: cd/ci/testing

#11249 fix(bug): Avgi: Defend Ensemble 1 fix
  data/avgi/avgi 0 first contact.txt
Labels: bug

#11244 feat(content): More Korath hails easter eggs
  data/korath/korath hails.txt
Labels: content

#11247 Revert "fix(graphics): Temporarily reduce scale of Z-3600 to prevent visual impairment"
  data/avgi/avgi outfits.txt
Labels: artwork

#11252 fix(ui): Add a missing message to the help command
  source/ShopPanel.cpp
Labels: UI

#11097 Hai Legacy: tweak according to player feedback
  data/hai/unfettered side missions.txt
Labels: content, text - short

#11089 Remnant: Deep Surveillance updates
  data/remnant/remnant 1 introduction.txt
Labels: text - short, typo

#11219 feat(content): unlock two Hai mission chains
  data/hai/hai missions.txt
Labels: content, waiting on dev

#11234 feat(content): adding an "education" attribute and more jobs
  data/human/campaign events.txt
  data/human/deep jobs.txt
  data/human/jobs.txt
  data/map planets.txt
Labels: content, text - long

#11243 Fix missing player condition and logbook entry in an Incipias mission
  data/incipias/incipias first contact.txt
Labels: bug, content, waiting on dev
