Repository endless-sky/endless-sky, pull requests merged in 2025-04, with the labels that each got.

#11251 feat(ci): Also run CI on overlay changes
  .github/path-filters.yml
  .github/workflows/ci.yml
Labels: cd/ci/testing

#11273 Rebalance Javelin Turret's Turn Rate
  data/human/weapons.txt
Labels: balance

#11261 feat(mechanics): Added 3 optional settings in gamerules.txt,
  data/gamerules.txt
  source/Engine.cpp
  source/Gamerules.cpp
  source/Gamerules.h
  source/System.cpp
Labels: mechanics

#11231 Flip the order of some map scales
  source/MapDetailPanel.cpp
Labels: UI

#11277 Fix typo with FW Pirates Attack 1
  data/human/free worlds 1 start.txt
Labels: typo

#11256 feat: Flagship property (bays, shields, hull, mass) autoconditions
  source/PlayerInfo.cpp
  source/Ship.cpp
  source/Ship.h
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
Labels: enhancement

#11172 feat(content): Variable Swizzles
  data/_ui/swizzles.txt
  source/Body.cpp
  source/Body.h
  source/CMakeLists.txt
  source/Engine.cpp
  source/Engine.h
  source/GameData.cpp
  source/GameData.h
  source/Government.cpp
  source/Government.h
  source/Information.cpp
  source/Information.h
  source/Interface.cpp
  source/MapOutfitterPanel.cpp
  source/MapSalesPanel.cpp
  source/MapSalesPanel.h
  source/MapShipyardPanel.cpp
  source/MapShipyardPanel.h
  source/Ship.cpp
  source/Ship.h
  source/ShipInfoPanel.cpp
  source/ShipyardPanel.cpp
  source/ShopPanel.cpp
  source/Swizzle.cpp
  source/Swizzle.h
  source/System.cpp
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  source/shader/DrawList.cpp
  source/shader/DrawList.h
  source/shader/SpriteShader.cpp
  source/shader/SpriteShader.h
Labels: enhancement, waiting on dev

#11282 fix(bug): remove extra character
  data/avgi/avgi outfits.txt
Labels: bug

#10562 feat[Content] New Flavor Missions for 10M Syndicate Business Mission
  data/human/human missions.txt
Labels: content, text - long, waiting on dev

#10427 fix(content): Improve Moving House 1 mission
  data/human/human missions.txt
Labels: content, waiting on OP, text - short

#11265 feat(content): new generic jobs
  data/human/deep jobs.txt
  data/human/jobs.txt
  data/human/rim jobs.txt
  data/human/syndicate jobs.txt
  data/quarg/quarg missions.txt
Labels: content, text - short

#11227 feat(content): Culture Conversations for a Plant Tour & Cactus
  data/human/culture conversations.txt
Labels: content, text - short

#11284 fix(ci/cd): Correct required CMake version
  CMakeLists.txt
Labels: cd/ci/testing

#11287 Remove spoiler suggesting hyperspace links are fragile
  data/human/free worlds 3 reconciliation.txt
Labels: content

#11299 fix(typo): Missing article in `FW Rogue Elements`
  data/human/free worlds 1 start.txt
Labels: typo, waiting on dev

#11246 feat(content): New multimodal armor type and sprites
  data/_deprecated/deprecated outfits.txt
  data/successors/successor outfits.txt
  data/successors/successor sales.txt
  data/successors/successor ships.txt
  data/successors/successor variants.txt
  images/outfit/successor armor heavy.png
  images/outfit/successor armor keystone.png
  images/outfit/successor armor light.png
  images/outfit/successor armor regen.png
  images/outfit/successor armor resilient.png
Labels: balance, content, artwork, waiting on dev

#11309 Update PR template to add an acknowledgement that the author has read the Contributing article
  .github/pull_request_template.md
  docs/CONTRIBUTING.md
Labels: documentation

#10531 Fix(content): Eliminate Softlock in FW Pirates
  data/human/free worlds 1 start.txt
Labels: bug, content

#11311 fix(ui): Display turret turn multipliers with consistent formatting
  source/OutfitInfoDisplay.cpp
Labels: bug, UI

#11310 Local Map reveals minables
  data/human/outfits.txt
Labels: balance, content

#11305 fix(ui): Allow unbinding commands set to the same key as the menu command
  source/PreferencesPanel.cpp
Labels: bug, UI

#11272 Fix: Restore Pre-Pug state in Pug-affected systems during Pug-flee Event
  data/human/campaign events.txt
Labels: bug

#11306 Create auto conditions for reading the attributes from your fleet's ships
  source/PlayerInfo.cpp
Labels: enhancement

#11316 feat: Warn the player if they are rebinding the menu key or the key is not bound properly
  source/PreferencesPanel.cpp
Labels: UI

#11332 Fix(content): Remove a reference to the player feeling creepy in FW Recon 1
  data/human/free worlds 0 prologue.txt
Labels: content, text - short

#11338 Fix "Remnant: Cognizance 24" completing unexpectedly on reloading save
  data/remnant/remnant 2 cognizance.txt
Labels: bug

#11337 Allow NPC "on board" conversations to destroy the ship
  source/NPC.cpp
  source/NPCAction.cpp
  source/NPCAction.h
Labels: mechanics

#11333 Make Sunday the first day of the week
  source/Date.cpp
  source/Date.h
Labels: style

#11274 fix(mechanics): Fix a mathematical error that lead to missiles' chance to keep a lock being wildly different from the intended value
  source/Projectile.cpp
Labels: bug, mechanics

#11341 Move the flagship autoconditions test out of the Ember Waste
  tests/integration/config/plugins/integration-tests/data/tests/tests_flagship_attribute_autoconditions.txt
Labels: bug, cd/ci/testing

#11285 fix(content): Condition setting in Successors FC3 and follow up questions in Successors FC1
  data/successors/successor 1 prologue.txt
Labels: bug

#11321 feat(conditions): Make ConditionEntry standalone and simplify condition providers
  source/CMakeLists.txt
  source/ConditionEntry.cpp
  source/ConditionEntry.h
  source/ConditionsStore.cpp
  source/ConditionsStore.h
  source/PlayerInfo.cpp
  tests/unit/src/test_conditionsStore.cpp
Labels: refactor

#11342 feat(docs): Add more info on why AI is not allowed in ES
  docs/CONTRIBUTING.md
Labels: documentation

#10787 fix(content): Lunarium/Heliarch jump tests
  data/coalition/heliarch intro.txt
  data/coalition/lunarium intro.txt
  data/remnant/remnant 1 introduction.txt
Labels: content, waiting on OP

#10612 fix(ui): Shrink scrollable TextAreas to keep their intended width
  source/TextArea.cpp
  source/TextArea.h
Labels: UI

#10371 feat(ui): Make long planet/spaceport descriptions scrollable
  data/_ui/interfaces.txt
  source/MapDetailPanel.cpp
  source/MapDetailPanel.h
  source/MapPanel.cpp
  source/Panel.cpp
  source/Panel.h
  source/PlanetPanel.cpp
  source/PlanetPanel.h
  source/SpaceportPanel.cpp
  source/SpaceportPanel.h
Labels: enhancement, UI

#11113 feat(balance): Balance the Arfecta against the new Quarg ships
  data/pug/pug outfits.txt
  data/pug/pug ships.txt
Labels: balance

#11334 Search a CategoryList's internal list when retrieving by name instead of maintaining a separate map
  source/CategoryList.cpp
  source/CategoryList.h
Labels: bug

#11328 feat(mechanics): Allow outfitters and shipyards to be empty
  source/Planet.cpp
  source/UniverseObjects.cpp
Labels: mechanics

#10381 feat(ui): Make long mission descriptions scrollable
  data/_ui/interfaces.txt
  source/MissionPanel.cpp
  source/MissionPanel.h
Labels: enhancement, UI

#11353 Rewording in Patir Mystery 1
  data/kahet/kahet missions.txt
Labels: content

#11350 refactor(conditions): Store a pointer to the player's ConditionsStore in all ConditionSets when the game is loaded
  source/AI.cpp
  source/CargoHold.cpp
  source/CargoHold.h
  source/ConditionAssignments.cpp
  source/ConditionAssignments.h
  source/ConditionSet.cpp
  source/ConditionSet.h
  source/Conversation.cpp
  source/Conversation.h
  source/ConversationPanel.cpp
  source/Engine.cpp
  source/GameAction.cpp
  source/GameAction.h
  source/GameData.cpp
  source/GameData.h
  source/GameEvent.cpp
  source/GameEvent.h
  source/Government.cpp
  source/Government.h
  source/MapDetailPanel.cpp
  source/MapPanel.cpp
  source/Mission.cpp
  source/Mission.h
  source/MissionAction.cpp
  source/MissionAction.h
  source/NPC.cpp
  source/NPC.h
  source/NPCAction.cpp
  source/NPCAction.h
  source/News.cpp
  source/News.h
  source/Paragraphs.cpp
  source/Paragraphs.h
  source/Planet.cpp
  source/Planet.h
  source/PlanetPanel.cpp
  source/PlayerInfo.cpp
  source/Politics.cpp
  source/Port.cpp
  source/Port.h
  source/PrintData.cpp
  source/RandomEvent.h
  source/Ship.cpp
  source/SpaceportPanel.cpp
  source/StartConditions.cpp
  source/StartConditions.h
  source/StartConditionsPanel.cpp
  source/System.cpp
  source/System.h
  source/TextReplacements.cpp
  source/TextReplacements.h
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  source/main.cpp
  source/test/Test.cpp
  source/test/Test.h
  source/test/TestData.cpp
  source/test/TestData.h
  tests/unit/src/test_conditionAssignments.cpp
  tests/unit/src/test_conditionSet.cpp
Labels: refactor

#11355 style(code): Fix the order of MapPanel members
  source/MapPanel.h
Labels: style

#11278 feat(performance): Add SSE2 code path to Point
  source/Point.cpp
  source/Point.h
  tests/unit/src/test_point.cpp
Labels: enhancement

#11363 style(code): Remove incorrect comments
  source/GameWindow.cpp
Labels: style

#11340 Allow outfitters and shipyards to have condition sets and location filters that determine where they appear
  source/CMakeLists.txt
  source/FleetCargo.cpp
  source/FleetCargo.h
  source/GameData.cpp
  source/GameData.h
  source/LocationFilter.cpp
  source/MapOutfitterPanel.cpp
  source/MapPanel.cpp
  source/MapShipyardPanel.cpp
  source/OutfitterPanel.cpp
  source/OutfitterPanel.h
  source/Planet.cpp
  source/Planet.h
  source/PlanetPanel.cpp
  source/PlanetPanel.h
  source/PrintData.cpp
  source/Sale.h
  source/ShipyardPanel.cpp
  source/ShipyardPanel.h
  source/Shop.h
  source/ShopPanel.cpp
  source/StartConditionsPanel.cpp
  source/UniverseObjects.cpp
  source/UniverseObjects.h
Labels: enhancement

#11207 feat(enhancement): Load plugins from zip files
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  CMakeLists.txt
  docs/readme-developer.md
  source/CMakeLists.txt
  source/Files.cpp
  source/Files.h
  source/GameData.cpp
  source/UniverseObjects.cpp
  source/ZipFile.cpp
  source/ZipFile.h
  source/audio/Audio.cpp
  source/audio/Music.cpp
  vcpkg.json
Labels: enhancement, waiting on dev

#8779 feat(missions): Allow missions to complete at alternative locations with `complete at`
  source/Mission.cpp
  source/Mission.h
Labels: enhancement

#11362 feat(ui): Resize dialogs dynamically
  source/Dialog.cpp
Labels: UI
