Repository endless-sky/endless-sky, pull requests merged in 2025-02, with the labels that each got.

#10976 Fix(Typo) Tim the Stowaway
  data/human/human missions.txt
Labels: typo

#10964 Fix conversation endpoint indentation in "Skadenga Call 5
  data/human/deep missions.txt
Labels: bug, content

#10963 Improve Dangerous Games source location filters
  data/human/human missions.txt
Labels: bug, content

#10975 Fix some issues with escorts jumping around on their own
  source/AI.cpp
Labels: bug, mechanics

#10952 fix(build): Add missing includes
  source/BoardingPanel.cpp
  source/PlayerInfo.cpp
  source/ShipInfoPanel.cpp
  source/ShipNameDialog.cpp
Labels: bug, waiting on dev

#10968 Fix stowaway tim logs
  data/human/human missions.txt
Labels: bug, content

#10967 Fix tooltip boxes being drawn when there is no tooltip text
  source/text/WrappedText.cpp
Labels: bug, UI

#10987 Typo fixes
  data/avgi/avgi news.txt
  data/avgi/avgi side missions.txt
  data/hai/hai culture conversations.txt
  data/hai/hai reveal 0 prologue.txt
  data/human/deep missions.txt
  data/map planets.txt
  data/remnant/remnant 1 introduction.txt
Labels: typo

#10977 feat(balance): Buff the bastion and bulwark
  data/human/ships.txt
Labels: balance

#11004 Benjamin should take up a bunk
  data/human/human missions.txt
Labels: bug, content

#10891 Fix(content): Make the Tractor Beam's description make sense
  data/human/weapons.txt
Labels: content, text - short

#10983 Tooltip for automaton + typo fixes
  data/_ui/tooltips.txt
Labels: text - short

#11013 refactor(ui): Move the unexplored systems color to the interfaces
  data/_ui/interfaces.txt
  source/MapPanel.cpp
Labels: refactor, UI

#11009 [Bugfix] Add missing `flotsam chance` tooltip
  data/_ui/tooltips.txt
Labels: text - short

#11000 Check that a weapon actually consumes a resource before requiring that the resource amount exceed some minimum value
  source/Ship.cpp
  source/Weapon.h
Labels: bug, mechanics

#10989 [Content] Avgi Map Tweaks
  data/map planets.txt
  data/map systems.txt
Labels: content

#11011 fix(crash): Handle snapshot file errors properly
  source/Files.cpp
  source/Files.h
  source/LoadPanel.cpp
Labels: bug

#11018 fix(content): Various Avgi typo fixes
  data/avgi/avgi 0 first contact.txt
  data/avgi/avgi ships.txt
  data/avgi/avgi side missions.txt
  data/avgi/avgi weapons.txt
  data/avgi/windjammers.txt
Labels: typo

#10991 feat(balance): Make Korath raids in human space `frugal`
  data/korath/korath.txt
Labels: balance

#10998 feat(content): Add angles and launch effects to Avgi bays
  copyright
  data/avgi/avgi ships.txt
  data/effects.txt
  sounds/avgi launch external.wav
  sounds/avgi launch internal.wav
Labels: content, sound

#10988 Fix Remnant Rescue 1 through 3 location filters FOR THE LAST TIME
  data/remnant/remnant jobs.txt
Labels: bug, content

#11001 Expand cognizance 29 conversation to account for destroying the Korath fleet
  data/remnant/remnant 2 cognizance.txt
Labels: bug, content

#11039 Add fighters to the Aerie in "FW Syndicate Capture 1B" and adjust dialog accordingly
  data/human/free worlds 3 reconciliation.txt
Labels: balance

#10469 feat(ci/test): Test parse images and sounds, too
  .github/workflows/ci.yml
  endless-sky.6
  source/audio/Audio.cpp
  source/audio/Audio.h
  source/main.cpp
Labels: waiting on OP, cd/ci/testing

#11049 fix(typo) lunarium intro grammatical error
  data/coalition/lunarium intro.txt
Labels: typo

#11035 Remove a duplicate line from .codespell.exclude
  .codespell.exclude
Labels: cd/ci/testing, typo

#11019 fix(content): Correctly redefine Giftbringer Carrier variant
  data/wanderer/wanderers start.txt
Labels: bug, content

#11053 fix(audio): Pause audio on the Ship Info panel
  source/ShipInfoPanel.cpp
  source/ShipInfoPanel.h
Labels: bug, sound

#11059 "Twilight Tavern Guard" fixes
  data/avgi/avgi side missions.txt
Labels: bug, typo

#10960 [Fixes] More Avgi Fixes
  data/avgi/avgi 0 first contact.txt
  data/avgi/avgi culture conversations.txt
  data/avgi/avgi fleets.txt
  data/avgi/avgi jobs.txt
  data/avgi/avgi news.txt
  data/avgi/avgi outfits.txt
  data/avgi/avgi ships.txt
  data/avgi/avgi side missions.txt
  data/avgi/avgi weapons.txt
  data/avgi/avgi.txt
  data/kahet/aberrant outfits.txt
  data/kahet/aberrant ships.txt
  data/kahet/aberrant.txt
  data/map planets.txt
  data/map systems.txt
  data/remnant/remnant jobs.txt
Labels: bug, text - short, typo, needs save

#11025 fix(bug): Make Coalition not bribeable
  data/governments.txt
  data/map planets.txt
Labels: bug, content

#11026 Fix Timothy Radrickson 1a being given inappropriately
  data/human/human missions.txt
Labels: bug, content

#11060 feat(balance): Make firelights jammable, slightly slower, smaller radius
  data/korath/korath weapons.txt
Labels: balance

#11055 feat(balance): Replace missiles with Particle Cannons on Reconciliation's Cruiser (Jump) Variant
  data/human/variants.txt
Labels: balance

#11054 feat(balance): Remove ammo racks from Lances
  data/human/ships.txt
Labels: balance

#11067 Reduce the maximum fuel capacity at which the fuel bar will be drawn segmented
  source/Engine.cpp
Labels: bug, UI

#11069 fix(graphics): Temporarily reduce scale of Z-3600 to prevent visual impairment
  data/avgi/avgi outfits.txt
Labels: bug, artwork

#11034 0.10.12 docs
  changelog
  credits.txt
  endless-sky.6
  io.github.endless_sky.endless_sky.appdata.xml
  source/main.cpp
Labels: documentation

#11073 0.10.13-alpha versions
  CMakeLists.txt
  credits.txt
  endless-sky.6
  resources/EndlessSky-Info.plist
  source/main.cpp
Labels: documentation

#11056 Add fleet jump description
  source/Command.cpp
Labels: mechanics

#11061 fix(bug): add cargo to the Deep River in Wanderers: Unfettered Diplomacy 1A
  data/wanderer/wanderers start.txt
Labels: bug, content

#11036 feat(ui): Support for reversing the draw order of HUD messages
  data/_ui/interfaces.txt
  source/Engine.cpp
Labels: enhancement, UI

#10875 content(news): Some new human news messages
  data/human/news.txt
Labels: content, text - short, to be merged

#10808 Unfettered Hai side-story: Acorn Cookies.
  data/hai/hai missions.txt
Labels: content, text - short, to be merged

#10847 content: Human mining jobs
  data/dialog phrases.txt
  data/human/jobs.txt
Labels: balance, content, text - short, to be merged

#11031 [Content] Aberrant First Contact
  data/kahet/aberrant missions.txt
  data/kahet/kahet missions.txt
Labels: content, text - short, to be merged

#10994 feat(ui): Show sums of salaries and tributes on the Player Info panel
  source/PlayerInfoPanel.cpp
Labels: UI, waiting on dev

#11074 Correct debug mode pause key
  source/main.cpp
Labels: bug

#10810 feat(conditions): Abstract syntax tree parser for conditions
  source/ConditionAssignments.cpp
  source/ConditionAssignments.h
  source/ConditionSet.cpp
  source/ConditionSet.h
  tests/unit/src/test_conditionAssignments.cpp
  tests/unit/src/test_conditionSet.cpp
Labels: enhancement, refactor

#10789 feat(ui): Allow Copy&Paste in string input dialogs
  source/Dialog.cpp
Labels: enhancement, UI

#11075 Timothy Radrickson 1: Remove extra quote
  data/human/human missions.txt
Labels: typo

#11080 feat(Balance): Reducing Autumn Leaf peacetime utility
  data/wanderer/wanderer ships.txt
Labels: balance
