Repository endless-sky/endless-sky, pull requests merged in 2025-06, with the labels that each got.

#11472 fix(mechanics): Skip invalid systems when calculating system neighbors
  source/System.cpp
Labels: bug, mechanics

#11475 fix(content): Specify the destination of FW Bounty 1
  data/human/free worlds 0 prologue.txt
Labels: bug

#11499 fix(ui): Use the small screen map buttons sooner to avoid overlapping UI elements
  source/MapPanel.cpp
Labels: bug, UI

#11369 Make endless-sky build on Raspberry Pi
  CMakeLists.txt
  CMakePresets.json
  docs/readme-developer.md
Labels: bug

#11508 Revert NPC travel instructions
  source/AI.cpp
  source/AI.h
  source/Engine.cpp
  source/Mission.cpp
  source/NPC.cpp
  source/NPC.h
  source/PlayerInfo.cpp
  source/Ship.cpp
  source/Ship.h
  source/ShipEvent.h
  tests/CMakeLists.txt
  tests/integration/config/plugins/integration-tests/data/tests/tests_npc_destination.txt
Labels: bug

#11497 fix(ui): Allow the fixed starfield zoom preference to immediately update the menu background when the menu animation is disabled
  source/MenuPanel.cpp
Labels: bug, UI

#11492 ui: Disable TextArea scrollshifting and optimize area resetting
  source/Dialog.cpp
  source/MissionPanel.cpp
  source/MissionPanel.h
  source/TextArea.cpp
  source/TextArea.h
Labels: bug, UI

#11525 fix(typo): Avalet description typo
  data/map planets.txt
Labels: typo

#11519 docs: Add an "Acceptable licenses" section to the contributing file
  docs/CONTRIBUTING.md
Labels: documentation

#11501 fix(ui): Cache the days remaining for completing deadline missions
  source/MapPanel.cpp
  source/MenuPanel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/PreferencesPanel.cpp
  source/PreferencesPanel.h
Labels: bug

#11532 Fix(typo): Agree with plural "words" in Successors: Trusted
  data/successors/successor 1 prologue.txt
Labels: typo

#11531 Fix(typo): Reword no-fly warning for ships in another system
  source/PlanetPanel.cpp
Labels: typo

#11523 chore(data): Alphabetize government data
  data/governments.txt
Labels: refactor

#11540 feat: Add text replacements that always convert to the player's flagship name/model
  data/kahet/kahet missions.txt
  source/PlayerInfo.cpp
  source/TextReplacements.cpp
  source/main.cpp
Labels: enhancement

#11552 fix(content): Rename the Incups language
  data/governments.txt
Labels: bug, content

#11554 fix(ui): Properly cache job deadlines on accept
  source/Mission.cpp
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: bug, UI

#11549 refactor: Replace a custom formatting function with Format::Decimal
  source/BoardingPanel.cpp
Labels: refactor

#11518 Fix MacOS Release CD
  .github/workflows/cd_release.yaml
Labels: bug, cd/ci/testing

#11555 fix(ui): Don't play sound when scrolling in the logbook
  source/LogbookPanel.cpp
Labels: sound, UI

#11556 fix(style): PlayerInfo cleanup
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: style

#11502 fix(ui): New, robust truncation functions used in DisplayText
  source/text/Font.cpp
  source/text/Font.h
Labels: bug, UI

#11569 Close message log by clicking empty space
  data/_ui/interfaces.txt
Labels: UI

#11571 Correct 'Patir Mystery 12.2A' indentation under 'to accept'.
  data/kahet/kahet missions.txt
Labels: typo

#11458 Don’t draw the same stars in different parallax layers
  source/shader/StarField.cpp
Labels: UI

#11524 feat(artwork): Replace non-free scenes
  copyright
  images/scene/Seasunset.jpg
  images/scene/hai shipyard.jpg
  images/scene/hai start.jpg
  images/scene/iceplains.jpg
  images/scene/iceplains2.jpg
  images/scene/iceplains3.jpg
  images/scene/redrocks.jpg
  images/scene/seasidecliffs.jpg
  images/scene/smeer.jpg
  images/scene/snowfield.jpg
  images/scene/snowvillage.jpg
  images/scene/sunset.jpg
  images/scene/tower.jpg
Labels: artwork

#11547 fix(typo)+feat(balance): Clarified exact requirements for pirate mission text and slightly adjusted spawning constraints
  data/human/pirate jobs.txt
Labels: content

#11577 Fix inappropriate dialog appearance in Cognizance 18
  data/remnant/remnant 2 cognizance.txt
Labels: bug, content

#11580 Fix(Typo): Superstitious Hai and Visit to Paradise Fixes
  data/hai/hai jobs.txt
  data/remnant/remnant 2 side missions.txt
Labels: typo

#11537 feat(content): Remove crew, bank, job, and trading services from automata planets
  data/map planets.txt
  data/wanderer/wanderers middle.txt
Labels: content

#11536 feat(condition): Add separate conditions for fleet/flagship cargo/passenger space total and free
  source/PlayerInfo.cpp
Labels: enhancement

#11576 feat(content): Make "Wanderers: Alpha Surveillance H" offer first before any other eligible missions can offer
  data/wanderer/wanderers start.txt
Labels: content

#11543 fix(mechanics): Properly place die effects spawned by projectiles
  source/Projectile.cpp
Labels: bug

#11568 feat(ui): Display a weapon's velocity and prospecting efficiency in the outfitter
  data/_ui/tooltips.txt
  source/OutfitInfoDisplay.cpp
Labels: UI

#11522 feat(build): Package Windows releases with installers
  .github/workflows/cd_release.yaml
  CMakeLists.txt
  installer/header.bmp
  installer/welcome.bmp
Labels: cd/ci/testing

#11539 feat(content): Allow "FW Southern Recon 1B" to be completed immediately if you already have an electron beam
  data/human/free worlds 2 middle.txt
Labels: bug, content, text - short

#11578 0.10.14 docs
  changelog
  credits.txt
  endless-sky.6
  io.github.endless_sky.endless_sky.appdata.xml
  source/WinApp.rc
  source/main.cpp
Labels: documentation

#11589 Fix Windows release CD
  .github/workflows/cd_release.yaml
Labels: cd/ci/testing

#11509 Graveyard gas giants
  data/map planets.txt
  data/map systems.txt
Labels: content, text - short, to be merged

#11593 docs: 0.10.15-alpha version numbers once again
  source/WinApp.rc
Labels: documentation

#11516 feat(ui): Added a "Show mini-map" preference option for having the system mini-map always on
  data/_ui/tooltips.txt
  source/Engine.cpp
  source/Engine.h
  source/MapPanel.cpp
  source/MapPanel.h
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
Labels: UI
