Repository endless-sky/endless-sky, pull requests merged in 2025-07, with the labels that each got.

#11602 feat(ui): Don't show invisible projectiles on the radar
  source/Engine.cpp
Labels: UI

#11610 fix(ui): Don't spam the "Coming to a stop" message
  source/AI.cpp
  source/AI.h
Labels: bug, UI

#11591 feat(ui): Animate incoming messages
  data/_ui/interfaces.txt
  source/Engine.cpp
  source/Messages.cpp
  source/Messages.h
Labels: UI

#11614 fix: Use the text mode for writing save files on Windows
  source/Files.cpp
Labels: bug

#11587 refactor: Move common code for listing items to Format
  source/AI.cpp
  source/Account.cpp
  source/ItemInfoDisplay.cpp
  source/Mission.cpp
  source/PlayerInfo.cpp
  source/text/Format.h
Labels: refactor

#11598 feat(content): Make the Heavy Gust available
  data/wanderer/wanderer ships.txt
  data/wanderer/wanderers middle.txt
  data/wanderer/wanderers start.txt
  data/wanderer/wanderers.txt
Labels: content

#11596 feat(enhancement): Allow weapon hardpoints to be swizzled with the ship
  source/Body.cpp
  source/Body.h
  source/Engine.cpp
Labels: enhancement

#11650 Fix local map minable mapping
  data/human/outfits.txt
Labels: bug, content

#11616 Variant map names for unfettered outfitted ships
  data/hai/hai ships.txt
Labels: content

#11661 Fix blurry text on the planet description
  data/_ui/interfaces.txt
Labels: bug, UI

#11670 fix(content): Fix bug where Cutthroats wouldn't spawn
  data/human/free worlds 2 middle.txt
Labels: bug

#11672 fix(code): Fix test_point failing abs test on ARM64
  tests/unit/src/test_point.cpp
Labels: cd/ci/testing
