Repository endless-sky/endless-sky, pull requests merged in 2025-01, with the labels that each got.

#10897 Update the "Major Programming" credits.txt section
  credits.txt
Labels: documentation

#10890 Streamline Viminal's description
  data/map planets.txt
Labels: text - short

#10904 fix(bug): fix an overindented `decline`
  data/human/human missions.txt
Labels: typo

#10380 feat(enhancement): Display names for systems and planets
  source/AI.cpp
  source/CoreStartData.cpp
  source/Engine.cpp
  source/EscortDisplay.cpp
  source/Fleet.cpp
  source/GameAction.cpp
  source/GameData.cpp
  source/GameEvent.cpp
  source/HailPanel.cpp
  source/LocationFilter.cpp
  source/MapDetailPanel.cpp
  source/MapPanel.cpp
  source/MapPlanetCard.cpp
  source/MenuPanel.cpp
  source/Mission.cpp
  source/NPC.cpp
  source/Planet.cpp
  source/Planet.h
  source/PlanetLabel.cpp
  source/PlayerInfo.cpp
  source/PlayerInfoPanel.cpp
  source/Ship.cpp
  source/StartConditions.cpp
  source/StellarObject.cpp
  source/StellarObject.h
  source/System.cpp
  source/System.h
  source/UniverseObjects.cpp
  source/Wormhole.cpp
  source/Wormhole.h
  source/test/Test.cpp
Labels: enhancement

#10888 feat(content): Gegno "Unwelcoming" mission that stops `clearance` workarounds
  data/gegno/gegno I corroboration.txt
  data/gegno/gegno intro missions.txt
Labels: balance, content

#10906 fix(build): Fix clangd errors on project files
  CMakeLists.txt
  source/CMakeLists.txt
Labels: cd/ci/testing

#10907 feat(ci): Add a content style check for trailing periods in a sentence enclosed in parenthesis
  utils/contentStyle.json
Labels: content, cd/ci/testing, typo, style

#10033 feat(content): Saving Ildico - Human mission
  .codespell.exclude
  copyright
  data/human/deep missions.txt
  data/human/human missions.txt
  data/human/outfits.txt
  images/outfit/surtrblood.png
Labels: content, artwork, text - long

#10757 feat(content): Make decline choices in FW prologue more direct
  data/human/free worlds 0 prologue.txt
Labels: text - short

#10807 feat(content): Culture Conversation About Far'en Lai
  data/korath/korath culture conversations.txt
Labels: content, text - short

#10909 fix: Deallocate the SDL base path properly
  source/Files.cpp
Labels: bug, to be merged

#10910 fix: Fix handling of paths with unicode characters on Windows
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  source/Files.cpp
Labels: bug, cd/ci/testing, waiting on dev

#10925 [Bugfix] Actually use neutron-small for the small-neutron-star icon
  images/map/small-neutron-star+.png
Labels: bug, artwork

#10927 fix(audio): Use relative path for sounds
  source/audio/Music.cpp
Labels: bug, sound

#10658 feat(audio): Individual volume controls for different sound categories
  data/_ui/interfaces.txt
  images/ui/audio low.png
  images/ui/audio max.png
  images/ui/audio medium.png
  images/ui/audio none.png
  images/ui/keys panel.png
  images/ui/plugins panel.png
  images/ui/settings panel.png
  source/AI.cpp
  source/CMakeLists.txt
  source/Effect.cpp
  source/Effect.h
  source/Engine.cpp
  source/Hardpoint.cpp
  source/MenuAnimationPanel.cpp
  source/PlayerInfo.cpp
  source/Preferences.cpp
  source/PreferencesPanel.cpp
  source/Ship.cpp
  source/Visual.cpp
  source/audio/Audio.cpp
  source/audio/Audio.h
  source/audio/SoundCategory.h
  source/main.cpp
Labels: enhancement, sound, UI, waiting on dev

#10879 feat(artwork): Add sprite for "Puny"
  copyright
  data/human/outfits.txt
  images/outfit/collar.png
Labels: artwork

#10918 feat(ui): Highlight name of selected system in map panel
  source/MapPanel.cpp
  source/MissionPanel.cpp
Labels: UI

#10901 fix(bug): specify destination in Successor tourist missions
  data/successors/successor jobs.txt
Labels: bug, content

#10818 feat(audio): Pause audio whenever the game is paused
  source/BoardingPanel.cpp
  source/BoardingPanel.h
  source/ConversationPanel.cpp
  source/ConversationPanel.h
  source/Dialog.cpp
  source/Dialog.h
  source/HailPanel.cpp
  source/HailPanel.h
  source/MapPanel.cpp
  source/MapPanel.h
  source/MessageLogPanel.cpp
  source/MessageLogPanel.h
  source/PlanetPanel.cpp
  source/PlanetPanel.h
  source/PlayerInfoPanel.cpp
  source/PlayerInfoPanel.h
  source/audio/Audio.cpp
Labels: enhancement, sound

#10862 feat(audio): Support speeding up audio in fast-forward mode
  sounds/archonteleport@3x.wav
  sounds/asteroid crunch large@3x.wav
  sounds/asteroid crunch medium@3x.wav
  sounds/asteroid crunch small@3x.wav
  sounds/dragonflame@3x.wav
  sounds/explosion ayym@3x.wav
  sounds/explosion huge@3x.wav
  sounds/explosion jje@3x.wav
  sounds/explosion large@3x.wav
  sounds/explosion medium@3x.wav
  sounds/explosion nuke@3x.wav
  sounds/explosion small@3x.wav
  sounds/explosion tiny@3x.wav
  sounds/final explosion large@3x.wav
  sounds/final explosion medium@3x.wav
  sounds/final explosion small@3x.wav
  sounds/finisher@3x.wav
  sounds/firestorm hit@3x.wav
  sounds/heavy rocket hit@3x.wav
  sounds/human launch@3x.wav
  sounds/hyperdrive in@3x.wav
  sounds/hyperdrive out@3x.wav
  sounds/hyperdrive@3x.wav
  sounds/jump drive@3x.wav
  sounds/jump in@3x.wav
  sounds/jump out@3x.wav
  sounds/korath launch@3x.wav
  sounds/missile hit@3x.wav
  sounds/nuke@3x.wav
  sounds/organ drive in@3x.wav
  sounds/organ drive out@3x.wav
  sounds/organ drive@3x.wav
  sounds/remnant launch external@3x.wav
  sounds/remnant launch@3x.wav
  sounds/rocket@3x.wav
  sounds/star tail@3x.wav
  sounds/takeoff@3x.wav
  sounds/thorax cannon@3x.wav
  sounds/torpedo hit@3x.wav
  sounds/torpedo@3x.wav
  sounds/typhoon@3x.wav
  source/audio/Audio.cpp
  source/audio/Audio.h
  source/audio/Sound.cpp
  source/audio/Sound.h
  source/main.cpp
Labels: enhancement, sound

#10860 feat(balance): revert nerf to turret turn rates from #10043 while preserving rebalance
  data/bunrodea/bunrodea weapons.txt
  data/coalition/coalition weapons.txt
  data/gegno/gegno outfits.txt
  data/hai/hai outfits.txt
  data/human/weapons.txt
  data/incipias/incipias outfits.txt
  data/kahet/kahet outfits.txt
  data/korath/korath weapons.txt
  data/pug/pug outfits.txt
  data/quarg/quarg outfits.txt
  data/remnant/remnant outfits.txt
  data/sheragi/sheragi outfits.txt
  data/successors/successor weapons.txt
  data/wanderer/wanderer outfits.txt
Labels: balance

#10929 fix(audio): Re-add missing `alSourcef` line removed from Audio.ccp in #10862
  source/audio/Audio.cpp
Labels: bug

#10921 Update copyright for tactical scan icons
  copyright
Labels: documentation

#10920 Delete ui/tactical/tactical image
  images/ui/tactical/tactical.png
Labels: bug

#10914 [Bugfix/Enhancement] Fix Starry Map Keybind Conflict + Adjust Scale Formula
  data/_ui/help.txt
  data/_ui/interfaces.txt
  source/MapPanel.cpp
Labels: bug, UI, waiting on dev

#10859 Readme for cmake on Ubuntu 22.04
  docs/readme-cmake.md
Labels: documentation

#10392 feat(enhancement): Support image formats with any extension
  source/CMakeLists.txt
  source/GameData.cpp
  source/GameWindow.cpp
  source/image/BlendingMode.h
  source/image/ImageBuffer.cpp
  source/image/ImageBuffer.h
  source/image/ImageFileData.cpp
  source/image/ImageFileData.h
  source/image/ImageSet.cpp
  source/image/ImageSet.h
  source/text/Font.cpp
Labels: enhancement, waiting on dev

#10932 Update tactical icon copyright again
  copyright
Labels: documentation

#10933 fix(explanation): clarify which jump drive in The Emerald Sword 2
  data/sheragi/archaeology missions.txt
Labels: content

#10931 Disable all help messages in integration tests
  tests/integration/config/preferences.txt
Labels: cd/ci/testing

#8828 Content(missions): Hai Legacy
  copyright
  data/governments.txt
  data/hai/hai ships.txt
  data/hai/unfettered 0 prologue.txt
  data/hai/unfettered side missions.txt
  images/scene/cave scene.png
  images/scene/emerging ladybug.png
  images/ship/hai anomalocaris.png
  images/thumbnail/hai anomalocaris.png
Labels: balance, content, artwork, text - short

#10930 feat(sound): Categorize existing sound effects
  data/bunrodea/bunrodea weapons.txt
  data/effects.txt
  data/hazards.txt
  data/human/engines.txt
  data/human/weapons.txt
  data/korath/korath outfits.txt
  data/korath/korath weapons.txt
  data/pug/pug outfits.txt
  data/quarg/quarg outfits.txt
  data/remnant/remnant outfits.txt
  data/successors/successor outfits.txt
  data/wanderer/wanderer outfits.txt
Labels: content, sound

#10640 feat(content): Culture Conversation for the 300th Anniversary of the Republic
  data/human/culture conversations.txt
Labels: content, text - short

#10922 fix(typo): Another batch of wording fixes
  data/map planets.txt
Labels: content, text - short, typo

#10937 [Bugfix] Quick Aberrant Player Rep Fix + Windjammer Timer Typo
  data/avgi/windjammers.txt
  data/governments.txt
Labels: bug

#10943 (news) Add Avgi and Really Unrelated Literally Excessive Innocuous poems
  data/quarg/quarg news.txt
Labels: text - short

#10941 Fix spellcheck errors
  changelog
  data/avgi/avgi.txt
Labels: typo

#10919 Fix various issues from #8172 (strategic scanning)
  source/Engine.cpp
Labels: bug, mechanics, refactor

#10939 fix(ui): Properly select the ShipInfoPanel's ship
  source/ShipInfoPanel.cpp
Labels: bug, UI

#10938 fix(audio): Don't pause sound effects when audio is already paused
  source/PlanetPanel.cpp
  source/audio/Audio.cpp
Labels: bug, sound

#10945 fix(audio): Fix some paused sources not getting resumed properly
  source/MenuPanel.h
  source/audio/Audio.cpp
Labels: bug, sound

#10926 0.10.11 docs
  changelog
  credits.txt
  endless-sky.6
  io.github.endless_sky.endless_sky.appdata.xml
  source/main.cpp
Labels: documentation

#10946 0.10.12 alpha version numbers
  CMakeLists.txt
  credits.txt
  endless-sky.6
  resources/EndlessSky-Info.plist
  source/main.cpp
Labels: documentation

#10948 Don't allow "Paradise Job: Wilderness Retreat" to go to a station
  data/human/paradise world jobs.txt
Labels: bug, content

#10940 Ildico Tweaks
  data/human/human missions.txt
Labels: content, text - short
