Repository endless-sky/endless-sky, pull requests merged in 2025-10, with the labels that each got.

#11797 fix(mechanics): Correctly apply fighter repair heat and fuel
  source/Ship.cpp
Labels: bug, mechanics

#11791 ui: Add a message category that allows duplicates
  source/Messages.cpp
  source/Messages.h
  source/Ship.cpp
Labels: UI

#11789 feat(content): Give Hand-to-hand outfits to Bunrodean ships
  data/bunrodea/bunrodea ships.txt
Labels: balance

#11787 docs: Update and expand system requirements
  README.md
Labels: documentation

#11794 fix(sound): Fix planet ambient music playback
  source/MenuPanel.cpp
  source/PlayerInfo.cpp
Labels: bug, sound

#11795 fix/feat/unfeat(sound) Handle unsupported WAV files properly
  source/audio/Sound.cpp
  source/audio/supplier/AudioSupplier.h
Labels: bug, sound

#11777 fix(mechanics): Correctly check blindspots on special weapons
  source/Hardpoint.cpp
Labels: bug, mechanics

#11800 Fixes needed to get this to compile on my debian box
  CMakeLists.txt
  source/audio/supplier/AudioSupplier.h
  tests/unit/src/test_weightedList.cpp
Labels: bug

#11793 (bugfix) Prevent Coalition Yottrite missions from offering on Gas Giants
  data/coalition/coalition missions.txt
Labels: bug, content

#11808 refactor(ui): Optimize the startup animation
  source/MenuAnimationPanel.cpp
Labels: refactor

#11807 Feat(Balance) Cut the Thorax's fire rate in half.
  data/bunrodea/bunrodea weapons.txt
Labels: balance

#11811 fix(ui): Don't spam the cloaked boarding message
  source/Ship.cpp
Labels: bug, UI

#11810 Acorn Delights: fix repeatable options
  data/hai/hai missions.txt
Labels: bug, content

#11809 Add label to STOP command
  source/Command.cpp
Labels: refactor

#11447 Refactor Shop Buttons into DrawButton function using ClickZones
  source/ShopPanel.cpp
  source/ShopPanel.h
Labels: refactor, UI

#11783 feat(ui): Use Windows DWM attributes preferred by the player
  data/_ui/tooltips.txt
  source/CMakeLists.txt
  source/GameWindow.cpp
  source/GameWindow.h
  source/Preferences.cpp
  source/Preferences.h
  source/PreferencesPanel.cpp
  source/main.cpp
  source/windows/WinVersion.cpp
  source/windows/WinVersion.h
Labels: UI

#11654 Fix repetitive display of fleet jump message.
  source/AI.cpp
Labels: bug, UI

#11486 feat(content): Add markers to systems in Wanderers: Alpha Surveillance D
  data/wanderer/wanderers start.txt
Labels: content
